### ISSUE TITLE
strange proxy error: SP324097: Your network proxy requires authentication

### ISSUE THREAD

**Issue by rs38** [Microsoft/vsts-agent#1029]
talking from onprem Agent to onprem TFS does not work for a particular Service account.

`powershell wget -uri onprem-tfs:8080/TFS -userdefaultcredentials` works fine

I have no further Idea to narrow down...any idea?

Version of Agent: from TFS 2015 Update 3
VSOWorker v14.102.25423.0
<br>
Windows Server 2012 R2
<br>
 On-Prem TFSelease 2015 U3
<br>
Agent is registered correctly and is listed as "green" in Agent Queue list.
But any build step failes immediately
<br>
```
06:27:44.098196 JobManager.StartJob(job.JobId = 14e31117-5e0b-4f86-9131-fa4283b9b779)
06:27:44.098196 JobInfo.ctor
06:27:44.098196 JobInfo.ctor - leave
06:27:44.098196 JobManager.StartJob - calling JobWriter.StartJob
06:27:44.098196 JobWriter.StartJob - enter
06:27:44.098196 JobWriter.StartJob - (SKIPPING)first renew
06:27:44.348196 JobWriter.StartJob - start continual renewing
06:27:44.363823 AuthorizationType : OAuth
06:27:44.410704 ---------------------------------------------------------------------------
06:27:44.410704 Microsoft.VisualStudio.Services.WebApi.ProxyAuthenticationRequiredException: SP324097: Your network proxy requires authentication.

06:27:44.410704    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)

06:27:44.410704    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__79.MoveNext()

06:27:44.410704 --- End of stack trace from previous location where exception was thrown ---

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

06:27:44.410704    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__76`1.MoveNext()

06:27:44.410704 --- End of stack trace from previous location where exception was thrown ---

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

06:27:44.410704    at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()

06:27:44.410704 --- End of stack trace from previous location where exception was thrown ---

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

06:27:44.410704    at Microsoft.VisualStudio.Services.Client.VssServerDataProvider.<ConnectAsync>d__39.MoveNext()

06:27:44.410704 --- End of stack trace from previous location where exception was thrown ---

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

06:27:44.410704    at Microsoft.TeamFoundation.DistributedTask.Agent.Common.ConnectionHelper.GetConnection(Uri serverUri, VssCredentials credentials)

06:27:44.410704    at Microsoft.TeamFoundation.DistributedTask.Agent.JobWriter.StartJob()
06:27:44.410704    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)

06:27:44.410704    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__79.MoveNext()

06:27:44.410704 --- End of stack trace from previous location where exception was thrown ---

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

06:27:44.410704    at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__76`1.MoveNext()

06:27:44.410704 --- End of stack trace from previous location where exception was thrown ---

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

06:27:44.410704    at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()

06:27:44.410704 --- End of stack trace from previous location where exception was thrown ---

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

06:27:44.410704    at Microsoft.VisualStudio.Services.Client.VssServerDataProvider.<ConnectAsync>d__39.MoveNext()

06:27:44.410704 --- End of stack trace from previous location where exception was thrown ---

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

06:27:44.410704    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

06:27:44.410704    at Microsoft.TeamFoundation.DistributedTask.Agent.Common.ConnectionHelper.GetConnection(Uri serverUri, VssCredentials credentials)

06:27:44.410704    at Microsoft.TeamFoundation.DistributedTask.Agent.JobWriter.StartJob()
```

**Comment by TingluoHuang** [comment]
@rs38 the 1.x version build agent never fully supported proxy and has been deprecated. Try the 2.x agent from this repository and follow doc to config it work through proxy. [Doc is here](https://www.visualstudio.com/en-us/docs/build/actions/agents/v2-windows#qa)

**Comment by rs38** [comment]
I already tried the 2.x agent, but it does not work with TFS 2015 on prem, so I have no choice.

**Comment by TingluoHuang** [comment]
@rs38 which version you tried, we blocked it recently, but i think you can try old version.
ex: https://github.com/Microsoft/vsts-agent/releases/tag/v2.112.0

**Comment by rs38** [comment]
I tried the latest non-prerelease release (v2.117.1). thank you for the hint, I will try it soon.
The main issue is the unknown or unexpected  behaviour to *bypass* the corporate proxy based on IE group policies or user (-> service account) dependend settings.

**Comment by TingluoHuang** [comment]
@rs38 why you need bypass the proxy?

**Comment by rs38** [comment]
in order to have a work around for the error "ProxyAuthenticationRequiredException: SP324097: Your network proxy requires authentication"

**Comment by rs38** [comment]
the auth issues with the proxy now indeed are gone with v2.112.0 :+1: 
But now I get different errors I did not witness before. same as here:
#890

**Comment by TingluoHuang** [comment]
@rs38 do you plan to upgrade your TFS server to 2017? i don't have good suggestion now. :(

**Comment by rs38** [comment]
the decision is not up to me. thanks for your help

**Comment by TingluoHuang** [comment]
I will close the issue as the proxy problem has been solved by using 2.x agent.
