### ISSUE TITLE
Timeout during artifact download on slow connection

### ISSUE THREAD

**Issue by sirjoekcb** [Microsoft/vsts-agent#1030]
## **Agent version and platform**
Version of your agent? 2.119.1
<br>
OS of the machine running the agent? RHEL 7.3
<br>
## **VSTS type and version**
On-Prem TFS 14.102.25423.0
<br>

## **What's not working?** 
I am trying to deploy a build using the release management functionality, however there is a slow network connection to the agent. This appears to cause the artifact download to fail and restart after 5 minutes or about 2/3rds into the download. I have tried setting the VSTS_HTTP_TIMEOUT environment variable as described in the troubleshooting doc, but that had no effect on the timeout.
<br>
## **Agent and Worker's diag log**

Stack trace fom the Worker log:
```
[2017-06-21 20:30:08Z WARN ReleaseJobExtension] System.Exception: Error download
ing /opt/tfsagent/_work/r1/a/branch-main/dist/artifact-name.zip.download: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseFileSystemManager.<WriteStreamToFile>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ContainerFetchEngine.FetchEngine.<GetFileAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ContainerFetchEngine.FetchEngine.<DownloadItemImplAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ContainerFetchEngine.FetchEngine.<FetchItemsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ContainerFetchEngine.ContainerFetchEngine.<FetchAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.BuildArtifact.<DownloadArtifactAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.BuildArtifact.<DownloadAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<>c__DisplayClass34_2.<<DownloadArtifacts>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.RetryExecutor.<ExecuteAsync>d__20.MoveNext()

```

**Comment by TingluoHuang** [comment]
@sirjoekcb i will make a fix to make sure those variable got work in Release. current they works in upload build artifacts.

**Comment by TingluoHuang** [comment]
@GitHubSriramB can you take look this? customer get timeout during artifact download.

**Comment by GitHubSriramB** [comment]
@sirjoekcb - will take up fixing this & let you know once it is fixed.

**Comment by sirjoekcb** [comment]
@GitHubSriramB Any chance of an ETA for this fix?

**Comment by GitHubSriramB** [comment]
@sirjoekcb - haven't been able to get to this till now. will try fixing it in a week or so.

**Comment by stephenmichaelf** [comment]
It looks like the issue is in FetchEngine.cs:

```csharp
Task timeoutTask = Task.Delay(ContainerFetchEngineOptions.GetFileAsyncTimeout, cancellationToken);
```

The only place I see that we set the GetFileAsyncTimeout is in ContainerFetchEngineDefaultOptions.cs where we set it to 5 minutes.

**Comment by GitHubSriramB** [comment]
@stephenmichaelf - we will take the PR you shared forward and come up with appropriate fix to increase the timeout for downloading a file. Will update once we have fixed this.

**Comment by connorposke** [comment]
Has this been fixed? We are currently experiencing a timeout when trying to download build artifacts of large sizes. The release process times out after about 20 seconds every time, which is a very short timeout. This is while using the TeamCity Artifacts for VSTS extension https://marketplace.visualstudio.com/items?itemName=ms-devlabs.vss-services-teamcity

**Comment by TingluoHuang** [comment]
@connorposke  can you share a sample log about the timeout?

**Comment by connorposke** [comment]
2018-02-01T16:49:48.6457077Z ##[debug]Evaluating condition for step: 'Download Artifacts'
2018-02-01T16:49:48.6485919Z ##[debug]Evaluating: succeeded()
2018-02-01T16:49:48.6494757Z ##[debug]Evaluating succeeded:
2018-02-01T16:49:48.6527264Z ##[debug]=> (Boolean) True
2018-02-01T16:49:48.6555101Z ##[debug]Expanded: True
2018-02-01T16:49:48.6555519Z ##[debug]Result: True
2018-02-01T16:49:48.6612830Z ##[section]Starting: Download Artifacts
2018-02-01T16:49:48.6721183Z Creating artifacts directory: C:\vstsagent\A6\_work\r3\a
2018-02-01T16:49:48.6766255Z Created artifacts directory: C:\vstsagent\A6\_work\r3\a
2018-02-01T16:49:48.6766505Z Downloading artifact
2018-02-01T16:49:48.6786192Z Starting artifacts download...
2018-02-01T16:49:48.6962456Z Downloading linked artifact PRISM Server of type Custom...
2018-02-01T16:49:48.6996769Z Ensuring artifact folder C:\vstsagent\A6\_work\r3\a\PRISM Server exists and is clean.
2018-02-01T16:50:09.8364400Z An error occurred during download: System.AggregateException: One or more errors occurred. (An error occurred while sending the request. The operation timed out) ---> System.Net.WebException: An error occurred while sending the request. The operation timed out ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.HttpWebRequest.<SendRequest>d__194.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.DistributedTask.Common.ServiceEndpoints.EndpointProxy.ExecuteRequest(String endpointUrl, String resourceUrl, ResponseSelector selector, IEndpointAuthorizer authorizer)
   at Microsoft.TeamFoundation.DistributedTask.Common.ServiceEndpoints.EndpointProxy.QueryEndpoint(ServiceEndpoint serviceEndpoint, String endpointUrl, String resourceUrl, String resultSelector, String resultTemplate, List`1 authorizationHeaders, Dictionary`2 parameters)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.CustomArtifact.EnsureVersionBelongsToLinkedDefinition(ArtifactDefinition artifactDefinition)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.CustomArtifact.<DownloadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<>c__DisplayClass39_2.<<DownloadArtifacts>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.RetryExecutor.<ExecuteAsync>d__20.MoveNext()
---> (Inner Exception #0) System.Net.WebException: An error occurred while sending the request. The operation timed out ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.HttpWebRequest.<SendRequest>d__194.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---

**Comment by connorposke** [comment]
Note the timestamp difference between the log line where the download begins and when the timeout error is thrown. About 21 seconds.

2018-02-01T16:49:48.6962456Z Downloading linked artifact PRISM Server of type Custom...
..................................
..................................
2018-02-01T16:50:09.8364400Z An error occurred during download: System.AggregateException: One or more errors occurred. (An error occurred while sending the request. The operation timed out) --->

**Comment by TingluoHuang** [comment]
@connorposke what's your agent version and where is it?
the 20 seconds timeout might indicate a TCP handshake failure, which might caused by socket exhausted on some network infrastructure.

**Comment by connorposke** [comment]
For all our builds we're using hosted agents. This is a "Release" in VSTS however. I'm not sure how that correlates to the build agent being used. I see agent versions of 1.98.1 and 2.0.0 in the logs in VSTS.

I don't believe this is a TCP handshake issue since we are able to verify with the logs in TeamCity that the REST API request to pull the artifacts from TC is making it through to the server. I don't think TeamCity would log the full REST API request that it receives from VSTS if the underlying TCP connection was never established. We also are able to verify connectivity since the Service Hook for TeamCity successfully verifies.
