### ISSUE TITLE
Windows Container .\config.cmd remove fails - Resource not available for anonymous access. Client authentication required.

### ISSUE THREAD

**Issue by jsacapdev** [Microsoft/vsts-agent#1088]
## **Agent version and platform**

Agent:
vsts-agent-win7-x64-2.117.1

OS:
Windows Container - microsoft/windowsservercore:latest (with .NET Framework Installed)

## **VSTS type and version**

Visual Studio Team Services:

https://jsadev.visualstudio.com/

## **What's not working?** 

I am succesfully able to register the build agent in the container OK when I run the docker container. 

However, when attempting to unregister the build agent in the container, using the following command (and associated error):

PS C:\agent> .\config.cmd remove
Removing service
Removing agent from the server
Enter authentication type (press enter for PAT) >
Enter personal access token > **************************************************
Connecting to server ...
Failed: Removing agent from the server
TF400813: Resource not available for anonymous access. Client authentication required.

I can delete the container, but the problem is that it leaves the agents that I have deleted lying around in Agent Pool, and I dont know a way to delete them from the agent pool, and there is no documentation on how to manually delete them from the agent pool in the docs (https://www.visualstudio.com/en-us/docs/build/concepts/agents/pools-queues).

If you want to try the container yourself, feel free using the following instructions:

docker login idevcr.azurecr.io -u="87b79218-c310-446d-8b29-265f3e87ad86" -p="77593d09-8f07-4cb6-92b0-51f40b402686"

docker pull idevcr.azurecr.io/vsts-agent

NOTE: the image is big at the moment - 22.5 GB

## **Agent and Worker's diag log**
[2017-07-20 07:47:44Z INFO AgentProcess] Agent is built for Windows - win7-x64.
[2017-07-20 07:47:44Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 10.0.14393 .
[2017-07-20 07:47:44Z INFO AgentProcess] Version: 2.117.1
[2017-07-20 07:47:44Z INFO AgentProcess] Commit: 7918fd875eb9f62955296d51bcc612904b37c733
[2017-07-20 07:47:44Z INFO AgentProcess] Culture: en-US
[2017-07-20 07:47:44Z INFO AgentProcess] UI Culture: en-US
[2017-07-20 07:47:44Z INFO HostContext] Well known directory 'Bin': 'C:\agent\bin'
[2017-07-20 07:47:44Z INFO HostContext] Well known directory 'Root': 'C:\agent'
[2017-07-20 07:47:44Z INFO AgentProcess] Validating directory permissions for: 'C:\agent'
[2017-07-20 07:47:44Z INFO PowerShellExeUtil] Generation: '1'
[2017-07-20 07:47:44Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1', value name 'Install': '1'
[2017-07-20 07:47:44Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2017-07-20 07:47:44Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2017-07-20 07:47:44Z INFO PowerShellExeUtil] Generation: '3'
[2017-07-20 07:47:44Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3', value name 'Install': '1'
[2017-07-20 07:47:44Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.1.14393.0'
[2017-07-20 07:47:44Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2017-07-20 07:47:44Z INFO NetFrameworkUtil]  'CDF'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil]  'v4'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil]  'v4.0'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2017-07-20 07:47:44Z INFO NetFrameworkUtil]  'Client'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil]  'Full'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.6.01586'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '394802'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Type is System.Int32
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Interpreted version: 4.6.2
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.6.01586'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '394802'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Type is System.Int32
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Interpreted version: 4.6.2
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Found 2 versions:
[2017-07-20 07:47:44Z INFO NetFrameworkUtil]  4.6.2
[2017-07-20 07:47:44Z INFO NetFrameworkUtil]  4.6.2
[2017-07-20 07:47:44Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.5'
[2017-07-20 07:47:44Z INFO CommandLineParser] Parse
[2017-07-20 07:47:44Z INFO CommandLineParser] Parsing 1 args
[2017-07-20 07:47:44Z INFO CommandLineParser] parsing argument
[2017-07-20 07:47:44Z INFO CommandLineParser] HasArgs: False
[2017-07-20 07:47:44Z INFO CommandLineParser] Adding Command: remove
[2017-07-20 07:47:44Z INFO AgentProcess] Arguments parsed
[2017-07-20 07:47:44Z INFO VstsAgentWebProxy] No proxy setting found.
[2017-07-20 07:47:44Z INFO Agent] ExecuteCommand
[2017-07-20 07:47:44Z INFO ConfigurationStore] currentAssemblyLocation: C:\agent\bin\Agent.Listener.dll
[2017-07-20 07:47:44Z INFO ConfigurationStore] binPath: C:\agent\bin
[2017-07-20 07:47:44Z INFO ConfigurationStore] RootFolder: C:\agent
[2017-07-20 07:47:44Z INFO ConfigurationStore] ConfigFilePath: C:\agent\.agent
[2017-07-20 07:47:44Z INFO ConfigurationStore] CredFilePath: C:\agent\.credentials
[2017-07-20 07:47:44Z INFO ConfigurationStore] ServiceConfigFilePath: C:\agent\.service
[2017-07-20 07:47:44Z INFO CommandSettings] Flag 'help': 'False'
[2017-07-20 07:47:44Z INFO CommandSettings] Flag 'version': 'False'
[2017-07-20 07:47:44Z INFO CommandSettings] Flag 'commit': 'False'
[2017-07-20 07:47:44Z INFO CommandSettings] Command 'configure': 'False'
[2017-07-20 07:47:44Z INFO CommandSettings] Command 'remove': 'True'
[2017-07-20 07:47:44Z INFO Terminal] WRITE LINE: Removing service
[2017-07-20 07:47:44Z INFO ConfigurationStore] IsServiceConfigured()
[2017-07-20 07:47:44Z INFO ConfigurationStore] IsServiceConfigured: False
[2017-07-20 07:47:44Z INFO Terminal] WRITE LINE: Removing agent from the server
[2017-07-20 07:47:44Z INFO ConfigurationStore] IsConfigured()
[2017-07-20 07:47:44Z INFO ConfigurationStore] IsConfigured: True
[2017-07-20 07:47:44Z INFO ConfigurationStore] HasCredentials()
[2017-07-20 07:47:44Z INFO ConfigurationStore] stored True
[2017-07-20 07:47:44Z INFO ConfigurationManager] GetCredentialProvider
[2017-07-20 07:47:44Z INFO CommandSettings] Arg 'auth': ''
[2017-07-20 07:47:44Z INFO CommandSettings] Flag 'unattended': 'False'
[2017-07-20 07:47:44Z INFO PromptManager] ReadValue
[2017-07-20 07:47:44Z INFO Terminal] WRITE: Enter authentication type (press enter for PAT) > 
[2017-07-20 07:47:44Z INFO Terminal] READ LINE
[2017-07-20 07:47:46Z INFO Terminal] Read value: ''
[2017-07-20 07:47:46Z INFO PromptManager] Falling back to the default: 'PAT'
[2017-07-20 07:47:46Z INFO ConfigurationManager] Creating credential for auth: PAT
[2017-07-20 07:47:46Z INFO CredentialManager] GetCredentialProvider
[2017-07-20 07:47:46Z INFO CredentialManager] Creating type PAT
[2017-07-20 07:47:46Z INFO CredentialManager] Creating credential type: PAT
[2017-07-20 07:47:46Z INFO PersonalAccessToken] EnsureCredential
[2017-07-20 07:47:46Z INFO CommandSettings] Arg 'token': ''
[2017-07-20 07:47:46Z INFO CommandSettings] Flag 'unattended': 'False'
[2017-07-20 07:47:46Z INFO PromptManager] ReadValue
[2017-07-20 07:47:46Z INFO Terminal] WRITE: Enter personal access token > 
[2017-07-20 07:47:46Z INFO Terminal] READ SECRET
[2017-07-20 07:47:55Z INFO Terminal] Read value: '********'
[2017-07-20 07:47:55Z INFO PersonalAccessToken] GetVssCredentials
[2017-07-20 07:47:55Z INFO PersonalAccessToken] token retrieved: 50 chars
[2017-07-20 07:47:55Z INFO ConfigurationManager] cred retrieved
[2017-07-20 07:47:55Z INFO ConfigurationManager] Agent configured for deploymentGroup : False
[2017-07-20 07:47:55Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2017-07-20 07:47:55Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2017-07-20 07:47:55Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2017-07-20 07:47:55Z INFO Terminal] WRITE LINE: Connecting to server ...
[2017-07-20 07:47:59Z INFO AgentServer] Catch exception during connect. 4 attemp left.
[2017-07-20 07:47:59Z ERR  AgentServer] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: Resource not available for anonymous access. Client authentication required.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
[2017-07-20 07:47:59Z INFO AgentServer] Catch exception during connect. 3 attemp left.
[2017-07-20 07:47:59Z ERR  AgentServer] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: Resource not available for anonymous access. Client authentication required.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
[2017-07-20 07:47:59Z INFO AgentServer] Catch exception during connect. 2 attemp left.
[2017-07-20 07:47:59Z ERR  AgentServer] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: Resource not available for anonymous access. Client authentication required.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
[2017-07-20 07:47:59Z INFO AgentServer] Catch exception during connect. 1 attemp left.
[2017-07-20 07:47:59Z ERR  AgentServer] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: Resource not available for anonymous access. Client authentication required.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
[2017-07-20 07:48:00Z INFO Terminal] WRITE LINE: Failed: Removing agent from the server
[2017-07-20 07:48:00Z ERR  Agent] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: TF400813: Resource not available for anonymous access. Client authentication required.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<TestConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<UnconfigureAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext()
[2017-07-20 07:48:00Z ERR  Terminal] WRITE ERROR: TF400813: Resource not available for anonymous access. Client authentication required.

**Comment by TingluoHuang** [comment]
@jsacapdev your PAT is wrong.
`[2017-07-20 07:47:55Z INFO PersonalAccessToken] token retrieved: 50 chars`

a valid token should has 52 chars
`[2017-07-08 20:49:47Z INFO PersonalAccessToken] token retrieved: 52 chars`

**Comment by jsacapdev** [comment]
Thanks for the guidance. It was down to a weird copy and paste in the container, where the string (PAT) gets corrupted on the paste. Manually (painfully) typing in the PAT de-registers the agent cleanly.
