### ISSUE TITLE
issue downloading package microsoft/sp-build-web"~1.1.0 (SASS 4.5.3)

### ISSUE THREAD

**Issue by cool-abhi** [Microsoft/vsts-agent#1154]
Summary : I am getting error. Can not download win32-x64 package. We are able to download all other packages from git. So its not proxy issue. Also user has admin rights on machine.
I am using package ": @microsoft/sp-build-web"~1.1.0 which intern is calling sass v4.5.3. I have node version of 4.6.1 (can not upgrade to 5 or above)
node v6.10.0

-- already deleted node_module
-- user has admin rights on machine
-- other packages are downloading so it should not be proxy issue
-- sass team mention this is issue with vsts proxy so raising issue here

Error :

2017-08-21T19:28:29.2218628Z npm WARN prefer global node-gyp@3.6.2 should be installed with -g

2017-08-21T19:28:29.3937360Z > node-sass@4.5.3 install D:\agent_work\38\s\node_modules\node-sass

2017-08-21T19:28:29.3937360Z > node scripts/install.js

2017-08-21T19:28:29.9562454Z Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-48_binding.node

2017-08-21T19:28:29.9874926Z Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-48_binding.node":

2017-08-21T19:28:29.9874926Z tunneling socket could not be established, statusCode=407

2017-08-21T19:28:29.9874926Z Hint: If github.com is not accessible in your location

2017-08-21T19:28:29.9874926Z try setting a proxy via HTTP_PROXY, e.g.

2017-08-21T19:28:29.9874926Z export HTTP_PROXY=http://example.com:1234

2017-08-21T19:28:29.9874926Z or configure npm proxy via

2017-08-21T19:28:29.9874926Z npm config set proxy http://example.com:8080

2017-08-21T19:28:30.1437422Z > node-sass@4.5.3 postinstall …..

2017-08-21T19:28:30.1437422Z > node scripts/build.js

2017-08-21T19:28:30.3156210Z Building:

2017-08-21T19:28:30.5656200Z gyp info it worked if it ends with ok

2017-08-21T19:28:30.5656200Z gyp verb cli [ ,

2017-08-21T19:28:30.5656200Z gyp verb cli ',

2017-08-21T19:28:30.5656200Z gyp verb cli 'rebuild',

2017-08-21T19:28:30.5656200Z gyp verb cli '--verbose',

2017-08-21T19:28:30.5656200Z gyp verb cli '--libsass_ext=',

2017-08-21T19:28:30.5656200Z gyp verb cli '--libsass_cflags=',

2017-08-21T19:28:30.5656200Z gyp verb cli '--libsass_ldflags=',

2017-08-21T19:28:30.5656200Z gyp verb cli '--libsass_library=' ]

2017-08-21T19:28:30.5656200Z gyp info using node-gyp@3.6.2

2017-08-21T19:28:30.5656200Z gyp info using node@6.9.5 | win32 | x64

2017-08-21T19:28:30.5812463Z gyp verb command rebuild []

2017-08-21T19:28:30.5812463Z gyp verb command clean []

2017-08-21T19:28:30.5968731Z gyp verb clean removing "build" directory

2017-08-21T19:28:30.6125004Z gyp verb command configure []

2017-08-21T19:28:30.6281221Z gyp verb check python checking for Python executable "python2" in the PATH

2017-08-21T19:28:30.6437480Z gyp verb which failed Error: not found: python2

2017-08-21T19:28:30.6437480Z gyp verb which failed at getNotFoundError (D:\agent_work\38\s\node_modules\which\which.js:13:12)

2017-08-21T19:28:30.6437480Z gyp verb which failed at F ( :68:19)

2017-08-21T19:28:30.6437480Z gyp verb which failed at E ( .js:80:29)

2017-08-21T19:28:30.6437480Z gyp verb which failed at :89:16

2017-08-21T19:28:30.6437480Z gyp verb which failed at :42:5

2017-08-21T19:28:30.6437480Z gyp verb which failed at FSReqWrap.oncomplete (fs.js:123:15)

2017-08-21T19:28:30.6593716Z gyp verb which failed python2 { Error: not found: python2

2017-08-21T19:28:30.6593716Z gyp verb which failed at F ( :68:19)

2017-08-21T19:28:30.6593716Z gyp verb which failed at FSReqWrap.oncomplete (fs.js:123:15)

2017-08-21T19:28:30.6593716Z gyp verb which failed code: 'ENOENT' }

2017-08-21T19:28:30.6593716Z gyp verb check python checking for Python executable "python" in the PATH

2017-08-21T19:28:30.6749961Z gyp verb which failed Error: not found: python

:36:5

2017-08-21T19:28:30.6749961Z gyp verb which failed at FSReqWrap.oncomplete (fs.js:123:15)

2017-08-21T19:28:30.6749961Z gyp verb which failed python { Error: not found: python

2017-08-21T19:28:30.6749961Z gyp verb which failed at getNotFoundError

2017-08-21T19:28:30.6906248Z gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

2017-08-21T19:28:30.6906248Z Build failed with error code: 1

NPM version (npm -v):
Node version (node -v):
Node Process (node -p process.versions):
Node Platform (node -p process.platform):
Node architecture (node -p process.arch):
node-sass version (node -p "require('node-sass').info"):
npm node-sass versions (npm ls node-sass):

**Comment by TingluoHuang** [comment]
@cool-abhi can you run the same command on the build machine successfully as the same runas user?

**Comment by stephenmichaelf** [comment]
@cool-abhi Please reopen the issue if you are still stuck.
