### ISSUE TITLE
TF.exe in a docker container: "The type initializer for 'System.Windows.Application' threw an exception."

### ISSUE THREAD

**Issue by HerrHoller** [Microsoft/vsts-agent#1163]
[Diag.txt](https://github.com/Microsoft/vsts-agent/files/1252033/Diag.txt)
[GetSources.txt](https://github.com/Microsoft/vsts-agent/files/1252032/GetSources.txt)

## Agent version and platform
2.120.2 - Windows

## VSTS type and version
On-Prem TFS 2017 (15.112.26307.0)

## What's not working?
tf.exe exits when executing the command (stated below)
cloning git repos works without any problem.

```
##[debug]tf vc workspaces /format:xml /collection:http://tfs:8080/tfs/IM-Dev/ /loginType:OAuth /login:.,******** /noprompt
##[debug]The type initializer for 'System.Windows.Application' threw an exception.
##[error]Exit code 100 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:http://tfs:8080/tfs/IM-Dev/ /loginType:OAuth /login:.,******** /noprompt'.
```

## Agent and Worker's diag log
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by TingluoHuang** [comment]
@HerrHoller have you ever modified any file under `externals\vstsom`? can you share your `tf.exe.config` file with me?

**Comment by HerrHoller** [comment]
Wow. I didn´t expect an answer until next week :)
Nothing is modified. Maybe i should mention that i am running the agent inside a docker container.

[tf.exe.config.txt](https://github.com/Microsoft/vsts-agent/files/1252049/tf.exe.config.txt)

**Comment by TingluoHuang** [comment]
@HerrHoller which docker image you are suing?

**Comment by TingluoHuang** [comment]
can you try run a .net 45 console app inside your container?

**Comment by HerrHoller** [comment]
@TingluoHuang  its self built and i can run .net 45 apps inside:

`FROM microsoft/windowsservercore:latest


ENV VSTS_AGENT_URL https://github.com/Microsoft/vsts-agent/releases/download/v2.120.2/vsts-agent-win7-x64-2.120.2.zip

# Environment variables
ENV vsts_url "http://tfs:8080/tfs"
ENV vsts_agentname DOCKER_TFS_WIN
ENV vsts_agentpool BirdIsland

ADD *.ps1 /agent/
WORKDIR "C:\agent"

RUN Invoke-WebRequest  -Proxy $env:http_proxy -UseBasicParsing -OutFile "vsts-agent-win.zip" -Uri ${env:VSTS_AGENT_URL}; \
    Expand-Archive -Path "vsts-agent-win.zip" -Destination .; \    
    Remove-Item "vsts-agent-win.zip";

RUN choco install microsoft-build-tools -y --allow-empty-checksums -version 14.0.23107.10
RUN choco install visualstudio2015testagents --allow-empty-checksums -y
RUN choco install windows-sdk-7.1 --allow-empty-checksums -y

ENTRYPOINT [ "powershell.exe", "-File", "agent.ps1"  ]
`

**Comment by TingluoHuang** [comment]
@HerrHoller can you try run the agent out side the container? see whether it can get pass the tf.exe problem?

**Comment by HerrHoller** [comment]
@TingluoHuang I installed the same agent version on a Windows Server 2016 and it works.
I have also added RUN choco install dotnet4.5.2 in my dockerfile to ensure that .net is installed but the error still occurs

**Comment by TingluoHuang** [comment]
@HerrHoller try install dotnet 4.6.x

**Comment by TingluoHuang** [comment]
@HerrHoller what dotnet version you have on your Server2016 that tf.exe works?

**Comment by TingluoHuang** [comment]
@HerrHoller I check the code, looks like the latest version `tf.exe` requires .net 4.6

**Comment by TingluoHuang** [comment]
@HerrHoller are you able to make it work?

**Comment by HerrHoller** [comment]
@TingluoHuang I have know .net 4.7 inside the container but it still does not work:

`[2017-08-29 12:31:24Z INFO ProcessInvoker] Starting process:
[2017-08-29 12:31:24Z INFO ProcessInvoker]   File name: 'tf'
[2017-08-29 12:31:24Z INFO ProcessInvoker]   Arguments: 'vc workspaces /format:xml /collection:http://tfs:8080/tfs/IM-Dev/ /loginType:OAuth /login:.,******** /noprompt'
[2017-08-29 12:31:24Z INFO ProcessInvoker]   Working directory: 'C:\agent\_work\1\s'
[2017-08-29 12:31:24Z INFO ProcessInvoker]   Require exit code zero: 'True'
[2017-08-29 12:31:24Z INFO ProcessInvoker]   Encoding web name: windows-1252 ; code page: '1252'
[2017-08-29 12:31:24Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-08-29 12:31:24Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-08-29 12:31:25Z INFO ProcessInvoker] Process started with process id 2780, waiting for process exit.
[2017-08-29 12:31:33Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-08-29 12:31:33Z INFO ProcessInvoker] Finished process with exit code 100, and elapsed time 00:00:09.0025440.
[2017-08-29 12:31:33Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-08-29 12:31:34Z ERR  StepsRunner] Caught exception from step: Microsoft.VisualStudio.Services.Agent.ProcessExitCodeException: Exit code 100 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:http://tfs:8080/tfs/IM-Dev/ /loginType:OAuth /login:.,******** /noprompt'.
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCCommandManager.<RunPorcelainCommandAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TFCommandManager.<WorkspacesAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCSourceProvider.<GetSourceAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.<PrepareAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
[2017-08-29 12:31:34Z INFO StepsRunner] Step result: Failed`

**Comment by TingluoHuang** [comment]
@HerrHoller Can you share your dockerfile? i will try build the container and run tf.exe

**Comment by chrisrpatterson** [comment]
TF is a bit more complicated than a simple console application and at this point we have not tested inside containers so I am not surprised it does not work.

**Comment by HerrHoller** [comment]
Hi,

[Desktop.zip](https://github.com/Microsoft/vsts-agent/files/1262532/Desktop.zip)
@TingluoHuang I have merged together all three dockerfiles we use.

**Comment by TingluoHuang** [comment]
@HerrHoller 
I tried to use the same base docker image as you had `microsoft/dotnet-framwork:latest`, and download the same version of `tf.exe` the agent has, but i am able to run the `tf.exe`

Here is what i tried:
`docker create microsoft/dotnet-framework:latest ping 127.0.0.1 -n 20000`
`docker start <HASH>`
`docker exec -it <HASH> cmd`
`which powershell`

// download tf.zip
`powershell Invoke-WebRequest -Uri "https://vstsagenttools.blob.core.windows.net/tools/vstsom/m121_1_c7acb19d/vstsom.zip" -OutFile tf.zip`

// unzip
`powershell Expand-Archive -Path .\tf.zip -DestinationPath .\tf`

// run tf.exe
```
C:\>tf\TF.exe
Microsoft (R) TF - Team Foundation Version Control Tool, Version 15.121.26803.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Type tf vc help for a list of supported Version Control commands.
Type tf git help for a list of supported Git commands.
Type tf settings help for a list of supported server settings commands.
```

So i am wonder whether those `chocolatey` packages you installed in your docker file cause corruption for .net framework.

Can you try to comment out all extra installations in your docker file, just put the agent there and see whether you can get pass the `tf.exe` crash problem?

**Comment by HerrHoller** [comment]
I´ve reduced my dockerfile to a minimum. Running tf.exe itself doesn´t throw an error

`PS C:\agent\externals\vstsom> .\TF.exe
Microsoft (R) TF - Team Foundation Version Control Tool, Version 15.121.26803.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Type tf vc help for a list of supported Version Control commands.
Type tf git help for a list of supported Git commands.
Type tf settings help for a list of supported server settings commands.

PS C:\agent\externals\vstsom> .\tf vc workspaces /format:xml /collection:http://tfs-its.avl01.avlcorp.lan:8080/tfs/IM-Dev/ /loginType:OAuth /login:user,password /noprompt
The type initializer for 'System.Windows.Application' threw an exception.`

**Comment by TingluoHuang** [comment]
@HerrHoller i am able to repro this as well, i will fix the product team of tf.exe and see how they can fix this.

**Comment by HerrHoller** [comment]
@TingluoHuang any update on this?

**Comment by TingluoHuang** [comment]
@HerrHoller I reported the problem with production team, they are looking.
I did some search online and find this issue, which might indicate this problem is a bug in server core container.
https://github.com/Microsoft/dotnet-framework-docker/issues/23
Can you try the workaround mentioned in the issue?

**Comment by HerrHoller** [comment]
@TingluoHuang using the latest windowsservercore image (10.0.14393.1715) fixed the problem.
