### ISSUE TITLE
Agent can't download new version of a task

### ISSUE THREAD

**Issue by tomkuijsten** [Microsoft/vsts-agent#1213]
## Agent version and platform
Agent version: 2.117.2
OS: Win 2012 R2 (x64)

## VSTS type and version
TFS 2017 update 2

## What's not working?
When a new version of a task is available, the agent has problems downloading the new task to the `_work\_tasks` folder. This time it was the task 'VSTest' version '2.0.55'. If I copy the task from another agent which already has this version and put it in the `_work\_tasks` folder, the build is working correctly. A couple of questions:
 - How does an agent know when a new version is available?
 - How does an agent get the new version?
 - Can I manually download the task from somewhere?

The log doesn't have any usefull info other then "The operation timed out". The agent is running as a windows service and the credentials have access to internet.

Already used fiddler to see if any traffic was blocked, but I didn't caught a single request. If I start a build on another agent (which doesn't use the VSTest step) I do get requests in fiddler.

## Agent and Worker's diag log
Agent
```
[2017-09-19 08:45:42Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file c:\TfsBuildAgents\06\.credentials_rsaparams
[2017-09-19 08:45:42Z INFO MessageListener] Message '5' received from session '8853a090-0f37-4193-af6e-77e4a095b8c8'.
[2017-09-19 08:45:42Z INFO JobDispatcher] Job request 904e7c36-6864-44ce-a96b-6eb8b80b7e60 received.
[2017-09-19 08:45:42Z INFO JobDispatcher] Job request f76abb40-cf21-4dce-9e87-e142d3e85e7c processed succeed.
[2017-09-19 08:45:42Z INFO Terminal] WRITE LINE: 2017-09-19 08:45:42Z: Running job: Build
[2017-09-19 08:45:42Z INFO JobDispatcher] Start renew job request 25565 for job 904e7c36-6864-44ce-a96b-6eb8b80b7e60.
[2017-09-19 08:45:42Z INFO JobDispatcher] Successfully renew job request 25565, job is valid till 9/19/2017 8:50:42 AM
[2017-09-19 08:45:42Z INFO ProcessInvoker] Starting process:
[2017-09-19 08:45:42Z INFO ProcessInvoker]   File name: 'c:\TfsBuildAgents\06\bin\Agent.Worker.exe'
[2017-09-19 08:45:42Z INFO ProcessInvoker]   Arguments: 'spawnclient 2492 2504'
[2017-09-19 08:45:42Z INFO ProcessInvoker]   Working directory: 'c:\TfsBuildAgents\06\bin'
[2017-09-19 08:45:42Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-09-19 08:45:42Z INFO ProcessInvoker]   Encoding web name:  ; code page: ''
[2017-09-19 08:45:42Z INFO ProcessInvoker]   Force kill process on cancellation: 'True'
[2017-09-19 08:45:42Z INFO ProcessInvoker] Process started with process id 13336, waiting for process exit.
[2017-09-19 08:45:42Z INFO JobDispatcher] Send job request message to worker for job 904e7c36-6864-44ce-a96b-6eb8b80b7e60.
[2017-09-19 08:45:42Z INFO JobNotification] Entering JobStarted Notification
[2017-09-19 08:45:58Z INFO ProcessInvoker] Finished process with exit code 102, and elapsed time 00:00:15.8414613.
[2017-09-19 08:45:58Z INFO JobDispatcher] Worker finished for job 904e7c36-6864-44ce-a96b-6eb8b80b7e60. Code: 102
[2017-09-19 08:45:58Z INFO JobDispatcher] finish job request for job 904e7c36-6864-44ce-a96b-6eb8b80b7e60 with result: Failed
[2017-09-19 08:45:58Z INFO Terminal] WRITE LINE: 2017-09-19 08:45:58Z: Job Build completed with result: Failed
[2017-09-19 08:45:58Z INFO JobDispatcher] Stop renew job request for job 904e7c36-6864-44ce-a96b-6eb8b80b7e60.
[2017-09-19 08:45:58Z INFO JobDispatcher] job renew has been canceled, stop renew job request 25565.
[2017-09-19 08:45:58Z INFO JobNotification] Entering JobCompleted Notification
```

Worker

```
[2017-09-19 08:45:46Z INFO TaskManager] Ensuring task exists: ID 'e213ff0f-5d5c-4791-802d-52ea3e7be1f1', version '1.2.3', name 'PowerShell', directory 'c:\TfsBuildAgents\06\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\1.2.3'.
[2017-09-19 08:45:46Z INFO TaskManager] Ensuring task exists: ID '333b11bd-d341-40d9-afcf-b32d5ce6f23b', version '0.2.31', name 'NuGetInstaller', directory 'c:\TfsBuildAgents\06\_work\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.31'.
[2017-09-19 08:45:46Z INFO TaskManager] Ensuring task exists: ID '71a9a2d3-a98a-4caa-96ab-affca411ecda', version '1.119.0', name 'VSBuild', directory 'c:\TfsBuildAgents\06\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.119.0'.
[2017-09-19 08:45:46Z INFO TaskManager] Ensuring task exists: ID 'ef087383-ee5e-42c7-9a53-ab56c98420f9', version '2.0.55', name 'VSTest', directory 'c:\TfsBuildAgents\06\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.0.55'.
[2017-09-19 08:45:56Z INFO JobServerQueue] Catch exception during append web console line, keep going since the process is best effort. Due with exception when all batches finish.
[2017-09-19 08:45:56Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 0/1.
[2017-09-19 08:45:56Z ERR  JobServerQueue] System.AggregateException: Catch exception during append web console line. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.ThrottlingReportHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.JobServerQueue.<ProcessWebConsoleLinesQueueAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.ThrottlingReportHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.JobServerQueue.<ProcessWebConsoleLinesQueueAsync>d__30.MoveNext()<---

```

**Comment by stephenmichaelf** [comment]
@tomkuijsten From the stack trace it looks like the job is timing out while trying to upload the web console lines.

The Agent will pull the latest version of the task for you automatically. There is one constraint: this happens within the major version you have selected. So if you select 1.* we will not pull 2.* versions, you have to first update in the UI:

![image](https://user-images.githubusercontent.com/450490/30592777-25cedbe8-9d16-11e7-871b-0bbc9a25c753.png)

What tasks are you having issues with besides VSTest? Is this On Prem?

If you could set system.debug to true, run again, and send the logs to:

stfrance at microsoft.com

I can take a look. 

The debug logs will have a line that says "Task [name] already downloaded at '[location]'."

**Comment by tomkuijsten** [comment]
I followed the official template for an issue which contains the version I'm running ;)

Besides VSTest (I was using the 2.* version) the "Publish Symbols" was having the same problem.

The output you see is already with "system.debug = true".

I was using fiddler to try and track the problem, a couple of answers to my own questions (might help others):
 - The agents will be triggered to start a build with the build definition (in json) as argument. This build definition already contains the version of a build task to use. The TFS server knows the versions available and which version whould be used.
 - The agent uses the TFS API to download the zip from the server (no internet involved). The api that's being used for VSTest:
   - `http://ourserver/tfs/DefaultCollection/_apis/distributedtask/tasks/ef087383-ee5e-42c7-9a53-ab56c98420f9/2.0.55`
 - You can manually download the step by using the API call yourself

The build agent is by default bypassing the fiddler proxy, by placing [a .proxy file](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows#qa) in the root of the agent, I was able to track all http request. The funny thing, the build immediately started working and download the build tasks without any problems.

I can't explain why it did work when fiddler was in the middle, can you?

**Comment by TingluoHuang** [comment]
@tomkuijsten can you share a full agent diag log and build log with us?
tihuang at microsoft.com

**Comment by tomkuijsten** [comment]
@TingluoHuang just send you the full logs

**Comment by TingluoHuang** [comment]
This is exception that cause the job to failed.
```
[2017-09-19 09:22:17Z ERR  BuildJobExtension] Caught exception from JobExtension Initialization: System.IO.IOException: The read operation failed, see inner exception. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.<DownloadAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.<DownloadAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.<InitializeJob>d__9.MoveNext()
[2017-09-19 09:22:18Z ERR  JobRunner] Job initialize failed.
```
The task download is failed when download VSTest Task, the only thing i can think of is do you have any firewall/proxy/antivirus  between your build agent and TFS server? the VSTest task contains binary assets which might some firewall/proxy/antivirus to block it.

**Comment by tomkuijsten** [comment]
Good point about the antivirus, will ask our security officer. The weird thing however, when I put fiddler in the middle (using a ,proxy file in the agent root), it downloads the task without any problem.

**Comment by TingluoHuang** [comment]
@tomkuijsten before agent version 2.119.x, the agent will follow IE proxy setting if you don't have a `.proxy` file, I guess you have a IE proxy setting on that box.
from agent 2.119.x, we change the agent only follow what you put in the `.proxy` file, if you don't have `.proxy`, no proxy will be used.

**Comment by tomkuijsten** [comment]
@TingluoHuang thanks, guess that was the problem after all
