### ISSUE TITLE
Deploy TestAgent on ... issue

### ISSUE THREAD

**Issue by DalpheSDC** [Microsoft/vsts-agent#1216]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting

## Agent version and platform
vsts-agent-win7-x64-2.123.0

OS of the machine running the agent? OSX/Windows/Linux...
Windows server 2012 r2

## VSTS type and version
On-Prem TFS?

If On-Prem TFS, which release, 2017 Update 1
we are facing this issue when trying to deploy an TestAgent with the newest prerelease of the Agent

## What's not working?
We are facing that the powershell make a exception every time it is trying to do the NeXT step after downloading the agent. The service account user does have admin right on the remote server and there are full trust og no firewall between them.
the servername is change to servername instead of the real name.
Please explain me if I'm missing something here.
it is running on http
remote powershell is enable and trustedhosts is set to *

## Agent and Worker's diag log
Executing the powershell script: D:\TFS\A4\w\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\DeployTestAgent.ps1
DistributedTests: Starting to deploy and configure test agent on test machines.
DistributedTests: Inputs provided are:
DistributedTests: Username: pi-windows\u3166
DistributedTests: Use HTTP Port: True
DistributedTests: Run as process: False
DistributedTests: Login Automatically: False
DistributedTests: Disable Screen saver: False
DistributedTests: Agent would be downloaded from https://go.microsoft.com/fwlink/?LinkId=615472
DistributedTests: Update test agent: False
DistributedTests: Run test agent as DataCollection only : False
DistributedTests: Path to script that installs test agent on remote machine: D:\TFS\A4\w\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\TestAgentInstall.ps1
DistributedTests: Path to script that configures test agent on remote machine: D:\TFS\A4\w\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\TestAgentConfiguration.ps1
DistributedTests: Path to script that downloads test agent on Azure remote machines : D:\TFS\A4\w\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\DownloadTestAgent.ps1
DistributedTests: Path to script that checks if test agent is installed on remote machine: D:\TFS\A4\w\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\CheckTestAgentInstallation.ps1
DistributedTests: Path to script that checks if test agent is already running on remote machine: D:\TFS\A4\w\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.42\VerifyTestMachinesAreInUse.ps1
DistributedTests: Path to script that helps to download and configure test agent : 
DistributedTests: Task 'PopulatingMachinesPresentState' on machine 'servername:5985' is being run
DistributedTests: Task 'PopulatingMachinesPresentState' on machine 'servername:5985' completed.
DistributedTests: Starting to download testagent

Unhandled Exception: System.Management.Automation.PSInvalidOperationException: The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread. Validate that the cmdlet makes these calls correctly, or contact Microsoft Customer Support Services.
   at System.Management.Automation.MshCommandRuntime.ThrowIfWriteNotPermitted(Boolean needsToWriteToPipeline)
   at System.Management.Automation.MshCommandRuntime.WriteHelper_ShouldWrite(ActionPreference preference, ContinueStatus lastContinueStatus)
   at System.Management.Automation.MshCommandRuntime.WriteWarning(WarningRecord record, Boolean overrideInquire)
   at System.Management.Automation.Cmdlet.WriteWarning(String text)
   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.Logger.WriteWarning(String message)
   at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.TestAgentDownloader.wc_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by TingluoHuang** [comment]
@DalpheSDC I think this an issue about `DeployVisualStudioTestAgent` task, not the agent.
I suggest you report the problem at https://github.com/microsoft/vsts-tasks
