### ISSUE TITLE
The artifact directory does not exist in VSTS releases

### ISSUE THREAD

**Issue by cycloguy** [Microsoft/vsts-agent#1223]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting

## Agent version and platform
Version of your agent? 2.102.0

OS of the machine running the agent?Windows 10

## VSTS type and version
VisualStudio.com

If VisualStudio.com, what is your account name? http://ezcm.visualstudio.com

## What's not working?
Please include error messages and screenshots

## Agent and Worker's diag log

2017-10-02T08:38:29.6612426Z ##[section]Starting: Download Artifacts
2017-10-02T08:38:30.1787440Z Downloading artifact
2017-10-02T08:38:30.1857447Z Creating artifacts directory: d:\a\r1\a
2017-10-02T08:38:30.1877442Z Created artifacts directory: d:\a\r1\a
2017-10-02T08:38:30.1887445Z Starting artifacts download...
2017-10-02T08:38:30.1927446Z Downloading linked artifact EZCM-Maven-CI of type Build...
2017-10-02T08:38:30.2197446Z Ensuring artifact folder d:\a\r1\a\EZCM-Maven-CI exists and is clean.
2017-10-02T08:38:30.2587987Z Preparing to get the list of available artifacts from build
2017-10-02T08:38:30.4627365Z Preparing to download artifact: drop
2017-10-02T08:38:30.4787393Z Artifact Type: FileShare
2017-10-02T08:38:32.8368121Z Directory '\\build_ezcm_01\build\Result\EZCM-Maven-CI\20170929.11\drop' does not exist. Falling back to parent directory: \\build_ezcm_01\build\Result\EZCM-Maven-CI\20170929.11
2017-10-02T08:38:33.1157548Z An error occurred during download: Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.ArtifactDownloadException: The artifact directory does not exist: \\build_ezcm_01\build\Result\EZCM-Maven-CI\20170929.11. It can happen if the password of the account factoryvm-az182\buildguest is changed recently and is not updated for the agent. If this is the case, please consider re-configuring the agent.
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.BuildArtifact.<DownloadArtifactAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.BuildArtifact.<DownloadAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<>c__DisplayClass34_2.<<DownloadArtifacts>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.RetryExecutor.<ExecuteAsync>d__20.MoveNext()
2017-10-02T08:38:33.1277549Z ##[error]The artifact directory does not exist: \\build_ezcm_01\build\Result\EZCM-Maven-CI\20170929.11. It can happen if the password of the account factoryvm-az182\buildguest is changed recently and is not updated for the agent. If this is the case, please consider re-configuring the agent.
2017-10-02T08:38:33.1307554Z ##[section]Finishing: Download Artifacts

**Comment by TingluoHuang** [comment]
@cycloguy how did you provide download url?
it's an UNC share, the url should looks like `\\build_ezcm_01` instead of `\build_ezcm_01`

**Comment by cycloguy** [comment]
@TingluoHuang In my log file it shows `\\build_ezcm_01` but in the post `\build_ezcm_01`
This is how I configured:
The task is Copy file. 
Source folder is $(Build.ArtifactStagingDirectory)
Content: **
Destination: d:\build\

**Comment by TingluoHuang** [comment]
@cycloguy the log you attached is from a Release job, right? what's the relation between that release job and your CopyFile task? Can you share some screenshot of what's your release's artifact setting looks like and the build definition that produce the artifact?

**Comment by cycloguy** [comment]
@TingluoHuang right, the log from the Release job. Here are build and release screenshots:
![build1](https://user-images.githubusercontent.com/5820670/31107702-89c3cc72-a81e-11e7-8303-18ff04b8cbc6.PNG)
![release](https://user-images.githubusercontent.com/5820670/31107703-89c9ad7c-a81e-11e7-8d54-e497bd221a24.PNG)

**Comment by TingluoHuang** [comment]
@cycloguy can you briefly explains what are you trying to accomplish?

**Comment by cycloguy** [comment]
After the build run, I simply want to copy artifacts to other place. I may add some more tasks after copying files. 
Does the issue relate to permission of user in VSTS Agent service? I have tried to use a new created user, local system account or Network service but no luck.

**Comment by TingluoHuang** [comment]
@cycloguy  the build and release are 2 different system. you need to tell the Release definition which build artifact it needs to consume, you can't just rely on local folder, since the build and release job may route to different agents.
 why don't you add another publish build artifiact task to your build definition and publish the stuff into an UNC share?

**Comment by TingluoHuang** [comment]
![image](https://user-images.githubusercontent.com/1750815/31110345-612af5d2-a7d4-11e7-9411-b9e94ba00772.png)

**Comment by cycloguy** [comment]
@TingluoHuang : Thanks for your advise but I'm doing a very simple case by using only one agent and build and release on the same machine. I'll try to work-around. Thanks
