### ISSUE TITLE
VSTS Hosted Agent User Account Denied Access to LocalDb

### ISSUE THREAD

**Issue by scottwojan** [Microsoft/vsts-agent#1231]
## Have you try trouble shooting doc?
Yes

## Agent version and platform
2.123.0

Windows Hosted VS2017

## VSTS type and version
VSTS p202.visualstudio.com

## What's not working?
The agent user is not able to login to localdb\ mssqllocaldb or a database explicitly created and lists the owner as the agent's login.

### Create the LocalDb Step Results
```
2017-10-06T01:16:26.0409378Z ##[section]Starting: Create LocalDb
2017-10-06T01:16:26.0409378Z ==============================================================================
2017-10-06T01:16:26.0409378Z Task         : Command Line
2017-10-06T01:16:26.0409378Z Description  : This is an early preview. Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
2017-10-06T01:16:26.0409378Z Version      : 2.120.1
2017-10-06T01:16:26.0409378Z Author       : Microsoft Corporation
2017-10-06T01:16:26.0409378Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2017-10-06T01:16:26.0409378Z ==============================================================================
2017-10-06T01:16:27.0634042Z Generating script.
2017-10-06T01:16:27.1275111Z ##[command]"C:\Windows\system32\cmd.exe" /Q /D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\fcf9afa4-4e8f-4d89-989f-28013b2bfd2d.cmd""
2017-10-06T01:16:27.1345249Z Creating TestingLocalDB
2017-10-06T01:16:27.2107798Z MSSQLLocalDB
2017-10-06T01:16:36.5965808Z LocalDB instance "TestingLocalDB" created with version 13.1.4001.0.
2017-10-06T01:16:36.5965808Z 
2017-10-06T01:16:36.5975820Z LocalDB instance "TestingLocalDB" started.
2017-10-06T01:16:36.5975820Z 
2017-10-06T01:16:36.6106196Z Microsoft (R) SQL Server Express LocalDB Command Line Tool
2017-10-06T01:16:36.6106196Z 
2017-10-06T01:16:36.6106196Z Version 13.0.1601.5
2017-10-06T01:16:36.6106196Z 
2017-10-06T01:16:36.6106196Z Copyright (c) Microsoft Corporation.  All rights reserved.
2017-10-06T01:16:36.6106196Z 
2017-10-06T01:16:36.6106196Z 
2017-10-06T01:16:36.6106196Z 
2017-10-06T01:16:36.6106196Z Usage: SqlLocalDB operation [parameters...]
2017-10-06T01:16:36.6106196Z 
2017-10-06T01:16:36.6106196Z 
2017-10-06T01:16:36.6106196Z 
2017-10-06T01:16:36.6106196Z Operations:
2017-10-06T01:16:36.6106196Z 
2017-10-06T01:16:36.6115936Z  
2017-10-06T01:16:36.6115936Z 
2017-10-06T01:16:36.6115936Z   -?
2017-10-06T01:16:36.6115936Z 
2017-10-06T01:16:36.6115936Z     Prints this information
2017-10-06T01:16:36.6115936Z 
2017-10-06T01:16:36.6115936Z 
2017-10-06T01:16:36.6115936Z 
2017-10-06T01:16:36.6115936Z   create|c ["instance name" [version-number] [-s]]
2017-10-06T01:16:36.6115936Z 
2017-10-06T01:16:36.6115936Z     Creates a new LocalDB instance with a specified name and version
2017-10-06T01:16:36.6115936Z 
2017-10-06T01:16:36.6115936Z     If the [version-number] parameter is omitted, it defaults to the
2017-10-06T01:16:36.6115936Z 
2017-10-06T01:16:36.6115936Z     latest LocalDB version installed in the system.
2017-10-06T01:16:36.6115936Z 
2017-10-06T01:16:36.6115936Z     -s starts the new LocalDB instance after it's created
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z   delete|d ["instance name"]
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z     Deletes the LocalDB instance with the specified name
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z   start|s ["instance name"]
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z     Starts the LocalDB instance with the specified name
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z  
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z   stop|p ["instance name" [-i|-k]]
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z     Stops the LocalDB instance with the specified name, 
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z     after current queries finish
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z     -i request LocalDB instance shutdown with NOWAIT option
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z     -k kills LocalDB instance process without contacting it
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z   share|h ["owner SID or account"] "private name" "shared name"
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z     Shares the specified private instance using the specified shared name. 
2017-10-06T01:16:36.6125943Z 
2017-10-06T01:16:36.6125943Z     If the user SID or account name is omitted, it defaults to current user.
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z   unshare|u ["shared name"]
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z     Stops the sharing of the specified shared LocalDB instance.
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z   info|i
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z     Lists all existing LocalDB instances owned by the current user
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z     and all shared LocalDB instances.
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z   info|i "instance name"
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z     Prints the information about the specified LocalDB instance.
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z   versions|v
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z     Lists all LocalDB versions installed on the computer.
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z   trace|t on|off
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z     Turns tracing on and off
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z SqlLocalDB treats spaces as delimiters. It is necessary to surround 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z instance names that contain spaces and special characters with quotes. 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z For example: 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z    SqlLocalDB create "My LocalDB Instance"
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z The instance name can sometimes be omitted, as indicated above, or
2017-10-06T01:16:36.6135966Z 
2017-10-06T01:16:36.6135966Z specified as "". In this case, the reference is to the default LocalDB
2017-10-06T01:16:36.6145956Z 
2017-10-06T01:16:36.6145956Z instance "MSSQLLocalDB".
2017-10-06T01:16:36.6145956Z 
2017-10-06T01:16:36.6251132Z Name:               TestingLocalDB
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z Version:            13.1.4001.0
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z Shared name:        
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z Owner:              FACTORYVM-AZ186\buildguest
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z Auto-create:        No
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z State:              Running
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z Last start time:    10/6/2017 1:16:35 AM
2017-10-06T01:16:36.6261137Z 
2017-10-06T01:16:36.6261137Z Instance pipe name: np:\\.\pipe\LOCALDB#48FCB69C\tsql\query
2017-10-06T01:16:36.6261137Z 
2017-10-06T01:16:46.7931803Z LocalDB instance "TestingLocalDB" stopped.
2017-10-06T01:16:46.7931803Z 
2017-10-06T01:16:47.7483059Z LocalDB instance "TestingLocalDB" started.
2017-10-06T01:16:47.7483059Z 
2017-10-06T01:16:47.7883240Z ##[section]Finishing: Create LocalDb
```

### Test Run Results
```
017-10-06T01:16:47.7893239Z ##[section]Starting: Run Tests
2017-10-06T01:16:47.7903237Z ==============================================================================
2017-10-06T01:16:47.7903237Z Task         : .NET Core
2017-10-06T01:16:47.7903237Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command. For package commands, supports NuGet.org and authenticated feeds like Package Management and MyGet.
2017-10-06T01:16:47.7903237Z Version      : 2.1.5
2017-10-06T01:16:47.7903237Z Author       : Microsoft Corporation
2017-10-06T01:16:47.7903237Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
2017-10-06T01:16:47.7903237Z ==============================================================================
2017-10-06T01:16:48.6366998Z [command]d:\a\_tool\dncs\2.0.0\x64\dotnet.exe test d:\a\3\s\CompanyXXX.SomeProduct.Api\test\CompanyXXX.SomeProduct.Api.Tests\CompanyXXX.SomeProduct.Api.Tests.csproj --configuration release
2017-10-06T01:16:51.1997242Z Build started, please wait...
2017-10-06T01:17:01.9576302Z Build completed.
2017-10-06T01:17:01.9576302Z 
2017-10-06T01:17:01.9596298Z Test run for d:\a\3\s\CompanyXXX.SomeProduct.Api\test\CompanyXXX.SomeProduct.Api.Tests\bin\release\netcoreapp2.0\CompanyXXX.SomeProduct.Api.Tests.dll(.NETCoreApp,Version=v2.0)
2017-10-06T01:17:02.0026059Z Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
2017-10-06T01:17:02.0026059Z Copyright (c) Microsoft Corporation.  All rights reserved.
2017-10-06T01:17:02.0026059Z 
2017-10-06T01:17:02.0785637Z Starting test execution, please wait...
2017-10-06T01:17:05.0156311Z [xUnit.net 00:00:01.2704470]   Discovering: CompanyXXX.SomeProduct.Api.Tests
2017-10-06T01:17:05.1695611Z [xUnit.net 00:00:01.4355184]   Discovered:  CompanyXXX.SomeProduct.Api.Tests
2017-10-06T01:17:05.2785109Z [xUnit.net 00:00:01.5447168]   Starting:    CompanyXXX.SomeProduct.Api.Tests
2017-10-06T01:17:07.9694248Z Connecting to database TestingLocalDB
2017-10-06T01:17:08.2663132Z Creating The Database
2017-10-06T01:17:24.3336177Z [xUnit.net 00:00:20.5981935]     CompanyXXX.SomeProduct.Api.Tests.DatabaseMigrationsTest.DatabaseMigrationsWork [FAIL]
2017-10-06T01:17:24.3346174Z [xUnit.net 00:00:20.5996440]       System.Data.SqlClient.SqlException : Cannot open database "Origin" requested by the login. The login failed.
2017-10-06T01:17:24.3356169Z [xUnit.net 00:00:20.5997165]       Login failed for user 'FACTORYVM-AZ186\buildguest'.
2017-10-06T01:17:24.3356169Z [xUnit.net 00:00:20.6007622]       Stack Trace:
2017-10-06T01:17:24.3366166Z [xUnit.net 00:00:20.6019649]            at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
2017-10-06T01:17:24.3366166Z [xUnit.net 00:00:20.6021468]            at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
2017-10-06T01:17:24.3376167Z [xUnit.net 00:00:20.6022938]            at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
2017-10-06T01:17:24.3376167Z [xUnit.net 00:00:20.6024178]            at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
2017-10-06T01:17:24.3586153Z [xUnit.net 00:00:20.6025458]            at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
2017-10-06T01:17:24.3586153Z [xUnit.net 00:00:20.6027221]            at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6028466]            at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6029184]            at System.Data.SqlClient.SqlConnection.Open()
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6029807]            at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6030331]            at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6030961]            at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6032027]            at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6032676]            at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6033610]            at lambda_method(Closure , QueryContext )
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6034258]            at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6034780]            at System.Linq.Queryable.Any[TSource](IQueryable`1 source)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6035537]         d:\a\3\s\CompanyXXX.SomeProduct.Api\src\CompanyXXX.SomeProduct.Data\Migrations\20171002200332_SeedCreditBureauRequests.cs(15,0): at CompanyXXX.SomeProduct.Data.Migrations.SeedCreditBureauRequests.Up(MigrationBuilder migrationBuilder)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6036834]            at Microsoft.EntityFrameworkCore.Migrations.Migration.BuildOperations(Action`1 buildAction)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6037437]            at Microsoft.EntityFrameworkCore.Migrations.Migration.<.ctor>b__4_1()
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6037945]            at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6038526]            at Microsoft.EntityFrameworkCore.Migrations.Migration.get_UpOperations()
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6039238]            at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6147047]            at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.<>c__DisplayClass13_2.<GetMigrationCommandLists>b__2()
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6147767]            at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
2017-10-06T01:17:24.3596150Z [xUnit.net 00:00:20.6148406]         d:\a\3\s\CompanyXXX.SomeProduct.Api\test\CompanyXXX.SomeProduct.Api.Tests\DatabaseMigrationsTest.cs(38,0): at CompanyXXX.SomeProduct.Api.Tests.DatabaseMigrationsTest.DatabaseMigrationsWork()
2017-10-06T01:17:24.3596150Z Failed   CompanyXXX.SomeProduct.Api.Tests.DatabaseMigrationsTest.DatabaseMigrationsWork
```

**Comment by TingluoHuang** [comment]
@scottwojan can you use `SqlLocalDB` create a new db and run dotnet test successfully on your local dev box?

**Comment by scottwojan** [comment]
Yes, it runs completely fine locally

**Comment by TingluoHuang** [comment]
@scottwojan i am not familiar with that tool, does it require admin privilege to run?
the build runs on hosted agent is not running as admin.

**Comment by scottwojan** [comment]
@TingluoHuang 
These lines above show that SqlLocalDB is being run successfully by the agent:
`2017-10-06T01:16:27.2107798Z MSSQLLocalDB
2017-10-06T01:16:36.5965808Z LocalDB instance "TestingLocalDB" created with version 13.1.4001.0.
2017-10-06T01:16:36.5965808Z 
2017-10-06T01:16:36.5975820Z LocalDB instance "TestingLocalDB" started.
`
And this shows that the database was created and the owner IS the account the agent is running as:
`
017-10-06T01:16:36.6145956Z instance "MSSQLLocalDB".
2017-10-06T01:16:36.6145956Z 
2017-10-06T01:16:36.6251132Z Name:               TestingLocalDB
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z Version:            13.1.4001.0
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z Shared name:        
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z Owner:              FACTORYVM-AZ186\buildguest
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z Auto-create:        No
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z State:              Running
2017-10-06T01:16:36.6251132Z 
2017-10-06T01:16:36.6251132Z Last start time:    10/6/2017 1:16:35 AM
2017-10-06T01:16:36.6261137Z 
2017-10-06T01:16:36.6261137Z Instance pipe name: np:\\.\pipe\LOCALDB#48FCB69C\tsql\query
`

**Comment by stephenmichaelf** [comment]
@scottwojan What is the authentication mechanism being used?

**Comment by scottwojan** [comment]
Integrated Auth

**Comment by stephenmichaelf** [comment]
Can you try using a username/pw and see if it works?

**Comment by TingluoHuang** [comment]
doesn't looks like an agent problem. please log an issue at https://github.com/Microsoft/vsts-image-generation if you need more help.

**Comment by scottwojan** [comment]
@TingluoHuang how can you close this if you don't know what the issue is?

**Comment by TingluoHuang** [comment]
@scottwojan the problem you run into seems like an environment problem to me not a build agent bug, that's why i want to redirect you to the image-generation repo, since that is the repository the hosted agent VM image got built. BTW, are you still running into this issue? i notice the hosted agent is now running as interactive user with admin privilege, the change happened for about a month.
