### ISSUE TITLE
Exit code 100 returned from process

### ISSUE THREAD

**Issue by balfa666** [Microsoft/vsts-agent#1273]
## Agent version and platform
Version of your agent? 2.123.0
OS of the machine running the agent? Windows Server 2012 R2

## VSTS type and version
On-Prem TFS 2017.u2
Multiple agents on same machine, using same acount

[Worker_20171030-163757-utc.log](https://github.com/Microsoft/vsts-agent/files/1428020/Worker_20171030-163757-utc.log)

## What's not working?
Build keep failing with workspace problems

## Agent and Worker's diag log
Exit code 100 returned from process: file name 'tf', arguments 'vc workspace /new /location:local /permission:Public ws_29_393 /collection:https:xxx.xxx.xxx /loginType:OAuth /login:.,******** /noprompt'.

**Comment by TingluoHuang** [comment]
@balfa666 what's the build error you get on your build log?

**Comment by balfa666** [comment]
[2017-10-30 16:38:02Z ERR  StepsRunner] Caught exception from step: Microsoft.VisualStudio.Services.Agent.ProcessExitCodeException: Exit code 100 returned from process: file name 'tf', arguments 'vc workspace /new /location:local /permission:Public ws_29_393 /collection:https://alm.investpsp.ca/tfs/IDS/ /loginType:OAuth /login:.,******** /noprompt'.
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCCommandManager.<RunCommandAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TFCommandManager.<WorkspaceNewAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCSourceProvider.<GetSourceAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.<GetSourceAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()

**Comment by TingluoHuang** [comment]
@balfa666 that's the worker diag log, what error you see on your build WebUI for that build (http://tfs:8080/tfs)?

**Comment by balfa666** [comment]
Exit code 100 returned from process: file name 'tf', arguments 'vc workspace /new /location:local /permission:Public ws_7_397 /collection:https://alm.investpsp.ca/tfs/IDS/ /loginType:OAuth /login:.,******** /noprompt'.

**Comment by TingluoHuang** [comment]
@balfa666 can you share the full build log from UI? there must be some output before that. :)

**Comment by balfa666** [comment]
There isn't much before, as it fails on get source.

2017-10-30T16:37:59.0666925Z ##[section]Starting: Build
2017-10-30T16:37:59.0666925Z Current agent version: '2.123.0'
2017-10-30T16:37:59.4885115Z ##[section]Starting: Initialize Job
2017-10-30T16:37:59.4885115Z Prepare build directory.
2017-10-30T16:37:59.5510331Z Set build variables.
2017-10-30T16:37:59.5667213Z Download all required tasks.
2017-10-30T16:37:59.6291495Z ##[section]Finishing: Initialize Job
2017-10-30T16:37:59.6760165Z ##[section]Starting: Get Sources
2017-10-30T16:37:59.7385633Z Prepending Path environment variable with directory containing 'tf.exe'.
2017-10-30T16:37:59.7385633Z Setting environment variable TFVC_BUILDAGENT_POLICYPATH
2017-10-30T16:37:59.7385633Z Querying workspace information.
2017-10-30T16:38:01.6136618Z ##[command]tf vc workspace /new /location:local /permission:Public ws_29_393 /collection:https://alm.investpsp.ca/tfs/IDS/ /loginType:OAuth /login:.,******** /noprompt
2017-10-30T16:38:02.2229034Z The path D:\b\2\29\s\BuildProcessTemplates\nuget.config is already mapped in workspace ws_29_393;Build\0c53621a-540e-4881-8040-62548469c477 [https://alm.investpsp.ca/tfs/ESD].
2017-10-30T16:38:02.3166576Z ##[error]Exit code 100 returned from process: file name 'tf', arguments 'vc workspace /new /location:local /permission:Public ws_29_393 /collection:https://alm.investpsp.ca/tfs/IDS/ /loginType:OAuth /login:.,******** /noprompt'.
2017-10-30T16:38:02.3166576Z ##[section]Finishing: Get Sources
2017-10-30T16:38:02.3166576Z ##[section]Starting: Post Job Cleanup
2017-10-30T16:38:02.3322776Z ##[section]Finishing: Post Job Cleanup
2017-10-30T16:38:02.3322776Z ##[section]Finishing: Build

**Comment by TingluoHuang** [comment]
`2017-10-30T16:38:02.2229034Z The path D:\b\2\29\s\BuildProcessTemplates\nuget.config is already mapped in workspace ws_29_393;Build\0c53621a-540e-4881-8040-62548469c477 [https://alm.investpsp.ca/tfs/ESD].`
that's the error cause TF.exe to failed.

**Comment by balfa666** [comment]
I cannot find the source of the error. It seems to point to variable Build.Clean being present, but i'm not sure about it

**Comment by TingluoHuang** [comment]
are you share single working directory for multiple agent on the same box?

**Comment by TingluoHuang** [comment]
@scottboehmer for TFVC question

**Comment by balfa666** [comment]
They are all configured to have different working directory on same server, but I do have another server with exactly the same setup.

Server 1
agent 1-8
working directory: D:\b\1-8

Server 2
Agent 1-8
working directory: D:\b\1-8

**Comment by scottboehmer** [comment]
Is this failing every build or only occasionally? If it is only failing occasionally, is there any pattern to when it fails?

**Comment by balfa666** [comment]
Without any checkin (same Source version), it will execute with success or fail randomly. We have multiple collections and they fail on all of them.

**Comment by scottboehmer** [comment]
One thing that you could try as a mitigation is reconfiguring the agents that are failing to use a new working directory.

Another approach would be to log in to the machine hosting the agents and use 'tf workspaces' to try to identify any conflicting workspace names and delete those conflicting workspaces.

**Comment by balfa666** [comment]
2 weeks ago we had to reinstall all of the agents. 
We installed the latest version 2.123.0 and used PAT instead of Integrated. 

Here is the temporary work around that works for about a day before we have to redo:
- Delete all workspaces related to servers and user with TFS sidekick
- Stop agents
- Delete cache on all servers (TFS and visual studio)
- Delete working directories of all agents
- Start Agents

**Comment by scottboehmer** [comment]
Did this problem exist before that reinstall or only after? Which agent version were you using before the reinstall?

**Comment by balfa666** [comment]
It started about a week after the reinstall. We where using the TFS 2015 agents, so version 1.xx

**Comment by balfa666** [comment]
I actually found the problem. We did a migration from XAML builds to Build 2.0. In the migration, some of the TFS variables where not converted to new format. Some of our builds execute custom scripts and since the variable was empty, it defaulted to root directory. 
In the scripts, the "remove-item -recurse" deleted all the files including the SourceRootMapping folder.

**Comment by ThePickNick** [comment]
Agent version 2.140.2

OS Ubuntu 18.04

We are getting similar error during get sources task 

2018-10-05T15:33:20.4980390Z ##[section]Starting: Checkout
2018-10-05T15:33:20.5437480Z ==============================================================================
2018-10-05T15:33:20.5437846Z Task         : Get sources
2018-10-05T15:33:20.5437911Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2018-10-05T15:33:20.5437964Z Version      : 1.0.0
2018-10-05T15:33:20.5438100Z Author       : Microsoft
2018-10-05T15:33:20.5438185Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2018-10-05T15:33:20.5438234Z ==============================================================================
2018-10-05T15:33:21.5879887Z Prepending PATH environment variable with directory containing 'tf'.
2018-10-05T15:33:21.5998745Z ##[command]tf eula -accept
2018-10-05T15:33:24.2302627Z ##[warning]Exit code 100 returned from process: file name 'tf', arguments 'eula -accept'.
2018-10-05T15:33:24.2359803Z Querying workspace information.
2018-10-05T15:33:26.8131697Z ##[error]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 100 returned from process: file name 'tf', arguments 'workspaces -format:xml "-collection:https://rttsnyc.visualstudio.com/" -jwt:*** -noprompt'.
   at Agent.Plugins.Repository.TeeCliManager.<WorkspacesAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.Plugins.Repository.TfsVCSourceProvider.<GetSourceAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.Plugins.Repository.CheckoutTask.<RunAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Agent.PluginHost.Program.Main(String[] args)
2018-10-05T15:33:26.8519680Z ##[section]Finishing: Checkout

**Comment by TingluoHuang** [comment]
@ThePickNick did you accept the ` tf eula` when you configure the agent?

**Comment by ThePickNick** [comment]
> @ThePickNick did you accept the `tf eula` when you configure the agent?

Yes, it wont let me configure the agent if i didn't accept it, that is why this look so weird to me.

**Comment by TingluoHuang** [comment]
@ThePickNick is your agent running as service? i noticed during `get sources` the agent also try to run `tf eula --accept` but also failed.

**Comment by ThePickNick** [comment]
@TingluoHuang  I run both ways As a service and interactively same issue.

**Comment by TingluoHuang** [comment]
@ThePickNick  can you run `tf eula -accept` manually from bash?  you can find `tf` under `agentroot/externals/tee/tf`

**Comment by ThePickNick** [comment]
@TingluoHuang  when I run it as a command there is no error don't relay know if anything happens but it does not spit out anything as it is in vsts

**Comment by TingluoHuang** [comment]
@ThePickNick when running as part of your build it failed with 100, what version of JAVA do you have on the machine?
```
2018-10-05T15:33:21.5998745Z ##[command]tf eula -accept
2018-10-05T15:33:24.2302627Z ##[warning]Exit code 100 returned from process: file name 'tf', arguments 'eula -accept'.
```

**Comment by ThePickNick** [comment]
rtts@rtts-virtual-machine:/opt/agent/externals/tee$ java --version
    openjdk 10.0.2 2018-07-17
    OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
    OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)

**Comment by TingluoHuang** [comment]
@ThePickNick can you try install Oracle Java? 1.6+

**Comment by ThePickNick** [comment]
@TingluoHuang after installing java 8 from oracle the get sources works! thanks for the help!

**Comment by TingluoHuang** [comment]
@ThePickNick can you share what exactly command you use to install? i might want to update the doc. :D

**Comment by ThePickNick** [comment]
add repo
     sudo add-apt-repository ppa:webupd8team/java

    install java 
     sudo apt install oracle-java8-installer
