### ISSUE TITLE
Linux ubuntu symlink Loop on Publish Artefact

### ISSUE THREAD

**Issue by alxdean** [Microsoft/vsts-agent#1279]
Hey folks, 
I've been trying to get the agent to run on my Ubuntu 17.10 machine but have had little luck. 
I get it installed and configured, even accepting jobs.
getting the repo is fine
But when it comes to publishing the artefact it dies on me. 

## Agent version and platform
vsts-agent-ubuntu.16.04-x64-2.123.0

OS of the machine running the agent? 
Ubuntu 17.10

## VSTS type and version
https://wholesalebydesign.visualstudio.com

## What's not working?
if I run the service using a normal user account I get following error:
##[error]Access to the path '/mnt/lost+found' is denied.

if I change permissions on that folder to 766 I instead get this error for a user who is not root
##[error]Access to the path '/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4750/root/proc/4731/ns' is denied.

now that looks like we're looping down the rabbit hole!!!

so when I then re-install the service under the root account (btw, the uninstall does not work on ubuntu 17.10 and I had to manually remove the systemd components)

I get following error instead (with extra debug info):
2017-11-05T12:02:46.5469830Z ##[error]Too many levels of symbolic links
2017-11-05T12:02:46.5530430Z ##[debug]System.IO.IOException: Too many levels of symbolic links
   at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)
   at System.IO.UnixFileSystem.FileSystemEnumerable`1.<Enumerate>d__11.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.FileContainerServer.<CopyToContainerAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.ArtifactCommandExtension.<UploadArtifactAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.AsyncCommandContext.<WaitAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2017-11-05T12:02:46.5564910Z ##[section]Finishing: Publish Artifact: website

the agent and worker logs are not giving me anything more. 

I'm not sure where the endless loop is being triggered, but it's for sure happening.

**Comment by TingluoHuang** [comment]
@alxdean how did you configure the agent service run as normal account instead of root?
the `./svc.sh` should has the check to make sure you run `./svc.sh install` as `sudo`.
what error you get when you try uninstall the service from `Systemd`?

I not sure about what's going on for the symlink loop, might be a bug in NetCore 1.x itself.

We are in the process of releasing a newer version agent that target netcore 2.x, you can try that once it is available.

**Comment by TingluoHuang** [comment]
@alxdean we only support the 2.123.0 agent on Ubuntu 14.04 and Ubuntu 16.04 (officially supported by NetCore 1.x). 
the next version we are going to release should works fine on Ubuntu 17.x (officially supported by Netcore 2.x)

**Comment by TingluoHuang** [comment]
@alxdean latest agent: https://github.com/Microsoft/vsts-agent/releases/tag/v2.125.0

**Comment by alxdean** [comment]
Hi,
when I install using sudo, it still runs under the current user. not root.
only when I switch using sudo su does it actually run under root

when i run svc.sh uninstall, all it does it stop the service. never
actually uninstalls anything. no error message. just a friendly message
that the service is stopped. which it was anyway already. so not sure what
it actually does.

Thanks for sending through the link for the new agent. will give it a try
and update you.

*-- *
*Alex Dean*
Enterprise Consultant
PTI Solutions
Phone:  +61 452 585 440 | *Web: http://www.linkedin.com/in/alxdean
<http://www.linkedin.com/in/alxdean>  *

**Comment by bryanmacfarlane** [comment]
@alxdean - any updates?
