### ISSUE TITLE
deployment agent installation error

### ISSUE THREAD

**Issue by vvikram05** [Microsoft/vsts-agent#1348]
We aere facing error while deployment on 2088 R2 SP1 servers.

[2017-12-28 01:02:42Z INFO RSAEncryptedFileKeyManager] Creating new RSA key using 2048-bit key length
[2017-12-28 01:02:42Z ERR  Agent] Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Object was not found
   at System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey(String algorithm, Int32 keySize)
   at System.Security.Cryptography.RSAImplementation.RSACng.GetDuplicatedKeyHandle()
   at System.Security.Cryptography.RSAImplementation.RSACng.ExportKeyBlob(Boolean includePrivateParameters)
   at System.Security.Cryptography.RSAImplementation.RSACng.ExportParameters(Boolean includePrivateParameters)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.RSAEncryptedFileKeyManager.CreateKey()
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess

**Comment by TingluoHuang** [comment]
@vvikram05 during configuration, what is your run as user? which user run the `config.cmd`?

**Comment by TingluoHuang** [comment]
@vvikram05 any news?

**Comment by TingluoHuang** [comment]
@vvikram05 are you still hitting this issue? I am going to close the issue for now, please reopen if needed.
