### ISSUE TITLE
Private agent gets error when running build: Exit code 100 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:https://oursite.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt'.

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/vsts-agent#1357]
Private agent (version vsts-agent-win-x64-2.126.0) running on local machine gets error when trying to build online VSTS with error:

````
Exit code 100 returned from process: file   name 'tf', arguments 'vc workspaces /format:xml   /collection:https://oursite.visualstudio.com/ /loginType:OAuth   /login:.,******** /noprompt'.
--
````
This happend during **Get Sources**. Log i have is this one:

````
2018-01-05T13:15:29.0871931Z ##[debug]Evaluating condition for step: 'Get Sources'
2018-01-05T13:15:29.0904430Z ##[debug]Evaluating: succeeded()
2018-01-05T13:15:29.0914310Z ##[debug]Evaluating succeeded:
2018-01-05T13:15:29.0950061Z ##[debug]=> (Boolean) True
2018-01-05T13:15:29.0993889Z ##[debug]Expanded: True
2018-01-05T13:15:29.0994315Z ##[debug]Result: True
2018-01-05T13:15:29.1060057Z ##[section]Starting: Get Sources
2018-01-05T13:15:29.1109399Z ##[debug]Sync source for endpoint: Ivan-test
2018-01-05T13:15:29.1609243Z Prepending Path environment variable with directory containing 'tf.exe'.
2018-01-05T13:15:29.1617489Z ##[debug]Path: 'C:\agent\externals\vstsom;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Docker\Docker\Resources\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Docker;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Java\jre1.8.0_151\;C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools\;C:\Users\idordevic\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin'
2018-01-05T13:15:29.1621362Z Setting environment variable TFVC_BUILDAGENT_POLICYPATH
2018-01-05T13:15:29.1622498Z Querying workspace information.
2018-01-05T13:15:29.1804999Z ##[debug]tf vc workspaces /format:xml /collection:https://oursite.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt
2018-01-05T13:15:29.4040638Z ##[debug]Method not found: 'Microsoft.VisualStudio.Services.Common.VssCredentials Microsoft.VisualStudio.Services.Common.VssCredentials.LoadCachedCredentialsFromRegisteredProviders(System.Uri, Boolean ByRef)'.
2018-01-05T13:15:29.4063773Z Method not found: 'Microsoft.VisualStudio.Services.Common.VssCredentials Microsoft.VisualStudio.Services.Common.VssCredentials.LoadCachedCredentialsFromRegisteredProviders(System.Uri, Boolean ByRef)'.
2018-01-05T13:15:29.4294822Z ##[error]Exit code 100 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:https://oursite.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt'.
2018-01-05T13:15:29.4353125Z ##[debug]Microsoft.VisualStudio.Services.Agent.ProcessExitCodeException: Exit code 100 returned from process: file name 'tf', arguments 'vc workspaces /format:xml /collection:https://oursite.visualstudio.com/ /loginType:OAuth /login:.,******** /noprompt'.
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCCommandManager.<RunPorcelainCommandAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TFCommandManager.<WorkspacesAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCSourceProvider.<GetSourceAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.<GetSourceAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2018-01-05T13:15:29.4360372Z ##[section]Finishing: Get Sources

````

**Comment by TingluoHuang** [comment]
@ivandjordjevic where did you get your private agent? can you zip up your agent's `externals\vstsom` folder and share with us? i am wonder there is a assembly mismatch.

**Comment by shtratos** [comment]
Related? #1358

**Comment by TingluoHuang** [comment]
@shtratos they are 2 different error.
```
2018-01-05T13:15:29.4040638Z ##[debug]Method not found: 'Microsoft.VisualStudio.Services.Common.VssCredentials Microsoft.VisualStudio.Services.Common.VssCredentials.LoadCachedCredentialsFromRegisteredProviders(System.Uri, Boolean ByRef)'.
```
VS
```
2018-01-05T12:13:08.5537766Z ##[debug]Invalid URI: The hostname could not be parsed.
```

**Comment by ivandjordjevic** [comment]
@TingluoHuang Try this [link](https://drive.google.com/file/d/1UFjrAbpz-rn_EalEYXospBNThCn5MTEg/view?usp=sharing).

**Comment by ivandjordjevic** [comment]
@TingluoHuang Does this dll looks good to you?

**Comment by TingluoHuang** [comment]
@ivandjordjevic can you check your GAC on that box? see whether this is an assembly like `Microsoft.VisualStudio.Services.Common`

**Comment by TingluoHuang** [comment]
`gacutil /l | findstr /I Microsoft.VisualStudio.*`

check #956 as reference.

**Comment by TingluoHuang** [comment]
@ivandjordjevic the binary looks fine, i guess there is an "evil" assembly in your GAC.

**Comment by ivandjordjevic** [comment]
I was able to get pass this issue when installing on different VM. Not sure the dll's were conflicting here.

I definitely had Microsoft.VisualStudio.Services.Common in GAC already.

**Comment by TingluoHuang** [comment]
@ivandjordjevic do you have idea why you have that assembly in GAC? did you put in yourself, or it installed by some software?
I want to find the source of that assembly since it should never be added into GAC.
