### ISSUE TITLE
Configuring agent for deployment group- error during final connection test from agent

### ISSUE THREAD

**Issue by vimudda** [Microsoft/vsts-agent#1376]
## Have you try trouble shooting doc?
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting
Yes, nothing helped 
## Agent version and platform
Version of your agent? 2.126.0 on Windows 

OS of the machine running the agent? OSX/Windows/Linux...
Windows 2008 R2 with PowerShell V3
## VSTS type and version
VisualStudio.com 

If On-Prem TFS, which release, 2015 RTM/QU1/QU2?

If VisualStudio.com, what is your account name? http://account.visualstudio.com
https://deloittebsg.visualstudio.com

## What's not working?
While configuring an agent in deployment group or just as an agent, the step fails at the last stage of testing connection. While performing configuration as deployment group agent, agent is visible under the deployment group in VSTS but the error remains the same. 

Have tried with existing PAT (expiry Jan 2019) and with a newly created PAT as well. 

Error:
Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
**An error occurred while sending the request.**

## Agent and Worker's diag log
 [2018-01-18 11:52:49Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\vstsagent\.credentials_rsaparams
[2018-01-18 11:52:49Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2018-01-18 11:52:49Z WARN VisualStudioServices] Authentication failed with status code 401.
Date: Thu, 18 Jan 2018 11:52:49 GMT
Server: Microsoft-IIS/10.0
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/36da45f1-dd2c-4d1f-af13-5abe46b99921, Basic realm="https://tfsprodcus1.app.visualstudio.com/", TFS-Federated

2018-01-18 11:52:49Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\vstsagent\.credentials_rsaparams
[2018-01-18 11:52:49Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\vstsagent\.credentials_rsaparams
[2018-01-18 11:53:10Z ERR  VisualStudioServices] POST request to https://deloittebsg.vssps.visualstudio.com/_apis/oauth2/token failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

2018-01-18 11:53:10Z ERR  VisualStudioServices] GET request to https://deloittebsg.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---

[2018-01-18 11:53:10Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\vstsagent\.credentials_rsaparams
[2018-01-18 11:53:31Z ERR  VisualStudioServices] POST request to https://deloittebsg.vssps.visualstudio.com/_apis/oauth2/token failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out

## when it configures agent and enters test phase, it gets a 401 which is kind of misleading to me** Any help is appreciated.

**Comment by TingluoHuang** [comment]
@vimudda do you have any proxy/firewall between the agent machine and VSTS that may block the traffic?

**Comment by vimudda** [comment]
@TingluoHuang Thanks for the response.

Before starting the configuration, firewall port has been opened from the source server to destination. Have tested via telnet and communication opens up fine over 443.

The setup of proxy ( and firewall rules) are same for this server and another already working one.

What i don't understand is the agent gets partially configured (visible in VSTS) but fails at the final stage of configuration which is testing agent connection!

**Comment by TingluoHuang** [comment]
@vimudda the final step calls the different endpoint.
https://deloittebsg.vssps.visualstudio.com/ VS https://deloittebsg.visualstudio.com/

Can you test your setup with a PowerShell script see whether you can hit that endpoint?

**Comment by TingluoHuang** [comment]
@vimudda are you still hitting this issue? I am going to close the issue for now, please reopen if needed.
