### ISSUE TITLE
"CurlException: SSL connect error" when connecting with self-signed certificate

### ISSUE THREAD

**Issue by hpbieker** [Microsoft/vsts-agent#1440]
## Agent version and platform
```
$ docker pull microsoft/vsts-agent:ubuntu-16.04-tfs-2018
Digest: sha256:f7e547d89d96433d5d9701bdfb715a665a7c67e64aaf5af3f84a4412f6fc155d
Status: Image is up to date for microsoft/vsts-agent:ubuntu-16.04-tfs-2018
$ ./agent/bin/Agent.Listener --version
2.122.1
$ uname -a
Linux 6148c93de81c 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

## VSTS type and version
On-Prem TFS 2017 15.117.26714.0

## What's not working?
The tsts-agent is not able to connect to the tfs server. The tfs server is using a self signed certificate.

```
Connecting to server ...
An error occurred while sending the request.
```

The exception reported in the log is:
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL connect error
    at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
    at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
```

My Dockerfile looks like:
```
FROM microsoft/vsts-agent:ubuntu-16.04-tfs-2017
COPY selfsigned.crt /usr/share/ca-certificates/selfsigned.crt 
RUN echo selfsigned.crt >> /etc/ca-certificates.conf && update-ca-certificates
```

running curl within the containers works without ssl issues:
```
* Connected to XXX.XXX.com (10.12.3.142) port 443 (#0)
* found 149 certificates in /etc/ssl/certs/ca-certificates.crt
* found 596 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_CBC_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: XXX-XXX-XXX.XXX.XXX.COM (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=CH,L=XXX,O=XXX Ltd.,CN=XXX-XXX-XXX.XXX.XXX.COM
* 	 start date: Thu, 07 Dec 2017 14:25:51 GMT
* 	 expire date: Thu, 14 May 2020 16:06:46 GMT
* 	 issuer: DC=COM,DC=XXX,O=XXX,CN=XX Issuing CA 3
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> Host: XXX.XXX.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Content-Type: text/html; charset=utf-8
< Server: Microsoft-IIS/8.5
< X-TFS-ProcessId: ef9de70a-322b-49aa-ad2b-858560a94f19
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< ActivityId: 039f6806-aa86-492a-82da-9d0c96161caa
< X-TFS-Session: 039f6806-aa86-492a-82da-9d0c96161caa
< X-VSS-E2EID: 039f6806-aa86-492a-82da-9d0c96161caa
< X-FRAME-OPTIONS: SAMEORIGIN
< X-TFS-SoapException: %3c%3fxml+version%3d%221.0%22+encoding%3d%22utf-8%22%3f%3e%3csoap%3aEnvelope+xmlns%3asoap%3d%22http%3a%2f%2fwww.w3.org%2f2003%2f05%2fsoap-envelope%22%3e%3csoap%3aBody%3e%3csoap%3aFault%3e%3csoap%3aCode%3e%3csoap%3aValue%3esoap%3aReceiver%3c%2fsoap%3aValue%3e%3csoap%3aSubcode%3e%3csoap%3aValue%3eUnauthorizedRequestException%3c%2fsoap%3aValue%3e%3c%2fsoap%3aSubcode%3e%3c%2fsoap%3aCode%3e%3csoap%3aReason%3e%3csoap%3aText+xml%3alang%3d%22en%22%3eTF400813%3a+Resource+not+available+for+anonymous+access.+Client+authentication+required.%3c%2fsoap%3aText%3e%3c%2fsoap%3aReason%3e%3c%2fsoap%3aFault%3e%3c%2fsoap%3aBody%3e%3c%2fsoap%3aEnvelope%3e
< X-TFS-ServiceError: TF400813%3a+Resource+not+available+for+anonymous+access.+Client+authentication+required.
< WWW-Authenticate: Bearer
< WWW-Authenticate: Basic realm="https://XXX.XXX.com/tfs"
< WWW-Authenticate: Negotiate
< WWW-Authenticate: NTLM
< X-Powered-By: ASP.NET
< P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
< Lfs-Authenticate: NTLM
< X-Content-Type-Options: nosniff
< Date: Tue, 06 Mar 2018 11:50:22 GMT
< Content-Length: 20076
< 
{ [14811 bytes data]
100 20076  100 20076    0     0  33465      0 --:--:-- --:--:-- --:--:-- 33460
* Connection #0 to host XXX.XXX.com left intact
```

## Agent and Worker's diag log
[agent.log](https://github.com/Microsoft/vsts-agent/files/1784808/agent.log)

**Comment by TingluoHuang** [comment]
@hpbieker base on the agent log, you are on really old version agent.
can you confirm whether this is still a problem in latest version agent?
```
[2018-03-06 11:37:09Z INFO AgentProcess] Agent is built for Linux - ubuntu.16.04-x64.
[2018-03-06 11:37:09Z INFO AgentProcess] RuntimeInformation: Linux 4.4.104-boot2docker #1 SMP Fri Dec 8 19:23:27 UTC 2017.
[2018-03-06 11:37:09Z INFO AgentProcess] Version: 2.105.7
[2018-03-06 11:37:09Z INFO AgentProcess] Commit: 5f286b1f01c51b7cace8c1649edd6b00893a3649
[2018-03-06 11:37:09Z INFO AgentProcess] Culture: 
[2018-03-06 11:37:09Z INFO AgentProcess] UI Culture: 
```

**Comment by hpbieker** [comment]
Thank you @TingluoHuang . It is the same result with agent 2.122.1 provided by the microsoft/vsts-agent:ubuntu-16.04-tfs-2018 docker image. See log below. I notice that i get two different exception messages for some reason.
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL connect error
```
and 
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Peer certificate cannot be authenticated with given CA certificates
```

[agent-2018.log](https://github.com/Microsoft/vsts-agent/files/1792158/agent-2018.log)

Is this the correct way to add a self signed sertificate? And is my assumption correct that if it works in curl it should work in the agent?

**Comment by hpbieker** [comment]
It got it working after changing the certificate file to the root certificate. It looks like multiple certificates are involved here.
