### ISSUE TITLE
In build definition intermittently task(VsTest Platform Installer) not getting executed 

### ISSUE THREAD

**Issue by smadala** [Microsoft/vsts-agent#1492]
- We have observing intermittently  VsTest Platform Installer task not getting executed, due to this vstest task failing with error `Error: VsTest Test Platform folder was not found in cache`.

- From logs it appears task execution not started (can't find [this](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTestPlatformToolInstaller/vstestplatformtoolinstaller.ts#L27) logging). 

- Attaching logs.
[logs_8859794.zip](https://github.com/Microsoft/vsts-agent/files/1874623/logs_8859794.zip)

This build definition 
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=8859794&_a=summary&tab=details
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=8859111&_a=summary&tab=details
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=8858765&_a=summary&tab=details
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=8858417&_a=summary&tab=details

- This was the reason to fail 8 out of 40 build failures in last 12 hours.

**Comment by smadala** [comment]
Created [a bug](https://mseng.visualstudio.com/DefaultCollection/VSOnline/_workitems/edit/1226424) in mseng to track this internally. Set the priority to P1.

**Comment by bryanmacfarlane** [comment]
There’s no diag logs or anything indicates caring this is an agent issue.  Reactive with more details

**Comment by ShreyasRmsft** [comment]
`2018-04-05T01:20:05.0231224Z ##[debug]Evaluating condition for step: 'VsTest Platform Installer'
2018-04-05T01:20:05.0231801Z ##[debug]Evaluating: succeeded()
2018-04-05T01:20:05.0232136Z ##[debug]Evaluating succeeded:
2018-04-05T01:20:05.0232471Z ##[debug]=> (Boolean) True
2018-04-05T01:20:05.0232794Z ##[debug]Expanded: True
2018-04-05T01:20:05.0233061Z ##[debug]Result: True
2018-04-05T01:20:05.0233346Z ##[section]Starting: VsTest Platform Installer
2018-04-05T01:20:05.0236708Z ==============================================================================
2018-04-05T01:20:05.0236923Z Task         : Visual Studio Test Platform Installer
2018-04-05T01:20:05.5370082Z Description  : Acquires the test platform from nuget.org or the tools cache. Satisfies the ‘vstest’ demand and can be used for running tests and collecting diagnostic data using the Visual Studio Test task.
2018-04-05T01:20:05.5370864Z Version      : 1.0.9
2018-04-05T01:20:05.5371010Z Author       : Microsoft Corporation
2018-04-05T01:20:05.5371298Z Help         : <a href="https://www.nuget.org/packages/Microsoft.TestPlatform/">Test platform package on NuGet</a>
2018-04-05T01:20:05.5371552Z ==============================================================================
2018-04-05T01:20:14.8021164Z ##[debug]agent.workFolder=E:\work
2018-04-05T01:20:19.8026377Z ##[debug]loading inputs and endpoints
2018-04-05T01:20:19.8044039Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2018-04-05T01:20:20.1016972Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2018-04-05T01:20:20.1369023Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2018-04-05T01:20:25.7409955Z ##[debug]loading INPUT_TESTPLATFORMVERSION
2018-04-05T01:20:30.4905118Z ##[debug]loading INPUT_VERSIONSELECTOR
2018-04-05T01:20:35.2403944Z ##[debug]loading SECRET_VSOACCESSTOKEN
2018-04-05T01:20:39.9903582Z ##[debug]loaded 6
2018-04-05T01:20:44.7405088Z ##[debug]Agent.ProxyUrl=undefined
2018-04-05T01:20:47.0261062Z ##[debug]check path : E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\node_modules\vsts-task-tool-lib\lib.json
2018-04-05T01:20:52.3963411Z ##[debug]adding resource file: E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\node_modules\vsts-task-tool-lib\lib.json
2018-04-05T01:20:52.3964830Z ##[section]Finishing: VsTest Platform Installer
`


Corresponding agent diagnostic logs file
[Build 8895023_Msn.Web.AdExperience.Tests.dll_MSN.Service.Web.Prime-Test.UnitTests.1-Phase 1.zip](https://github.com/Microsoft/vsts-agent/files/1878713/Build.8895023_Msn.Web.AdExperience.Tests.dll_MSN.Service.Web.Prime-Test.UnitTests.1-Phase.1.zip)


There seem to be no indication of any errors in the agent diagnostic logs, It is just that the execution is stopping abruptly. From the timing in the logs the last line printed in the logs corresponds to loading the resources file

2018-04-05T01:20:52.3963411Z ##[debug]adding resource file: E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\node_modules\vsts-task-tool-lib\lib.json
2018-04-05T01:20:52.3964830Z ##[section]Finishing: VsTest Platform Installer

And from the agent diagnostics:

[2018-04-05 01:20:05Z INFO ProcessInvoker] Starting process:
[2018-04-05 01:20:05Z INFO ProcessInvoker]   File name: 'C:\Agent\externals\node\bin\node.exe'
[2018-04-05 01:20:05Z INFO ProcessInvoker]   Arguments: '"E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\vstestplatformtoolinstaller.js"'
[2018-04-05 01:20:05Z INFO ProcessInvoker]   Working directory: 'E:\work\1\s'
[2018-04-05 01:20:05Z INFO ProcessInvoker]   Require exit code zero: 'True'
[2018-04-05 01:20:05Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2018-04-05 01:20:05Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2018-04-05 01:20:05Z INFO ProcessInvoker] Process started with process id 6908, waiting for process exit.
[2018-04-05 01:20:13Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2018-04-05 01:20:19Z INFO JobServerQueue] Try to upload 1 log files or attachments, success rate: 1/1.
[2018-04-05 01:20:20Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2018-04-05 01:20:25Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2018-04-05 01:20:35Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2018-04-05 01:20:39Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2018-04-05 01:20:39Z INFO ProcessInvoker] Scan all processes to find relationship between all processes.
[2018-04-05 01:20:45Z INFO ProcessInvoker] Find all child processes of process '6908'.
[2018-04-05 01:20:45Z INFO ProcessInvoker] Kill process '6908'.
[2018-04-05 01:20:47Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2018-04-05 01:20:47Z ERR  ProcessInvoker] Ignore Win32Exception with NativeErrorCode 5 during Process.Kill().
[2018-04-05 01:20:47Z ERR  ProcessInvoker] System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.Kill()
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.WindowsKillProcessTree()
[2018-04-05 01:20:52Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:46.7198257.
[2018-04-05 01:20:52Z INFO StepsRunner] Step result: 

Execution ended without execution the complete task script.

**Comment by ShreyasRmsft** [comment]
@bryanmacfarlane Also the execution stops at various points before ever coming to our task code. Each time the last line in the logs is different (Indicating that it's not failing at a particular point in the task or something)

https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=8859794&_a=summary

2018-04-03T19:56:07.6174873Z ##[debug]Evaluating condition for step: 'VsTest Platform Installer'
2018-04-03T19:56:07.6175454Z ##[debug]Evaluating: succeeded()
2018-04-03T19:56:07.6175677Z ##[debug]Evaluating succeeded:
2018-04-03T19:56:07.6176004Z ##[debug]=> (Boolean) True
2018-04-03T19:56:07.6176345Z ##[debug]Expanded: True
2018-04-03T19:56:07.6176629Z ##[debug]Result: True
2018-04-03T19:56:07.6176931Z ##[section]Starting: VsTest Platform Installer
2018-04-03T19:56:07.6180250Z ==============================================================================
2018-04-03T19:56:07.6180463Z Task         : Visual Studio Test Platform Installer
2018-04-03T19:56:07.6521840Z Description  : Acquires the test platform from nuget.org or the tools cache. Satisfies the ‘vstest’ demand and can be used for running tests and collecting diagnostic data using the Visual Studio Test task.
2018-04-03T19:56:07.6522570Z Version      : 1.0.9
2018-04-03T19:56:07.6522753Z Author       : Microsoft Corporation
2018-04-03T19:56:07.6522927Z Help         : <a href="https://www.nuget.org/packages/Microsoft.TestPlatform/">Test platform package on NuGet</a>
2018-04-03T19:56:07.6523168Z ==============================================================================
2018-04-03T19:56:14.5122427Z ##[debug]agent.workFolder=E:\work
2018-04-03T19:56:14.5123154Z ##[debug]loading inputs and endpoints
2018-04-03T19:56:14.5587093Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2018-04-03T19:56:14.6054338Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2018-04-03T19:56:14.6522803Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2018-04-03T19:56:17.1527418Z ##[debug]loading INPUT_TESTPLATFORMVERSION
2018-04-03T19:56:21.6212648Z ##[debug]loading INPUT_VERSIONSELECTOR
2018-04-03T19:56:22.3801109Z ##[debug]loading SECRET_VSOACCESSTOKEN
2018-04-03T19:56:22.4662240Z ##[section]Finishing: VsTest Platform Installer

**Comment by ShreyasRmsft** [comment]
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=8858765&_a=summary

2018-04-03T19:17:24.7612947Z ##[debug]Evaluating condition for step: 'VsTest Platform Installer'
2018-04-03T19:17:24.7613692Z ##[debug]Evaluating: succeeded()
2018-04-03T19:17:24.7613915Z ##[debug]Evaluating succeeded:
2018-04-03T19:17:24.7614276Z ##[debug]=> (Boolean) True
2018-04-03T19:17:24.7614572Z ##[debug]Expanded: True
2018-04-03T19:17:24.7614838Z ##[debug]Result: True
2018-04-03T19:17:24.7615124Z ##[section]Starting: VsTest Platform Installer
2018-04-03T19:17:24.7618287Z ==============================================================================
2018-04-03T19:17:24.7618495Z Task         : Visual Studio Test Platform Installer
2018-04-03T19:17:24.7989419Z Description  : Acquires the test platform from nuget.org or the tools cache. Satisfies the ‘vstest’ demand and can be used for running tests and collecting diagnostic data using the Visual Studio Test task.
2018-04-03T19:17:24.7990330Z Version      : 1.0.9
2018-04-03T19:17:24.7990476Z Author       : Microsoft Corporation
2018-04-03T19:17:24.7990679Z Help         : <a href="https://www.nuget.org/packages/Microsoft.TestPlatform/">Test platform package on NuGet</a>
2018-04-03T19:17:24.7990917Z ==============================================================================
2018-04-03T19:17:26.1783572Z ##[debug]agent.workFolder=E:\work
2018-04-03T19:17:26.1785684Z ##[debug]loading inputs and endpoints
2018-04-03T19:17:26.1802546Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2018-04-03T19:17:26.1802978Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2018-04-03T19:17:26.1803346Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2018-04-03T19:17:26.1803687Z ##[debug]loading INPUT_TESTPLATFORMVERSION
2018-04-03T19:17:26.1803999Z ##[debug]loading INPUT_VERSIONSELECTOR
2018-04-03T19:17:26.1804414Z ##[debug]loading SECRET_VSOACCESSTOKEN
2018-04-03T19:17:26.1804718Z ##[debug]loaded 6
2018-04-03T19:17:27.6016784Z ##[debug]Agent.ProxyUrl=undefined
2018-04-03T19:17:27.6020839Z ##[debug]check path : E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\node_modules\vsts-task-tool-lib\lib.json
2018-04-03T19:17:30.2049178Z ##[debug]adding resource file: E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\node_modules\vsts-task-tool-lib\lib.json
2018-04-03T19:17:35.3387287Z ##[debug]system.culture=en-US
2018-04-03T19:17:36.9683127Z ##[debug]check path : E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\task.json
2018-04-03T19:17:42.4630126Z ##[debug]set resource file to: E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\task.json
2018-04-03T19:17:47.2130288Z ##[debug]system.culture=en-US
2018-04-03T19:17:53.1512000Z ##[debug]Agent.Version=2.129.1
2018-04-03T19:17:57.9039071Z ##[debug]Release.ReleaseUri=undefined
2018-04-03T19:17:57.9086148Z ##[section]Finishing: VsTest Platform Installer

**Comment by ShreyasRmsft** [comment]
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=8858417&_a=summary

2018-04-03T19:14:28.0662311Z ##[debug]Evaluating condition for step: 'VsTest Platform Installer'
2018-04-03T19:14:28.0664021Z ##[debug]Evaluating: succeeded()
2018-04-03T19:14:28.0664218Z ##[debug]Evaluating succeeded:
2018-04-03T19:14:28.0664566Z ##[debug]=> (Boolean) True
2018-04-03T19:14:28.0664889Z ##[debug]Expanded: True
2018-04-03T19:14:28.0665132Z ##[debug]Result: True
2018-04-03T19:14:28.0665440Z ##[section]Starting: VsTest Platform Installer
2018-04-03T19:14:28.0672398Z ==============================================================================
2018-04-03T19:14:28.0672589Z Task         : Visual Studio Test Platform Installer
2018-04-03T19:14:28.2256741Z Description  : Acquires the test platform from nuget.org or the tools cache. Satisfies the ‘vstest’ demand and can be used for running tests and collecting diagnostic data using the Visual Studio Test task.
2018-04-03T19:14:28.2257491Z Version      : 1.0.9
2018-04-03T19:14:28.2257642Z Author       : Microsoft Corporation
2018-04-03T19:14:28.2259292Z Help         : <a href="https://www.nuget.org/packages/Microsoft.TestPlatform/">Test platform package on NuGet</a>
2018-04-03T19:14:28.2259582Z ==============================================================================
2018-04-03T19:14:33.0805782Z ##[debug]agent.workFolder=E:\work
2018-04-03T19:14:33.4146247Z ##[debug]loading inputs and endpoints
2018-04-03T19:14:33.4606598Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2018-04-03T19:14:33.5041251Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2018-04-03T19:14:33.6100278Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2018-04-03T19:14:33.9440032Z ##[debug]loading INPUT_TESTPLATFORMVERSION
2018-04-03T19:14:38.3947608Z ##[debug]loading INPUT_VERSIONSELECTOR
2018-04-03T19:14:43.5636330Z ##[debug]loading SECRET_VSOACCESSTOKEN
2018-04-03T19:14:44.2262274Z ##[debug]loaded 6
2018-04-03T19:14:48.9763255Z ##[debug]Agent.ProxyUrl=undefined
2018-04-03T19:14:48.9866111Z ##[section]Finishing: VsTest Platform Installer

**Comment by ShreyasRmsft** [comment]
And although this is happening intermittently it has been recurring since yesterday.

Below are the list of builds where this occurred:

https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=8895604&_a=summary
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=8895604&_a=summary

**Comment by bryanmacfarlane** [comment]
The agent ran the task.  Your task script ran for 46 seconds and returned 0

[2018-04-05 01:20:05Z INFO ProcessInvoker] Starting process:
[2018-04-05 01:20:05Z INFO ProcessInvoker]   File name: 'C:\Agent\externals\node\bin\node.exe'
[2018-04-05 01:20:05Z INFO ProcessInvoker]   Arguments: '"E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\vstestplatformtoolinstaller.js"'
[2018-04-05 01:20:05Z INFO ProcessInvoker]   Working directory: 'E:\work\1\s'
[2018-04-05 01:20:05Z INFO ProcessInvoker]   Require exit code zero: 'True'
[2018-04-05 01:20:05Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2018-04-05 01:20:05Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2018-04-05 01:20:05Z INFO ProcessInvoker] Process started with process id 6908, waiting for process exit.
...
 
[2018-04-05 01:20:52Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:46.7198257.

**Comment by bryanmacfarlane** [comment]
> but I see no logs from the task 

The task does produce logs.  This is from the top of your task loading the task lib and tool-lib.  That's actually output from your task script.

2018-04-05T01:20:19.8026442Z ##[debug]loading inputs and endpoints
2018-04-05T01:20:19.8044074Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2018-04-05T01:20:20.1017015Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2018-04-05T01:20:20.1369088Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2018-04-05T01:20:25.7409993Z ##[debug]loading INPUT_TESTPLATFORMVERSION
2018-04-05T01:20:30.4905180Z ##[debug]loading INPUT_VERSIONSELECTOR
2018-04-05T01:20:35.2403986Z ##[debug]loading SECRET_VSOACCESSTOKEN
2018-04-05T01:20:39.9903620Z ##[debug]loaded 6
2018-04-05T01:20:44.7405192Z ##[debug]Agent.ProxyUrl=undefined
2018-04-05T01:20:47.0261139Z ##[debug]check path : E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\node_modules\vsts-task-tool-lib\lib.json
2018-04-05T01:20:52.3963483Z ##[debug]adding resource file: E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\node_modules\vsts-task-tool-lib\lib.json

Once it your task code starts running, there's no output.

You should figure out what is happening in your task between all the initialization code and *almost* immediately logging.  Something is missing a callback chain after timing out etc..., not getting handled and your script is executing.

**Comment by ShreyasRmsft** [comment]
@bryanmacfarlane could it be the telemetry call?

**Comment by bryanmacfarlane** [comment]
It's something between the libs loading and that first logging line.  I would suggest some additional logging / debug before anything runs.  The telemetry call is a server call before any logging ...  although in a try / catch, something to look at.

**Comment by bryanmacfarlane** [comment]
@TingluoHuang can have another look as well.  @ericsciple and I will look at task to see if something jumps out at us.

**Comment by bryanmacfarlane** [comment]
You also call this between libs loading and your first log line.  Not sure what it does.

```
const perf = require('performance-now');

const executionStartTime = perf();
```

**Comment by ShreyasRmsft** [comment]
@bryanmacfarlane performance-now is a profiling library. What i'm not able to wrap my head around is why the rest of the code doesn't execute.

I'm no expert on node or js but these are my assumptions (please correct me if I am wrong):
The things that can go wrong are that any of the calls I am making can

1.  End up taking time - in which case it should end up running till the build timeout occurs
2.  An unhandled error/exception occurs inside one of these invoked functions - in which case the task should fail

The only way I can see the execution ending abruptly if one of those calls is internally doing the equivalent of process.exit(0) in which case the task won't fail as the exit code is 0. But it is highly unlikely that an exit is occurring with a 0 exit code. (non-zero maybe but exit code 0 seems far-fetched)


In any other scenario the next statement should get executed and I should see some other logs/indication that the task code is executing.

**Comment by ShreyasRmsft** [comment]
@bryanmacfarlane also there have been instances where the task exited while still loading the resources.json of the task-lib or task-tool-lib and this definitely occurs before 
const executionStartTime = perf(); this every executes
as in [this case ](https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=8859794&_a=summary) where I don't see the following line 
2018-04-05T08:17:12.2270655Z ##[debug]adding resource file: E:\work\_tasks\VisualStudioTestPlatformInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7111\1.0.9\node_modules\vsts-task-tool-lib\lib.json

**Comment by bryanmacfarlane** [comment]
Closing off this discussion.  The agent did the right thing.  There should be a side investigation where and why it failed to run once it got in your task code.
