### ISSUE TITLE
VstsAgentWebProxy No proxy setting found.

### ISSUE THREAD

**Issue by ericbrunner** [Microsoft/vsts-agent#1497]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 2.131.0

OS of the machine running the agent? OSX 10.12.6 (16G1114)

## VSTS Type and Version
VisualStudio.com or On-Prem TFS? VisualStudio.com

If On-Prem TFS, which release? No

If VisualStudio.com, what is your account name? http://rolsped.visualstudio.com

## What's not working?
After I enter my PAT the message is written to the terminal window.

```
Enter server URL > https://rolsped.visualstudio.com
Enter authentication type (press enter for PAT) > 
Enter personal access token > ****************************************************
Connecting to server ...
An error occurred while sending the request.
Failed to connect.  Try again or ctrl-c to quit
```

We are behind a proxy / firewall. Proxy is set in Settings-> network. Browser access to our VSTS HTTPS site is possible. I tried setting the proxy as environment variable with export ALL_PROXY=10.37.99.254:3128. 

What I wonder is the line in the agent log

`[2018-04-11 13:16:16Z INFO VstsAgentWebProxy] No proxy setting found.`

## Agent and Worker's Diagnostic Logs

[2018-04-11 13:16:16Z INFO AgentProcess] Agent is built for OSX - osx-x64.
[2018-04-11 13:16:16Z INFO AgentProcess] RuntimeInformation: Darwin 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64.
[2018-04-11 13:16:16Z INFO AgentProcess] Version: 2.131.0
[2018-04-11 13:16:16Z INFO AgentProcess] Commit: 0cf7b2e90c2258027f198114885ce8d9f9f3497e
[2018-04-11 13:16:16Z INFO AgentProcess] Culture: 
[2018-04-11 13:16:16Z INFO AgentProcess] UI Culture: 
[2018-04-11 13:16:16Z INFO HostContext] Well known directory 'Bin': '/Users/roland/myagent/bin'
[2018-04-11 13:16:16Z INFO HostContext] Well known directory 'Root': '/Users/roland/myagent'
[2018-04-11 13:16:16Z INFO AgentProcess] Validating directory permissions for: '/Users/roland/myagent'
[2018-04-11 13:16:16Z INFO CommandLineParser] Parse
[2018-04-11 13:16:16Z INFO CommandLineParser] Parsing 1 args
[2018-04-11 13:16:16Z INFO CommandLineParser] parsing argument
[2018-04-11 13:16:16Z INFO CommandLineParser] HasArgs: False
[2018-04-11 13:16:16Z INFO CommandLineParser] Adding Command: configure
[2018-04-11 13:16:16Z INFO AgentProcess] Arguments parsed
[2018-04-11 13:16:16Z INFO VstsAgentWebProxy] No proxy setting found.
[2018-04-11 13:16:16Z INFO AgentCertificateManager] No certificate setting found.
[2018-04-11 13:16:16Z INFO Agent] ExecuteCommand
[2018-04-11 13:16:16Z INFO ConfigurationStore] currentAssemblyLocation: /Users/roland/myagent/bin/Agent.Listener.dll
[2018-04-11 13:16:16Z INFO HostContext] Well known directory 'Bin': '/Users/roland/myagent/bin'
[2018-04-11 13:16:16Z INFO ConfigurationStore] binPath: /Users/roland/myagent/bin
[2018-04-11 13:16:16Z INFO HostContext] Well known directory 'Bin': '/Users/roland/myagent/bin'
[2018-04-11 13:16:16Z INFO HostContext] Well known directory 'Root': '/Users/roland/myagent'
[2018-04-11 13:16:16Z INFO ConfigurationStore] RootFolder: /Users/roland/myagent
[2018-04-11 13:16:16Z INFO ConfigurationStore] ConfigFilePath: /Users/roland/myagent/.agent
[2018-04-11 13:16:16Z INFO ConfigurationStore] CredFilePath: /Users/roland/myagent/.credentials
[2018-04-11 13:16:16Z INFO ConfigurationStore] ServiceConfigFilePath: /Users/roland/myagent/.service
[2018-04-11 13:16:16Z INFO ConfigurationStore] AutoLogonSettingsFilePath: /Users/roland/myagent/.autologon
[2018-04-11 13:16:16Z INFO ConfigurationStore] RuntimeOptionsFilePath: /Users/roland/myagent/.options
[2018-04-11 13:16:16Z INFO CommandSettings] Flag 'help': 'False'
[2018-04-11 13:16:16Z INFO CommandSettings] Flag 'version': 'False'
[2018-04-11 13:16:16Z INFO CommandSettings] Flag 'commit': 'False'
[2018-04-11 13:16:16Z INFO CommandSettings] Command 'configure': 'True'
[2018-04-11 13:16:16Z INFO ConfigurationManager] ConfigureAsync
[2018-04-11 13:16:16Z INFO ConfigurationStore] IsConfigured()
[2018-04-11 13:16:16Z INFO ConfigurationStore] IsConfigured: False
[2018-04-11 13:16:16Z INFO ConfigurationManager] Is configured: False
[2018-04-11 13:16:16Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'False'
[2018-04-11 13:16:16Z INFO Terminal] WRITE LINE: 
[2018-04-11 13:16:16Z INFO Terminal] WRITE LINE: >> End User License Agreements:
[2018-04-11 13:16:16Z INFO Terminal] WRITE LINE: 
[2018-04-11 13:16:16Z INFO Terminal] WRITE LINE: Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /Users/roland/myagent/externals/tee/license.html
[2018-04-11 13:16:16Z INFO Terminal] WRITE LINE: 
[2018-04-11 13:16:16Z INFO CommandSettings] Flag 'acceptteeeula': 'False'
[2018-04-11 13:16:16Z INFO CommandSettings] Flag 'unattended': 'False'
[2018-04-11 13:16:16Z INFO PromptManager] ReadValue
[2018-04-11 13:16:16Z INFO Terminal] WRITE: Enter (Y/N) Accept the Team Explorer Everywhere license agreement now? (press enter for N) > 
[2018-04-11 13:16:16Z INFO Terminal] READ LINE
[2018-04-11 13:16:19Z INFO Terminal] Read value: 'Y'
[2018-04-11 13:16:19Z INFO CommandSettings] Flag 'machinegroup': 'False'
[2018-04-11 13:16:19Z INFO CommandSettings] Flag 'deploymentgroup': 'False'
[2018-04-11 13:16:19Z INFO CommandSettings] Flag 'deploymentpool': 'False'
[2018-04-11 13:16:19Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2018-04-11 13:16:19Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2018-04-11 13:16:19Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2018-04-11 13:16:19Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.SharedDeploymentAgentConfigProvider, Agent.Listener
[2018-04-11 13:16:19Z INFO Terminal] WRITE LINE: 
[2018-04-11 13:16:19Z INFO Terminal] WRITE LINE: >> Connect:
[2018-04-11 13:16:19Z INFO Terminal] WRITE LINE: 
[2018-04-11 13:16:19Z INFO CommandSettings] Arg 'url': ''
[2018-04-11 13:16:19Z INFO CommandSettings] Flag 'unattended': 'False'
[2018-04-11 13:16:19Z INFO PromptManager] ReadValue
[2018-04-11 13:16:19Z INFO Terminal] WRITE: Enter server URL > 
[2018-04-11 13:16:19Z INFO Terminal] READ LINE
[2018-04-11 13:16:31Z INFO Terminal] Read value: 'https://rolsped.visualstudio.com'
[2018-04-11 13:16:31Z INFO ConfigurationManager] GetCredentialProvider
[2018-04-11 13:16:31Z INFO CommandSettings] Arg 'auth': ''
[2018-04-11 13:16:31Z INFO CommandSettings] Flag 'unattended': 'False'
[2018-04-11 13:16:31Z INFO PromptManager] ReadValue
[2018-04-11 13:16:31Z INFO Terminal] WRITE: Enter authentication type (press enter for PAT) > 
[2018-04-11 13:16:31Z INFO Terminal] READ LINE
[2018-04-11 13:16:32Z INFO Terminal] Read value: ''
[2018-04-11 13:16:32Z INFO PromptManager] Falling back to the default: 'PAT'
[2018-04-11 13:16:32Z INFO ConfigurationManager] Creating credential for auth: PAT
[2018-04-11 13:16:32Z INFO CredentialManager] GetCredentialProvider
[2018-04-11 13:16:32Z INFO CredentialManager] Creating type PAT
[2018-04-11 13:16:32Z INFO CredentialManager] Creating credential type: PAT
[2018-04-11 13:16:32Z INFO PersonalAccessToken] EnsureCredential
[2018-04-11 13:16:32Z INFO CommandSettings] Arg 'token': ''
[2018-04-11 13:16:32Z INFO CommandSettings] Flag 'unattended': 'False'
[2018-04-11 13:16:32Z INFO PromptManager] ReadValue
[2018-04-11 13:16:32Z INFO Terminal] WRITE: Enter personal access token > 
[2018-04-11 13:16:32Z INFO Terminal] READ SECRET
[2018-04-11 13:16:43Z INFO Terminal] Read value: '********'
[2018-04-11 13:16:43Z INFO PersonalAccessToken] GetVssCredentials
[2018-04-11 13:16:43Z INFO PersonalAccessToken] token retrieved: 52 chars
[2018-04-11 13:16:43Z INFO ConfigurationManager] cred retrieved
[2018-04-11 13:16:43Z INFO Terminal] WRITE LINE: Connecting to server ...
[2018-04-11 13:16:44Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2018-04-11 13:16:44Z ERR  VisualStudioServices] GET request to https://rolsped.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
[2018-04-11 13:16:44Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2018-04-11 13:16:44Z INFO AgentServer] Catch exception during connect. 4 attemp left.
[2018-04-11 13:16:44Z ERR  AgentServer] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
[2018-04-11 13:16:44Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2018-04-11 13:16:44Z ERR  VisualStudioServices] GET request to https://rolsped.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
[2018-04-11 13:16:44Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2018-04-11 13:16:44Z INFO AgentServer] Catch exception during connect. 3 attemp left.
[2018-04-11 13:16:44Z ERR  AgentServer] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
[2018-04-11 13:16:44Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2018-04-11 13:16:44Z ERR  VisualStudioServices] GET request to https://rolsped.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
[2018-04-11 13:16:44Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2018-04-11 13:16:44Z INFO AgentServer] Catch exception during connect. 2 attemp left.
[2018-04-11 13:16:44Z ERR  AgentServer] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
[2018-04-11 13:16:44Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2018-04-11 13:16:44Z ERR  VisualStudioServices] GET request to https://rolsped.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
[2018-04-11 13:16:44Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2018-04-11 13:16:44Z INFO AgentServer] Catch exception during connect. 1 attemp left.
[2018-04-11 13:16:44Z ERR  AgentServer] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
[2018-04-11 13:16:44Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2018-04-11 13:16:44Z ERR  VisualStudioServices] GET request to https://rolsped.visualstudio.com/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
[2018-04-11 13:16:44Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2018-04-11 13:16:44Z INFO CommandSettings] Flag 'unattended': 'False'
[2018-04-11 13:16:44Z ERR  Terminal] WRITE ERROR (exception):
[2018-04-11 13:16:44Z ERR  Terminal] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<TestConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__6.MoveNext()
[2018-04-11 13:16:44Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2018-04-11 13:16:44Z INFO CommandSettings] Arg 'url': ''
[2018-04-11 13:16:44Z INFO CommandSettings] Flag 'unattended': 'False'
[2018-04-11 13:16:44Z INFO PromptManager] ReadValue
[2018-04-11 13:16:44Z INFO Terminal] WRITE: Enter server URL > 
[2018-04-11 13:16:44Z INFO Terminal] READ LINE

**Comment by ericbrunner** [comment]
SOLUTION
[https://github.com/Microsoft/vsts-agent/blob/master/docs/start/proxyconfig.md](https://github.com/Microsoft/vsts-agent/blob/master/docs/start/proxyconfig.md)
