### ISSUE TITLE
Fix integrated Auth for TFS.vNext on-prem (2015 works)

### ISSUE THREAD

**Issue by stiliev** [Microsoft/vsts-agent#150]
Integrated auth on Windows does not work

**Comment by dpurge** [comment]
I am trying to use build agent with TFS 2015.2.1 on premise, but with basic authentication.
I have tried 2.100.1 built for windows.
During configuration:
Enter server URL > https://MYTFSSERVER/tfs/
I've tried both "Integrated" and "Negotiate" authentication type; in both cases I am getting the same error:
VS30063: You are not authorized to access https://MYTFSSERVER.
(note that trailing .../tfs/ is cut off)

From the diagnostic log:

[2016-05-17 08:16:41Z INFO Terminal] WRITE: Enter authentication type (press enter for Integrated) > 
[2016-05-17 08:16:41Z INFO Terminal] READ LINE
[2016-05-17 08:22:25Z INFO Terminal] Read value: 'Negotiate'
[2016-05-17 08:22:25Z INFO ConfigurationManager] Creating credential for auth: Negotiate
[2016-05-17 08:22:25Z INFO CredentialManager] GetCredentialProvider
[2016-05-17 08:22:25Z INFO CredentialManager] Creating type Negotiate
[2016-05-17 08:22:25Z INFO CredentialManager] Creating credential type: Negotiate
[2016-05-17 08:22:25Z INFO PersonalAccessToken] EnsureCredential
[2016-05-17 08:22:25Z INFO CommandSettings] Arg 'username': ''
[2016-05-17 08:22:25Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-05-17 08:22:25Z INFO PromptManager] ReadValue
[2016-05-17 08:22:25Z INFO Terminal] WRITE: Enter user name > 
[2016-05-17 08:22:25Z INFO Terminal] READ LINE
[2016-05-17 08:22:40Z INFO Terminal] Read value: 'MYUSER@MYDOMAIN'
[2016-05-17 08:22:40Z INFO CommandSettings] Arg 'password': ''
[2016-05-17 08:22:40Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-05-17 08:22:40Z INFO PromptManager] ReadValue
[2016-05-17 08:22:40Z INFO Terminal] WRITE: Enter password > 
[2016-05-17 08:22:40Z INFO Terminal] READ SECRET
[2016-05-17 08:22:48Z INFO Terminal] Read value: '********'
[2016-05-17 08:22:48Z INFO NegotiateCredential] GetVssCredentials
[2016-05-17 08:22:48Z INFO NegotiateCredential] User name retrieved.
[2016-05-17 08:22:48Z INFO NegotiateCredential] Password retrieved.
[2016-05-17 08:22:48Z INFO NegotiateCredential] URL retrieved: https://MYTFSSERVER/tfs/
[2016-05-17 08:22:48Z INFO ConfigurationManager] cred retrieved
[2016-05-17 08:22:48Z INFO Terminal] WRITE LINE: Connecting to server ...
[2016-05-17 08:22:48Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-05-17 08:22:48Z ERR  Terminal] WRITE ERROR (exception):
[2016-05-17 08:22:48Z ERR  Terminal] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access https://MYTFSSERVER.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Client.VssServerDataProvider.<ConnectAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<TestConnectAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__8.MoveNext()
[2016-05-17 08:22:48Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit


When I try build agent that came with TFS, it is failing with exactly the same error on basic authentication (it does work with windows authentication enabled)

It would be great if you could look into this. Even the information that you cannot repro (ie. that it can work at all) would be a valuable feedback for me.

**Comment by bryanmacfarlane** [comment]
@dpurge - the current preview is only for VSTS.  on-prem support is in the works.  when it's ready for on-prem (likely next preview drop), you will not need basic enabled on the server.  It will use Integrated on windows (you, no creds entered) or NTLM on nix.

**Comment by dpurge** [comment]
Brian, thank you for your response. Windows authentication does work with the vNext build if enabled,  but I am in an environment where for some independent reason we use basic authentication and cannot enable windows authentication. I was checking out your preview build exactly because XAML build does work, but vNext build no longer works in this configuration.

Could you confirm whether my scenario (Basic Authentication enabled, everything else disabled, including Windows Authentication) is going to be supported for on-premise TFS? I'll appreciate any answer that will clarify what I can count on in the future.

**Comment by bryanmacfarlane** [comment]
@dpurge - please log another issue to support basic only.  Simple enough to add.  I have some questions but I'll leave it for that issue.

**Comment by bryanmacfarlane** [comment]
this specific issue was narrowed down to a net core issue.  only against latest (unshipped) dev15 server

**Comment by stiliev** [comment]
this has been fixed now.
