### ISSUE TITLE
Exception while writing warnings Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by navin22** [Microsoft/vsts-agent#1502]
## Have you tried trouble shooting?
Getting the error intermittently when writing the warning in parallel threads from PublishTestResults task.
It should have been any task. Thinking writing in parallel is causing this issue.

Using `IExecutionContext` to write the warning, like [here](https://github.com/Microsoft/vsts-agent/blob/master/src/Agent.Worker/TestResults/TestRunPublisher.cs#L278).

Below is the call stack during the error.
`at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.TeamFoundation.DistributedTask.WebApi.TimelineRecord..ctor(TimelineRecord recordToBeCloned)
   at Microsoft.TeamFoundation.DistributedTask.WebApi.TimelineRecord.Clone()
   at Microsoft.VisualStudio.Services.Agent.JobServerQueue.QueueTimelineRecordUpdate(Guid timelineId, TimelineRecord timelineRecord) in E:\repos\navin22\vsts-agent\src\Microsoft.VisualStudio.Services.Agent\JobServerQueue.cs:line 228
   at Microsoft.VisualStudio.Services.Agent.Worker.ExecutionContext.AddIssue(Issue issue) in E:\repos\navin22\vsts-agent\src\Agent.Worker\ExecutionContext.cs:line 293
   at Microsoft.VisualStudio.Services.Agent.Worker.ExecutionContextExtension.Warning(IExecutionContext context, String message) in E:\repos\navin22\vsts-agent\src\Agent.Worker\ExecutionContext.cs:line 562
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestRunPublisher.GetAttachmentRequestModel(String attachment) in E:\repos\navin22\vsts-agent\src\Agent.Worker\TestResults\TestRunPublisher.cs:line 278
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestRunPublisher.<>c__DisplayClass9_3.<<AddResultsAsync>b__0>d.MoveNext() in E:\repos\navin22\vsts-agent\src\Agent.Worker\TestResults\TestRunPublisher.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.TestRunPublisher.<AddResultsAsync>d__9.MoveNext() in E:\repos\navin22\vsts-agent\src\Agent.Worker\TestResults\TestRunPublisher.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.ResultsCommandExtension.<>c__DisplayClass20_0.<<PublishToNewTestRunPerTestResultFileAsync>b__4>d.MoveNext() in E:\repos\navin22\vsts-agent\src\Agent.Worker\TestResults\ResultsCommandExtension.cs:line 252
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TestResults.ResultsCommandExtension.<PublishToNewTestRunPerTestResultFileAsync>d__20.MoveNext() in E:\repos\navin22\vsts-agent\src\Agent.Worker\TestResults\ResultsCommandExtension.cs:line 260`

On devfabric environment I am able to repro it once in every 10 times.

## Agent Version and Platform
latest agent from master branch.

OS of the machine running the agent?
Windows

**Comment by TingluoHuang** [comment]
@navin22 https://github.com/Microsoft/vsts-agent/blob/master/src/Agent.Worker/ExecutionContext.cs#L256
the method is not thread safe, the caller need to take lock if need.
