### ISSUE TITLE
CredRead throw an error for 'VSTS_AGENT_PROXY_66C6DADE-3FEF-41 49-B0F0-5E42A6A5C2F9'

### ISSUE THREAD

**Issue by VerdonTrigance** [Microsoft/vsts-agent#1602]
## Have you tried trouble shooting?
y

## Agent Version and Platform
2.126.0

OS of the machine running the agent? OSX/Windows/Linux/...
Windows

## VSTS Type and Version
VSTS

## What's not working?
CredRead throw an error for 'VSTS_AGENT_PROXY_66C6DADE-3FEF-41
49-B0F0-5E42A6A5C2F9'

## Agent and Worker's Diagnostic Logs
```
[2018-06-04 07:12:16Z INFO AgentProcess] Agent is built for Windows - win-x64.
[2018-06-04 07:12:16Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 6.3.9600 .
[2018-06-04 07:12:16Z INFO AgentProcess] Version: 2.126.0
[2018-06-04 07:12:16Z INFO AgentProcess] Commit: 54fa61b7cbd67e9c769b22fd7b63007e7d4827a1
[2018-06-04 07:12:16Z INFO AgentProcess] Culture: ru-RU
[2018-06-04 07:12:16Z INFO AgentProcess] UI Culture: en-US
[2018-06-04 07:12:16Z INFO HostContext] Well known directory 'Bin': 'C:\DeployAgent\bin'
[2018-06-04 07:12:16Z INFO HostContext] Well known directory 'Root': 'C:\DeployAgent'
[2018-06-04 07:12:16Z INFO AgentProcess] Validating directory permissions for: 'C:\DeployAgent'
[2018-06-04 07:12:16Z INFO PowerShellExeUtil] Generation: '1'
[2018-06-04 07:12:16Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1', value name 'Install': '1'
[2018-06-04 07:12:16Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2018-06-04 07:12:16Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2018-06-04 07:12:16Z INFO PowerShellExeUtil] Generation: '3'
[2018-06-04 07:12:16Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3', value name 'Install': '1'
[2018-06-04 07:12:16Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.1.14409.1005'
[2018-06-04 07:12:16Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  'CDF'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  'v2.0.50727'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  'v3.0'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  'v3.5'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  'v4'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  'v4.0'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Version': '2.0.50727.4927'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Install': '1'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v2.0.50727'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Found version: 2.0.50727
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Version': '3.0.30729.4926'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Install': '1'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.0'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Found version: 3.0
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Version': '3.5.30729.4926'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Install': '1'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.5'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Found version: 3.5
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  'Client'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  'Full'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.7.02053'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '460805'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Type is System.Int32
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Interpreted version: 4.7.0
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.7.02053'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '460805'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Type is System.Int32
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Interpreted version: 4.7.0
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Found 5 versions:
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  2.0.50727
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  3.0
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  3.5
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  4.7.0
[2018-06-04 07:12:16Z INFO NetFrameworkUtil]  4.7.0
[2018-06-04 07:12:16Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.5'
[2018-06-04 07:12:16Z INFO CommandLineParser] Parse
[2018-06-04 07:12:16Z INFO CommandLineParser] Parsing 1 args
[2018-06-04 07:12:16Z INFO CommandLineParser] parsing argument
[2018-06-04 07:12:16Z INFO CommandLineParser] HasArgs: False
[2018-06-04 07:12:16Z INFO CommandLineParser] Adding Command: run
[2018-06-04 07:12:16Z INFO AgentProcess] Arguments parsed
[2018-06-04 07:12:16Z INFO VstsAgentWebProxy] Config proxy at: http://webs-v10k-cg.corp.mvideo.ru:8080.
[2018-06-04 07:12:16Z ERR  Terminal] WRITE ERROR: Произошла ошибка: CredRead throw an error for 'VSTS_AGENT_PROXY_66C6DADE-3FEF-4149-B0F0-5E42A6A5C2F9'
[2018-06-04 07:12:16Z ERR  AgentProcess] System.ComponentModel.Win32Exception (0x80004005): CredRead throw an error for 'VSTS_AGENT_PROXY_66C6DADE-3FEF-4149-B0F0-5E42A6A5C2F9'
   at Microsoft.VisualStudio.Services.Agent.WindowsAgentCredentialStore.Read(String target)
   at Microsoft.VisualStudio.Services.Agent.VstsAgentWebProxy.LoadProxySetting()
   at Microsoft.VisualStudio.Services.Agent.HostContext.CreateService[T]()
   at Microsoft.VisualStudio.Services.Agent.HostContext.GetService[T]()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.<MainAsync>d__1.MoveNext()

```

## Description
Agent is configured to run manually behind the proxy like this:
`C:\DeployAgent\config.cmd --url https://x.visualstudio.com --auth pat --token dev_userPAT --unattended --pool Default --agent tst-01 --replace --acceptTeeEula --deploymentGroup --projectName Global --addDeploymentGroupTags --deploymentGroupName QA01 --deploymentGroupTags "tst-01" --proxyurl http://proxy:8080 --proxyusername c\dev_user --proxypassword dev_userPass
`
When I run agent - everything is ok. When other local admins run agent they get CredRead error as above. What is wrong?

**Comment by VerdonTrigance** [comment]
Update: user found credential for VSTS_AGENT_PROXY_66C6DADE-3FEF-4149-B0F0-5E42A6A5C2F9 in Control Panel\User Accounts\Credential Manager, and there were his creds instead of c\dev_user. Why this happened? Agent proxy setting up credential only for current user, not for everyone?

**Comment by TingluoHuang** [comment]
@VerdonTrigance this is actually a limitation of windows credential manager, the windows credential manager only provide per user credential storage, it doesn't allow store credential at machine level.

if you want to share proxy creds on the machine, you can use machine level environment variable to feed in proxy credential to agent when configure the agent.
```
$env:VSTS_HTTP_PROXY_USERNAME = "proxyuser"
$env:VSTS_HTTP_PROXY_PASSWORD = "proxypassword"
``` 
the downside will be your proxy credential is in your environment variable list.
https://docs.microsoft.com/en-us/vsts/pipelines/agents/proxy?view=tfs-2017&tabs=windows

**Comment by VerdonTrigance** [comment]
But there is a file .credentials in agent folder. They used early before proxy parameter appear. If I don’t wonna show or tell proxy password for some developers or QA enginers I can’t configure agent like this, right?

**Comment by TingluoHuang** [comment]
the .credentials file store the RSA key info the agent used to exchange an OAuth token from service.
for proxy credential we only have 2 solutions today.
1. Use environment variables.
2. Use windows credential store, this means if you run as interactive agent, your config user and run as user must be same.

**Comment by VerdonTrigance** [comment]
I don’t understand last phrase “config user and run as user must be same”. Config user means proxy user from config and ran as user means user who’s run agent? But what if my proxy user don’t have logonlocally permission? I can’t run agent from proxy user. Only first option remains?
