### ISSUE TITLE
FileNotFoundException when run tests in VSTS

### ISSUE THREAD

**Issue by Marusyk** [Microsoft/vsts-agent#1624]
## Agent Version and Platform
Hosted VS2017

## VSTS Type and Version
VisualStudio.com http://deezze.visualstudio.com

## What's not working?
I got this error when I run test in VSTS

> System.IO.FileNotFoundException: Unable to find tests for D:\agent\_work\2\s\src\backend\Modules\FileStorage\***.FileStorage.Tests\bin\x64\Debug\netcoreapp2.1\xunit.runner.visualstudio.dotnetcore.testadapter.dll. Make sure test project has a nuget reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate. Rerun with /diag option to diagnose further.
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, CancellationToken cancellationToken)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyExecutionManager.StartTestRun(TestRunCriteria testRunCriteria, ITestRunEventsHandler eventHandler)
>  xUnit.net VSTest Adapter v2.4.0-beta.2.build4010 (64-bit .NET Core 4.6.26406.07)

My csproj contains:
  ```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.2" />
    <PackageReference Include="xunit.core" Version="2.4.0-beta.2.build4010" />
    <PackageReference Include="xunit.assert.source" Version="2.4.0-beta.2.build4010" />
    <PackageReference Include="xunit.runner.console" Version="2.4.0-beta.2.build4010" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0-beta.2.build4010" />
```
Also I tried xunit 2.3.1, but the same result. 

I'm using **netcoreapp2.1** as a target framework. Some tests passed but not all. On my machine everything works fine without any errors

I've attached log file from VSTS. Please suggest how can I fix that.
[7_Run tests.txt](https://github.com/xunit/xunit/files/2091532/7_Run.tests.txt)

My VSTS settings
```
{
            "environment": {},
            "enabled": true,
            "continueOnError": false,
            "alwaysRun": false,
            "displayName": "Run tests",
            "timeoutInMinutes": 0,
            "condition": "succeeded()",
            "refName": "",
            "task": {
              "id": "ef087383-ee5e-42c7-9a53-ab56c98420f9",
              "versionSpec": "2.*",
              "definitionType": "task"
            },
            "inputs": {
              "testSelector": "testAssemblies",
              "testAssemblyVer2": "**\\*test*.dll\n!**\\obj\\**",
              "testPlan": "",
              "testSuite": "",
              "testConfiguration": "",
              "tcmTestRun": "$(test.RunId)",
              "searchFolder": "$(System.DefaultWorkingDirectory)",
              "testFiltercriteria": "",
              "runOnlyImpactedTests": "False",
              "runAllTestsAfterXBuilds": "50",
              "uiTests": "false",
              "vstestLocationMethod": "version",
              "vsTestVersion": "latest",
              "vstestLocation": "",
              "runSettingsFile": "src/backend/default.runsettings",
              "overrideTestrunParameters": "",
              "pathtoCustomTestAdapters": "",
              "runInParallel": "false",
              "runTestsInIsolation": "false",
              "codeCoverageEnabled": "False",
              "otherConsoleOptions": "",
              "distributionBatchType": "basedOnTestCases",
              "batchingBasedOnAgentsOption": "autoBatchSize",
              "customBatchSizeValue": "10",
              "batchingBasedOnExecutionTimeOption": "autoBatchSize",
              "customRunTimePerBatchValue": "60",
              "dontDistribute": "False",
              "testRunTitle": "",
              "platform": "$(BuildPlatform)",
              "configuration": "$(BuildConfiguration)",
              "publishRunAttachments": "true",
              "rerunFailedTests": "false",
              "rerunType": "basedOnTestFailurePercentage",
              "rerunFailedThreshold": "30",
              "rerunFailedTestCasesMaxLimit": "5",
              "rerunMaxAttempts": "5"
            }
          }
```

**Comment by Marusyk** [comment]
Fixed 🙃. The problem was in my build configuration in this line:
` "testAssemblyVer2": "**\\*test*.dll\n!**\\obj\\**",`

where I tried to find all assemblies that contains word "test" in the name. 

There are **xunit.runner.visualstudio.dotnetcore.testadapter.dll** that, of course doesn't have any tests. So, the runner was actually right when says

>  Unable to find tests for xunit.runner.visualstudio.dotnetcore.testadapter.dll

My fault 😕. Thanks
