### ISSUE TITLE
VSTS Agent - Copy Files - does chmod while "Override" option not ticked on

### ISSUE THREAD

**Issue by phil123456** [Microsoft/vsts-agent#1636]
## Agent Version and Platform
Where can I find the info ?

OS : Windows

## VSTS Type and Version
VisualStudio.com 

## What's not working?

Using the "Copy File" task in a release, I untick "override" since I only want to update some files

but the agent does chmod on files already on the system (which is not allowed by our security team)

2018-06-19T13:03:59.9255736Z ##[section]Starting: Copy Files to: /data/apache/var/www/html/******
2018-06-19T13:03:59.9380638Z ==============================================================================
2018-06-19T13:03:59.9408913Z Task         : Copy Files
2018-06-19T13:03:59.9437816Z Description  : Copy files from source folder to target folder using match patterns (The match patterns will only match file paths, not folder paths)
2018-06-19T13:03:59.9466225Z Version      : 2.117.0
2018-06-19T13:03:59.9494054Z Author       : Microsoft Corporation
2018-06-19T13:03:59.9522338Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=708389)
2018-06-19T13:03:59.9550616Z ==============================================================================
2018-06-19T13:04:00.5528521Z found 7 files
2018-06-19T13:04:00.5585656Z Copying /home/saehqvsts/vstsagent2/_work/r3/a/artifact/drop/delete_files.sh to /data/apache/var/www/html/******/delete_files.sh
2018-06-19T13:04:00.5743041Z Copying /home/saehqvsts/vstsagent2/_work/r3/a/artifact/drop/images/home/blog-image01.png to /data/apache/var/www/html/******/images/home/blog-image01.png
2018-06-19T13:04:00.5773633Z Copying /home/saehqvsts/vstsagent2/_work/r3/a/artifact/drop/images/home/blog-image02.png to /data/apache/var/www/html/******/images/home/blog-image02.png
2018-06-19T13:04:00.5803794Z Copying /home/saehqvsts/vstsagent2/_work/r3/a/artifact/drop/images/home/blog-image03.png to /data/apache/var/www/html/******/images/home/blog-image03.png
2018-06-19T13:04:00.5833235Z Copying /home/saehqvsts/vstsagent2/_work/r3/a/artifact/drop/index.php to /data/apache/var/www/html/******/index.php
2018-06-19T13:04:00.5861627Z shell.js: internal error
2018-06-19T13:04:00.5890403Z Error: EPERM: operation not permitted, chmod '/data/apache/var/www/html/******/index.php'
2018-06-19T13:04:00.5918532Z     at Error (native)
2018-06-19T13:04:00.5946236Z     at Object.fs.chmodSync (fs.js:1168:18)
2018-06-19T13:04:00.5975560Z     at copyFileSync (/home/saehqvsts/vstsagent2/_work/_tasks/CopyFiles_5bfb729a-a7c8-4a78-a7c3-8d717bb7c13c/2.117.0/node_modules/shelljs/src/cp.js:41:6)
2018-06-19T13:04:00.6005484Z     at /home/saehqvsts/vstsagent2/_work/_tasks/CopyFiles_5bfb729a-a7c8-4a78-a7c3-8d717bb7c13c/2.117.0/node_modules/shelljs/src/cp.js:198:5
2018-06-19T13:04:00.6034026Z     at Array.forEach (native)
2018-06-19T13:04:00.6063516Z     at Object._cp (/home/saehqvsts/vstsagent2/_work/_tasks/CopyFiles_5bfb729a-a7c8-4a78-a7c3-8d717bb7c13c/2.117.0/node_modules/shelljs/src/cp.js:157:11)
2018-06-19T13:04:00.6094451Z     at Object.cp (/home/saehqvsts/vstsagent2/_work/_tasks/CopyFiles_5bfb729a-a7c8-4a78-a7c3-8d717bb7c13c/2.117.0/node_modules/shelljs/src/common.js:186:23)
2018-06-19T13:04:00.6124783Z     at Object.cp (/home/saehqvsts/vstsagent2/_work/_tasks/CopyFiles_5bfb729a-a7c8-4a78-a7c3-8d717bb7c13c/2.117.0/node_modules/vsts-task-lib/task.js:827:15)
2018-06-19T13:04:00.6154870Z     at matchedFiles.forEach.err (/home/saehqvsts/vstsagent2/_work/_tasks/CopyFiles_5bfb729a-a7c8-4a78-a7c3-8d717bb7c13c/2.117.0/copyfiles.js:119:20)
2018-06-19T13:04:00.6183521Z     at Array.forEach (native)
2018-06-19T13:04:00.6774571Z ##[error]Exit code 1 returned from process: file name '/home/saehqvsts/vstsagent2/externals/node/bin/node', arguments '"/home/saehqvsts/vstsagent2/_work/_tasks/CopyFiles_5bfb729a-a7c8-4a78-a7c3-8d717bb7c13c/2.117.0/copyfiles.js"'.
2018-06-19T13:04:00.6890413Z ##[section]Finishing: Copy Files to: /data/apache/var/www/html/******

how can I address this issue ?
is it possible to have the agent not doing a chmod ?

regards

**Comment by TingluoHuang** [comment]
@phil123456 should this be an issue for the `copy files` task? i don't recall the agent did any chmod for working directory. Task Repo: https://github.com/microsoft/vsts-tasks

**Comment by phil123456** [comment]
well you can see the log, it triggers an EPERM doing a chmod
is there a way to fork the copyfiles.js to use a custom one and put it on our build server ?

**Comment by phil123456** [comment]
actualy, copying the files in the /home/vstsagent/temp/appname folder is simpler and also solves other issues

thanks, so no I know how to fork a VSTS task if needed
