### ISSUE TITLE
VS30063: You are not authorized to access

### ISSUE THREAD

**Issue by lxkbest** [Microsoft/vsts-agent#1646]
## VS30063: You are not authorized to access http://[tfs host]:8686. ?
 
 what's meaning?? did not see the required validation information?? where is wrong

**Comment by bryanmacfarlane** [comment]
Can you please add more context?  What we're you doing when that error was returned?  What log?  A task?  Configuring the agent?

**Comment by lxkbest** [comment]
@bryanmacfarlane Yes Configuring the agent [https://coding.net/u/lxkbest/p/SexyColor_Document/git/blob/master/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180629092933.png](url)

[2018-06-29 01:33:57Z INFO AgentProcess] Agent is built for Windows - win7-x64.
[2018-06-29 01:33:57Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 10.0.16299 .
[2018-06-29 01:33:57Z INFO AgentProcess] Version: 2.105.7
[2018-06-29 01:33:57Z INFO AgentProcess] Commit: 5f286b1f01c51b7cace8c1649edd6b00893a3649
[2018-06-29 01:33:57Z INFO AgentProcess] Culture: zh-CN
[2018-06-29 01:33:57Z INFO AgentProcess] UI Culture: zh-CN
[2018-06-29 01:33:57Z INFO HostContext] Well known directory 'Bin': 'C:\agent\bin'
[2018-06-29 01:33:57Z INFO HostContext] Well known directory 'Root': 'C:\agent'
[2018-06-29 01:33:57Z INFO AgentProcess] Validating directory permissions for: 'C:\agent'
[2018-06-29 01:33:58Z INFO PowerShellExeUtil] Generation: '1'
[2018-06-29 01:33:58Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1', value name 'Install': '1'
[2018-06-29 01:33:58Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2018-06-29 01:33:58Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2018-06-29 01:33:58Z INFO PowerShellExeUtil] Generation: '3'
[2018-06-29 01:33:58Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3', value name 'Install': '1'
[2018-06-29 01:33:58Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.1.16299.15'
[2018-06-29 01:33:58Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2018-06-29 01:33:58Z INFO NetFrameworkUtil]  'CDF'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil]  'v3.0'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil]  'v4'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil]  'v4.0'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Version' is null.
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name '' is null.
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0' contains sub keys:
[2018-06-29 01:33:58Z INFO NetFrameworkUtil]  'Setup'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0\Setup', value name 'Version' is null.
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2018-06-29 01:33:58Z INFO NetFrameworkUtil]  'Client'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil]  'Full'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.7.02556'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '461308'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Type is System.Int32
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Interpreted version: 4.6.2
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.7.02556'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '461308'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Type is System.Int32
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Interpreted version: 4.6.2
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Found 2 versions:
[2018-06-29 01:33:58Z INFO NetFrameworkUtil]  4.6.2
[2018-06-29 01:33:58Z INFO NetFrameworkUtil]  4.6.2
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.5'
[2018-06-29 01:33:58Z INFO CommandLineParser] Parse
[2018-06-29 01:33:58Z INFO CommandLineParser] Parsing 1 args
[2018-06-29 01:33:58Z INFO CommandLineParser] parsing argument
[2018-06-29 01:33:58Z INFO CommandLineParser] HasArgs: False
[2018-06-29 01:33:58Z INFO CommandLineParser] Adding Command: configure
[2018-06-29 01:33:58Z INFO AgentProcess] Arguments parsed
[2018-06-29 01:33:58Z INFO ProxyConfiguration] No proxy setting found.
[2018-06-29 01:33:58Z INFO Agent] ExecuteCommand
[2018-06-29 01:33:58Z INFO ConfigurationStore] currentAssemblyLocation: C:\agent\bin\Agent.Listener.dll
[2018-06-29 01:33:58Z INFO ConfigurationStore] binPath: C:\agent\bin
[2018-06-29 01:33:58Z INFO ConfigurationStore] RootFolder: C:\agent
[2018-06-29 01:33:58Z INFO ConfigurationStore] ConfigFilePath: C:\agent\.agent
[2018-06-29 01:33:58Z INFO ConfigurationStore] CredFilePath: C:\agent\.credentials
[2018-06-29 01:33:58Z INFO ConfigurationStore] ServiceConfigFilePath: C:\agent\.service
[2018-06-29 01:33:58Z INFO CommandSettings] Flag 'help': 'False'
[2018-06-29 01:33:58Z INFO CommandSettings] Flag 'version': 'False'
[2018-06-29 01:33:58Z INFO CommandSettings] Flag 'commit': 'False'
[2018-06-29 01:33:58Z INFO CommandSettings] Command 'configure': 'True'
[2018-06-29 01:33:58Z INFO ConfigurationManager] ConfigureAsync
[2018-06-29 01:33:58Z INFO ConfigurationStore] IsConfigured()
[2018-06-29 01:33:58Z INFO ConfigurationStore] IsConfigured: False
[2018-06-29 01:33:58Z INFO ConfigurationManager] Is configured: False
[2018-06-29 01:33:58Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.6'
[2018-06-29 01:33:58Z INFO Terminal] WRITE LINE: 
[2018-06-29 01:33:58Z INFO Terminal] WRITE LINE: >> 连接:
[2018-06-29 01:33:58Z INFO Terminal] WRITE LINE: 
[2018-06-29 01:33:58Z INFO CommandSettings] Arg 'url': ''
[2018-06-29 01:33:58Z INFO CommandSettings] Flag 'unattended': 'False'
[2018-06-29 01:33:58Z INFO PromptManager] ReadValue
[2018-06-29 01:33:58Z INFO Terminal] WRITE: 输入 服务器 URL > 
[2018-06-29 01:33:58Z INFO Terminal] READ LINE
[2018-06-29 01:34:17Z INFO Terminal] Read value: 'http://192.168.1.66:8686/tfs'
[2018-06-29 01:34:17Z INFO ConfigurationManager] GetCredentialProvider
[2018-06-29 01:34:17Z INFO CommandSettings] Arg 'auth': ''
[2018-06-29 01:34:17Z INFO CommandSettings] Flag 'unattended': 'False'
[2018-06-29 01:34:17Z INFO PromptManager] ReadValue
[2018-06-29 01:34:17Z INFO Terminal] WRITE: 输入 身份验证类型 (对于 Integrated 按 Enter) > 
[2018-06-29 01:34:17Z INFO Terminal] READ LINE
[2018-06-29 01:34:19Z INFO Terminal] Read value: ''
[2018-06-29 01:34:19Z INFO PromptManager] Falling back to the default: 'Integrated'
[2018-06-29 01:34:19Z INFO ConfigurationManager] Creating credential for auth: Integrated
[2018-06-29 01:34:19Z INFO CredentialManager] GetCredentialProvider
[2018-06-29 01:34:19Z INFO CredentialManager] Creating type Integrated
[2018-06-29 01:34:19Z INFO CredentialManager] Creating credential type: Integrated
[2018-06-29 01:34:19Z INFO IntegratedCredential] GetVssCredentials
[2018-06-29 01:34:19Z INFO ConfigurationManager] cred retrieved
[2018-06-29 01:34:19Z INFO Terminal] WRITE LINE: 正在连接到服务器...
[2018-06-29 01:34:19Z INFO CommandSettings] Flag 'unattended': 'False'
[2018-06-29 01:34:19Z ERR  Terminal] WRITE ERROR (exception):
[2018-06-29 01:34:19Z ERR  Terminal] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access http://192.168.1.66:8686.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<TestConnectAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
[2018-06-29 01:34:19Z ERR  Terminal] WRITE ERROR: 连接失败。请重试或按 Ctrl-C 退出
[2018-06-29 01:34:19Z INFO CommandSettings] Arg 'url': ''
[2018-06-29 01:34:19Z INFO CommandSettings] Flag 'unattended': 'False'
[2018-06-29 01:34:19Z INFO PromptManager] ReadValue
[2018-06-29 01:34:19Z INFO Terminal] WRITE: 输入 服务器 URL > 
[2018-06-29 01:34:19Z INFO Terminal] READ LINE

**Comment by TingluoHuang** [comment]
@lxkbest looks like your `Integrate` auth is not work with your TFS server, can you access your TFS website from browser on the same machine as same user?

**Comment by lxkbest** [comment]
@TingluoHuang I Can ，browser may auth, but agent may not

**Comment by TingluoHuang** [comment]
@lxkbest you might want to capture http trace from the agent.
https://docs.microsoft.com/en-us/vsts/pipelines/troubleshooting?view=vsts#http-trace-logs

**Comment by lxkbest** [comment]
@TingluoHuang thank you，but anonymous authentication has been turned on , The same error will occur
VS30063: You are not authorized to access

**Comment by TingluoHuang** [comment]
@lxkbest You need to capture Http trace, so we can figure out why `Integrate` auth doesn't work.
https://docs.microsoft.com/en-us/vsts/pipelines/troubleshooting?view=vsts#http-trace-logs

**Comment by lxkbest** [comment]
@TingluoHuang Use fiddlet http tool, Request status code 401.  There is nothing wrong status code, Authorization does not appear.
Request the address : http://192.168.1.66:8686/tfs/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1
[https://raw.githubusercontent.com/lxkbest/SexyColorCore/master/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180702165150.png](url)
[https://raw.githubusercontent.com/lxkbest/SexyColorCore/master/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180702165051.png](url)

**Comment by TingluoHuang** [comment]
@lxkbest can you save your Fiddler trace and send it to me? `tihuang @ microsoft.com`

**Comment by lxkbest** [comment]
@TingluoHuang OK, No problem, This is my email lxkbest@qq.com.  Please check Email

**Comment by TingluoHuang** [comment]
@lxkbest any luck with your config?

**Comment by lxkbest** [comment]
@TingluoHuang Already configured，It's already working。Thank you

**Comment by TingluoHuang** [comment]
cool, i am going to close this issue.

**Comment by asifibrahim** [comment]
What was the resolution?  I am able to access TFS url from browser but not during configuring the agent.

**Comment by lxkbest** [comment]
@asifibrahim Do you have the same problem with me?  Refer to this address and it will help you
https://docs.microsoft.com/zh-cn/vsts/pipelines/agents/configure-tfs-authentication?view=tfs-2015

**Comment by asifibrahim** [comment]
When configuring tfs agent I used Authentication type Negotiate instead of  default Integrated and that seemed to  resolve issues with configuring tfs agent in a different domain.

**Comment by lxkbest** [comment]
@asifibrahim Just solve the problem
