### ISSUE TITLE
PowerShell task "Access is denied" from Symantec false positive

### ISSUE THREAD

**Issue by nschonni** [Microsoft/vsts-agent#1661]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes

## Agent Version and Platform
Version of your agent? 2.122.1

OS of the machine running the agent? Windows 7

## VSTS Type and Version
On-Prem TFS?

If On-Prem TFS, which release? TFS 2017.3.1

If VisualStudio.com, what is your account name? http://account.visualstudio.com

## What's not working?
Symantec is flagging the agent process as [`SONAR.AM.PS!g1`](https://www.symantec.com/security-center/writeup/2018-051414-0415-99)

## Agent and Worker's Diagnostic Logs
Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, please double check before pasting here.

```
[2018-06-29 15:45:36Z INFO ProcessInvoker]   File name: 'C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe'
[2018-06-29 15:45:36Z INFO ProcessInvoker]   Arguments: '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "try { $null = [System.Security.Cryptography.ProtectedData] } catch { Write-Verbose 'Adding assemly: System.Security' ; Add-Type -AssemblyName 'System.Security' ; $null = [System.Security.Cryptography.ProtectedData] ; $Error.Clear() } ; Invoke-Expression -Command ([System.Text.Encoding]::UTF8.GetString([System.Security.Cryptography.ProtectedData]::Unprotect([System.Convert]::FromBase64String('AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA+SZ4DY/hsE6IUTkw0hvwMAAAAAACAAAAAAADZgAAwAAAABAAAAC8CPC5e/vofNEsrjqxwwVxAAAAAASAAACgAAAAEAAAAO9MhXKspQ1QQ/kq4zQqcGhQAAAAWp68Xh/UH1jQT8ndi97HBSwfEgBf/MEi4IGVsDeEu4e7Ao6lIW7H7pBj4v34YUZvHLO5N0a/uUjf1OX3CV8KKwVNFTasZBcF81ECGBJ28kEUAAAApujYUlbDfYXPc4KKu1hcD7daQ0s='), [System.Convert]::FromBase64String('x+E90Z86ZCKgZVyJGCpycw=='), [System.Security.Cryptography.DataProtectionScope]::CurrentUser))) ; if (!(Test-Path -LiteralPath variable:\LastExitCode)) { Write-Verbose 'Last exit code is not set.' } else { Write-Verbose ('$LastExitCode: {0}' -f $LastExitCode) ; exit $LastExitCode }"'
[2018-06-29 15:45:36Z INFO ProcessInvoker]   Working directory: 'D:\agent-005\_work\29\s'
[2018-06-29 15:45:36Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2018-06-29 15:45:36Z INFO ProcessInvoker]   Encoding web name:  ; code page: ''
[2018-06-29 15:45:36Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2018-06-29 15:45:36Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2018-06-29 15:45:36Z ERR  StepsRunner] Caught exception from step: System.ComponentModel.Win32Exception: Access is denied
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShellExeHandler.<RunAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
```

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by nschonni** [comment]
I'm more sharing this in case someone else hits it, since the error when this happens is pretty hard to figure out. I don't even know if giving a different error message for this would even be possible.

**Comment by MattGal** [comment]
+1, we see this regularly from  the ProcessInvoker trying to start 'C:\Windows\system32\cmd.exe' as well.

**Comment by nschonni** [comment]
I'll look when I'm back in the office next week, but it looks like that is the behaviour still for the 2017.3.1 agent https://github.com/Microsoft/vsts-agent/blob/v2.122.1/src/Agent.Worker/Handlers/PowerShellExeHandler.cs#L89-L92
I did also try the latest 2.136.0 agent and got the same result, but that may be a difference between the selectable version in TFS vs the agent. It does appear to have the same code handling though https://github.com/Microsoft/vsts-agent/blob/v2.136.0/src/Agent.Worker/Handlers/PowerShellExeHandler.cs#L89-L92

It appears the the virus scan is just interpreting any encrypted PowerShell spawning as an instance of this attack. I'm not sure if something like signing the releases (if they aren't already) would even remove the false positive.

**Comment by nschonni** [comment]
Confirmed that we are running the V1 PowerShell task since that is what ships with 2017

**Comment by nschonni** [comment]
Looks like the latest virus defs might have unflagged this. I'll close in a few days if it looks resolved again

**Comment by TingluoHuang** [comment]
@nschonni i am going to help you close this issue, i guess few days has passed. :D
