### ISSUE TITLE
The remote procedure call failed and did not execute

### ISSUE THREAD

**Issue by chcosta** [Microsoft/vsts-agent#1698]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)

## Agent Version and Platform
Version of your agent? 6.3.9600 

OS of the machine running the agent? Windows

## VSTS Type and Version
VisualStudio.com or On-Prem TFS? Visual Studio

If On-Prem TFS, which release? 2015 RTM/QU1/QU2/...

If VisualStudio.com, what is your account name? http://dotnet.visualstudio.com

## What's not working?
Please include error messages and screenshots.
```
2018-07-11T22:24:55.7748096Z The remote procedure call failed and did not execute.
2018-07-11T22:24:55.7748585Z 
2018-07-11T22:24:55.7806295Z System.SystemException: The remote procedure call failed and did not execute.
2018-07-11T22:24:55.7806488Z 
2018-07-11T22:24:55.7806772Z    at System.Security.Principal.Win32.LsaOpenPolicy(String systemName, PolicyRights rights)
2018-07-11T22:24:55.7807062Z    at System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(IdentityReferenceCollection sourceSids, Boolean& someFailed)
2018-07-11T22:24:55.7807390Z    at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean forceSuccess)
2018-07-11T22:24:55.7807663Z    at System.Security.Principal.SecurityIdentifier.Translate(Type targetType)
2018-07-11T22:24:55.7807939Z    at System.Security.Principal.WindowsIdentity.GetName()
2018-07-11T22:24:55.7808167Z    at System.Security.Principal.WindowsIdentity.get_Name()
2018-07-11T22:24:55.7808418Z    at System.Management.Automation.InformationRecord..ctor(Object messageData, String source)
2018-07-11T22:24:55.7808674Z    at System.Management.Automation.Cmdlet.WriteInformation(Object messageData, String[] tags)
2018-07-11T22:24:55.7808937Z    at Microsoft.PowerShell.Commands.WriteHostCommand.ProcessRecord()
2018-07-11T22:24:55.7809160Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
```

## Agent and Worker's Diagnostic Logs
Available upon request.  I didn't want to accidentally expose something, but I'm happy to send the log if needed

## Related Repositories
Please ensure you are logging issues to the correct repository in order to get the best support.

- [Tasks Repository](https://github.com/Microsoft/vsts-tasks) - contains all of the inbox tasks we ship with VSTS/TFS. If you are having issues with tasks in Build/Release jobs (e.g. unreasonable task failure) please log an issue [here](https://github.com/Microsoft/vsts-tasks/issues).
- [Hosted Agent Image Repository](https://github.com/Microsoft/vsts-image-generation) - contains the VM image used in the VSTS Hosted Agent Pool. If you are having Build/Release failures that seems like they are related to software installed on the Hosted Agent (e.g. the DotnetSDK is missing or the AzureSDK is not on the latest version) please log an issue [here](https://github.com/Microsoft/vsts-image-generation/issues).

If you are hitting a generic issue about VSTS/TFS, please report it to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by TingluoHuang** [comment]
@chcosta where is the error coming from? from a build/release job?

**Comment by chcosta** [comment]
Build job - https://dotnet.visualstudio.com/public/_build/results?buildId=5387&view=logs

**Comment by TingluoHuang** [comment]
```
2018-07-11T22:24:55.7748096Z The remote procedure call failed and did not execute.
2018-07-11T22:24:55.7748585Z 
2018-07-11T22:24:55.7806295Z System.SystemException: The remote procedure call failed and did not execute.
2018-07-11T22:24:55.7806488Z 
2018-07-11T22:24:55.7806772Z    at System.Security.Principal.Win32.LsaOpenPolicy(String systemName, PolicyRights rights)
2018-07-11T22:24:55.7807062Z    at System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(IdentityReferenceCollection sourceSids, Boolean& someFailed)
2018-07-11T22:24:55.7807390Z    at System.Security.Principal.SecurityIdentifier.Translate(IdentityReferenceCollection sourceSids, Type targetType, Boolean forceSuccess)
2018-07-11T22:24:55.7807663Z    at System.Security.Principal.SecurityIdentifier.Translate(Type targetType)
2018-07-11T22:24:55.7807939Z    at System.Security.Principal.WindowsIdentity.GetName()
2018-07-11T22:24:55.7808167Z    at System.Security.Principal.WindowsIdentity.get_Name()
2018-07-11T22:24:55.7808418Z    at System.Management.Automation.InformationRecord..ctor(Object messageData, String source)
2018-07-11T22:24:55.7808674Z    at System.Management.Automation.Cmdlet.WriteInformation(Object messageData, String[] tags)
2018-07-11T22:24:55.7808937Z    at Microsoft.PowerShell.Commands.WriteHostCommand.ProcessRecord()
2018-07-11T22:24:55.7809160Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
2018-07-11T22:24:55.7826729Z at Create-PerfTests, E:\A\_work\669\s\build\scripts\build.ps1: line 321
2018-07-11T22:24:55.7827067Z at Build-InsertionItems, E:\A\_work\669\s\build\scripts\build.ps1: line 339
2018-07-11T22:24:55.7827330Z at Build-Artifacts, E:\A\_work\669\s\build\scripts\build.ps1: line 278
2018-07-11T22:24:55.7827842Z at <ScriptBlock>, E:\A\_work\669\s\build\scripts\build.ps1: line 807
```
`E:\A\_work\669\s\build\scripts\build.ps1: line 807`
The error is coming from the powershell script in the source code, you need to contact the author of that script.

**Comment by chcosta** [comment]
I think that the powershell error

```
2018-07-11T22:24:55.7826729Z at Create-PerfTests, E:\A\_work\669\s\build\scripts\build.ps1: line 321
2018-07-11T22:24:55.7827067Z at Build-InsertionItems, E:\A\_work\669\s\build\scripts\build.ps1: line 339
2018-07-11T22:24:55.7827330Z at Build-Artifacts, E:\A\_work\669\s\build\scripts\build.ps1: line 278
2018-07-11T22:24:55.7827842Z at <ScriptBlock>, E:\A\_work\669\s\build\scripts\build.ps1: line 807
```

and the `remote procedure call` failure are unrelated.  I took a look at the script when the issue was reported to me, and all that it's doing at that point is calling `Write-Host`

```
        $target = Join-Path $configDir "PerfTests"
        Write-Host "PerfTests: $target"
```

**Comment by chcosta** [comment]
I'm not actually certain where this issue should go.  I don't think PowerShell folks will do anything with it because it seems like a system issue.

https://technet.microsoft.com/en-us/library/2007.07.howitworks.aspx

I was kind of hoping the agent could somehow protect from this occurring but that doesn't really seem feasible either.  It's not clear to me if the "remote procedure call" error would have caused the job to fail or not (given that there was an authoring issue in the build which caused a build failure regardless).  My preference would be for it to not cause a build failure.

**Comment by TingluoHuang** [comment]
@chcosta then you can handle the error in your script, the agent just run your script and fail the task based on return code from PowerShell.exe

**Comment by chcosta** [comment]
It would be a poor experience if everyone had to wrap every instance of powershell output to prevent this error.

As I said, I'm not convinced that it actually causes a powershell task failure.

This isn't a script I own. I'm just reporting the issue for Jared parsons (I don't seem to be able to tag him here.

**Comment by chcosta** [comment]
As long as the RPC error isn't blocking, this isn't a big deal, I just wanted to report it in case it was something you wanted the agent to handle.  I'm Ok with closing this issue and looking at hardware / system changes on our team if these errors become prevalent.
