### ISSUE TITLE
Support Basic Only for on-premise 

### ISSUE THREAD

**Issue by dpurge** [Microsoft/vsts-agent#170]
The old XAML-based build system does work with on-premise TFS where only basic authentication is enabled (anonymous, forms and Windows authentication are all disabled).

As of TFS 2015.2 the vNext build cannot connect to TFS in such configuration, returning VS30063 (You  are not authorised to access...)

I have tested vsts-agent build 2.100.1 for Windows, and it fails with VS30063 too. I've pasted fragment of the diagnostic log in issue #150

**Comment by bryanmacfarlane** [comment]
So, just to confirm.  After you install TFS, you go into IIS, enable basic and disable windows authentication?  Just making sure, we test with the exact setup.

**Comment by dpurge** [comment]
After the TFS has been installed, I disabled Windows Authentication on both "Team Foundation Server" website and the "tfs" application underneath and enabled Basic Authentication on both.

I was using https, because the vNext build agent required it (did not even try to connect without https, complained about not being able to establish trust relationship when I had warnings related to the certificate, returned VS30063 when all these issues were corrected).

I tried to login with user that was from the domain to which tfs server is joined, and I also tried to setup shadow accounts - none of that worked.

I'd like to be able to use this both cross-domain, without domain trust established, and in a situation when build agent is in the same domain, but windows authentication is disabled.

**Comment by bryanmacfarlane** [comment]
For the agent, this means auth type: Basic during config.  It will use basic auth to interactively configure the agent.

**Comment by yunidbauza** [comment]
Has this been solved? 
Seems it was removed from the On-Premise release milestone in Aug but I'm getting exactly the same issue described by @dpurge 

I'm running TFS 15RC2 and had to enable Windows Auth to configure and run the agents.
With only Basic authentication, it simply doesn't work (VS30063 error).

Probably related to the issue https://github.com/Microsoft/vsts-agent/issues/326

**Comment by bryanmacfarlane** [comment]
Correct.  This has not been solved and we currently don't support basic only.  We should get to it soon.

**Comment by TingluoHuang** [comment]
@yunidbauza @dpurge the next agent release will support your scenario. 2.108.1

**Comment by dpurge** [comment]
Thank you guys :+1:

**Comment by softwaretirol** [comment]
I tried to setup a new VSTS agent with our On-Premise TFS 2017 with BASIC Authentication only, but it gives me always an "VS30063: you are not authorized to access https://<MYTFS>"

Is it still possible to use Basic Only?

**Comment by bryanmacfarlane** [comment]
@softwaretirol - I presume you configured basic only in IIS (removed NTLM, anonymous?).  Have you tried to iisreset after configuring? (long story)  Have you also tried Basic, Anonymous in IIS (we have to let a bearer token through the front door).

**Comment by softwaretirol** [comment]
That is the configuration of the TFS website within TFS.

![image](https://cloud.githubusercontent.com/assets/7993272/23656291/5f241010-0339-11e7-90cb-05f5ff50b856.png)

With fiddler i see the BASIC with the correct Base64 value...
![image](https://cloud.githubusercontent.com/assets/7993272/23656401/dd7b21b0-0339-11e7-84b9-99ac9c908308.png)


Within the logfile we have:

[2017-03-07 12:25:52Z ERR  Terminal] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Falscher Parameter
   at System.Net.Http.WinHttpAuthHelper.SetWinHttpCredential(SafeWinHttpHandle requestHandle, ICredentials credentials, Uri uri, UInt32 authScheme, UInt32 authTarget)
   at System.Net.Http.WinHttpAuthHelper.CheckResponseForAuthentication(WinHttpRequestState state, UInt32& proxyAuthScheme, UInt32& serverAuthScheme)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<TestConnectAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()

**Comment by TingluoHuang** [comment]
@softwaretirol Are you using PAT token? does you PAT has right scope of permission?

**Comment by softwaretirol** [comment]
@TingluoHuang Hi, yes the PAT token is valid and has the right scope. I solved the issue now on my own behalf and hacked the Basic Authentication into the IntegratedCredential.cs and OAuthCredential.cs - that is working fine for me.

Thanks for the support anyway :-)
