### ISSUE TITLE
Restart of terminal causes release pipeline to fail

### ISSUE THREAD

**Issue by xtreampb** [Microsoft/vsts-agent#1709]
## Agent Version and Platform
Agent 2.136.1
Windows 7 embedded

## VSTS Type and Version
grovergaming.VisualStudio.com

## What's not working?
As part of our release process for one of our on-premise devices deploying to, the final step is to restart the device.  On all previous versions of the deployment group agent (2.134.2 for example) this task (and the release as a whole) was successful.  When using agent version 2.136.1 the terminals would restart, but VSTS wouldn't receive the logs of either the restart task and many times most of the tasks from downloading build artifacts to restarting the terminal (about 5 tasks in total).  The release would eventually time out after about a total of 10 min with the error that VSTS lost connection with the agent.
All the tasks do indeed execute but the results are never reported to VSTS, thus giving false errors.
This does not occur using agent version 2.134.2

VSTS actual reported the following in the web view:
![failed to initialize](https://user-images.githubusercontent.com/1777628/42840989-970e5cfe-89d6-11e8-9227-9706d01537f7.PNG)

This is what i have been receiving and expected to receive:
![successfull deployment](https://user-images.githubusercontent.com/1777628/42841185-45126a0c-89d7-11e8-9dbc-530da0e6c939.PNG)
the only difference is that the successful deployment was using agent 2.134.2 and the failed deployment used agent 2.136.1.  The successful deployment started working when i downgraded it from 2.136.1 to 2.134.2.

## Agent and Worker's Diagnostic Logs
**WorkerLog:**
This shows that all the steps were completed (in contrast to the attached picture where the job didn't even initialize and download the tasks).

[2018-07-17 19:10:49Z INFO JobRunner] Job result after all job steps finish: SucceededWithIssues
[2018-07-17 19:10:49Z INFO JobRunner] Completing the job execution context.
[2018-07-17 19:10:49Z INFO JobRunner] Shutting down the job server queue.
[2018-07-17 19:10:49Z INFO JobServerQueue] Fire signal to shutdown all queues.
[2018-07-17 19:10:51Z INFO Worker] Cancellation/Shutdown message received.
[2018-07-17 19:10:51Z INFO HostContext] Agent will be shutdown for OperatingSystemShutdown
[2018-07-17 19:10:52Z INFO JobServerQueue] Try to append 1 batches web console lines for record 'fd56d6e8-edb0-4944-92de-17cfd6b5ee94', success rate: 1/1.
[2018-07-17 19:10:54Z ERR  VisualStudioServices] POST request to https://grovergaming.vsrm.visualstudio.com/_apis/CustomerIntelligence/Events failed. System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__4.MoveNext()

the finished with issues is okay as there were some previous powershell steps the failed in a non-critical manner that are to continue on error.

**AgentLog:**
[2018-07-17 19:11:25Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\vstsagent\A1\.credentials_rsaparams
[2018-07-17 19:11:31Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2018-07-17 19:11:33Z ERR  VisualStudioServices] POST request to https://grovergaming.visualstudio.com/_apis/distributedtask/pools/20/sessions failed. HTTP Status: Conflict
[2018-07-17 19:11:33Z ERR  MessageListener] Catch exception during create session.
[2018-07-17 19:11:33Z ERR  MessageListener] Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentSessionConflictException: The task agent HORSERACING-GT1 already has an active session for owner HORSERACING-GT1.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<CreateSessionAsync>d__11.MoveNext()
[2018-07-17 19:11:33Z INFO MessageListener] The session for this agent already exists.
[2018-07-17 19:11:33Z ERR  Terminal] WRITE ERROR: A session for this agent already exists.
[2018-07-17 19:11:33Z INFO MessageListener] The session conflict exception haven't reached retry limit.
[2018-07-17 19:11:33Z ERR  Terminal] WRITE ERROR: 2018-07-17 19:11:33Z: Agent connect error: The task agent HORSERACING-GT1 already has an active session for owner HORSERACING-GT1.. Retrying until reconnected.
[2018-07-17 19:11:33Z INFO MessageListener] Sleeping for 30 seconds before retrying.
[2018-07-17 19:12:03Z INFO MessageListener] Attempt to create session.
[2018-07-17 19:12:03Z INFO MessageListener] Connecting to the Agent Server...
[2018-07-17 19:12:06Z ERR  VisualStudioServices] POST request to https://grovergaming.visualstudio.com/_apis/distributedtask/pools/20/sessions failed. HTTP Status: Conflict
[2018-07-17 19:12:06Z ERR  MessageListener] Catch exception during create session.
[2018-07-17 19:12:06Z ERR  MessageListener] Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentSessionConflictException: The task agent HORSERACING-GT1 already has an active session for owner HORSERACING-GT1.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__28`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<CreateSessionAsync>d__11.MoveNext()
[2018-07-17 19:12:06Z INFO MessageListener] The session for this agent already exists.
[2018-07-17 19:12:06Z ERR  Terminal] WRITE ERROR: A session for this agent already exists.
[2018-07-17 19:12:06Z INFO MessageListener] The session conflict exception haven't reached retry limit.
[2018-07-17 19:12:06Z INFO MessageListener] Sleeping for 30 seconds before retrying.
[2018-07-17 19:12:36Z INFO MessageListener] Attempt to create session.
[2018-07-17 19:12:36Z INFO MessageListener] Connecting to the Agent Server...
[2018-07-17 19:12:49Z INFO MessageListener] Session created.
[2018-07-17 19:12:49Z INFO Terminal] WRITE LINE: 2018-07-17 19:12:49Z: Agent reconnected.
[2018-07-17 19:12:49Z INFO Terminal] WRITE LINE: 2018-07-17 19:12:49Z: Listening for Jobs
[2018-07-17 19:12:49Z INFO JobDispatcher] Set agent/worker IPC timeout to 30 seconds.

Attached is from the pages directory showing what should be in the VSTS log but didn't make it:
[bd27a351-9e2d-4d9d-969f-962309f8c105_1.log](https://github.com/Microsoft/vsts-agent/files/2203109/bd27a351-9e2d-4d9d-969f-962309f8c105_1.log)

Logs are located in the agent's `_diag` folder. The agent logs are prefixed with `Agent_` and the worker logs are prefixed with `Worker_`. All sensitive information should already be masked out, please double check before pasting here.

**Comment by TingluoHuang** [comment]
@xtreampb the attached log shows it runs on 2.136.1 agent, so i am not sure whether it's the newer version agent causing the problem.
```
2018-07-17T19:10:33.0629352Z ##[section]Starting: Release
2018-07-17T19:10:33.0639352Z Current agent version: '2.136.1'
```

Can you also share more detail on what's 'Restart the device' means? you have a step to restart the machine?

@chshrikh FYI, in case of a Deployment Group related question.

**Comment by xtreampb** [comment]
@TingluoHuang correct, agent 2.136.1 which VSTS informed me to use this morning is causing the symptoms.  When i downgrade to 2.134.2, the symptoms go away.  The provided logs are from the failed release attempt (agent version 2.136.1).

By resarting the machine, i mean run the powershell inline task with the following command: `Restart-Computer -Force`

**Comment by TingluoHuang** [comment]
@xtreampb your release failed because of following error:
```
2018-07-17T19:10:48.0537926Z ##[command]. 'C:\Users\terminaluser\AppData\Local\Temp\0d313df4-323f-4218-87b2-65e8583e51c3.ps1' 
2018-07-17T19:10:48.4148133Z ##[error]Rename-Item : Cannot rename because item at 
'C:\grover\maestro\GoteMaestro.exe' does not exist.
```
have you check that error?

**Comment by xtreampb** [comment]
that powershell script task says to continue on error b/c i anticipated that

**Comment by TingluoHuang** [comment]
there isn't a reliable way to restart the agent and grantee the running job succeed, i don't think this is changed between 2.134 and 2.136, can you share agent log from 2.134 agent that indicate everything works?

**Comment by xtreampb** [comment]
The second image posted shows it working, and has always worked reliably until this last version.  I think the logs will be the same, I think it is more or less an issue where the agent isn't reporting before shutting down.
Successful Worker Log:
[Worker_20180717-182534-utc.log](https://github.com/Microsoft/vsts-agent/files/2205944/Worker_20180717-182534-utc.log)
Successful Agent Log:
[Agent_20180717-182443-utc.log](https://github.com/Microsoft/vsts-agent/files/2205945/Agent_20180717-182443-utc.log)

**Comment by xtreampb** [comment]
Attached are all the agent and worker logs i have for the failed terminal:  I had cleared all the logs before starting the job.
[Agent_20180717-175639-utc.log](https://github.com/Microsoft/vsts-agent/files/2206193/Agent_20180717-175639-utc.log)
[Agent_20180717-191109-utc.log](https://github.com/Microsoft/vsts-agent/files/2206194/Agent_20180717-191109-utc.log)
[Agent_20180717-191310-utc.log](https://github.com/Microsoft/vsts-agent/files/2206195/Agent_20180717-191310-utc.log)
[Worker_20180717-191027-utc.log](https://github.com/Microsoft/vsts-agent/files/2206196/Worker_20180717-191027-utc.log)

**Comment by TingluoHuang** [comment]
@xtreampb believe or not, i guess your machine is restart quicker for the failed case.
in succeed case:
agent receive shutdown signal from OS at `[2018-07-17 18:25:58Z INFO Agent] Received Ctrl-Break signal from agent service host, this indicate the operating system is shutting down.` 
if you check the worker log, your powershell script to call restart finished at `[2018-07-17 18:25:51Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.3477566.`
it toke 7 seconds for windows to response Restart command.

in failed case:
agent receive shutdown signal from OS at `[2018-07-17 19:10:51Z INFO Agent] Received Ctrl-Break signal from agent service host, this indicate the operating system is shutting down.` 
the worker log shows your powershell script finished at `[2018-07-17 19:10:49Z INFO ProcessInvokerWrapper] Finished process with exit code 0, and elapsed time 00:00:00.3635295.`
it only toke 2 seconds for OS to handle Restart.

i believe the 2s vs 7s will make a huge different for your case.

**Comment by xtreampb** [comment]
Okay i understand what your saying, however, when I use the agent version 2.134.2 and I get the same failure on that powershell task, but the status is fully reported to VSTS release manager, not giving me a connection error.  These are the logs from the same machine and release, just downgraded to agent version 2.134.2:
[Agent_20180718-141539-utc.log](https://github.com/Microsoft/vsts-agent/files/2206286/Agent_20180718-141539-utc.log)
[Agent_20180718-141644-utc.log](https://github.com/Microsoft/vsts-agent/files/2206287/Agent_20180718-141644-utc.log)
[Agent_20180718-142025-utc.log](https://github.com/Microsoft/vsts-agent/files/2206288/Agent_20180718-142025-utc.log)
[Worker_20180718-141753-utc.log](https://github.com/Microsoft/vsts-agent/files/2206289/Worker_20180718-141753-utc.log)

and the resulting VSTS release view:
![partial successfull deployment](https://user-images.githubusercontent.com/1777628/42890456-e2ccbb28-8a7a-11e8-86d0-84eda11d38c8.PNG)

This picture is in contrast to the same release, but shown as a complete failure. (re attached below for convenience): 
![failed to initialize](https://user-images.githubusercontent.com/1777628/42890534-12468e6a-8a7b-11e8-99e4-f11490a30530.PNG)

**Comment by TingluoHuang** [comment]
@xtreampb your entire release only runs for less than 30 seconds.

**Comment by TingluoHuang** [comment]
I am going to close this issue, the agent never support handle machine reboot, we do have a backlog work item to improve it.
#1505
