### ISSUE TITLE
Process cleanup not working on MacOS

### ISSUE THREAD

**Issue by vitru** [Microsoft/vsts-agent#1717]
## Have you tried trouble shooting?
Yes

## Agent Version and Platform
Agent 2.131.0
MacOS 10.13.2

## VSTS Type and Version
VisualStudio.com 

http://office.visualstudio.com

## What's not working?
Cancelling the build should terminate all the processes started during the build. There is process cleanup mechanism in JobRunner.cs which looks for processes that have a certain environment variable and kills them. This doesn't work on MacOS. Processes started during the build keep running even if the build is cancelled, which causes issues for the subsequent builds on the same machine.

## Agent and Worker's Diagnostic Logs
Running with VSTSAGENT_TRACE=1 shows that the agent tries to use /proc namespace, which is not available on MacOS:
[2018-07-20 06:20:25Z INFO StepsRunner] Current state: job state = 'Canceled'
[2018-07-20 06:20:25Z INFO JobRunner] Total accessible running process: 295.
[2018-07-20 06:20:25Z INFO JobRunner] Inspecting process environment variables. PID: 60818 (clang)
[2018-07-20 06:20:25Z VERB JobRunner] Ignore any exception during read process environment variables.
[2018-07-20 06:20:25Z VERB JobRunner] System.IO.DirectoryNotFoundException: Could not find a part of the path '/proc/60818/environ'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.VisualStudio.Services.Agent.LinuxProcessExtensions.GetEnvironmentVariables(Process process)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobRunner.<RunAsync>d__2.MoveNext()

**Comment by TingluoHuang** [comment]
@vitru thanks for report this, i will fix it in next agent release.

**Comment by TingluoHuang** [comment]
I am going to close this issue as the fix has merged, we are working on the roll out.
