### ISSUE TITLE
Request to https://<account>.visualstudio.com/_apis/connectionData failed. HTTP Status: NotFound

### ISSUE THREAD

**Issue by danielstocker** [Microsoft/vsts-agent#1720]
## Have you tried trouble shooting?
[Trouble shooting doc](https://www.visualstudio.com/en-us/docs/build/troubleshooting)
Yes, we initially troubleshooted a proxy issue, which led us to download the latest agent. 
The agent seems to connect successfully, but then comes up as offline in VSTS (see screenshot) 

Here is the command line used:
.\config.cmd --url https://account.visualstudio.com --auth pat --token actualPat --runAsService --windowsLogonAccount "domain\account" --windowslogonpassword "password" --acceptTeeEula --pool poolName --proxyurl proxyUrl --proxyusername userName --proxypassword password

Looking at the logs, it looks like the agent is trying to call out to https://cemobiledevelopment.visualstudio.com/_apis/connectionData?connectOptions=0&lastChangeId=172793905&lastChangeId64=172793905 (or similar), but the get request ends in a 404

## Agent Version and Platform
Version of your agent? **v2.138.0** 
_latest at the moment_

OS of the machine running the agent? 
Windows Server 2012 R2

## VSTS Type and Version
VisualStudio.com or On-Prem TFS?
_VisualStudio.com_

If VisualStudio.com, what is your account name?
_https://cemobiledevelopment.visualstudio.com_

## What's not working?
As above. 
Screenshot underneath. 

![vsts-issue-agent](https://user-images.githubusercontent.com/9444698/43001787-09950750-8c16-11e8-8a8a-6af81bf73441.png)

Here is the exception from the agent diagnostics log:
[2018-07-20 11:52:36Z ERR  MessageListener] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Not Found
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<HandleResponseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__47`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<CreateSessionAsync>d__11.MoveNext()

It retries 4 times before giving up, which is when the service restarts. 

We enabled HTTP tracing, but it only shows that the 404 comes back:
[2018-07-20 11:52:36Z INFO HttpTrace] Trace System.Net.Http.HttpRequestOut.Start event:
{ Request = Method: GET, RequestUri: 'https://cemobiledevelopment.visualstudio.com/_apis/connectionData?connectOptions=0&lastChangeId=172793905&lastChangeId64=172793905', Version: 1.1, Content: <null>, Headers:
{
  Accept: application/json
  User-Agent: VSServices/16.138.27905.0
  User-Agent: (NetStandard; Microsoft Windows 6.3.9600)
  User-Agent: VstsAgentCore-win-x64/2.138.0
  User-Agent: (Microsoft Windows 6.3.9600)
  X-VSS-E2EID: 18c86d6f-df32-404a-9338-0f9fd93a625a
  Accept-Language: en-US
  Accept-Language: en-GB
  X-TFS-FedAuthRedirect: Suppress
  X-TFS-Session: 24404187-9dea-402f-b64c-c96ec4597108
} }
[2018-07-20 11:52:36Z INFO HttpTrace] Trace System.Net.Http.Request event:
{ Request = Method: GET, RequestUri: 'https://cemobiledevelopment.visualstudio.com/_apis/connectionData?connectOptions=0&lastChangeId=172793905&lastChangeId64=172793905', Version: 1.1, Content: <null>, Headers:
{
  Accept: application/json
  User-Agent: VSServices/16.138.27905.0
  User-Agent: (NetStandard; Microsoft Windows 6.3.9600)
  User-Agent: VstsAgentCore-win-x64/2.138.0
  User-Agent: (Microsoft Windows 6.3.9600)
  X-VSS-E2EID: 18c86d6f-df32-404a-9338-0f9fd93a625a
  Accept-Language: en-US
  Accept-Language: en-GB
  X-TFS-FedAuthRedirect: Suppress
  X-TFS-Session: 24404187-9dea-402f-b64c-c96ec4597108
}, LoggingRequestId = 89847b42-0e02-4f0a-ac7b-8a8223b86517, Timestamp = 72360141585795 }
[2018-07-20 11:52:36Z INFO HttpTrace] Trace System.Net.Http.HttpRequestOut.Stop event:
{ Response = StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.0, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
{
  Connection: Keep-Alive
  Server: BigIP
  Content-Length: 111
  Content-Type: text/html
}, Request = Method: GET, RequestUri: 'https://cemobiledevelopment.visualstudio.com/_apis/connectionData?connectOptions=0&lastChangeId=172793905&lastChangeId64=172793905', Version: 1.1, Content: <null>, Headers:
{
  Accept: application/json
  User-Agent: VSServices/16.138.27905.0
  User-Agent: (NetStandard; Microsoft Windows 6.3.9600)
  User-Agent: VstsAgentCore-win-x64/2.138.0
  User-Agent: (Microsoft Windows 6.3.9600)
  X-VSS-E2EID: 18c86d6f-df32-404a-9338-0f9fd93a625a
  Accept-Language: en-US
  Accept-Language: en-GB
  X-TFS-FedAuthRedirect: Suppress
  X-TFS-Session: 24404187-9dea-402f-b64c-c96ec4597108
  Request-Id: |8c839059-43110833347ab474.
}, RequestTaskStatus = RanToCompletion }
[2018-07-20 11:52:36Z INFO HttpTrace] Trace System.Net.Http.Response event:
{ Response = StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.0, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
{
  Connection: Keep-Alive
  Server: BigIP
  Content-Length: 111
  Content-Type: text/html
}, LoggingRequestId = 89847b42-0e02-4f0a-ac7b-8a8223b86517, TimeStamp = 72360141593213, RequestTaskStatus = RanToCompletion }
[2018-07-20 11:52:36Z ERR  VisualStudioServices] GET request to https://cemobiledevelopment.visualstudio.com/_apis/connectionData?connectOptions=0&lastChangeId=172793905&lastChangeId64=172793905 failed. HTTP Status: NotFound

## Agent and Worker's Diagnostic Logs
as above, can provide full log if necessary

**Comment by TingluoHuang** [comment]
@danielstocker where is the 404 coming from?
```
{ Response = StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.0, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
{
Connection: Keep-Alive
Server: BigIP
Content-Length: 111
Content-Type: text/html
}, LoggingRequestId = 89847b42-0e02-4f0a-ac7b-8a8223b86517, TimeStamp = 72360141593213, RequestTaskStatus = RanToCompletion }
```
doesn't it coming from your proxy server `BigIP`?
can you hit that url `https://cemobiledevelopment.visualstudio.com/_apis/connectionData?connectOptions=0&lastChangeId=172793905&lastChangeId64=172793905` manually in browser (with/without proxy)?

**Comment by danielstocker** [comment]
Hi @TingluoHuang 
Just checked with the customer that is hitting this issue.

It looks like the wrong proxy was configured. It allowed only very selective access to the internet. We'll continue to investigate here locally. 

Thanks for your efforts! I'll close this issue for now
