### ISSUE TITLE
VSTS OnPrem-agent registration fails with VS30063 Company Proxy

### ISSUE THREAD

**Issue by bmpcon** [Microsoft/vsts-agent#1723]
## Agent Version and Platform:
vsts-agent-win-x64-2.136.1

## OS of the machine running the agent?
Microsoft Windows [Version 10.0.14393]

## VSTS Type and Version
Visual Studio Team Services (Azure) visualstudio.com

## What's not working?
We are able to download and install vsts agent and to register the current system as an VSTS agent within an existing agent-pool within on-prem enterprise network.

However after registering the agent itself we get an error:
Die Agent-Verbindung wird getestet. (Agent connection will be tested)
VS30063: You are not authorized to access https://xxxxxxxx.visualstudio.com. 

We are running the agent within enterprise network including web firewall with settings:
./config.cmd --proxyurl http://ourproxy:8080 --proxyusername "us" --proxypassword "pw"

## Agent and Worker's Diagnostic Logs

[2018-07-23 14:59:03Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\vstsagent\d\.credentials_rsaparams
[2018-07-23 14:59:03Z ERR  VisualStudioServices] POST request to https://xxxx.vssps.visualstudio.com/_apis/oauth2/token failed. HTTP Status: ProxyAuthenticationRequired
[2018-07-23 14:59:03Z ERR  VisualStudioServices] OAuth issued token provider instance 25605893 failed to retrieve a token.
Reason: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenHttpClient.<GetTokenAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenProvider.<OnGetTokenAsync>d__14.MoveNext()

**Comment by TingluoHuang** [comment]
@bmpcon thanks for reporting this, i will fix the regression.

**Comment by TingluoHuang** [comment]
I am going to close this issue as the fix has merged, we are working on the roll out.
