### ISSUE TITLE
Cleaning up artifacts folder failing with System.OperationCanceledException exception

### ISSUE THREAD

**Issue by GitHubSriramB** [Microsoft/vsts-agent#1738]
## Agent Version and Platform
Version of your agent? 2.136.1

OS of the machine running the agent? Windows

## VSTS Type and Version
VisualStudio.com

If VisualStudio.com, what is your account name? https://marketingops.vssps.visualstudio.com/

## What's not working?
Cleaning up artifacts directory is failing with "System.OperationCanceledException: The operation was canceled" exception. This exception is not being retried currently.

Here's the failure stack:
[2018-07-24 14:03:42Z ERR  DeploymentJobExtension] Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.ArtifactDirectoryCreationFailedException: Failed to create Release artifact directory 'C:\VSTSAgent\_work\r1\a'. ---> System.OperationCanceledException: The operation was canceled.
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseFileSystemManager.EnsureEmptyDirectory(String directoryPath, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseFileSystemManager.EnsureEmptyDirectory(String directoryPath, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.RetryExecutor.Execute(Action action)

**Comment by GitHubSriramB** [comment]
@ericsciple / @TingluoHuang - is IOUtil.DeleteDirectory supposed to throw System.OperationCanceledException?

**Comment by bryanmacfarlane** [comment]
@GitHubSriramB - I think it can if the job is cancelled and there's a cancellation token.

https://msdn.microsoft.com/en-us/library/system.operationcanceledexception(v=vs.110).aspx

"The exception that is thrown in a thread upon cancellation of an operation that the thread was executing."

Ting can confirm.

**Comment by TingluoHuang** [comment]
@GitHubSriramB if your build/release is canceled, we fire all cancellation tokens in the worker process tree to stop running threads/tasks ASAP, i assume that is when the OperationCancel exception will throw.

**Comment by TingluoHuang** [comment]
@GitHubSriramB i don't think we want to retry IO operation on cancellation, the worker process has a limited time to exit after receive cancellation message, if the IO operation's retry takes longer then that, the agent will just force kill the worker process.
