### ISSUE TITLE
VSTS agent can no longer get sources/clone a repository after update

### ISSUE THREAD

**Issue by shmatkotija** [Microsoft/vsts-agent#1781]
Agent Version and Platform: 2.138.6 and 2.139.0
OS: Ubuntu 16.04
VSTS Type and Version: VisualStudio.com

Our Linux agents tried to automatically update today and failed and then promptly stopped picking up jobs, so I manually removed each agent and downloaded the latest version to configure. They are picking up jobs now, but the Get Sources step now fails with Permission Denied.

Here's the actual exception:

[2018-08-23 23:17:17Z ERR  StepsRunner] Caught exception from step: System.ComponentModel.Win32Exception (13): Permission denied
   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userI$
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Enc$
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, E$
   at Microsoft.VisualStudio.Services.Agent.Worker.AgentPluginManager.RunPluginTaskAsync(IExecutionContext context, String plugin, Dictionary`2 inputs, Dictionary`2 environment, Variables runtimeV$
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.AgentPluginHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)

This affects *all* of our build agents that are using the new vsts agent version. Interestingly, our builds that do not "Get Sources" actually succeed until they get to the Post-job step "Get Sources" and fail then.

**Comment by shmatkotija** [comment]
I was able to figure this out - the newer version of the vsts agent does not install all of the executables with executable permissions. For example:
* Agent.Listener and Agent.Worker are "installed" with executable permissions if you follow the instructions to extract the archive
* Agent.PluginHost (which contains the Checkout task) is *not* "installed" with executable permissions.

So the Permission Denied error was coming from Agent.PluginHost when the parent task tried to run it.

**Comment by TingluoHuang** [comment]
@shmatkotija cool, thanks for figuring this out, it's weird i didn't catch this during testing, i will investigate and release a fix.

**Comment by TingluoHuang** [comment]
A newer version with the fix has been released, please check.
