### ISSUE TITLE
Release Agent: Error: No plan found for identifier

### ISSUE THREAD

**Issue by giggio** [Microsoft/vsts-agent#217]
I am getting this error on a Ubuntu 14.04 machine when a release is requested.

From the `_diag` folder, this is from the `Worker_20160531-192730-utc.log` file:

````
[2016-05-31 19:27:37Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 0/1.
[2016-05-31 19:27:37Z ERR  JobServerQueue] System.AggregateException: Catch exception during append web console line. (No plan found for identifier 46dfe81a-0e3f-409e-882b-4432ee0ca4b1.) ---> Microsoft.TeamFoundation.DistributedTask.WebA
pi.TaskOrchestrationPlanNotFoundException: No plan found for identifier 46dfe81a-0e3f-409e-882b-4432ee0ca4b1.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.JobServerQueue.<ProcessWebConsoleLinesQueueAsync>d__26.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.TeamFoundation.DistributedTask.WebApi.TaskOrchestrationPlanNotFoundException: No plan found for identifier 46dfe81a-0e3f-409e-882b-4432ee0ca4b1.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.JobServerQueue.<ProcessWebConsoleLinesQueueAsync>d__26.MoveNext()<---
````

On VSTS I get `Deployment on this environment was cancelled`.

In `Agent_20160531-192702-utc.log` I get:

````
[2016-05-31 19:27:09Z INFO Terminal] WRITE LINE: 2016-05-31 19:27:09Z: Listening for Jobs
[2016-05-31 19:27:28Z INFO JobDispatcher] Job request 6fd16eca-ab7b-41e0-919e-2d69d7d580c3 received.
[2016-05-31 19:27:28Z INFO Terminal] WRITE LINE: 2016-05-31 19:27:28Z: Running job: Release
[2016-05-31 19:27:28Z INFO JobDispatcher] Start renew job request.
[2016-05-31 19:27:29Z INFO JobDispatcher] Successfully renew job request, job is valid till 5/31/16 7:32:30 PM
[2016-05-31 19:27:29Z INFO ProcessInvoker] Starting process with file name '/agent/bin/Agent.Worker', arguments 'spawnclient 129 133', and working directory '/agent/bin'.
[2016-05-31 19:27:29Z INFO JobDispatcher] Send job request message to worker.
[2016-05-31 19:27:44Z INFO ProcessInvoker] Finished process with file name '/agent/bin/Agent.Worker', arguments 'spawnclient 129 133', exit code 102, and elapsed time 00:00:15.4110133.
[2016-05-31 19:27:44Z INFO JobDispatcher] Worker finished. Code: 102
[2016-05-31 19:27:44Z INFO JobDispatcher] finish job request with result: Failed
[2016-05-31 19:27:44Z INFO Terminal] WRITE LINE: 2016-05-31 19:27:44Z: Job Release completed with result: Failed
[2016-05-31 19:27:45Z INFO JobDispatcher] Stop renew job request.
[2016-05-31 19:27:45Z INFO JobDispatcher] job renew has been canceled, stop renew job request
````

I have installed all prerequisites as stated on the documentation.

**Comment by keannan5390** [comment]
I'm getting this same error on my OSx build agent. This is a huge problem right now, as I can build and not release. 

Since I can only run 1 local agent I'm hosed right now for build & release. Build will not work with the old xplat agent & release will not work with the new agent.

**Comment by kasubram** [comment]
I am looking into it. It looks like while trying to upload the task logs it throws the above exception. However the task itself should succeed.

**Comment by bryanmacfarlane** [comment]
@keannan5390 - the old xplat agent does work for build.  It is being deprecated in favor of moving to this one but it still works.

**Comment by keannan5390** [comment]
@kasubram if you're able to find a fix, is there anyway you can release a hotfix? All of my CI/CD configuration is now in VSTS and I need to do a release this week.

**Comment by bryanmacfarlane** [comment]
we are doing an updated agent preview drop tomorrow or next day at the latest.  @kasubram - please treat with high priority

**Comment by keannan5390** [comment]
@bryanmacfarlane hmmm, the build is never triggered for me with the xplat agent. It just sits and hangs in the queue and eventually seems to timeout after about 25 minutes with an error similar to this:
`The job has been abandoned because agent Devs-Mac-mini.local did not renew the lock. Ensure agent is running, not sleeping, and has not lost communication with the service.`

I upgraded the agent to see if that would resolve the issues for build -- which it did. I then ran into this error for preview 6.

Thank you for looking into this as a high priority. its greatly appreciated.

**Comment by kasubram** [comment]
https://github.com/Microsoft/vsts-agent/pull/258 should fix this. RM service port number is different from TFS. We were reconstructing the URL based on the config url, which is then used in uploading the log. When running the release, its talking to TFS instead of RM and trying to find the plan.

**Comment by kasubram** [comment]
This fix will be available in the upcoming preview

**Comment by keannan5390** [comment]
@kasubram thanks for the update. is there an estimated date for the release of the preview?

**Comment by udayalwala** [comment]
```
{
  "$id": "1",
  "innerException": null,
  "message": "No plan found for identifier 0097f397-6b6f-497a-9f6b-c9986ae59c5b.",
  "typeName": "Microsoft.TeamFoundation.DistributedTask.WebApi.TaskOrchestrationPlanNotFoundException, Microsoft.TeamFoundation.DistributedTask.WebApi",
  "typeKey": "TaskOrchestrationPlanNotFoundException",
  "errorCode": 0,
  "eventId": 3000
}
```

⚠️ Resource Authorization Issue:

"An error occurred while loading the YAML build pipeline. Variable group was not found or is not authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."

Verify Variable Group Access

Go to: Pipelines → Library

Select your variable group

Navigate to Pipeline Permissions

Ensure the variable group is either:

Open to all pipelines, or

Explicitly grants permission to the required pipeline(s)

Check Security Settings

Within the variable group → Security tab

Ensure the following identity has at least Read access:

[Project Name] Build Service ([Organization Name])

Ensure Correct Variable Group Names

Double-check the variable group names used in your YAML match the actual group names in the Library

Branch Consistency Between CI and CD Pipelines

If using pipeline triggers (e.g., CI triggers CD):

Make sure the branch in the CI pipeline and CD pipeline repo is the same

If branches differ, the CD pipeline may fail to retrieve variable group values



In my scenario:

CI pipeline is running on one branch (e.g., feature/xyz)

CD pipeline is on another (e.g., main)

The trigger from CI to CD worked, but the CD pipeline failed due to unauthorized access to variable groups — because variable groups are branch-scoped or misconfigured
