### ISSUE TITLE
Using TFS .local url from OSX leads to "Not found" error for on-premise TFS during configuration

### ISSUE THREAD

**Issue by aplex** [Microsoft/vsts-agent#218]
I'm trying to configure OS X agent with on-premise TFS, configuration script accepts url and credentials, but then prints "Not Found"

```
Enter server URL > https://tfsserv.mydomain.local
Enter authentication type (press enter for Negotiate) >
Enter user name > mydomain\buildagent
Enter password > *******
Connecting to server ...
Not Found
Failed to connect.  Try again or ctrl-c to quit
```

Docs show url ending with "/tfs", but it is not accepted by configuration script:

```
Enter server URL > https://tfsserv.mydomain.local/tfs
Enter a valid value for server URL.
```

Logs have the following stack trace for that "not found":

```
[2016-05-31 19:42:04Z INFO Terminal] WRITE LINE: Connecting to server ...
[2016-05-31 19:42:08Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-05-31 19:42:08Z ERR  Terminal] WRITE ERROR (exception):
[2016-05-31 19:42:08Z ERR  Terminal] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Not Found
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Client.VssServerDataProvider.<ConnectAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<TestConnectAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__8.MoveNext()
[2016-05-31 19:42:08Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit

```

OS X 10.11
TFS 2015 update 2

**Comment by bryanmacfarlane** [comment]
What url shows for the notification url in the admin console on the AT?

**Comment by aplex** [comment]
Notification url is https://tfsserv.mydomain.local/tfs

**Comment by bryanmacfarlane** [comment]
Does that resolve via DNS and nslookup from mac?  What about other OSes? The notification url in TFS needs to be set to an url that all platforms, OSes and clients can resolve (it will put in emails).

It's OK for the OSX box to know the server by a different name (machinename.local etc...) than the notification url, we handle that in the agent.

**Comment by aplex** [comment]
Yep, I can ping/nslookup that server from os x. It also opens fine in Safari on that box. That url also opens fine on a different Windows box.

This server has a certificate signed by in-house domain CA, but that domain CA is added as a trusted root to the keychain.

**Comment by bryanmacfarlane** [comment]
Link for Stan: https://support.apple.com/en-us/HT201275

**Comment by bryanmacfarlane** [comment]
It seems that the not found is correct.  There is no application at the root.

The core issue seems to be that it thinks https://tfsserv.mydomain.local/tfs is an invalid url and obviously it's not.

**Comment by aplex** [comment]
Oh, interesting. I was putting different urls when config.sh re-prompted me for them, and they were rejected. But, after I closed/restarted config.sh, the new url (https://tfsserv.mydomain.local/tfs) was accepted and it connected fine.

**Comment by stiliev** [comment]
There is an issue with using "DEL" key while typing in config.sh, that may have caused the initial attempt to type the URL to be rejected.

**Comment by bryanmacfarlane** [comment]
oooh - good point

**Comment by bryanmacfarlane** [comment]
Closing since we're tracking DEL key issue separately and it connected fine.
