### ISSUE TITLE
Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063

### ISSUE THREAD

**Issue by WebDucer** [Microsoft/vsts-agent#223]
We switched to TFS 2015 on perm.

The xplat agent on a mac works fine (except the checkout git of submodules).

Now I wanted to test the new cross platform agent and fails with following error message on agent. During the configuration agent was added to the agent pool and is seen as online.

```
[2016-06-01 13:34:56Z INFO Program] Version: 2.101.0
[2016-06-01 13:34:56Z INFO Program] Commit: 043f11f423a30cdc7143344a72e66f49f8b13861
[2016-06-01 13:34:56Z INFO Worker] Waiting to receive the job message from the channel.
[2016-06-01 13:34:56Z INFO Worker] Message received.
[2016-06-01 13:34:57Z INFO Worker] Job message: {"tasks":[{"instanceId":"1675c3ed-c74d-48fb-a647-c5968d74c549","displayName":"gradlew assemblyDebug","enabled":true,"continueOnError":false,"alwaysRun":false,"id":"8d8eebd8-2b94-4c97-85af-839254cc6da4","name":"Gradle","version":"1.0.26","inputs":{"wrapperScript":"gradlew","options":"","tasks":"assemblyDebug","cwd":"","javaHomeSelection":"JDKVersion","jdkVersion":"default","jdkUserInputPath":"","jdkArchitecture":"x86","publishJUnitResults":"false","testResultsFiles":"**/build/test-results/TEST-*.xml","testRunTitle":"","codeCoverageTool":"None","classFilesDirectories":"build/classes/main/","classFilter":""}}],"requestId":49,"lockToken":"00000000-0000-0000-0000-000000000000","lockedUntil":"0001-01-01T00:00:00","plan":{"scopeIdentifier":"ad66c17f-9e99-4632-86b6-0753aca7736a","planType":"Build","version":5,"planId":"0973ec0a-f706-4e89-8761-eafdbfd9516b","artifactUri":"vstfs:///Build/Build/30","artifactLocation":null},"timeline":{"id":"0be77d0b-b5d8-44cb-ae45-5014ef962672","changeId":1,"location":null},"jobId":"4da723ae-9d5a-4161-9d5e-0633a47f7044","jobName":"Build","environment":{"endpoints":[{"data":{"repositoryId":"0699e0aa-4400-447e-b6e1-ee1c7f6d3c52","rootFolder":null,"clean":"false","checkoutSubmodules":"True"},"name":"iRecy Mobilewaage (Android)","type":"TfsGit","url":"http://devteam:8080/tfs/iRecy Android/_git/iRecy%20Mobilewaage%20%28Android%29","authorization":{"parameters":{"AccessToken":"********"},"scheme":"OAuth"}}],"mask":[{"type":"regex","value":********}],"variables":{"system.definitionId":"2","build.definitionName":"CI Build","build.definitionVersion":"7","build.queuedBy":"TFSService","build.queuedById":"6dcca9b6-d9eb-4a1a-a28b-9b20a28c5f0e","build.requestedFor":"TFSService","build.requestedForId":"6dcca9b6-d9eb-4a1a-a28b-9b20a28c5f0e","build.sourceVersion":"9fb78a4eb0ce3ca6dfd21d53a74d77da4beb4406","build.sourceBranch":"refs/heads/develop","build.sourceBranchName":"develop","system.debug":"false","ANDROID_HOME":"/Users/Shared/android-sdk","build.buildId":"30","build.buildUri":"vstfs:///Build/Build/30","build.buildNumber":"30","build.containerId":"35","system":"build","system.hosttype":"build","system.collectionId":"876fee52-bd4d-493f-a140-f3899d451672","system.teamProjectId":"ad66c17f-9e99-4632-86b6-0753aca7736a","system.teamProject":"iRecy Mobilewaage (Android)","system.culture":"en-US","system.teamFoundationCollectionUri":"http://devteam:8080/tfs/iRecy%20Android/","system.taskDefinitionsUri":"http://devteam:8080/tfs/iRecy%20Android/","build.sourceVersionAuthor":"Gavin Fuchs","build.sourceVersionMessage":"Merge branch 'Thommen_Änderungen_Mobile_Waage_feedback_001' into develop"},"systemConnection":{"data":{"ServerId":"876fee52-bd4d-493f-a140-f3899d451672","ServerName":"iRecy Android"},"name":"SystemVssConnection","url":"http://devteam:8080/tfs/iRecy Android/","authorization":{"parameters":{"AccessToken":"********"},"scheme":"OAuth"}}}}
[2016-06-01 13:34:57Z INFO JobRunner] Job ID 4da723ae-9d5a-4161-9d5e-0633a47f7044
[2016-06-01 13:34:57Z INFO ConfigurationStore] currentAssemblyLocation: /Users/admin/vsts-agent-osx/bin/Agent.Worker.dll
[2016-06-01 13:34:57Z INFO ConfigurationStore] binPath: /Users/admin/vsts-agent-osx/bin
[2016-06-01 13:34:57Z INFO ConfigurationStore] RootFolder: /Users/admin/vsts-agent-osx
[2016-06-01 13:34:57Z INFO ConfigurationStore] ConfigFilePath: /Users/admin/vsts-agent-osx/.Agent
[2016-06-01 13:34:57Z INFO ConfigurationStore] CredFilePath: /Users/admin/vsts-agent-osx/.Credentials
[2016-06-01 13:34:57Z INFO ConfigurationStore] ServiceConfigFilePath: /Users/admin/vsts-agent-osx/.Service
[2016-06-01 13:34:57Z INFO Worker] Listening for cancel message from the channel.
[2016-06-01 13:34:57Z INFO Worker] Waiting for the job to complete or for a cancel message from the channel.
[2016-06-01 13:34:57Z INFO Worker] Job completed.
[2016-06-01 13:34:57Z ERR  Program] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access http://devteam:8080.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
...
```

I use the same domain user for this agent as for the xplat agent. both are configured as deamons on OS X.

**Comment by bryanmacfarlane** [comment]
Can you try and setup 2.101.1? 
Above is the agent listener log.  When it ran, was there another worker log created?

**Comment by bryanmacfarlane** [comment]
Can't repro - can you send all logs (worker log)?  In the next drop we'll also support proxies so we can trap http traffic to troubleshoot

**Comment by WebDucer** [comment]
I tried the new 2.101.1 version today with the same result (tested with domain and local tfs user).

Here are the logs:
[Logs.zip](https://github.com/Microsoft/vsts-agent/files/300413/Logs.zip)

**Comment by bryanmacfarlane** [comment]
Let's get an http trace when the next update comes out (2.102.0)

**Comment by bryanmacfarlane** [comment]
2.102.0 is dropped and supports capturing http trace.  See troubleshooting section.  Don't post http trace publicly - see security notice

**Comment by bryanmacfarlane** [comment]
Any luck on 2.102.0 and the http trace?  Details on failed call?

**Comment by ericsciple** [comment]
@WebDucer what version of TFS 2015? e.g. RTM or Update 2

**Comment by WebDucer** [comment]
No luck with version 2.102.1 on my OS X test system. Currently I'm trying to create the HTTP trace.

@ericsciple We use TFS 2015 Update 2 (14.95.25122.0 (Tfs2015.Update2))

**Comment by WebDucer** [comment]
If I try to trace the HTTP with Charles Proxy on, I got the error:

```
SP324097: Your network proxy requires authentification.
```

We use no proxy in our network. The build agent user is a domain user.

**Comment by bryanmacfarlane** [comment]
@WebDucer - attach _diag from 2.102.1 with no proxy running.  Are you using TfsVC?  After the trace, if you retry with charles,only trace the agent - see how I setup charles in [this video](https://www.youtube.com/watch?v=PAVG50t_1bw)

@ericsciple - that proxy error looks to be coming from TEE.

**Comment by WebDucer** [comment]
@bryanmacfarlane 
[_diag.zip](https://github.com/Microsoft/vsts-agent/files/334929/_diag.zip)

Logs are attached.

Depend on project we use TFVC and Git. Currently I test all builds with team projects based on Git as version control.

I cannot start the agent, after Charles is running.

[buildagent.zip](https://github.com/Microsoft/vsts-agent/files/334946/buildagent.zip)

**Comment by TingluoHuang** [comment]
@WebDucer Would you like to try out a private agent that i built for testing?

**Comment by WebDucer** [comment]
@TingluoHuang Yes. How do I get them?

**Comment by TingluoHuang** [comment]
@WebDucer are you able to build the agent from source? i can push a branch, and you build the agent from that branch?

**Comment by TingluoHuang** [comment]
@WebDucer if you can, `users/tihuang/tryout` is the branch.

**Comment by ericsciple** [comment]
fyi - prerequisites are here: https://github.com/Microsoft/vsts-agent/blob/master/docs/contribute.md

`./dev.sh layout` is what you want to do. The layout folder is created under the root of the repo in a _layout folder.

**Comment by WebDucer** [comment]
Can I build OS X agent on a Windows OS? Or does I need to build this on OS X?

**Comment by WebDucer** [comment]
I have build the agent on OS X (agent host). With the same result. Logs (with and without proxy attached).
[Run with test version.zip](https://github.com/Microsoft/vsts-agent/files/340877/Run.with.test.version.zip)

**Comment by TingluoHuang** [comment]
Did you build my branch? `users/tihuang/tryout` i didn't see my change base on the log file you send.

**Comment by WebDucer** [comment]
You are right. Have build the correct branch on Windows, but wrong on OS X.

Now the log of the tryout build is attached.

[Tryout logs.zip](https://github.com/Microsoft/vsts-agent/files/341614/Tryout.logs.zip)

**Comment by TingluoHuang** [comment]
Thanks for try out, we need http trace for debug. if you have access to the Server machine, you may also able to use Fiddler catch the traffic from server side if you not able to use Charles catch http trace.

**Comment by TingluoHuang** [comment]
@WebDucer few more tryout.
1. Can you repro this issue with a Windows vsts-agent 2.102.1 connect to the same TFS instance?
2. Can you check your cURL version, can you try to upgrade to latest?

**Comment by WebDucer** [comment]
I cannot trance on production tfs server. I will try the windows agent on monday and report back.

**Comment by WebDucer** [comment]
I've had cURL 7.43.0 on OS X. I updated this to 7.49.1 (no changes in agent behavior).

Windows agent can connect TFS, but got the "User does not have write permissions for orchestration plan" error.

[_diag.zip](https://github.com/Microsoft/vsts-agent/files/345973/_diag.zip)

**Comment by TingluoHuang** [comment]
@WebDucer on the build definition you get "User does not have write permissions for orchestration plan" exception, 
what security setting does that definition has?

Here is one of my build definition's security setting.
Make sure your definition has similar settings.
![image](https://cloud.githubusercontent.com/assets/1750815/16827131/9adce944-4951-11e6-8831-5031416d887a.png)

**Comment by WebDucer** [comment]
@TingluoHuang:  I have the same permissions set

![tfs-build-security](https://cloud.githubusercontent.com/assets/761881/16827960/baea0232-498b-11e6-9df2-e10031efd9ba.png)

**Comment by TingluoHuang** [comment]
@WebDucer  We published 2.104.1 which contains the change might able to fix your problem, can you take a try? Thanks,

**Comment by bryanmacfarlane** [comment]
We can't repro and the fix was in 104.1 we believe.  Reactivate if you're having an issue still.

**Comment by peterM** [comment]
[2016-09-26 20:52:35Z ERR  Agent] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access "https" 

I have installed TFS '15' RC2 on premise and this issue i had on RC1 too.

I tried RC1 agent, RC2 agent and VSO Agent. 
Last agent i tried is  vsts-agent-win7-x64-2.107.0

So thank tou for help.

**Comment by TingluoHuang** [comment]
@peterM this is a different issue, can you open a new issue with full agent diag log attached?

**Comment by peterM** [comment]
I got the same error so i think is the same issue but OK . I created another one: #612
