### ISSUE TITLE
xcode build clean fails

### ISSUE THREAD

**Issue by schmichri** [Microsoft/vsts-agent#236]
Hi all, 

when I configure a "build clean" action in a xcode build step my agent returns with an error after the clean

```

 ##[error]Commond doesn't have valid result value.
 ##[error]Unable to process command Microsoft.VisualStudio.Services.Agent.Command successfully.
```

and the build step breaks with an error in VSTS. 
I'm running the currently latest agent (Preview 6 v2.101.1 / June)

**Comment by ericsciple** [comment]
Are you on VSTS or on-premises TFS? If TFS, which version?

**Comment by ericsciple** [comment]
@schmichri What is the offending command? It should be in the build log and starts with `##vso[`.

If it's not printed in the log, try running a build with `system.debug` set to `true` (on the variables tab of the definition)?

**Comment by schmichri** [comment]
It's on VSTS.

after the 

2016-06-04T05:58:10.4328310Z ** CLEAN SUCCEEDED **
2016-06-04T05:58:10.4333040Z 
2016-06-04T05:58:10.4498520Z ##[debug]packageApp=true
2016-06-04T05:58:10.4506260Z ##[debug]Processed logging command: ##vso[task.debug]packageApp=true
2016-06-04T05:58:10.4518770Z ##[debug]Packaging apps.
2016-06-04T05:58:10.4526560Z ##[debug]Processed logging command: ##vso[task.debug]Packaging apps.
2016-06-04T05:58:10.4539260Z ##[debug]out: /Users/builder/myagent-june/_work/3/output/iphoneos/Release
2016-06-04T05:58:10.4547930Z ##[debug]Processed logging command: ##vso[task.debug]out: /Users/builder/myagent-june/_work/3/output/iphoneos/Release
2016-06-04T05:58:10.4564090Z ##[debug]outPath: /Users/builder/myagent-june/_work/3/output/iphoneos/Release/build.sym
2016-06-04T05:58:10.4573320Z ##[debug]Processed logging command: ##vso[task.debug]outPath: /Users/builder/myagent-june/_work/3/output/iphoneos/Release/build.sym
2016-06-04T05:58:10.4586670Z ##[debug]glob /Users/builder/myagent-june/_work/3/output/iphoneos/Release/build.sym/**/*.app
2016-06-04T05:58:10.4596140Z ##[debug]Processed logging command: ##vso[task.debug]glob /Users/builder/myagent-june/_work/3/output/iphoneos/Release/build.sym/**/*.app
2016-06-04T05:58:10.4609060Z ##[debug]found 0 matches
2016-06-04T05:58:10.4616730Z ##[debug]Processed logging command: ##vso[task.debug]found 0 matches
2016-06-04T05:58:10.4629390Z ##[debug]0 apps found for packaging.
2016-06-04T05:58:10.4637120Z ##[debug]Processed logging command: ##vso[task.debug]0 apps found for packaging.
2016-06-04T05:58:10.4649090Z ##[debug]check path : /usr/bin/xcrun
2016-06-04T05:58:10.4656790Z ##[debug]Processed logging command: ##vso[task.debug]check path : /usr/bin/xcrun
2016-06-04T05:58:10.4668750Z ##[debug]xcrun=/usr/bin/xcrun
2016-06-04T05:58:10.4676400Z ##[debug]Processed logging command: ##vso[task.debug]xcrun=/usr/bin/xcrun
2016-06-04T05:58:10.4700220Z ##[debug]task result: undefined
2016-06-04T05:58:10.4708050Z ##[debug]Processed logging command: ##vso[task.debug]task result: undefined
2016-06-04T05:58:10.4754750Z ##[error]Commond doesn't have valid result value.
2016-06-04T05:58:10.4861110Z ##[debug]System.Exception: Commond doesn't have valid result value.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskCommandExtension.ProcessTaskCompleteCommand(IExecutionContext context, Dictionary`2 eventProperties, String data)
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
2016-06-04T05:58:10.4871480Z ##[error]Unable to process command Microsoft.VisualStudio.Services.Agent.Command successfully.
2016-06-04T05:58:10.5126600Z ##[section]Finishing: Xcode build clean

**Comment by schmichri** [comment]
do you need more information?

**Comment by madhurig** [comment]
I can repro the issue, I will take a look

**Comment by madhurig** [comment]
@schmichri: please see my fix in the task to avoid this issue. If you update the task in your agent's _work folder, it should unblock you. The task-lib/agent can do a better job of handling this, I will follow up on that.

Thanks,
Madhuri

**Comment by madhurig** [comment]
Fix has been merged and will be deployed to Team Services in a couple of weeks. 

In the meanwhile, as a workaround apply this fix https://github.com/Microsoft/vsts-tasks/pull/1857/commits/0469025331ae544f237f2c40e2c4381e029535ca to the xcodebuild2.js in the agent's work folder. 

@schmichri: Thank you for reporting the issue.

-Madhuri

**Comment by schmichri** [comment]
@madhurig: welcome and thanks for the fix. 
I'm curious when it's deployed in VSTS. Any chance you let me know?

**Comment by madhurig** [comment]
I don't have exact date but the fix should be deployed to VSTS around July 1st. Sorry for the inconvenience.

**Comment by schmichri** [comment]
I've had the chance to test yesterday, I'm calling now:
`Actions: clean build`

And it worked well. Thanks
