### ISSUE TITLE
running as windows service works only if using the same account that executed config script

### ISSUE THREAD

**Issue by stiliev** [Microsoft/vsts-agent#254]
Running as windows service works only if using the same account that executed config script. If another account is used to run the service an exception is thrown (below). 
2016-06-06 14:36:38Z ERR  AgentProcess] Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Keyset does not exist
   at System.Security.Cryptography.CngKey.Open(String keyName, CngProvider provider, CngKeyOpenOptions openOptions)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.RSACngKeyManager.GetKey() in D:\prj\vsts-agent2\src\Agent.Listener\Configuration\RSACngKeyManager.cs:line 97
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.OAuthCredential.<>c__DisplayClass2_0.<GetVssCredentials>b__0() in D:\prj\vsts-agent2\src\Agent.Listener\Configuration\OAuthCredential.cs:line 31
   at Microsoft.VisualStudio.Services.WebApi.VssSigningCredentials.Create(Func`1 factory)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.OAuthCredential.GetVssCredentials(IHostContext context) in D:\prj\vsts-agent2\src\Agent.Listener\Configuration\OAuthCredential.cs:line 31
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.CredentialManager.LoadCredentials() in D:\prj\vsts-agent2\src\Agent.Listener\Configuration\CredentialManager.cs:line 56
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<CreateSessionAsync>d__12.MoveNext() in D:\prj\vsts-agent2\src\Agent.Listener\MessageListener.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<RunAsync>d__11.MoveNext() in D:\prj\vsts-agent2\src\Agent.Listener\Agent.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext() in D:\prj\vsts-agent2\src\Agent.Listener\Agent.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.<MainAsync>d__2.MoveNext() in D:\prj\vsts-agent2\src\Agent.Listener\Program.cs:line 84

**Comment by bryanmacfarlane** [comment]
@patrickcarnahan - I think we agreed to store machine level correct?

**Comment by stiliev** [comment]
I switched the key store to machine level and improved a bit the situation, but not completely. The "network service" account still gets the same exception "Key not found". However I'm able to run the service under a different account, just not "Network service" (for example config with domain account, run the service with an account I created locally on my box).

**Comment by stiliev** [comment]
"Network service" account is restricted. I found an article on MSDN, that suggests how to grant read privilege for a certain key, but have not tried if it is going to work.

**Comment by bryanmacfarlane** [comment]
Fixed with https://github.com/Microsoft/vsts-agent/commit/cd23507341a55648d609914539b70fc4c3ced77d
