### ISSUE TITLE
'submodule' appears to be a git command, but we were not able to execute it. Maybe git-submodule is broken?

### ISSUE THREAD

**Issue by neilhuiz** [Microsoft/vsts-agent#304]
I just stood up my first agent and each build fails when it tries to pull in submodules. I verified that if I run the copy of git installed on the box, it works fine, but manually running the git tools in agent\external\git it fails as well.

Version: 2.102.0 (RC1)

````
******************************************************************************
Starting: Build
******************************************************************************
******************************************************************************
Starting: Get Sources
******************************************************************************
Syncing repository: ******** (TfsGit)
git version
git config --get remote.origin.url
git clean -fdx
git reset --hard HEAD
HEAD is now at e9d1578 Little tweaks to layout & colors
git config gc.auto 0
git -c http.extraheader="AUTHORIZATION: bearer ********" fetch --tags --prune --progress origin
git checkout --progress --force e9d15780e32c00775a296de008cf809b015f119c
HEAD is now at e9d1578... Little tweaks to layout & colors Added legend to branch rotation pages Added text to home page related to branch look-up tool
git submodule init
fatal: 'submodule' appears to be a git command, but we were not
able to execute it. Maybe git-submodule is broken?
Git submodule init failed with exit code: 128
******************************************************************************
Finishing: Get Sources
******************************************************************************
````

**Comment by TingluoHuang** [comment]
Can you share your machine's OS info? and paste your agent/worker _diag log located at _diag folder of agent? and what is the version of the git you paste works?

**Comment by bryanmacfarlane** [comment]
@neilhuiz - details?

**Comment by neilhuiz** [comment]
Machine/OS: Azure VM running **Windows Server 2012 R2 Datacenter**
Working git version: **2.9.0.1**
Diag output **(Worker)**:

````
[2016-06-16 22:09:01Z INFO Program] Version: 2.102.0
[2016-06-16 22:09:01Z INFO Program] Commit: 94d84052aeb11d6dfd9cef7d190ebcb5a3f11095
[2016-06-16 22:09:01Z INFO Program] Culture: en-US
[2016-06-16 22:09:01Z INFO Program] UI Culture: en-US
[2016-06-16 22:09:01Z INFO Worker] Waiting to receive the job message from the channel.
[2016-06-16 22:09:02Z INFO Worker] Message received.
[2016-06-16 22:09:02Z INFO Worker] Job message: {"tasks":[{"instanceId":"84a7826e-bbda-426b-b7da-3cddf995fcc8","displayName":"Powershell: mod-build/pre-build.ps1","enabled":true,"continueOnError":false,"alwaysRun":false,"timeoutInMinutes":0,"id":"e213ff0f-5d5c-4791-802d-52ea3e7be1f1","name":"PowerShell","version":"1.1.1","inputs":{"scriptType":"filePath","scriptName":"mod-build/pre-build.ps1","arguments":"-sourceRoot $(Build.SourcesDirectory)","inlineScript":"# You can write your powershell scripts inline here. \n# You can also pass predefined and custom variables to this scripts using arguments\n\n Write-Host \"Hello World\"","workingFolder":""}},{"instanceId":"e16504c8-4bf6-4012-a094-6a4c53fc9267","displayName":"Build project build/build.proj","enabled":true,"continueOnError":false,"alwaysRun":false,"timeoutInMinutes":0,"id":"71a9a2d3-a98a-4caa-96ab-affca411ecda","name":"VSBuild","version":"1.0.31","inputs":{"solution":"build/build.proj","msbuildArgs":"/p:Drop=$(Build.StagingDirectory) /p:Source=$(Build.SourcesDirectory)","platform":"$(BuildPlatform)","configuration":"$(BuildConfiguration)","clean":"true","vsVersion":"latest","restoreNugetPackages":"false","msbuildArchitecture":"x86","logProjectEvents":"true"}},{"instanceId":"1778c896-70c4-43d6-84d7-28a8fdb87f5f","displayName":"Deploy project build/deploy.proj","enabled":true,"continueOnError":false,"alwaysRun":false,"timeoutInMinutes":0,"id":"71a9a2d3-a98a-4caa-96ab-affca411ecda","name":"VSBuild","version":"1.0.31","inputs":{"solution":"build/deploy.proj","msbuildArgs":"/t:Deploy /p:Drop=$(Build.StagingDirectory) /p:Source=$(Build.SourcesDirectory)","platform":"$(BuildPlatform)","configuration":"$(BuildConfiguration)","clean":"false","vsVersion":"latest","restoreNugetPackages":"false","msbuildArchitecture":"x86","logProjectEvents":"true"}},{"instanceId":"9d3e1d20-b8f7-420f-a603-c452e99c3308","displayName":"Test Assemblies $(Build.StagingDirectory)\\test\\**\\*smoke.test*.dll","enabled":true,"continueOnError":false,"alwaysRun":false,"timeoutInMinutes":0,"id":"ef087383-ee5e-42c7-9a53-ab56c98420f9","name":"VSTest","version":"1.0.37","inputs":{"testAssembly":"$(Build.StagingDirectory)\\test\\**\\*smoke.test*.dll","testFiltercriteria":"","runSettingsFile":"","overrideTestrunParameters":"","codeCoverageEnabled":"false","runInParallel":"false","vsTestVersion":"latest","pathtoCustomTestAdapters":"","otherConsoleOptions":"","testRunTitle":"","platform":"$(BuildPlatform)","configuration":"$(BuildConfigration)","publishRunAttachments":"true"}}],"requestId":424791,"lockToken":"00000000-0000-0000-0000-000000000000","lockedUntil":"0001-01-01T00:00:00","plan":{"scopeIdentifier":"7ace5871-dfd7-4ab9-bc89-863146bad37d","planType":"Build","version":5,"planId":"c518258a-9531-4dc5-88fa-809afc3ab8af","artifactUri":"vstfs:///Build/Build/655772","artifactLocation":null},"timeline":{"id":"3e347f2d-74cc-40c7-be8a-485657c24133","changeId":1,"location":null},"jobId":"8205bcb3-34c1-4566-b5bb-ec6b4bca3277","jobName":"Build","environment":{"endpoints":[{"data":{"repositoryId":"2f6ab705-c1e2-4a4c-81d8-9302245fc6b2","rootFolder":null,"clean":"true","checkoutSubmodules":"True","onpremtfsgit":"False"},"name":"wsd.es.wit.services","type":"TfsGit","url":"https://microsoft.visualstudio.com/OSGCXE/_git/wsd.es.wit.services","authorization":{"parameters":{"AccessToken":********},"scheme":"OAuth"}}],"mask":[{"type":"regex","value":********},{"type":"regex","value":********},{"type":"regex","value":********},{"type":"regex","value":********}],"variables":{"system":"build","system.collectionId":"cb55739e-4afe-46a3-970f-1b49d8ee7564","system.teamProject":"OSGCXE","system.teamProjectId":"7ace5871-dfd7-4ab9-bc89-863146bad37d","system.definitionId":"1714","build.definitionName":"wsd.es.wit.services-develop-ci","build.definitionVersion":"5","build.queuedBy":"Neil Huizenga","build.queuedById":"ecd83bad-952a-41e5-a08a-281b2d30677b","build.requestedFor":"Neil Huizenga","build.requestedForId":"ecd83bad-952a-41e5-a08a-281b2d30677b","build.sourceVersion":"e9d15780e32c00775a296de008cf809b015f119c","build.sourceBranch":"refs/heads/dev/deadlines","build.sourceBranchName":"deadlines","BuildConfiguration":"UAT","BuildPlatform":"Any CPU","build.buildId":"655772","build.buildUri":"vstfs:///Build/Build/655772","build.buildNumber":"20160616.5","build.containerId":"817810","system.hosttype":"build","system.culture":"en-US","system.teamFoundationCollectionUri":"https://microsoft.visualstudio.com/","system.taskDefinitionsUri":"https://microsoft.visualstudio.com/","build.sourceVersionAuthor":"Neil Huizenga","build.sourceVersionMessage":"Little tweaks to layout & colors\nAdded legend to branch rotation pages\nAdded text to home page relat"},"systemConnection":{"data":{"ServerId":"cb55739e-4afe-46a3-970f-1b49d8ee7564","ServerName":"microsoft"},"name":"SystemVssConnection","url":"https://microsoft.visualstudio.com/","authorization":{"parameters":{"AccessToken":********},"scheme":"OAuth"}}}}
[2016-06-16 22:09:02Z INFO JobRunner] Job ID 8205bcb3-34c1-4566-b5bb-ec6b4bca3277
[2016-06-16 22:09:02Z INFO ConfigurationStore] currentAssemblyLocation: C:\agent\bin\Agent.Worker.dll
[2016-06-16 22:09:02Z INFO ConfigurationStore] binPath: C:\agent\bin
[2016-06-16 22:09:02Z INFO ConfigurationStore] RootFolder: C:\agent
[2016-06-16 22:09:02Z INFO ConfigurationStore] ConfigFilePath: C:\agent\.agent
[2016-06-16 22:09:02Z INFO ConfigurationStore] CredFilePath: C:\agent\.credentials
[2016-06-16 22:09:02Z INFO ConfigurationStore] ServiceConfigFilePath: C:\agent\.service
[2016-06-16 22:09:02Z INFO JobRunner] Creating job server with URL: https://microsoft.visualstudio.com/
[2016-06-16 22:09:02Z INFO Worker] Listening for cancel message from the channel.
[2016-06-16 22:09:02Z INFO Worker] Waiting for the job to complete or for a cancel message from the channel.
[2016-06-16 22:09:04Z INFO JobServerQueue] Start process web console line queue.
[2016-06-16 22:09:04Z INFO JobServerQueue] Start process file upload queue.
[2016-06-16 22:09:04Z INFO JobServerQueue] Start process timeline update queue.
[2016-06-16 22:09:04Z INFO JobRunner] Starting the job execution context.
[2016-06-16 22:09:04Z INFO JobRunner] Creating task server with https://microsoft.visualstudio.com/
[2016-06-16 22:09:04Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2016-06-16 22:09:06Z INFO JobRunner] Getting job extensions.
[2016-06-16 22:09:06Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.IJobExtension'
[2016-06-16 22:09:06Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension, Agent.Worker
[2016-06-16 22:09:06Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension, Agent.Worker
[2016-06-16 22:09:06Z INFO JobRunner] Adding job prepare extensions.
[2016-06-16 22:09:06Z INFO JobRunner] Adding tasks.
[2016-06-16 22:09:06Z INFO JobRunner] Adding job finally extensions.
[2016-06-16 22:09:06Z INFO JobRunner] Downloading task definitions.
[2016-06-16 22:09:06Z INFO TaskManager] Ensuring task exists: ID 'e213ff0f-5d5c-4791-802d-52ea3e7be1f1', version '1.1.1', name 'PowerShell', directory 'd:\agent\_work\_tasks\PowerShell_e213ff0f-5d5c-4791-802d-52ea3e7be1f1\1.1.1'.
[2016-06-16 22:09:06Z INFO TaskManager] Task already downloaded.
[2016-06-16 22:09:06Z INFO TaskManager] Ensuring task exists: ID '71a9a2d3-a98a-4caa-96ab-affca411ecda', version '1.0.31', name 'VSBuild', directory 'd:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.0.31'.
[2016-06-16 22:09:06Z INFO TaskManager] Task already downloaded.
[2016-06-16 22:09:06Z INFO TaskManager] Ensuring task exists: ID 'ef087383-ee5e-42c7-9a53-ab56c98420f9', version '1.0.37', name 'VSTest', directory 'd:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\1.0.37'.
[2016-06-16 22:09:06Z INFO TaskManager] Task already downloaded.
[2016-06-16 22:09:06Z INFO StepsRunner] Processing step: DisplayName='Get Sources', AlwaysRun=False, ContinueOnError=False, Critical=True, Enabled=True, Finally=False
[2016-06-16 22:09:06Z INFO StepsRunner] Starting the step.
[2016-06-16 22:09:06Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.Build.ISourceProvider'
[2016-06-16 22:09:06Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.GitSourceProvider, Agent.Worker
[2016-06-16 22:09:06Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.GitHubSourceProvider, Agent.Worker
[2016-06-16 22:09:06Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.SvnSourceProvider, Agent.Worker
[2016-06-16 22:09:06Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsGitSourceProvider, Agent.Worker
[2016-06-16 22:09:06Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCSourceProvider, Agent.Worker
[2016-06-16 22:09:06Z INFO BuildDirectoryManager] Checking if artifacts directory exists: 'd:\agent\_work\1\a'
[2016-06-16 22:09:06Z INFO BuildDirectoryManager] Creating artifacts directory.
[2016-06-16 22:09:06Z INFO BuildDirectoryManager] Checking if test results directory exists: 'd:\agent\_work\1\TestResults'
[2016-06-16 22:09:06Z INFO BuildDirectoryManager] Creating test results directory.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Starting process with file name 'C:\agent\externals\git\cmd\git.exe', arguments 'version', and working directory 'd:\agent\_work'.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Process started with process id 1648, waiting for process exit.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0616171.
[2016-06-16 22:09:06Z INFO TfsGitSourceProvider] Repository url=https://microsoft.visualstudio.com/OSGCXE/_git/wsd.es.wit.services
[2016-06-16 22:09:06Z INFO TfsGitSourceProvider] targetPath=d:\agent\_work\1\s
[2016-06-16 22:09:06Z INFO TfsGitSourceProvider] sourceBranch=refs/heads/dev/deadlines
[2016-06-16 22:09:06Z INFO TfsGitSourceProvider] sourceVersion=e9d15780e32c00775a296de008cf809b015f119c
[2016-06-16 22:09:06Z INFO TfsGitSourceProvider] clean=True
[2016-06-16 22:09:06Z INFO TfsGitSourceProvider] checkoutSubmodules=True
[2016-06-16 22:09:06Z INFO TfsGitSourceProvider] exposeCred=False
[2016-06-16 22:09:06Z INFO ProcessInvoker] Starting process with file name 'C:\agent\externals\git\cmd\git.exe', arguments 'config --get remote.origin.url', and working directory 'd:\agent\_work\1\s'.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Process started with process id 1816, waiting for process exit.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0250575.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Starting process with file name 'C:\agent\externals\git\cmd\git.exe', arguments 'clean -fdx', and working directory 'd:\agent\_work\1\s'.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Process started with process id 2300, waiting for process exit.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0283076.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Starting process with file name 'C:\agent\externals\git\cmd\git.exe', arguments 'reset --hard HEAD', and working directory 'd:\agent\_work\1\s'.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Process started with process id 2888, waiting for process exit.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0481865.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Starting process with file name 'C:\agent\externals\git\cmd\git.exe', arguments 'config gc.auto 0', and working directory 'd:\agent\_work\1\s'.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Process started with process id 1364, waiting for process exit.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0245678.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Starting process with file name 'C:\agent\externals\git\cmd\git.exe', arguments '-c http.extraheader="AUTHORIZATION: bearer ********" fetch --tags --prune --progress origin', and working directory 'd:\agent\_work\1\s'.
[2016-06-16 22:09:06Z INFO ProcessInvoker] Process started with process id 792, waiting for process exit.
[2016-06-16 22:09:07Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2016-06-16 22:09:07Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.5555600.
[2016-06-16 22:09:07Z INFO ProcessInvoker] Starting process with file name 'C:\agent\externals\git\cmd\git.exe', arguments 'checkout --progress --force e9d15780e32c00775a296de008cf809b015f119c', and working directory 'd:\agent\_work\1\s'.
[2016-06-16 22:09:07Z INFO ProcessInvoker] Process started with process id 2908, waiting for process exit.
[2016-06-16 22:09:08Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:01.0322563.
[2016-06-16 22:09:08Z INFO ProcessInvoker] Starting process with file name 'C:\agent\externals\git\cmd\git.exe', arguments 'submodule init', and working directory 'd:\agent\_work\1\s'.
[2016-06-16 22:09:08Z INFO ProcessInvoker] Process started with process id 2320, waiting for process exit.
[2016-06-16 22:09:08Z INFO ProcessInvoker] Finished process with exit code 128, and elapsed time 00:00:00.0458751.
[2016-06-16 22:09:08Z ERR  StepsRunner] Caught exception from step: System.InvalidOperationException: Git submodule init failed with exit code: 128
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsGitSourceProvider.<GetSourceAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.<PrepareAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
[2016-06-16 22:09:08Z INFO StepsRunner] Step result: Failed
[2016-06-16 22:09:08Z INFO StepsRunner] Current state: job state = 'Failed', step failed = True, critical step failed = True
[2016-06-16 22:09:08Z INFO StepsRunner] Processing step: DisplayName='Powershell: mod-build/pre-build.ps1', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2016-06-16 22:09:08Z INFO StepsRunner] Skipping step.
[2016-06-16 22:09:08Z INFO StepsRunner] Processing step: DisplayName='Build project build/build.proj', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2016-06-16 22:09:08Z INFO StepsRunner] Skipping step.
[2016-06-16 22:09:08Z INFO StepsRunner] Processing step: DisplayName='Deploy project build/deploy.proj', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2016-06-16 22:09:08Z INFO StepsRunner] Skipping step.
[2016-06-16 22:09:08Z INFO StepsRunner] Processing step: DisplayName='Test Assemblies $(Build.StagingDirectory)\test\**\*smoke.test*.dll', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2016-06-16 22:09:08Z INFO StepsRunner] Skipping step.
[2016-06-16 22:09:08Z INFO StepsRunner] Processing step: DisplayName='Post Job Cleanup', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=True
[2016-06-16 22:09:08Z INFO StepsRunner] Starting the step.
[2016-06-16 22:09:08Z INFO StepsRunner] Step result: 
[2016-06-16 22:09:08Z INFO StepsRunner] Current state: job state = 'Failed', step failed = True, critical step failed = True
[2016-06-16 22:09:08Z INFO JobRunner] Job result: Failed
[2016-06-16 22:09:08Z INFO JobRunner] Completing the job execution context.
[2016-06-16 22:09:08Z INFO JobRunner] Shutting down the job server queue.
[2016-06-16 22:09:08Z INFO JobServerQueue] Fire signal to shutdown all queues.
[2016-06-16 22:09:08Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2016-06-16 22:09:09Z INFO JobServerQueue] All queue process task stopped.
[2016-06-16 22:09:09Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2016-06-16 22:09:09Z INFO JobServerQueue] Web console line queue drained.
[2016-06-16 22:09:10Z INFO JobServerQueue] Try to upload 3 log files or attachments, success rate: 3/3.
[2016-06-16 22:09:10Z INFO JobServerQueue] File upload queue drained.
[2016-06-16 22:09:10Z INFO JobServerQueue] Timeline update queue drained.
[2016-06-16 22:09:10Z INFO JobServerQueue] All queue process tasks have been stopped, and all queues are drained.
[2016-06-16 22:09:10Z INFO Worker] Job completed.
````

**Comment by bryanmacfarlane** [comment]
I've looked online and seen similar issues with just interactive git usage and other build systems like Team City etc...  It appears to be external to git (perhaps corruption?).  In those cases, they could never reproduce off that box.

Does this repro on another machine?  Is it possible one of the binaries or git is corrupt?

**Comment by neilhuiz** [comment]
Thanks, @bryanmacfarlane I was not able to repro on a couple other machines, so that sounds like a reasonable explanation.

**Comment by IAMtheIAM** [comment]
I'm still having this same issue when trying to install an npm package from a custom URL

```
    "materialize-css": "github:tomscholz/materialize#remove-roboto",

``` 

I think that's breaking the submodule
