### ISSUE TITLE
Agent connect error: Value cannot be null. Parameter name: version.

### ISSUE THREAD

**Issue by BluMist** [Microsoft/vsts-agent#309]
2.102.0 on OSX
visualstudio.com

[2016-06-17 19:36:07Z INFO JobDispatcher] Start renew job request.
[2016-06-17 19:36:07Z INFO JobDispatcher] TaskAgentJobTokenExpiredException received, job is no longer valid, stop renew job request.
[2016-06-17 19:36:07Z INFO JobDispatcher] Unable to renew job request for the first time, stop dispatching job to worker.
[2016-06-17 19:36:48Z ERR  MessageListener] Catch exception during get next message.
[2016-06-17 19:36:48Z ERR  MessageListener] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Value cannot be null.
Parameter name: version ---> System.ArgumentNullException: Value cannot be null.
Parameter name: version
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Extensions.<WithCancellation>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<GetNextMessageAsync>d__14.MoveNext()
[2016-06-17 19:36:48Z INFO MessageListener] Retriable exception: Value cannot be null.
Parameter name: version
[2016-06-17 19:36:48Z ERR  Terminal] WRITE ERROR: 2016-06-17 19:36:48Z: Agent connect error: Value cannot be null.
Parameter name: version. Retrying every 15 seconds until reconnected.

**Comment by BluMist** [comment]
ballpark ETA for the hotfix? all our build agents are blocked by this at the moment.

**Comment by TingluoHuang** [comment]
@BluMist 2-3 Hours.

**Comment by TingluoHuang** [comment]
@BluMist if you restart your agent the problem should goes away.

**Comment by BluMist** [comment]
Still hitting the same error after restarting machine. I am running in interactive mode.

**Comment by TingluoHuang** [comment]
@BluMist what's your visualstudio.com account name?

**Comment by BluMist** [comment]
It took a few tries, but I think we are back online

**Comment by BluMist** [comment]
Confirmed that the last couple builds succeeded, closing the issue now.

**Comment by bradyjoslin** [comment]
I'm still having the same "value cannot be null" problem as reported above.  A few builds made it through, but failure is the most common result.  Happening with multiple agents I use.

`Scanning for tool capabilities.
Connecting to the server.
2016-06-17 21:34:00Z: Listening for Jobs
2016-06-17 21:34:03Z: Running job: Build
2016-06-17 21:34:37Z: Running job: Build
2016-06-17 21:43:02Z: Job Build completed with result: Succeeded
2016-06-17 21:48:36Z: Running job: Build
2016-06-17 21:51:14Z: Job Build completed with result: Failed
2016-06-17 22:28:34Z: Agent connect error: Value cannot be null.
Parameter name: version. Retrying every 15 seconds until reconnected.`

**Comment by simmdan** [comment]
Same issue here.

**Comment by BluMist** [comment]
reopened since we are seeing intermittent errors as well...

**Comment by TingluoHuang** [comment]
@BluMist  @simmdan @bradyjoslin The deployment that contains the fix is still running. Can you guys share your account name, so i can provide some ETA?

**Comment by TingluoHuang** [comment]
Everything should be fixed right now.

**Comment by simmdan** [comment]
My account is msdata.

**Comment by simmdan** [comment]
My builds are working again.  thanks.

**Comment by TingluoHuang** [comment]
Close since the hotfix has already deployed.
