### ISSUE TITLE
Agent can't connect to TFS if the Basic Authentication Enabled

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vsts-agent#326]
## **Agent version and platform**
Version of your agent? Any windows agent version
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS?
<br>
On-Prem TFS 2015 U2/Dev 15

## **What's not working?** 
Agent can't be configured/reconfigure if basic authentication is enabled in IIS.
Even though I am using any authentication mechanism (Integrated), it just throws up error.
Disable basic auth and it works. pretty weird. it shouldn't impact other auth mechanism 
<br>
## **Agent and Worker's diag log**
```
[2016-06-23 05:00:52Z ERR  Agent] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation identifier is not valid
   at System.Net.Http.WinHttpAuthHelper.CheckResponseForAuthentication(WinHttpRequestState state, UInt32& proxyAuthScheme, UInt32& serverAuthScheme)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
```

**Comment by bryanmacfarlane** [comment]
Only with dev15 server right? It works with dev14 ( TFS 2015 )

**Comment by bryanmacfarlane** [comment]
It's a bug in Windows exposed by a bug in the identity team's on prem pat support where it leads to the server challenging with two basic headers with different realms.  I'll reply with all the bug numbers but not an agent issue

**Comment by bryanmacfarlane** [comment]
Here'e the dupe: https://github.com/dotnet/corefx/issues/9124#issuecomment-224055727

It's bug for identity 597431 - they added basic in config file in dev15 and you added to IIS settings
