### ISSUE TITLE
Cannot find type `Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces.IServiceManager`

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-agent#333]
## **Agent version and platform**
Version of your agent? 2.102.0
<br>
OS of the machine running the agent? Win10
## **VSTS type and version**
VisualStudio.com 
<br>
If VisualStudio.com, what is your account name? http://jessehouwing-dev.visualstudio.com
<br>
## **What's not working?** 
Please include error messages and screenshots
<br>
```
2016-06-24T18:12:45.8491603Z ##[section]Starting: Expand variables: '*'
2016-06-24T18:12:46.6812197Z Executing the powershell script: C:\TfsData\Build-dev-v3\_work\_tasks\VariableExpandTask_5f8f1adf-42bd-442d-8a0f-ae009a66b99e\0.5.868\vsts-variable-expand.ps1
2016-06-24T18:12:47.2263947Z ##[error]System.Management.Automation.RuntimeException: Unable to find type [Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces.IServiceManager].
2016-06-24T18:12:47.2263947Z    at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos)
2016-06-24T18:12:47.2344042Z    at System.Management.Automation.Interpreter.FuncCallInstruction`3.Run(InterpretedFrame frame)
2016-06-24T18:12:47.2839030Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-06-24T18:12:47.3229038Z ##[error]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
2016-06-24T18:12:47.3254047Z    at CallSite.Target(Closure , CallSite , Object , String )
2016-06-24T18:12:47.3479036Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2016-06-24T18:12:47.3609030Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2016-06-24T18:12:47.3829024Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-06-24T18:12:47.3964034Z ##[error]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
2016-06-24T18:12:47.4105288Z    at CallSite.Target(Closure , CallSite , Object , Object )
2016-06-24T18:12:47.4160284Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
2016-06-24T18:12:47.4190297Z    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
2016-06-24T18:12:47.4295299Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-06-24T18:12:47.4375275Z ##[error]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
2016-06-24T18:12:47.4480289Z    at CallSite.Target(Closure , CallSite , Object )
2016-06-24T18:12:47.4650290Z    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
2016-06-24T18:12:47.4840293Z    at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
2016-06-24T18:12:47.4905296Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2016-06-24T18:12:47.5645300Z 
2016-06-24T18:12:47.5655307Z 
2016-06-24T18:12:47.6110293Z ##[section]Finishing: Expand variables: '*'
```

The code in question is here:
https://github.com/jessehouwing/vsts-variable-tasks/blob/master/vsts-variable-expand/vsts-variable-expand.ps1#L54

The code use Reflection to call a generic method from Powershell. It's not calling into private or internal code. I was just too lazy to write a .NET wrapper method for it.

I wouldn't mind hiding this task on VSTS / TFS 2015u2+, as it is only really needed for TFS 2015 RTM and/or U1.

**Comment by bryanmacfarlane** [comment]
I believe you're reflecting into internal agent binaries (per namespace).  That can't work.

**Comment by jessehouwing** [comment]
That's fair. The task in question is not really valuable to anyone except TFS 2015 RTM and Update 1 users.

**Comment by jessehouwing** [comment]
The interface I'm requesting is not in a library that has "Internal" in its name. And it's public. If i turn on my OCD that makes it a public interface, but I'd fully understand of that was never the intention.

```
public interface IServiceManager : IServiceProvider

Name: Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces.IServiceManager 
Assembly: Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces, Version=15.0.0.0 
```

**Comment by bryanmacfarlane** [comment]
You're reflecting into the agent binaries itself : DistributedTask.Agent

**Comment by jessehouwing** [comment]
But but but... It's not DistributedTask.Agent.Internal or DistributedTask.Agent.Private. It's Interfaces, those things that are meant to be used when extending things ;).

Ok ok... I'll figure out another way.
