### ISSUE TITLE
Windows: Could not load type 'Microsoft.TeamFoundation.DistributedTask.WebApi.AgentJobRequestMessage

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vsts-agent#341]
## **Agent version and platform**
Version of your agent? build from source
<br>
Windows
<br>

This is the error when we queue job to new agent
[2016-06-29 04:30:32Z INFO Program] Version: 2.102.1
[2016-06-29 04:30:32Z INFO Program] Commit: e7b76d31cb2035a7319639bda2243b0c12b12ae5
[2016-06-29 04:30:32Z INFO Program] Culture: en-US
[2016-06-29 04:30:32Z INFO Program] UI Culture: en-US
[2016-06-29 04:30:33Z ERR  Program] System.TypeLoadException: Could not load type 'Microsoft.TeamFoundation.DistributedTask.WebApi.AgentJobRequestMessage' from assembly 'Microsoft.TeamFoundation.DistributedTask.WebApi, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.VisualStudio.Services.Agent.Worker.Worker.<RunAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.VisualStudio.Services.Agent.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at Microsoft.VisualStudio.Services.Agent.Worker.Program.<MainAsync>d__1.MoveNext()

Seems like this commit is breaking the agent:
https://github.com/Microsoft/vsts-agent/commit/63c87779a89c907d5da8c4ce2cacc583418e192e

**Comment by nigurr** [comment]
Internal bug tracker in mseng: 613962

**Comment by bryanmacfarlane** [comment]
@nigurr - have you tried running the agent produced by the CI system is this repro for your local build?
@TingluoHuang - did we miss updating [the dev docs](https://github.com/Microsoft/vsts-agent/blob/master/docs/dev/netcore.md)?  I believe devs need to install new tools/clr?

**Comment by TingluoHuang** [comment]
@bryanmacfarlane this change doesn't require new CLI tooling, we just change to consume RTM corefx library. I will dig in.

**Comment by TingluoHuang** [comment]
@nigurr how did you build your agent? dev.cmd layout? can you ran `dotnet --version` and let me know the output?

**Comment by nigurr** [comment]
We are using the CI system drop builds for RB. So we are not building anything in local

**Comment by TingluoHuang** [comment]
@nigurr VSTS.Agent.CI-Win on MSENG? what is RB?

**Comment by nigurr** [comment]
Rolling Builds. 24x7 Tests run on that infra. Yes. I am using Release definition drop to RB
Release def: DTA RB - VSTS Agent - Win

**Comment by nigurr** [comment]
@TingluoHuang yesterday while I was investigating, I found that `Microsoft.TeamFoundation.DistributedTask.WebApi` dll shipped with agent doesn't contain `Microsoft.TeamFoundation.DistributedTask.WebApi.AgentJobRequestMessage`. May be you are pulling the DLL from myget package which requires update?

**Comment by nigurr** [comment]
![image](https://cloud.githubusercontent.com/assets/15208679/16476236/f2e3aac4-3ea2-11e6-81ea-5304bacf7889.png)

**Comment by nigurr** [comment]
The DLL which is getting shipped with "Agent" [DistributedTask.WebApi], doesn't contain `AgentJobQueueMessage`

**Comment by TingluoHuang** [comment]
Are you download artifact zip from the build directly? I just tried zip produced by https://mseng.visualstudio.com/VSOnline/Build/_build/definitions?buildId=3094881&_a=summary
everything works fine.

**Comment by nigurr** [comment]
Did you queue the build definition from latest master tfs?

**Comment by TingluoHuang** [comment]
I believe that is latest build.

**Comment by nigurr** [comment]
Closing this issue as it's not happening with new agent
