### ISSUE TITLE
Discovering clock skew ( leads to ssOAuthTokenRequestException ) should be easier and earlier

### ISSUE THREAD

**Issue by tebeco** [Microsoft/vsts-agent#348]
## **Agent version and platform**
2.102.1
<br>
Windows 2012 R2
<br>
## **VSTS type and version**
VisualStudio.com
<br>
If VisualStudio.com, what is your account name? http://tebeco.visualstudio.com
<br>
## **What's not working?** 

Agent cannot connect from my server whereas I just did same step on a laptop and it's working
FYI : I'm using PAT to connect and I read OAuth Issue (not sure it's normal or linked)

[ERR  MessageListener] System.AggregateException: One or more errors occurred. (The client is not valid) ---> Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenRequestException: The client is not valid

<br>
## **Agent and Worker's diag log**

[2016-06-29 17:37:01Z INFO AgentCapabilitiesProvider] Adding 'Agent.Name': 'VsoAgent'
[2016-06-29 17:37:01Z INFO AgentCapabilitiesProvider] Adding 'Agent.OS': 'Windows_NT'
[2016-06-29 17:37:01Z INFO AgentCapabilitiesProvider] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value name 'CurrentMajorVersionNumber' is null.
[2016-06-29 17:37:01Z INFO AgentCapabilitiesProvider] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value name 'CurrentMinorVersionNumber' is null.
[2016-06-29 17:37:01Z INFO AgentCapabilitiesProvider] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value name 'CurrentVersion': '6.3'
[2016-06-29 17:37:01Z INFO AgentCapabilitiesProvider] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion', value name 'CurrentBuildNumber': '9600'
[2016-06-29 17:37:01Z INFO AgentCapabilitiesProvider] Adding 'Agent.OSVersion': '6.3.9600'
[2016-06-29 17:37:01Z INFO AgentCapabilitiesProvider] Adding 'Cmd': 'C:\Windows\system32\cmd.exe'
[2016-06-29 17:37:01Z INFO AgentCapabilitiesProvider] Adding 'Agent.Version': '2.102.1'
[2016-06-29 17:37:01Z INFO AgentCapabilitiesProvider] Adding 'Agent.ComputerName': 'VSOBUILDSERVER'
[2016-06-29 17:37:01Z INFO ConfigurationStore] HasCredentials()
[2016-06-29 17:37:01Z INFO ConfigurationStore] stored True
[2016-06-29 17:37:01Z INFO CredentialManager] GetCredentialProvider
[2016-06-29 17:37:01Z INFO CredentialManager] Creating type OAuth
[2016-06-29 17:37:01Z INFO CredentialManager] Creating credential type: OAuth
[2016-06-29 17:37:01Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\VsoAgents\MyProject\.credentials_rsaparams
[2016-06-29 17:37:01Z INFO Terminal] WRITE LINE: Connecting to the server.
[2016-06-29 17:37:01Z INFO MessageListener] Attempt to create session.
[2016-06-29 17:37:01Z INFO MessageListener] Connecting to the Agent Server...
[2016-06-29 17:37:01Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\VsoAgents\MyProject\.credentials_rsaparams
[2016-06-29 17:37:01Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\VsoAgents\MyProject\.credentials_rsaparams
[2016-06-29 17:37:02Z ERR  MessageListener] Catch exception during create session.
[2016-06-29 17:37:02Z ERR  MessageListener] System.AggregateException: One or more errors occurred. (The client is not valid) ---> Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenRequestException: The client is not valid
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenProvider.<OnGetTokenAsync>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenProvider.GetTokenOperation.<>c__DisplayClass17_0.<GetTokenAsync>b__1(Task`1 x)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.IssuedTokenProvider.GetTokenOperation.<GetTokenAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.IssuedTokenProvider.<GetTokenAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Client.VssServerDataProvider.<ConnectAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<CreateSessionAsync>d__12.MoveNext()
---> (Inner Exception #0) Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenRequestException: The client is not valid
   at Microsoft.VisualStudio.Services.OAuth.VssOAuthTokenProvider.<OnGetTokenAsync>d__14.MoveNext()<---

[2016-06-29 17:37:02Z INFO MessageListener] Retriable exception: One or more errors occurred. (The client is not valid)
[2016-06-29 17:37:02Z ERR  Terminal] WRITE ERROR: 2016-06-29 17:37:02Z: Agent connect error: One or more errors occurred. (The client is not valid). Retrying every 30 seconds until reconnected.
[2016-06-29 17:37:02Z INFO MessageListener] Sleeping for 30 seconds before retrying.

[2016-06-29 17:37:32Z INFO MessageListener] Attempt to create session.
[2016-06-29 17:37:32Z INFO MessageListener] Connecting to the Agent Server...
[2016-06-29 17:37:33Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\VsoAgents\MyProject\.credentials_rsaparams
[2016-06-29 17:37:34Z ERR  MessageListener] Catch exception during create session.
....

Was working fine until I decided :
* Update 3 for Vs2015 (in order to build .Net Core 1.0 Rtm
* Update PowerShell to version 5 (powershell Zip for build)
* Update SDK Azure for vs2015 (using Web PI)
* Install Azure CLI (using Web PI)
* Install Azure PowerShell (using Web PI)
* Install Azure Service Fabrik (using Web PI)

(Works on a Laptop with Powershell 5.1 & Vs Update 3 + Azure CLI & powershell)

I've uninstall PowerShell 5 to 4 did nothing ;)
I could not find a way to unstall from Wen PI, the buttons are disable once installed :(

**Comment by TingluoHuang** [comment]
@tebeco Can you send us the content of .credentials file under your agent folder? it's a hidden file.

**Comment by tebeco** [comment]
@TingluoHuang 
send it how  ? here ? a credential file ? no security issue with that file ?

**Comment by TingluoHuang** [comment]
@tebeco you can paste the content here, that credential file just contains a lookup guid, so we can query backend DB. there is no security issue about it.

**Comment by tebeco** [comment]
{
  "scheme": "OAuth",
  "data": {
    "clientId": "a404699b-ca69-4cfd-8e12-d2c0c19dc8dc",
    "authorizationUrl": "https://tebeco.vssps.visualstudio.com/_apis/oauth2/token"
  }
}

**Comment by TingluoHuang** [comment]
@tebeco cool, thanks, are you still hitting the exception on that agent?

**Comment by tebeco** [comment]
yep

**Comment by TingluoHuang** [comment]
@tebeco please leave it in that state, Can you .zip up the entire _diag folder, and paste here? All secret should already be masked out.

**Comment by tebeco** [comment]
agent is install *NOT* as a service so i can clean the _diag folder re reun once and send only the last try right ?

**Comment by TingluoHuang** [comment]
@tebeco please include all logs since it start hitting this exception, i also want to figure out how you run into this situation.

**Comment by tebeco** [comment]
[_diag.zip](https://github.com/Microsoft/vsts-agent/files/340057/_diag.zip)

**Comment by TingluoHuang** [comment]
So the agent has never successfully connected and able to run any build, is that correct?

**Comment by tebeco** [comment]
Not this one no,

I'm running the Agent "on demand" inside a Consol Host in Admin (not as a service)
It was working until i've installed all the updates.

Then I got the error, I thought about a cache issue or whatever other issue ... So i've downloading the latest bits of vsts Agent, deleted the previous one and installed this one
To discover that it changed nothing ...

I've installed the same version on my laptop with the same value (just changed the agent Name) and it works.

**Comment by TingluoHuang** [comment]
@tebeco do you still have the _diag folder of the one you deleted?

**Comment by tebeco** [comment]
nop ...
SHAME, SHAME, SHAME !!!

(I've lookup for backup to restore the server as of yesterday but it seems the feature is not installed so i can't)
It's a mess i know

**Comment by TingluoHuang** [comment]
that's fine, i will try to figure this out,

**Comment by tebeco** [comment]
If there's anything I can try on the server or the Laptop to make some diagnotic ...

**Comment by patrickcarnahan** [comment]
Not scientific or anything, but it would appear your local clock is skewed quite a bit based on the timestamps we recorded for the errors and the timestamps from your log (on the order of maybe 10 minutes). We allow for a 5 minute clock skew on client tokens used for OAuth exchanges, and you appear to be out of that range. Could you verify that your computer clock is accurately set?

Patrick

**Comment by tebeco** [comment]
NICE CATCH !!!! You're amazing !!! It's connecting finally

Do you think a feature inside Vsts Agent to write a huge red error if a check detect that ?

**Comment by tebeco** [comment]
This is weird now i have a message telling me that there's no agent with the capabilities "azureps" and 'vstest'

I've juste installed Azure powershell using WebPI :(
And there's Visual studio 2013 & 2015 installed

I've disabled the Test step ... so it only require 'azureps' but I don't get why it's not detected

**Comment by TingluoHuang** [comment]
you can check agent diag log to see how it detect all capabilities.

**Comment by patrickcarnahan** [comment]
I have filed a bug against the server product to provide a better error message and data in the case that it appears clock skew is at play. Once that is in, the agent can react to the data and provide a more definitive diagnostic message to help diagnose the issue.

Thanks for reporting the problem, glad it was an easy fix.

Patrick

**Comment by bryanmacfarlane** [comment]
I've updated the title to cover the work so we can do a connect check earlier when you interactively configure and ensure a good error gets to the log

**Comment by tebeco** [comment]
For the capabilities i'll check tomorrow (from France)

I think it's linked to azure Rm



THANKS A LOT

**Comment by ericsciple** [comment]
This is the code used to detect the azureps capability: https://github.com/Microsoft/vsts-agent/blob/master/src/Misc/layoutbin/powershell/Add-AzurePowerShellCapabilities.ps1

If you find fault with it, it would be good to troubleshoot on a separate issue. Output from the script is written into the agent diag log.

**Comment by tebeco** [comment]
@ericsciple 
I'm creationg a new issue separate from this one, i think there's an error message inside the _diag when agent detect Azure Capabilities.
Wich block Azure Publish

**Comment by tebeco** [comment]
@ericsciple here is the azure caps issue : https://github.com/Microsoft/vsts-agent/issues/353

**Comment by TingluoHuang** [comment]
#356 will improve this.
