### ISSUE TITLE
Unable to configure OS X client.

### ISSUE THREAD

**Issue by kristoferreierson** [Microsoft/vsts-agent#373]
## **Agent version and platform**
Version of your agent? 2.102.0/2.100.1...
<br>
OS of the machine running the agent? OSX/Windows/Linux...
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS?
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://msazurevisualstudio.com
<br>
## **What's not working?** 
Please include error messages and screenshots
the OS X client can't find System.Security.Cryptography.Native when configuring itself.

<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

[2016-07-08 18:08:56Z INFO AgentProcess] Agent is built for OSX - osx.10.11-x64.
[2016-07-08 18:08:56Z INFO AgentProcess] RuntimeInformation: Darwin 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64.
[2016-07-08 18:08:56Z INFO AgentProcess] Version: 2.102.1
[2016-07-08 18:08:56Z INFO AgentProcess] Commit: b096b439b4d2720d53ad6429d9600489ef08467a
[2016-07-08 18:08:56Z INFO AgentProcess] Culture: en-US
[2016-07-08 18:08:56Z INFO AgentProcess] UI Culture: en-US
[2016-07-08 18:08:56Z INFO CommandLineParser] Parse
[2016-07-08 18:08:56Z INFO CommandLineParser] Parsing 1 args
[2016-07-08 18:08:56Z INFO CommandLineParser] parsing argument
[2016-07-08 18:08:56Z INFO CommandLineParser] HasArgs: False
[2016-07-08 18:08:56Z INFO CommandLineParser] Adding Command: configure
[2016-07-08 18:08:56Z INFO AgentProcess] Arguments parsed
[2016-07-08 18:08:56Z INFO Agent] ExecuteCommand
[2016-07-08 18:08:56Z INFO ConfigurationStore] currentAssemblyLocation: /Users/buildmam/msazurebuildagent/bin/Agent.Listener.dll
[2016-07-08 18:08:56Z INFO ConfigurationStore] binPath: /Users/buildmam/msazurebuildagent/bin
[2016-07-08 18:08:56Z INFO ConfigurationStore] RootFolder: /Users/buildmam/msazurebuildagent
[2016-07-08 18:08:56Z INFO ConfigurationStore] ConfigFilePath: /Users/buildmam/msazurebuildagent/.agent
[2016-07-08 18:08:56Z INFO ConfigurationStore] CredFilePath: /Users/buildmam/msazurebuildagent/.credentials
[2016-07-08 18:08:56Z INFO ConfigurationStore] ServiceConfigFilePath: /Users/buildmam/msazurebuildagent/.service
[2016-07-08 18:08:56Z INFO CommandSettings] Flag 'help': 'False'
[2016-07-08 18:08:56Z INFO CommandSettings] Flag 'version': 'False'
[2016-07-08 18:08:56Z INFO CommandSettings] Flag 'commit': 'False'
[2016-07-08 18:08:56Z INFO CommandSettings] Command 'remove': 'False'
[2016-07-08 18:08:56Z INFO CommandSettings] Command 'run': 'False'
[2016-07-08 18:08:56Z INFO CommandSettings] Command 'configure': 'True'
[2016-07-08 18:08:56Z INFO ConfigurationManager] ConfigureAsync
[2016-07-08 18:08:56Z INFO ConfigurationStore] IsConfigured()
[2016-07-08 18:08:56Z INFO ConfigurationStore] IsConfigured: False
[2016-07-08 18:08:56Z INFO ConfigurationManager] Is configured: False
[2016-07-08 18:08:57Z INFO Terminal] WRITE LINE: 
[2016-07-08 18:08:57Z INFO Terminal] WRITE LINE: >> End User License Agreements:
[2016-07-08 18:08:57Z INFO Terminal] WRITE LINE: 
[2016-07-08 18:08:57Z INFO Terminal] WRITE LINE: Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /Users/buildmam/msazurebuildagent/externals/tee/license.html
[2016-07-08 18:08:57Z INFO Terminal] WRITE LINE: 
[2016-07-08 18:08:57Z INFO CommandSettings] Flag 'acceptteeeula': 'False'
[2016-07-08 18:08:57Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-08 18:08:57Z INFO PromptManager] ReadValue
[2016-07-08 18:08:57Z INFO Terminal] WRITE: Enter accept the Team Explorer Everywhere license agreement now? (Y/N) (press enter for N) > 
[2016-07-08 18:08:57Z INFO Terminal] READ LINE
[2016-07-08 18:09:04Z INFO Terminal] Read value: 'Y'
[2016-07-08 18:09:04Z INFO Terminal] WRITE LINE: 
[2016-07-08 18:09:04Z INFO Terminal] WRITE LINE: >> Connect:
[2016-07-08 18:09:04Z INFO Terminal] WRITE LINE: 
[2016-07-08 18:09:04Z INFO CommandSettings] Arg 'url': ''
[2016-07-08 18:09:04Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-08 18:09:04Z INFO PromptManager] ReadValue
[2016-07-08 18:09:04Z INFO Terminal] WRITE: Enter server URL > 
[2016-07-08 18:09:04Z INFO Terminal] READ LINE
[2016-07-08 18:09:07Z INFO Terminal] Read value: 'https://msazure.visualstudio.com/Intune'
[2016-07-08 18:09:07Z INFO ConfigurationManager] GetCredentialProvider
[2016-07-08 18:09:07Z INFO CommandSettings] Arg 'auth': ''
[2016-07-08 18:09:07Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-08 18:09:07Z INFO PromptManager] ReadValue
[2016-07-08 18:09:07Z INFO Terminal] WRITE: Enter authentication type (press enter for PAT) > 
[2016-07-08 18:09:07Z INFO Terminal] READ LINE
[2016-07-08 18:09:09Z INFO Terminal] Read value: ''
[2016-07-08 18:09:09Z INFO PromptManager] Falling back to the default: 'PAT'
[2016-07-08 18:09:09Z INFO ConfigurationManager] Creating credential for auth: PAT
[2016-07-08 18:09:09Z INFO CredentialManager] GetCredentialProvider
[2016-07-08 18:09:09Z INFO CredentialManager] Creating type PAT
[2016-07-08 18:09:09Z INFO CredentialManager] Creating credential type: PAT
[2016-07-08 18:09:09Z INFO PersonalAccessToken] EnsureCredential
[2016-07-08 18:09:09Z INFO CommandSettings] Arg 'token': ''
[2016-07-08 18:09:09Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-08 18:09:09Z INFO PromptManager] ReadValue
[2016-07-08 18:09:09Z INFO Terminal] WRITE: Enter personal access token > 
[2016-07-08 18:09:09Z INFO Terminal] READ SECRET
[2016-07-08 18:09:17Z INFO Terminal] Read value: '********'
[2016-07-08 18:09:17Z INFO PersonalAccessToken] GetVssCredentials
[2016-07-08 18:09:17Z INFO PersonalAccessToken] token retrieved: 52 chars
[2016-07-08 18:09:17Z INFO ConfigurationManager] cred retrieved
[2016-07-08 18:09:17Z INFO Terminal] WRITE LINE: Connecting to server ...
[2016-07-08 18:09:17Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-08 18:09:17Z ERR  Terminal] WRITE ERROR (exception):
[2016-07-08 18:09:17Z ERR  Terminal] System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.CryptoInitializer.Initialize()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler..ctor(VssCredentials credentials, VssHttpRequestSettings settings)
   at Microsoft.VisualStudio.Services.Client.VssConnection..ctor(Uri baseUrl, VssCredentials credentials, VssHttpRequestSettings settings)
   at Microsoft.VisualStudio.Services.Agent.Util.ApiUtil.CreateConnection(Uri serverUri, VssCredentials credentials)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<TestConnectAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__8.MoveNext()
[2016-07-08 18:09:17Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2016-07-08 18:09:17Z INFO CommandSettings] Arg 'url': ''
[2016-07-08 18:09:17Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-08 18:09:17Z INFO PromptManager] ReadValue
[2016-07-08 18:09:17Z INFO Terminal] WRITE: Enter server URL > 
[2016-07-08 18:09:17Z INFO Terminal] READ LINE
[2016-07-08 19:03:21Z INFO Terminal] Read value: 'https://msazure.visualstudio.com/Intune'
[2016-07-08 19:03:21Z INFO PromptManager] Invalid value.
[2016-07-08 19:03:21Z INFO Terminal] WRITE LINE: Enter a valid value for server URL.
[2016-07-08 19:03:21Z INFO Terminal] WRITE: Enter server URL > 
[2016-07-08 19:03:21Z INFO Terminal] READ LINE
[2016-07-08 19:03:23Z INFO Terminal] Read value: 'https://msazure.visualstudio.com/Intune'
[2016-07-08 19:03:23Z INFO ConfigurationManager] GetCredentialProvider
[2016-07-08 19:03:23Z INFO CommandSettings] Arg 'auth': ''
[2016-07-08 19:03:23Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-08 19:03:23Z INFO PromptManager] ReadValue
[2016-07-08 19:03:23Z INFO Terminal] WRITE: Enter authentication type (press enter for PAT) > 
[2016-07-08 19:03:23Z INFO Terminal] READ LINE
[2016-07-08 19:03:24Z INFO Terminal] Read value: 'https://msazure.visualstudio.com/Intune'
[2016-07-08 19:03:24Z INFO PromptManager] Invalid value.
[2016-07-08 19:03:24Z INFO Terminal] WRITE LINE: Enter a valid value for authentication type.
[2016-07-08 19:03:24Z INFO Terminal] WRITE: Enter authentication type (press enter for PAT) > 
[2016-07-08 19:03:24Z INFO Terminal] READ LINE
[2016-07-08 19:03:27Z INFO Terminal] Read value: ''
[2016-07-08 19:03:27Z INFO PromptManager] Falling back to the default: 'PAT'
[2016-07-08 19:03:27Z INFO ConfigurationManager] Creating credential for auth: PAT
[2016-07-08 19:03:27Z INFO CredentialManager] GetCredentialProvider
[2016-07-08 19:03:27Z INFO CredentialManager] Creating type PAT
[2016-07-08 19:03:27Z INFO CredentialManager] Creating credential type: PAT
[2016-07-08 19:03:27Z INFO PersonalAccessToken] EnsureCredential
[2016-07-08 19:03:27Z INFO CommandSettings] Arg 'token': ''
[2016-07-08 19:03:27Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-08 19:03:27Z INFO PromptManager] ReadValue
[2016-07-08 19:03:27Z INFO Terminal] WRITE: Enter personal access token > 
[2016-07-08 19:03:27Z INFO Terminal] READ SECRET
[2016-07-08 19:03:34Z INFO Terminal] Read value: '********'
[2016-07-08 19:03:34Z INFO PersonalAccessToken] GetVssCredentials
[2016-07-08 19:03:34Z INFO PersonalAccessToken] token retrieved: 52 chars
[2016-07-08 19:03:34Z INFO ConfigurationManager] cred retrieved
[2016-07-08 19:03:34Z INFO Terminal] WRITE LINE: Connecting to server ...
[2016-07-08 19:03:34Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-08 19:03:34Z ERR  Terminal] WRITE ERROR (exception):
[2016-07-08 19:03:34Z ERR  Terminal] System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.CryptoInitializer.Initialize()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler..ctor(VssCredentials credentials, VssHttpRequestSettings settings)
   at Microsoft.VisualStudio.Services.Client.VssConnection..ctor(Uri baseUrl, VssCredentials credentials, VssHttpRequestSettings settings)
   at Microsoft.VisualStudio.Services.Agent.Util.ApiUtil.CreateConnection(Uri serverUri, VssCredentials credentials)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<TestConnectAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__8.MoveNext()
[2016-07-08 19:03:34Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2016-07-08 19:03:34Z INFO CommandSettings] Arg 'url': ''
[2016-07-08 19:03:34Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-08 19:03:34Z INFO PromptManager] ReadValue
[2016-07-08 19:03:34Z INFO Terminal] WRITE: Enter server URL > 
[2016-07-08 19:03:34Z INFO Terminal] READ LINE
[2016-07-08 19:03:48Z INFO Terminal] WRITE LINE: Exiting...

**Comment by bryanmacfarlane** [comment]
Dupe if #110

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/latebreaking.md

**Comment by bryanmacfarlane** [comment]
Ensure you run all.  I had one customer who had to run it multiple times to take for some reason:
```
brew update
brew install openssl
brew link --force openssl 
```
