### ISSUE TITLE
VSTS - Release Agent tasks failing

### ISSUE THREAD

**Issue by Dan-Co** [Microsoft/vsts-agent#388]
## **Agent version and platform**
Version of your agent? 
2.103.0
<br>
OS of the machine running the agent? RHEL 7.2
<br>
## **VSTS type and version**
On-Prem TFS 2015 update 2
<br>
## **What's not working?** 
Build tasks seem to work, but Release tasks always fail with:
**Errors (2)
Downloading artifacts failed: System.ArgumentNullException: Value cannot be null.
Value cannot be null.**

<br>
## **Agent and Worker's diag log**
**WorkerLog:**
[2016-07-12 15:21:46Z INFO Program] Version: 2.103.0
[2016-07-12 15:21:46Z INFO Program] Commit: 130a17ed8ee3f2f85efcf1152d89c0e6d0bcb7ec
[2016-07-12 15:21:46Z INFO Program] Culture: en-GB
[2016-07-12 15:21:46Z INFO Program] UI Culture: en-GB
[2016-07-12 15:21:46Z INFO Worker] Waiting to receive the job message from the channel.
[2016-07-12 15:21:46Z INFO Worker] Message received.
...
...
..
[2016-07-12 15:21:48Z INFO JobRunner] Starting the job execution context.
[2016-07-12 15:21:48Z INFO JobRunner] Creating task server with http://dev-tfs:8080/tfs/DefaultCollection/
[2016-07-12 15:21:49Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2016-07-12 15:21:49Z INFO JobRunner] Getting job extensions.
[2016-07-12 15:21:49Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Wo                                                 rker.IJobExtension'
[2016-07-12 15:21:49Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.Build                                                 JobExtension, Agent.Worker
[2016-07-12 15:21:49Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Release.Rel                                                 easeJobExtension, Agent.Worker
[2016-07-12 15:21:49Z INFO JobRunner] Adding job prepare extensions.
[2016-07-12 15:21:49Z INFO JobRunner] Adding tasks.
[2016-07-12 15:21:49Z INFO JobRunner] Adding job finally extensions.
[2016-07-12 15:21:49Z INFO JobRunner] Downloading task definitions.
[2016-07-12 15:21:49Z INFO StepsRunner] Processing step: DisplayName='Download Artifacts', AlwaysRun=False, ContinueOnEr                                                 ror=False, Critical=True, Enabled=True, Finally=False
[2016-07-12 15:21:49Z INFO StepsRunner] Starting the step.
[2016-07-12 15:21:49Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2016-07-12 15:21:49Z ERR  StepsRunner] Caught exception from step: System.ArgumentNullException: Value cannot be null.
Parameter name: paths
   at System.IO.Path.Combine(String[] paths)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseDirectoryManager.PrepareArtifactsDirectory(String work                                                 ingDirectory, String collectionId, String projectId, String releaseDefinitionId)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.InitializeAgent(IExecutionContext executi                                                 onContext, Boolean& skipArtifactsDownload, Guid& teamProjectId, String& artifactsWorkingFolder, Int32& releaseId)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<PrepareAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
[2016-07-12 15:21:49Z INFO StepsRunner] Step result: Failed
[2016-07-12 15:21:49Z INFO StepsRunner] Current state: job state = 'Failed', step failed = True, critical step failed =                                                  True
[2016-07-12 15:21:49Z INFO JobRunner] Job result: Failed

**Agent Log**
[2016-07-12 15:21:42Z INFO Terminal] WRITE LINE: 2016-07-12 15:21:42Z: Listening for Jobs
[2016-07-12 15:21:46Z INFO JobDispatcher] Job request a30ca81e-f226-4970-b5de-faf171f3a2e6 received.
[2016-07-12 15:21:46Z INFO Terminal] WRITE LINE: 2016-07-12 15:21:46Z: Running job: Release
[2016-07-12 15:21:46Z INFO JobNotification] Entering JobStarted Notification
[2016-07-12 15:21:46Z INFO JobDispatcher] Start renew job request.
[2016-07-12 15:21:46Z INFO JobDispatcher] Successfully renew job request, job is valid till 12/07/2016 15:27:21
[2016-07-12 15:21:46Z INFO ProcessInvoker] Starting process with file name '**SENSITIVE**/myagent/bin/Agent.Worker', arguments 'spawnclient 141 145', and working directory '/home/dancodevops/myagent/bin'.
[2016-07-12 15:21:46Z INFO ProcessInvoker] Process started with process id 21449, waiting for process exit.
[2016-07-12 15:21:46Z INFO JobDispatcher] Send job request message to worker.
[2016-07-12 15:21:50Z INFO ProcessInvoker] Finished process with exit code 102, and elapsed time 00:00:04.0712411.
[2016-07-12 15:21:50Z INFO JobDispatcher] Worker finished. Code: 102
[2016-07-12 15:21:50Z INFO JobDispatcher] finish job request with result: Failed
[2016-07-12 15:21:50Z INFO Terminal] WRITE LINE: 2016-07-12 15:21:50Z: Job Release completed with result: Failed
[2016-07-12 15:21:50Z INFO JobNotification] Entering JobCompleted Notification
[2016-07-12 15:21:50Z INFO JobDispatcher] Stop renew job request.
[2016-07-12 15:21:50Z INFO JobDispatcher] job renew has been canceled, stop renew job request.
[2016-07-12 15:22:46Z INFO Terminal] WRITE LINE: Exiting...
[2016-07-12 15:22:46Z INFO MessageListener] Get next message has been cancelled.
[2016-07-12 15:22:46Z INFO JobDispatcher] Shutting down JobDispather. Make sure all WorkerDispatcher has finished.
[2016-07-12 15:22:46Z INFO JobDispatcher] Ensure WorkerDispather for job a30ca81e-f226-4970-b5de-faf171f3a2e6 run to finish.
[2016-07-12 15:22:46Z INFO JobDispatcher] Job request a30ca81e-f226-4970-b5de-faf171f3a2e6 processed succeed.
[2016-07-12 15:22:46Z INFO AgentProcess] Agent execution been cancelled.

**Comment by TingluoHuang** [comment]
@Dan-Co can you paste the full worker log? the one you paste now has some '...'

**Comment by TingluoHuang** [comment]
@Dan-Co Can you paste the full worker log? the current one has some '...', Can you share a failed release log as well?
Thanks

**Comment by ericsciple** [comment]
@ankitgo - null ref is coming from path.combine in PrepareArtifactsDirectory

**Comment by ankitgo** [comment]
Now that is a bit strange. Only things that can be null here are, collection id, projectid and release defintion id. All these are variables and are set by service. 
Could be that the variables have changed from u2- latest but thats highly unlikely.
Investigating further, but as a first step i ll be adding null checks to this public method so that i get to know the culprit variable.

@Dan-Co  Do you see this with all the release definitions or only specific release definitions?

**Comment by ankitgo** [comment]
Got the issue. Fixing it.
Here is the PR to track: https://github.com/Microsoft/vsts-agent/pull/400

**Comment by Dan-Co** [comment]
Sorry guys just got back to this. Do you still need the full logs? If not happy we found the bug. Yes it was every single release task, but on none of the equivalent build tasks.

**Comment by bryanmacfarlane** [comment]
Closing since the PR is merged.  Should be in 2.104.1
