### ISSUE TITLE
Security: Do we need to keep .credentials_rsaparams file?

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#402]
## **Agent version and platform**
2.103.0
<br>
Linux Centos 7
<br>
## **VSTS type and version**
VisualStudio.com

## **What's not working?** 

I run the agent in two steps:

**Step 1: configure**

like this

```
exec ./bin/Agent.Listener \
        configure \
        --unattended \
        --nostart \
        --agent ${VSTS_AGENT_NAME} \
        --auth ${VSTS_AUTH_TYPE} \
        --token ${VSTS_AUTH_TOKEN} \
        --pool ${VSTS_POOL} \
        --url ${VSTS_URL} \
        --acceptteeeula Y
```

**Step 2: run**

like this

```
exec ./bin/Agent.Listener --unattended
```

After the agent successfully connects and says `Listening for Jobs`, I remove all files with credential: `.credentials` and `.credentials_rsaparams`.

However, when I queue a build, I get errors in the agent and the build does not work:

```
2016-07-15 18:40:40Z: Agent connect error: RSA key file /home/vsoagent/.credentials_rsaparams was not found. Retrying every 15 seconds until reconnected.
An error occurred: Unexpected character encountered while parsing number: y. Path '', line 1, position 1.
```

This is different from the behaviour in the `preview 2.101.1` where things were kept in `.Credentials` file -- I could remove the file and everything would keep running just fine.

**Why I delete credential files**

Using `chmod 600` on files with sensitive information does not provide any real security if the file is owned by the same user which runs the build jobs. The reason is I can easily create a build task with shell command `cat .credentials`. Because the build task executes under same user id which owns the sensitive files -- I get all those file contents in my build log.

This is obviously highly undesirable.

The solution I employed in the past is to delete these files once the agent connects to VSO.

Of course now we have `.credentials_rsaparams` files which seems to be required every time we queue the build so the solution no longer works.

**Questions**

- What is the content of the `.credentials_rsaparams` file used for?

- Do we need to read from it every time we queue the build? Isn't it enough to read once at agent startup keep all that in memory?

- If we do need to keep the file around -- is it safe to do so? 

<br>
## **Agent and Worker's diag log**

The exception trace:

```
[2016-07-15 18:40:40Z ERR  MessageListener] Catch exception during get next message.
[2016-07-15 18:40:40Z ERR  MessageListener] System.Security.Cryptography.CryptographicException: RSA key file /home/vsoagent/.credentials_rsaparams was not found
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.RSAFileKeyManager.GetKey()
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.GetMessageDecryptor(Aes aes, TaskAgentMessage message)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.DecryptMessage(TaskAgentMessage message)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<GetNextMessageAsync>d__13.MoveNext()
[2016-07-15 18:40:40Z INFO MessageListener] Retriable exception: RSA key file /home/vsoagent/.credentials_rsaparams was not found
[2016-07-15 18:40:40Z ERR  Terminal] WRITE ERROR: 2016-07-15 18:40:40Z: Agent connect error: RSA key file /home/vsoagent/.credentials_rsaparams was not found. Retrying every 15 seconds until reconnected.
[2016-07-15 18:40:40Z INFO MessageListener] Sleeping for 15 seconds before retrying.
[2016-07-15 18:40:56Z INFO JobDispatcher] Shutting down JobDispather. Make sure all WorkerDispatcher has finished.
[2016-07-15 18:40:56Z ERR  Terminal] WRITE ERROR: An error occurred: Unexpected character encountered while parsing number: y. Path '', line 1, position 1.
[2016-07-15 18:40:56Z ERR  AgentProcess] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing number: y. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Microsoft.TeamFoundation.DistributedTask.WebApi.JsonUtility.FromString[T](String toDeserialize)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<RunAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<RunAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<RunAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.<MainAsync>d__1.MoveNext()
```

**Comment by TingluoHuang** [comment]
@ppanyukov 
What is the content of the .credentials_rsaparams file used for?
`It's a RSA private key for OAuth token exchange between agent and server. server hold the public key, every 50 mins server will send a new token to agent encrypted by the public key.`
Do we need to read from it every time we queue the build? Isn't it enough to read once at agent startup keep all that in memory?
`We can do it, but your agent will exit due to auto upgrade, so you still can't delete that file after agent startup`
If we do need to keep the file around -- is it safe to do so?
`it's not 100% safe, worst case someone who has permission to queue build against the agent can steal it from server. the solution should be let the worker and agent run as different user.`

**Comment by bryanmacfarlane** [comment]
Yes you need to keep it around or we wouldn't write it.  It's to make the agent much, much more secure than it was in previous releases.

We ask for you for your elevated admin permissions when you register the agent.  To avoid storing that powerful credential, when the agent is registered, we acquire a signed JWT token (OAuth exchange) from the server which only has permissions to listen to the queue.  

Then when the build runs, we generate another **per build** token with limited scope (defined on the general tab of the definition) which is time bombed for the life of the build (when build ends or timeout also defined on definition).  

Further that per build token is not accessible via ad hoc scripts or untrusted code - only to the build agent and task/plugins.  For example when unit tests are run, they run and send a command back to the agent to write results back.  This prevents something like a unit test to elevate and do something that developer would otherwise have permissions to do.

So, these make this agent more secure than the previous agents and an order of magnitude more secure than previous xaml and other build server generations. 

As Ting noted, in the future we are considering running even the worker as another identity for even another layer of security.

**Comment by ppanyukov** [comment]
Looks quite a comprehensive setup.  Also answers the question of #403.

It would be super nice if all this were put into docs at some point -- these are normally the questions that bother our ops people a lot.

**Comment by bryanmacfarlane** [comment]
Yes.  I do plan to write something documenting how security works.  Thanks!
