### ISSUE TITLE
Why do we require --token command line arg during remove?

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#403]
## **Agent version and platform**
2.103.0
<br>
Linux Centos 7

## **VSTS type and version**
VisualStudio.com

## **What's not working?** 

After I configure the agent like this

```
exec ./bin/Agent.Listener \
        configure \
        --unattended \
        --nostart \
        --agent ${VSTS_AGENT_NAME} \
        --auth ${VSTS_AUTH_TYPE} \
        --token ${VSTS_AUTH_TOKEN} \
        --pool ${VSTS_POOL} \
        --url ${VSTS_URL} \
        --acceptteeeula Y
```

After this I can start the agent without any other parameters like this and everything works.

```
exec ./bin/Agent.Listener --unattended
```

I expect the `remove` command to work in the similar way. However when I run this:

```
./bin/Agent.Listener remove --unattended
```

I get an errors:

```
**stderr: **
Invalid configuration provided for token. Terminating unattended configuration.

**stdout: **
Removing agent from VSO
Removing service
Removing agent from the server
Failed: Removing agent from the server


[2016-07-15 19:41:02Z INFO Terminal] WRITE LINE: Failed: Removing agent from the server
[2016-07-15 19:41:03Z ERR  Agent] System.Exception: Invalid configuration provided for token. Terminating unattended configuration.
```

To fix this I need to run:

```
./bin/Agent.Listener remove --unattended --auth ${VSTS_AUTH_TYPE} --token ${VSTS_AUTH_TOKEN}
```

Looks like a bug?

Full agent logs for remove command below.

<br>
## **Agent and Worker's diag log**

```
====== Agent_20160715-194904-utc.log =====
     1  [2016-07-15 19:49:04Z INFO AgentProcess] Agent is built for Linux - rhel.7.2-x64.
     2  [2016-07-15 19:49:04Z INFO AgentProcess] RuntimeInformation: Linux 4.1.17-boot2docker #1 SMP Thu Feb 11 08:12:31 UTC 2016.
     3  [2016-07-15 19:49:04Z INFO AgentProcess] Version: 2.103.0
     4  [2016-07-15 19:49:04Z INFO AgentProcess] Commit: 130a17ed8ee3f2f85efcf1152d89c0e6d0bcb7ec
     5  [2016-07-15 19:49:04Z INFO AgentProcess] Culture: en-US
     6  [2016-07-15 19:49:04Z INFO AgentProcess] UI Culture: en-US
     7  [2016-07-15 19:49:04Z INFO CommandLineParser] Parse
     8  [2016-07-15 19:49:04Z INFO CommandLineParser] Parsing 2 args
     9  [2016-07-15 19:49:04Z INFO CommandLineParser] parsing argument
    10  [2016-07-15 19:49:04Z INFO CommandLineParser] HasArgs: False
    11  [2016-07-15 19:49:04Z INFO CommandLineParser] Adding Command: remove
    12  [2016-07-15 19:49:04Z INFO CommandLineParser] parsing argument
    13  [2016-07-15 19:49:04Z INFO CommandLineParser] HasArgs: True
    14  [2016-07-15 19:49:04Z INFO CommandLineParser] arg: unattended
    15  [2016-07-15 19:49:04Z INFO AgentProcess] Arguments parsed
    16  [2016-07-15 19:49:04Z INFO Agent] ExecuteCommand
    17  [2016-07-15 19:49:04Z INFO ConfigurationStore] currentAssemblyLocation: /home/vsoagent/bin/Agent.Listener.dll
    18  [2016-07-15 19:49:04Z INFO ConfigurationStore] binPath: /home/vsoagent/bin
    19  [2016-07-15 19:49:04Z INFO ConfigurationStore] RootFolder: /home/vsoagent
    20  [2016-07-15 19:49:04Z INFO ConfigurationStore] ConfigFilePath: /home/vsoagent/.agent
    21  [2016-07-15 19:49:04Z INFO ConfigurationStore] CredFilePath: /home/vsoagent/.credentials
    22  [2016-07-15 19:49:04Z INFO ConfigurationStore] ServiceConfigFilePath: /home/vsoagent/.service
    23  [2016-07-15 19:49:04Z INFO CommandSettings] Flag 'help': 'False'
    24  [2016-07-15 19:49:04Z INFO CommandSettings] Flag 'version': 'False'
    25  [2016-07-15 19:49:04Z INFO CommandSettings] Flag 'commit': 'False'
    26  [2016-07-15 19:49:04Z INFO CommandSettings] Command 'remove': 'True'
    27  [2016-07-15 19:49:04Z INFO Terminal] WRITE LINE: Removing service
    28  [2016-07-15 19:49:04Z INFO ConfigurationStore] IsServiceConfigured()
    29  [2016-07-15 19:49:04Z INFO ConfigurationStore] IsServiceConfigured: False
    30  [2016-07-15 19:49:04Z INFO Terminal] WRITE LINE: Removing agent from the server
    31  [2016-07-15 19:49:04Z INFO ConfigurationStore] IsConfigured()
    32  [2016-07-15 19:49:04Z INFO ConfigurationStore] IsConfigured: True
    33  [2016-07-15 19:49:04Z INFO ConfigurationStore] HasCredentials()
    34  [2016-07-15 19:49:04Z INFO ConfigurationStore] stored True
    35  [2016-07-15 19:49:04Z INFO ConfigurationManager] GetCredentialProvider
    36  [2016-07-15 19:49:04Z INFO CommandSettings] Arg 'auth': ''
    37  [2016-07-15 19:49:04Z INFO CommandSettings] Flag 'unattended': 'True'
    38  [2016-07-15 19:49:04Z INFO PromptManager] ReadValue
    39  [2016-07-15 19:49:04Z INFO ConfigurationManager] Creating credential for auth: PAT
    40  [2016-07-15 19:49:04Z INFO CredentialManager] GetCredentialProvider
    41  [2016-07-15 19:49:04Z INFO CredentialManager] Creating type PAT
    42  [2016-07-15 19:49:04Z INFO CredentialManager] Creating credential type: PAT
    43  [2016-07-15 19:49:04Z INFO PersonalAccessToken] EnsureCredential
    44  [2016-07-15 19:49:04Z INFO CommandSettings] Arg 'token': ''
    45  [2016-07-15 19:49:04Z INFO CommandSettings] Flag 'unattended': 'True'
    46  [2016-07-15 19:49:04Z INFO PromptManager] ReadValue
    47  [2016-07-15 19:49:04Z INFO Terminal] WRITE LINE: Failed: Removing agent from the server
    48  [2016-07-15 19:49:04Z ERR  Agent] System.Exception: Invalid configuration provided for token. Terminating unattended configuration.
    49     at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.PromptManager.ReadValue(String argName, String description, Boolean secret, String defaultValue, Func`2 validator, Boolean unattended)
    50     at Microsoft.VisualStudio.Services.Agent.Listener.CommandSettings.GetArgOrPrompt(String name, String description, String defaultValue, Func`2 validator)
    51     at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.PersonalAccessToken.EnsureCredential(IHostContext context, CommandSettings command, String serverUrl)
    52     at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.GetCredentialProvider(CommandSettings command, String serverUrl)
    53     at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<UnconfigureAsync>d__9.MoveNext()
    54  --- End of stack trace from previous location where exception was thrown ---
    55     at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    56     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    57     at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext()
    58  [2016-07-15 19:49:04Z ERR  Terminal] WRITE ERROR: Invalid configuration provided for token. Terminating unattended configuration.

```

**Comment by TingluoHuang** [comment]
@ppanyukov when you remove an agent from pool, you need admin permission on that pool, same permission required when you config agent. we don't store your admin credential after config, so we ask that credential during unconfig.

**Comment by bryanmacfarlane** [comment]
Correct.  We don't (and shouldn't) store you admin credentials you provided when registering.  When you register we acquire an oauth token with limited privs to listen to the queue.  When a build is run, a scoped token (per scope on general tab of definition) is generated and time bombed per build.  So, when you unregister, we need to prompt for creds.
