### ISSUE TITLE
Question: how does auto-update work?

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#410]
## **Agent version and platform**
2.103.0
<br>
Linux Centos 7
<br>
## **VSTS type and version**
VisualStudio.com

## **What's not working?** 

I see some glimpses of *"the agent will auto-update"* in the issue here but cannot find any docs on the subject.

There are two questions actually:

1. Could someone confirm whether auto-update is the feature and how it works?

2. Is it possible to prevent auto-updates? We are running in containers so is certain to not work as expected.

**Comment by bryanmacfarlane** [comment]
Yes, it is a feature.  the agent will auto update if there's a new update advertised by the server.  It checks when it restarts.  There's also an update agents action in the pool web admin UI.

The server can also send an update message if a new feature demands a newer agent.  For example, when we did gated support, if it was a gated build, it demanded a newer version and the agent must be pulled forward.

So, it's possible to just not update or restart.  But, if a new capability is required to fulfill the build, a message will be sent and it will get pulled forward.  You can't opt out - think of it as a web app where server sends code to the client to run.

It works by the agent simply downloading the new agent, extracting to the side and generating a script to exit, copy the bits over, then starting itself back up.

**Comment by ppanyukov** [comment]
Thanks @bryanmacfarlane , this is useful. 

If the agent restarts, this will certainly not work with docker containers, because the container terminates once the running process terminates.  So those "forced upgrades" will probably send such agents into the infinite loop: "forced update -> restart -> container dies -> orchestrater brings it up again -> forced update ..."

I don't know whether this will become a problem in practice but I can see this may cause some head-scratching if this scenario does occur.

From my own perspective (and some may share this) -- I personally rather not have this auto update because I prefer to be in control of what is running in my environments and something that we tested. There are known breaking changes still going on (e.g. bundled git apparently is removed in 2.103.1?).  But I can see this may be a not entirely clear-cut case here.

I wonder if the an alternative approach to forced updates might be the tasks (or whatever) place a demand on the agent version, e.g. `Agent.Version >= 2.103.0` rather than automatically forcing the update.

Another alternative might be to go via standard distro packaging on nix, e.g. RPMs for Centos. This way at least this would be more in line with everything else on nix and would also make it easier to automate the rebuild/test/redeploy of any container-based deployments.

Yet another alternative might be to have a completely totally dumb agent listener which itself would never have to be updated, but instead all tasks are carried by child process(es), and it is those child processes which would get updated and restarted. This may also help with running those child processes under different identity thus may help with additional security. Of course this is probably a big design change.

And as always, having this kind of information in the official docs and manuals would be great at some point! :)

**Comment by bryanmacfarlane** [comment]
Git was a temporary redist while we waited for 2.9 to be released.  We also put in quite a bit of fallback code where it will use the git on your box and use creds in url instead of bearer token if it's < 2.9.  So, breaking changes should not happen in the agent.

Further, the service is constantly moving forward and the agent is just an extension of the service.  the service, all the tasks and everything is updated every 3 weeks and patched every day. 

We are looking at docker right now as well.  If we need a mode where the listener doesn't update (BTW, it is just a dumb http long poll listener - worker does all the work), then we will do that.  Another option we're looking at is dockerizing the worker.

**Comment by ppanyukov** [comment]
This feature has just done what I was afraid it would do: we are now getting into perpetual loop of start-upgrade-exit-start-upgrade-exit... (as a reminder we are running the agent in docker)

I start the agent which is 2.103.1.  After a little while it receives an update message and does a forced update.

The problem here, I am not even queueing a build at this stage, so this statement does not seem to hold at the moment:

> So, it's possible to just not update or restart. But, if a new capability is required to fulfill the build, a message will be sent and it will get pulled forward. 

This is a very bad news for dockerised agents :(

The options for us now are: a) abandon docker, which would be very, very undesirable for us;  or b) come up with some bash hacks which will allow the agent to self update and restart but will not terminate the container -- it's doable but is not particularly docker way and will have side effects.

If docker is something that is considered in the future, this kind of issues is something that people need to be aware of.

For completeness, logs which demonstrate the forced upgrade:

```
==> logs/vsts-agent-d.vnl.0/Agent_20160722-095658-utc.log <==
[2016-07-22 09:57:03Z INFO Agent] Refresh message received, kick-off selfupdate background process.
[2016-07-22 09:57:04Z INFO SelfUpdater] Latest version of 'agent' package availiable in server is 2.104.0
[2016-07-22 09:57:04Z INFO SelfUpdater] Current running agent version is 2.103.1
[2016-07-22 09:57:04Z INFO SelfUpdater] An update is availiable.



[2016-07-22 09:57:46Z INFO WhichUtil] Which: 'tar'
[2016-07-22 09:57:46Z INFO WhichUtil] Location: '/usr/bin/tar'
[2016-07-22 09:57:46Z INFO ProcessInvoker] Starting process:
[2016-07-22 09:57:46Z INFO ProcessInvoker]   File name: '/usr/bin/tar'
[2016-07-22 09:57:46Z INFO ProcessInvoker]   Arguments: '-xzf /home/vsoagent/_work/_update/vsts-agent-rhel.7.2-x64-2.104.0.tar.gz'
[2016-07-22 09:57:46Z INFO ProcessInvoker]   Working directory: '/home/vsoagent/_work/_update'
[2016-07-22 09:57:46Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2016-07-22 09:57:46Z INFO ProcessInvoker]   Encoding web name:  ; code page: ''
[2016-07-22 09:57:46Z INFO ProcessInvoker] Process started with process id 64, waiting for process exit.

[2016-07-22 09:58:07Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:21.6544752.
[2016-07-22 09:58:07Z INFO SelfUpdater] Finished getting latest agent package at: /home/vsoagent/_work/_update.
[2016-07-22 09:58:07Z INFO SelfUpdater] Download latest agent into: /home/vsoagent/_work/_update
[2016-07-22 09:58:07Z INFO SelfUpdater] All running job has exited.
[2016-07-22 09:58:07Z INFO SelfUpdater] Generate update script into: /home/vsoagent/_work/_update.sh
[2016-07-22 09:58:07Z INFO WhichUtil] Which: 'bash'
[2016-07-22 09:58:07Z INFO WhichUtil] Location: '/usr/bin/bash'
[2016-07-22 09:58:07Z INFO SelfUpdater] Update script start running
[2016-07-22 09:58:07Z INFO Agent] Auto update task finished at backend, an agent update is ready to apply exit the current agent instance.
[2016-07-22 09:58:07Z INFO Agent] Stop message queue looping.
[2016-07-22 09:58:07Z INFO MessageListener] Get next message has been cancelled.
[2016-07-22 09:58:08Z INFO Agent] Ignore any exception after cancel message loop. System.OperationCanceledException: The operation was canceled.
   at Microsoft.VisualStudio.Services.Agent.Extensions.<WithCancellation>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<GetNextMessageAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<RunAsync>d__12.MoveNext()
[2016-07-22 09:58:08Z INFO JobDispatcher] Shutting down JobDispather. Make sure all WorkerDispatcher has finished.

```
