### ISSUE TITLE
Error while copying content to a stream. Failed to connect. Try again or ctrl-c to quit

### ISSUE THREAD

**Issue by vjeevaflynn** [Microsoft/vsts-agent#412]
## **Agent version and platform**
Version of your agent? 2.103.0
<br>
Windows
<br>
## **VSTS type and version**
VisualStudio.com
<br>
<br>
If VisualStudio.com, what is your account name? ****** Prefer not to say, unless necessary
<br>
## **What's not working?** 
Can't run config.cmd, getting message 'Error while copying content to a stream. Failed to connect. Try again or ctrl-c to quit'
<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

[2016-07-18 18:52:30Z INFO AgentProcess] Agent is built for Windows - win7-x64.
[2016-07-18 18:52:30Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 6.1.7601 S.
[2016-07-18 18:52:30Z INFO AgentProcess] Version: 2.103.0
[2016-07-18 18:52:30Z INFO AgentProcess] Commit: 130a17ed8ee3f2f85efcf1152d89c0e6d0bcb7ec
[2016-07-18 18:52:30Z INFO AgentProcess] Culture: en-US
[2016-07-18 18:52:30Z INFO AgentProcess] UI Culture: en-US
[2016-07-18 18:52:30Z INFO CommandLineParser] Parse
[2016-07-18 18:52:30Z INFO CommandLineParser] Parsing 1 args
[2016-07-18 18:52:30Z INFO CommandLineParser] parsing argument
[2016-07-18 18:52:30Z INFO CommandLineParser] HasArgs: False
[2016-07-18 18:52:30Z INFO CommandLineParser] Adding Command: configure
[2016-07-18 18:52:30Z INFO AgentProcess] Arguments parsed
[2016-07-18 18:52:30Z INFO Agent] ExecuteCommand
[2016-07-18 18:52:30Z INFO ConfigurationStore] currentAssemblyLocation: C:\myagent\bin\Agent.Listener.dll
[2016-07-18 18:52:30Z INFO ConfigurationStore] binPath: C:\myagent\bin
[2016-07-18 18:52:30Z INFO ConfigurationStore] RootFolder: C:\myagent
[2016-07-18 18:52:30Z INFO ConfigurationStore] ConfigFilePath: C:\myagent\.agent
[2016-07-18 18:52:30Z INFO ConfigurationStore] CredFilePath: C:\myagent\.credentials
[2016-07-18 18:52:30Z INFO ConfigurationStore] ServiceConfigFilePath: C:\myagent\.service
[2016-07-18 18:52:30Z INFO CommandSettings] Flag 'help': 'False'
[2016-07-18 18:52:30Z INFO CommandSettings] Flag 'version': 'False'
[2016-07-18 18:52:30Z INFO CommandSettings] Flag 'commit': 'False'
[2016-07-18 18:52:30Z INFO CommandSettings] Command 'remove': 'False'
[2016-07-18 18:52:30Z INFO CommandSettings] Command 'run': 'False'
[2016-07-18 18:52:30Z INFO CommandSettings] Command 'configure': 'True'
[2016-07-18 18:52:30Z INFO ConfigurationManager] ConfigureAsync
[2016-07-18 18:52:30Z INFO ConfigurationStore] IsConfigured()
[2016-07-18 18:52:30Z INFO ConfigurationStore] IsConfigured: False
[2016-07-18 18:52:30Z INFO ConfigurationManager] Is configured: False
[2016-07-18 18:52:30Z INFO Terminal] WRITE LINE: 
[2016-07-18 18:52:30Z INFO Terminal] WRITE LINE: >> Connect:
[2016-07-18 18:52:30Z INFO Terminal] WRITE LINE: 
[2016-07-18 18:52:30Z INFO CommandSettings] Arg 'url': ''
[2016-07-18 18:52:30Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-18 18:52:30Z INFO PromptManager] ReadValue
[2016-07-18 18:52:30Z INFO Terminal] WRITE: Enter server URL > 
[2016-07-18 18:52:30Z INFO Terminal] READ LINE
[2016-07-18 18:52:38Z INFO Terminal] Read value: '****************'
[2016-07-18 18:52:39Z INFO ConfigurationManager] GetCredentialProvider
[2016-07-18 18:52:39Z INFO CommandSettings] Arg 'auth': ''
[2016-07-18 18:52:39Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-18 18:52:39Z INFO PromptManager] ReadValue
[2016-07-18 18:52:39Z INFO Terminal] WRITE: Enter authentication type (press enter for PAT) > 
[2016-07-18 18:52:39Z INFO Terminal] READ LINE
[2016-07-18 18:52:39Z INFO Terminal] Read value: ''
[2016-07-18 18:52:39Z INFO PromptManager] Falling back to the default: 'PAT'
[2016-07-18 18:52:39Z INFO ConfigurationManager] Creating credential for auth: PAT
[2016-07-18 18:52:39Z INFO CredentialManager] GetCredentialProvider
[2016-07-18 18:52:39Z INFO CredentialManager] Creating type PAT
[2016-07-18 18:52:39Z INFO CredentialManager] Creating credential type: PAT
[2016-07-18 18:52:39Z INFO PersonalAccessToken] EnsureCredential
[2016-07-18 18:52:39Z INFO CommandSettings] Arg 'token': ''
[2016-07-18 18:52:39Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-18 18:52:39Z INFO PromptManager] ReadValue
[2016-07-18 18:52:39Z INFO Terminal] WRITE: Enter personal access token > 
[2016-07-18 18:52:39Z INFO Terminal] READ SECRET
[2016-07-18 18:52:42Z INFO Terminal] Read value: '********'
[2016-07-18 18:52:42Z INFO PersonalAccessToken] GetVssCredentials
[2016-07-18 18:52:42Z INFO PersonalAccessToken] token retrieved: 52 chars
[2016-07-18 18:52:42Z INFO ConfigurationManager] cred retrieved
[2016-07-18 18:52:42Z INFO Terminal] WRITE LINE: Connecting to server ...
[2016-07-18 18:52:42Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-18 18:52:42Z ERR  Terminal] WRITE ERROR (exception):
[2016-07-18 18:52:42Z ERR  Terminal] System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to read data from the transport connection. The connection was closed before all data could be read. Expected 1984 bytes, read 0 bytes.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.StreamToStreamCopy.<CopyAsyncToPreSizedLimitMemoryStream>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<TestConnectAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__8.MoveNext()
[2016-07-18 18:52:42Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2016-07-18 18:52:42Z INFO CommandSettings] Arg 'url': ''
[2016-07-18 18:52:42Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-07-18 18:52:42Z INFO PromptManager] ReadValue
[2016-07-18 18:52:42Z INFO Terminal] WRITE: Enter server URL > 
[2016-07-18 18:52:42Z INFO Terminal] READ LINE

**Comment by vjeevaflynn** [comment]
Any help would be greatly appreciated, thank you!

**Comment by TingluoHuang** [comment]
@vjeevaflynn are you able to get Fiddler trace while you hitting this error?

**Comment by vjeevaflynn** [comment]
I just got Fiddler and checked, the call was failing due to our work proxy server. Disabled the server and tried the command again and worked. Thanks for the help!
