### ISSUE TITLE
Occasional `Value cannot be null` error during `get sources` phase

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-agent#467]
## **Agent version and platform**
Version of your agent? 2.104.0
<br>
Linux, Centos 7
<br>
## **VSTS type and version**
VisualStudio.com

## **What's not working?** 

Sometimes we have a failed build due to this mysterious error `Value cannot be null` in `get sources` phase.

```
2016-08-01T16:16:33.7636070Z ##[section]Starting: Build
2016-08-01T16:16:35.6342100Z ##[section]Starting: Get Sources
2016-08-01T16:16:35.8461270Z Syncing repository: vnl-platform (TfsGit)
2016-08-01T16:16:35.8791920Z ##[command]git version
2016-08-01T16:16:36.0383980Z ##[error]Value cannot be null.
Parameter name: _version
2016-08-01T16:16:36.0519880Z ##[section]Finishing: Get Sources
2016-08-01T16:16:36.0714850Z ##[section]Starting: Post Job Cleanup
2016-08-01T16:16:36.0953200Z Cleaning any cached credential from repository: vnl-platform (Git)
2016-08-01T16:16:36.1002870Z ##[section]Finishing: Post Job Cleanup
2016-08-01T16:16:36.1027280Z ##[section]Finishing: Build
```

Could there be some race condition trying to get git version?

<br>
## **Agent and Worker's diag log**

**Agent log:**

```
[2016-08-01 16:16:29Z INFO JobNotification] Entering JobStarted Notification
[2016-08-01 16:16:29Z INFO JobDispatcher] Start renew job request.
[2016-08-01 16:16:30Z INFO JobDispatcher] Successfully renew job request, job is valid till 8/1/16 4:21:29 PM
[2016-08-01 16:16:30Z INFO ProcessInvoker] Starting process:
[2016-08-01 16:16:30Z INFO ProcessInvoker]   File name: '/home/vsoagent/bin/Agent.Worker'
[2016-08-01 16:16:30Z INFO ProcessInvoker]   Arguments: 'spawnclient 162 165'
[2016-08-01 16:16:30Z INFO ProcessInvoker]   Working directory: '/home/vsoagent/bin'
[2016-08-01 16:16:30Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2016-08-01 16:16:30Z INFO ProcessInvoker]   Encoding web name:  ; code page: ''
[2016-08-01 16:16:30Z INFO ProcessInvoker] Process started with process id 29105, waiting for process exit.
[2016-08-01 16:16:30Z INFO JobDispatcher] Send job request message to worker.
[2016-08-01 16:16:37Z INFO ProcessInvoker] Finished process with exit code 102, and elapsed time 00:00:07.2322373.
[2016-08-01 16:16:37Z INFO JobDispatcher] Worker finished. Code: 102
[2016-08-01 16:16:37Z INFO JobDispatcher] finish job request with result: Failed
[2016-08-01 16:16:37Z INFO Terminal] WRITE LINE: 2016-08-01 16:16:37Z: Job Build completed with result: Failed
[2016-08-01 16:16:38Z INFO JobNotification] Entering JobCompleted Notification
```

**Worker log:**

```
[2016-08-01 16:16:35Z INFO WhichUtil] Which: 'git'
[2016-08-01 16:16:35Z INFO WhichUtil] Location: '/usr/local/bin/git'
[2016-08-01 16:16:35Z INFO ProcessInvoker] Starting process:
[2016-08-01 16:16:35Z INFO ProcessInvoker]   File name: '/usr/local/bin/git'
[2016-08-01 16:16:35Z INFO ProcessInvoker]   Arguments: 'version'
[2016-08-01 16:16:35Z INFO ProcessInvoker]   Working directory: '/home/vsoagent/_work'
[2016-08-01 16:16:35Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2016-08-01 16:16:35Z INFO ProcessInvoker]   Encoding web name:  ; code page: ''
[2016-08-01 16:16:35Z INFO ProcessInvoker] Process started with process id 29133, waiting for process exit.
[2016-08-01 16:16:35Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0493017.
[2016-08-01 16:16:36Z ERR  StepsRunner] Caught exception from step: System.ArgumentNullException: Value cannot be null.
Parameter name: _version
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.GitCommandManager.<LoadGitExecutionInfo>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.GitSourceProvider.<GetSourceAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.<PrepareAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
[2016-08-01 16:16:36Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2016-08-01 16:16:36Z INFO StepsRunner] Step result: Failed
```

**Comment by TingluoHuang** [comment]
@ppanyukov are you able to get consistency repro? what are the chance of this happen?

**Comment by ppanyukov** [comment]
@TingluoHuang no consistent/reliable repro here unfortunately. This happens very rarely and randomly. Hence looks like may be a race somewhere.

Quickly looking at the code (`ProcessInvoker` and `GitCommandManager.ExecuteGitCommandAsync`) -- it does seem likely that the exit code `0` arrives before the output from the command makes it into the `IList<string> output`.

The code in `ProcessInvoker` is quite involved so I guess you may be in a better position to check if such arrival order bug is possible.

PS. Also not sure that the following locking is 100% effective:

```
// ExecuteGitCommandAsync

                lock (outputLock)
                {
                    output.Add(message.Data);
                }
```

because in `GitVersion` this same list is accessed without any lock whatsoever. 

I can see this potentially might be the source of the issue.

**Comment by ppanyukov** [comment]
Oh, and a tiny little typo there, in `GitCommandManager` :)

<img width="859" alt="screen shot 2016-08-02 at 11 21 39" src="https://cloud.githubusercontent.com/assets/300031/17325437/76dcc152-58a3-11e6-827a-fe9fe661bf78.png">

**Comment by bryanmacfarlane** [comment]
Someone else hit this today ...

**Comment by TingluoHuang** [comment]
I was able to repro this problem with a small console app that invoke git version.

**Comment by ppanyukov** [comment]
@TingluoHuang would be nice to know the root cause at some point when you are ready.

**Comment by bryanmacfarlane** [comment]
I'm worried it's a bug in the process invoker.  What's interesting about `git version` is it runs very, very fast (returns a baked in constant).

**Comment by bryanmacfarlane** [comment]
Shouldn't happen in most recent release 2.104.2

Let us know if you see it again.
