### ISSUE TITLE
Cyclical variable reference causes null ref in worker.

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-agent#480]
Cyclical variable reference, e.g.
r1 = r1\$(r2)
r2 = r2\$(r1)

The cycle is detected properly by the variables class but then shortly after a null ref bubbles all the way out from initialization of the execution context. It basically crashes the worker and no tasks are ever run.
```
[2016-08-04 05:53:52Z ERR  Program] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Services.Agent.Worker.ExecutionContext.Write(String tag, String message) in C:\vsts-agent\src\Agent.Worker\ExecutionContext.cs:line 317
   at Microsoft.VisualStudio.Services.Agent.Worker.ExecutionContextExtension.Warning(IExecutionContext context, String message) in C:\vsts-agent\src\Agent.Worker\ExecutionContext.cs:line 399
   at Microsoft.VisualStudio.Services.Agent.Worker.ExecutionContext.<InitializeJob>b__47_0(String x) in C:\vsts-agent\src\Agent.Worker\ExecutionContext.cs:line 303
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Microsoft.VisualStudio.Services.Agent.Worker.ExecutionContext.InitializeJob(JobRequestMessage message, CancellationToken token) in C:\vsts-agent\src\Agent.Worker\ExecutionContext.cs:line 303
   at Microsoft.VisualStudio.Services.Agent.Worker.JobRunner.<RunAsync>d__1.MoveNext() in C:\vsts-agent\src\Agent.Worker\JobRunner.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.Agent.Worker.JobRunner.<RunAsync>d__1.MoveNext() in C:\vsts-agent\src\Agent.Worker\JobRunner.cs:line 225
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Services.Agent.Worker.Worker.<RunAsync>d__1.MoveNext() in C:\vsts-agent\src\Agent.Worker\Worker.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Services.Agent.Worker.Program.<MainAsync>d__1.MoveNext() in C:\vsts-agent\src\Agent.Worker\Program.cs:line 41
```

**Comment by bryanmacfarlane** [comment]
Make sure we get a test as well with the fix.

**Comment by ericsciple** [comment]
https://github.com/Microsoft/vsts-agent/pull/531
