### ISSUE TITLE
[BUG]:  .NET Framework 4.7 required for agent installation as a service

### ISSUE THREAD

**Issue by gt97** [Microsoft/vsts-agent#4841]
### What happened?

Installing the agent on a windows server from powershell as admin I am not able to continue the installation because framework 4.7 is required.

According to documentation (https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/windows-agent?view=azure-devops#check-prerequisites) The agent software installs its own version of .NET so there's no .NET prerequisite.

![Immagine](https://github.com/microsoft/azure-pipelines-agent/assets/40632454/e09ddb1b-42d2-4e3d-9207-1b319a7608d6)

### Versions

Azure Devops version 2.329.1/WIN2012

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2012

### Relevant log output

```shell
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper] Starting process:
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   File name: '"D:\azagent\bin\AgentService.exe"'
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   Arguments: 'init'
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   Working directory: ''
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   Require exit code zero: 'True'
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   Encoding web name:  ; code page: ''
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   Force kill process on cancellation: 'False'
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   Redirected STDIN: 'False'
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   Persist current code page: 'False'
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   Keep redirected STDIN open: 'False'
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   High priority process: 'False'
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   ContinueAfterCancelProcessTreeKillAttempt: 'False'
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   Sigint timeout: '00:00:07.5000000'
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   Sigterm timeout: '00:00:02.5000000'
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper]   Try to use graceful shutdown: False
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper] OOM score adjustment is Linux-only.
[2024-06-13 13:23:29Z INFO ProcessInvokerWrapper] Process started with process id 10408, waiting for process exit.
[2024-06-13 13:23:32Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2024-06-13 13:23:32Z INFO ProcessInvokerWrapper] STDOUT/STDERR stream read finished.
[2024-06-13 13:23:32Z INFO ProcessInvokerWrapper] Exited process 10408 with exit code -2146232576
[2024-06-13 13:23:32Z INFO ProcessInvokerWrapper] Finished process 10408 with exit code -2146232576, and elapsed time 00:00:03.1487455.
[2024-06-13 13:23:33Z ERR  Agent] Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code -2146232576 returned from process: file name '"D:\azagent\bin\AgentService.exe"', arguments 'init'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, Boolean continueAfterCancelProcessTreeKillAttempt, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Agent.Sdk\ProcessInvoker.cs:line 389
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, Boolean continueAfterCancelProcessTreeKillAttempt, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.VisualStudio.Services.Agent\ProcessInvoker.cs:line 329
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.NativeWindowsServiceHelper.InstallService(String serviceName, String serviceDisplayName, String logonAccount, String logonPassword, Boolean setServiceSidTypeAsUnrestricted) in D:\a\_work\1\s\src\Agent.Listener\Configuration.Windows\NativeWindowsServiceHelper.cs:line 500
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.WindowsServiceControlManager.ConfigureService(AgentSettings settings, CommandSettings command) in D:\a\_work\1\s\src\Agent.Listener\Configuration.Windows\WindowsServiceControlManager.cs:line 142
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command) in D:\a\_work\1\s\src\Agent.Listener\Configuration\ConfigurationManager.cs:line 442
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.ExecuteCommand(CommandSettings command) in D:\a\_work\1\s\src\Agent.Listener\Agent.cs:line 103
[2024-06-13 13:23:33Z ERR  Terminal] WRITE ERROR: Exit code -2146232576 returned from process: file name '"D:\azagent\bin\AgentService.exe"', arguments 'init'.
```

**Comment by NenoLoje** [comment]
> We are working on more prioritized issues at the moment, but will get back to this one soon.

I got the same issue. Cannot install the latest Agent due to this.

**Comment by vishplanet** [comment]
is this issue resolved? I having the same issue.

**Comment by JoshWeepie** [comment]
Same issue. Agent stopped yesterday and now won't start because it says it needs .NET Framework 4.7.1, yet the Azure Pipelines Self-Hosted Windows docs say "The agent software installs its own version of .NET so there's no .NET prerequisite.". 

https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/windows-agent?view=azure-devops#check-prerequisites

Lol.

**Comment by JoshWeepie** [comment]
If anyone else runs into this, I installed .NET Framework 4.7.2, and then I was able to ./config the agent successfully.

**Comment by vishplanet** [comment]
Thanks @JoshWeepie  for the feedback. I tried 4.7.1 but it did not work. Let me try 4.7.2. Thanks again.

**Comment by gt97** [comment]
I think this is an issue that has to be solved, otherwise I have to keep the update agent on the agent pool unchecked because maybe the update fails.

**Comment by michaerlrob92** [comment]
Getting this issue on Server 2016, .NET 4.7.1 installed, .NET 4.7.2 installed. Fix it please.

**Comment by drdamour** [comment]
this is quite a bummer...anyone have any success using an older agent install that auto updates as a workaround?

**Comment by uha666** [comment]
A temporary fix is to edit the following line in the AgentService.exe.config

<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1"/>

to 

<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>

It will allow the service to run properly and since the worker itself is auto contained it doesn't affect deploy operations.

**Comment by osmansonmez** [comment]
Download Last version of hosted agents. For example last version is vsts-agent-win-x64-4.260.0
unzip zip file and change AgentService.exe.config  in bin folder. change <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1"/> to <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5"/>
and zip again with the same name or increase minor version for example vsts-agent-win-x64-4.260.1 
and copy this zip  file to on Azure devops server C:\ProgramData\Microsoft\Azure DevOps\Agents  folder after that 
agents will update and fixed this problem.
