### ISSUE TITLE
Failed to create session. No agent pool found with identifier 2  when using Windows Agent with TFS 15 RC1

### ISSUE THREAD

**Issue by bbusacker** [Microsoft/vsts-agent#489]
## **Agent version and platform**
Version of your agent? 2.104.2
<br>
OS of the machine running the agent?  Windows Server 2012
<br>
## **VSTS type and version**
On-Prem TFS
<br>
TFS 15 RC1
<br>
## **What's not working?** 

All agents (both Windows and Linux) were working prior to upgrading to RC1.   Now agents install okay but cannot run.  Not sure what the permission scheme is now.  It appears to have changed since TFS 2015.  

>> Connect:

Enter server URL > http://bowdmxtfs01:8080/tfs
Enter authentication type (press enter for Integrated) >
Connecting to server ...

>> Register Agent:

Enter agent pool (press enter for default) >
Enter agent name (press enter for BOWDMXTFS01) > Agent1-BOWDMXTFS01
Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
Enter work folder (press enter for _work) >
2016-08-09 06:15:54Z: Settings Saved.
Enter run agent as service? (Y/N) (press enter for N) > n

E:\TfsBuildAgents\Agent1-BOWDMXTFS01>run.cmd
Scanning for tool capabilities.
Connecting to the server.
**Failed to create session. No agent pool found with identifier 2.**
<br>
## **Agent and Worker's diag log**
[2016-08-09 06:16:16Z INFO MessageListener] Connecting to the Agent Server...
[2016-08-09 06:16:16Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file E:\TfsBuildAgents\Agent1-BOWDMXTFS01\.credentials_rsaparams
[2016-08-09 06:16:17Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file E:\TfsBuildAgents\Agent1-BOWDMXTFS01\.credentials_rsaparams
[2016-08-09 06:16:17Z ERR  MessageListener] Catch exception during create session.
[2016-08-09 06:16:18Z ERR  MessageListener] Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentPoolNotFoundException: No agent pool found with identifier 2.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<CreateSessionAsync>d__11.MoveNext()
[2016-08-09 06:16:18Z INFO MessageListener] Non-retriable exception: No agent pool found with identifier 2.
[2016-08-09 06:16:18Z ERR  Terminal] WRITE ERROR: Failed to create session. No agent pool found with identifier 2.

**Comment by bbusacker** [comment]
This appears to most likely be a TFS RC1 issue and not an agent issue.  I've asked the TFS technical support team to look into it.

**Comment by TingluoHuang** [comment]
@bbusacker let us know if you need any agent side support.

**Comment by jmezach** [comment]
We are hitting this issue with TFS 2017 RTM at the moment. Exact same message as in the original post. We are seeing 404's being returned from TFS on the POST request to the pool's session resource. I've checked the identifier multiple times but as far as I can tell it is the correct one. I've even looked in the TFS configuration database and I can see the same identifier there, yet it is still giving us this error.

Our working theory is that it has something to do with authentication/authorization but whatever combination of protocols we're trying to use we keep getting this error message.

**Comment by jmezach** [comment]
We've got it to work now. We had to completely delete the default pool and create a new one and now it seems to work.

**Comment by fishbits** [comment]
Encountered this issue in TFS 2017 Update 1 testing (on prem). The agent version is 2.112.0.

```
[2017-03-22 23:16:50Z INFO Terminal] WRITE LINE: Connecting to the server.
[2017-03-22 23:16:50Z INFO MessageListener] Attempt to create session.
[2017-03-22 23:16:50Z INFO MessageListener] Connecting to the Agent Server...
[2017-03-22 23:16:50Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file E:\Agent3\.credentials_rsaparams
[2017-03-22 23:16:50Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file E:\Agent3\.credentials_rsaparams
[2017-03-22 23:16:50Z ERR  MessageListener] Catch exception during create session.
[2017-03-22 23:16:51Z ERR  MessageListener] Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentPoolNotFoundException: No agent pool found with identifier 3.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<CreateSessionAsync>d__11.MoveNext()
[2017-03-22 23:16:51Z INFO MessageListener] Non-retriable exception: No agent pool found with identifier 3.
[2017-03-22 23:16:51Z ERR  Terminal] WRITE ERROR: Failed to create session. No agent pool found with identifier 3.
```
This is encountered after creating the agent successfully and then executing ".\run.cmd" (or even trying to start from Services console).

The agents not giving any trouble? The older VsoAgent.exe (v15.105.25910.0)
