### ISSUE TITLE
Agent unable to connect after successful config.  Oauth error

### ISSUE THREAD

**Issue by strtdusty** [Microsoft/vsts-agent#644]
## **Agent version and platform**
Version of your agent? 2.107
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com 

If VisualStudio.com, what is your account name? http://itron.visualstudio.com
<br>
## **What's not working?** 
Using a PAT will no scope limitations I configure an agent.  I enter a unique agent name and the agent is registered successfully.  When running (interactive or as a service) no connection is made.  Log files indicate   I can provided http request headers as well if necessary.  I have tried using a new PAT and tried from different Windows machines.
<br>
## **Agent and Worker's diag log**
[2016-10-13 20:03:11Z INFO CredentialManager] GetCredentialProvider
[2016-10-13 20:03:11Z INFO CredentialManager] Creating type OAuth
[2016-10-13 20:03:11Z INFO CredentialManager] Creating credential type: OAuth
[2016-10-13 20:03:11Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\agent\.credentials_rsaparams
[2016-10-13 20:03:11Z INFO Terminal] WRITE LINE: Connecting to the server.
[2016-10-13 20:03:11Z INFO MessageListener] Attempt to create session.
[2016-10-13 20:03:11Z INFO MessageListener] Connecting to the Agent Server...
[2016-10-13 20:03:14Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\agent\.credentials_rsaparams
[2016-10-13 20:03:14Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\agent\.credentials_rsaparams
[2016-10-13 20:03:16Z ERR  MessageListener] Catch exception during create session.
[2016-10-13 20:03:16Z ERR  MessageListener] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation identifier is not valid
   at System.Net.Http.WinHttpAuthHelper.CheckResponseForAuthentication(WinHttpRequestState state, UInt32& proxyAuthScheme, UInt32& serverAuthScheme)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by TingluoHuang** [comment]
@strtdusty we only use your PAT token during config/unconfigure, when the agent running, it will use a time bombed token generated by server for agent-server communication. Did you every modify your agent pool roles?

**Comment by strtdusty** [comment]
@TingluoHuang : no changes to agent pool roles.  Other agents in the same pool are still connecting.

**Comment by TingluoHuang** [comment]
@strtdusty Are there 2.x agents in the same pool?

**Comment by strtdusty** [comment]
Yes.  I have 2 other 2.106 agents.  I have tried to bring up new agents using 2.106 and 2.107 with the same results.

**Comment by TingluoHuang** [comment]
@strtdusty can you share the full agent log? both config log and run log, do you have http proxy configured? can you capture Fiddler trace? thanks,

**Comment by strtdusty** [comment]
@TingluoHuang : both log files attached

[_diag.zip](https://github.com/Microsoft/vsts-agent/files/528311/_diag.zip)

**Comment by TingluoHuang** [comment]
@strtdusty do you have http proxy configured? can you capture Fiddler trace?

**Comment by TingluoHuang** [comment]
@strtdusty also, open task manager, make sure there is only one `agent.listener.exe` running on that box, if you only configured one agent on that box.

**Comment by strtdusty** [comment]
@TingluoHuang : it is running.  We have no proxy config.  Do you need the decrypted HTTPS or is the encrypted OK?  I'm attaching the encrypted.  The decrypted does show 401 responses to itron.visualstudio.com and a 200 from itron.vssps.visualstudio.com with an access token in response.
[1_Full.zip](https://github.com/Microsoft/vsts-agent/files/528351/1_Full.zip)

**Comment by TingluoHuang** [comment]
@strtdusty  What is running? how many agent.listener.exe are running on that box `SPO-JBAILEY`? are they running interactively or service, i did the the agent `SPO-JBAILEY` shows online.
You can send me the decrypted traffic, as i said, we use the generated token to communicate, (not your PAT).

**Comment by strtdusty** [comment]
@TingluoHuang The box I sent the logs from is only running that agent, so only one agent.listener.exe running.  Can I PM or email the logs to you?  Assuming the bearer token has not expired that would still be sensitive I believe.

**Comment by TingluoHuang** [comment]
@strtdusty sure, tihuang@microsoft.com

**Comment by strtdusty** [comment]
@TingluoHuang Configuring against https://itron.visualstudio.com instead of https://itron.visualstudio.com/defaultcollection worked.  Am I wrong or did you have to do defaultcollection before?

**Comment by TingluoHuang** [comment]
it's not your problem i log an separate issue to tracking. something on service side changed.
#645 
close this one for now.
