### ISSUE TITLE
The type initializer for 'System.Net.Http.CurlHandler' threw an exception for Openssl 1.0.2j

### ISSUE THREAD

**Issue by changeworld** [Microsoft/vsts-agent#673]
## **Agent version and platform**
Version of your agent? 2.108
OS of the machine running the agent? OSX 10.10.5

## **VSTS type and version**
VisualStudio.com
If VisualStudio.com, what is your account name? http://changesworlds.visualstudio.com

## **What's not working?** 
Please include error messages and screenshots

I run `./config.sh`.
Error occurred.

<img width="595" alt="2016-11-05 15 55 17" src="https://cloud.githubusercontent.com/assets/1207985/20028439/be2bea6c-a374-11e6-9dc6-88fdd0ef6e63.png">

I do not think this is not a duplicate of #110 because my OpenSSL version is 1.0.2j.

```
$ openssl version
OpenSSL 1.0.2j  26 Sep 2016
```

## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

```
[2016-11-05 07:02:17Z INFO AgentProcess] Agent is built for OSX - osx.10.11-x64.
[2016-11-05 07:02:17Z INFO AgentProcess] RuntimeInformation: Darwin 14.5.0 Darwin Kernel Version 14.5.0: Mon Aug 29 21:14:16 PDT 2016; root:xnu-2782.50.6~1/RELEASE_X86_64.
[2016-11-05 07:02:17Z INFO AgentProcess] Version: 2.108.0
[2016-11-05 07:02:17Z INFO AgentProcess] Commit: c339954225fd3466d82c4038859ca71bc83cf819
[2016-11-05 07:02:17Z INFO AgentProcess] Culture: ja-JP
[2016-11-05 07:02:17Z INFO AgentProcess] UI Culture: ja-JP
[2016-11-05 07:02:17Z INFO HostContext] Well known directory 'Bin': '/vsts/myagent/bin'
[2016-11-05 07:02:17Z INFO HostContext] Well known directory 'Root': '/vsts/myagent'
[2016-11-05 07:02:17Z INFO AgentProcess] Validating directory permissions for: '/vsts/myagent'
[2016-11-05 07:02:17Z INFO CommandLineParser] Parse
[2016-11-05 07:02:17Z INFO CommandLineParser] Parsing 1 args
[2016-11-05 07:02:17Z INFO CommandLineParser] parsing argument
[2016-11-05 07:02:17Z INFO CommandLineParser] HasArgs: False
[2016-11-05 07:02:17Z INFO CommandLineParser] Adding Command: configure
[2016-11-05 07:02:17Z INFO AgentProcess] Arguments parsed
[2016-11-05 07:02:17Z INFO ProxyConfiguration] No proxy setting found.
[2016-11-05 07:02:17Z INFO Agent] ExecuteCommand
[2016-11-05 07:02:17Z INFO ConfigurationStore] currentAssemblyLocation: /vsts/myagent/bin/Agent.Listener.dll
[2016-11-05 07:02:17Z INFO ConfigurationStore] binPath: /vsts/myagent/bin
[2016-11-05 07:02:17Z INFO ConfigurationStore] RootFolder: /vsts/myagent
[2016-11-05 07:02:17Z INFO ConfigurationStore] ConfigFilePath: /vsts/myagent/.agent
[2016-11-05 07:02:17Z INFO ConfigurationStore] CredFilePath: /vsts/myagent/.credentials
[2016-11-05 07:02:17Z INFO ConfigurationStore] ServiceConfigFilePath: /vsts/myagent/.service
[2016-11-05 07:02:17Z INFO CommandSettings] Flag 'help': 'False'
[2016-11-05 07:02:17Z INFO CommandSettings] Flag 'version': 'False'
[2016-11-05 07:02:17Z INFO CommandSettings] Flag 'commit': 'False'
[2016-11-05 07:02:17Z INFO CommandSettings] Command 'configure': 'True'
[2016-11-05 07:02:17Z INFO ConfigurationManager] ConfigureAsync
[2016-11-05 07:02:17Z INFO ConfigurationStore] IsConfigured()
[2016-11-05 07:02:17Z INFO ConfigurationStore] IsConfigured: False
[2016-11-05 07:02:17Z INFO ConfigurationManager] Is configured: False
[2016-11-05 07:02:17Z INFO Terminal] WRITE LINE: 
[2016-11-05 07:02:17Z INFO Terminal] WRITE LINE: >> End User License Agreements:
[2016-11-05 07:02:17Z INFO Terminal] WRITE LINE: 
[2016-11-05 07:02:17Z INFO Terminal] WRITE LINE: Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /vsts/myagent/externals/tee/license.html
[2016-11-05 07:02:17Z INFO Terminal] WRITE LINE: 
[2016-11-05 07:02:17Z INFO CommandSettings] Flag 'acceptteeeula': 'False'
[2016-11-05 07:02:17Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-05 07:02:17Z INFO PromptManager] ReadValue
[2016-11-05 07:02:17Z INFO Terminal] WRITE: Enter (Y/N) Accept the Team Explorer Everywhere license agreement now? (press enter for N) > 
[2016-11-05 07:02:17Z INFO Terminal] READ LINE
[2016-11-05 07:02:20Z INFO Terminal] Read value: ''
[2016-11-05 07:02:20Z INFO PromptManager] Falling back to the default: 'N'
[2016-11-05 07:02:20Z INFO CommandSettings] Flag 'machinegroup': 'False'
[2016-11-05 07:02:20Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2016-11-05 07:02:20Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2016-11-05 07:02:20Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.MachineGroupAgentConfigProvider, Agent.Listener
[2016-11-05 07:02:20Z INFO Terminal] WRITE LINE: 
[2016-11-05 07:02:20Z INFO Terminal] WRITE LINE: >> Connect:
[2016-11-05 07:02:20Z INFO Terminal] WRITE LINE: 
[2016-11-05 07:02:20Z INFO CommandSettings] Arg 'url': ''
[2016-11-05 07:02:20Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-05 07:02:20Z INFO PromptManager] ReadValue
[2016-11-05 07:02:20Z INFO Terminal] WRITE: Enter server URL > 
[2016-11-05 07:02:20Z INFO Terminal] READ LINE
[2016-11-05 07:06:23Z INFO Terminal] Read value: 'https://changesworlds.visualstudio.com'
[2016-11-05 07:06:23Z INFO ConfigurationManager] GetCredentialProvider
[2016-11-05 07:06:23Z INFO CommandSettings] Arg 'auth': ''
[2016-11-05 07:06:23Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-05 07:06:23Z INFO PromptManager] ReadValue
[2016-11-05 07:06:23Z INFO Terminal] WRITE: Enter authentication type (press enter for PAT) > 
[2016-11-05 07:06:23Z INFO Terminal] READ LINE
[2016-11-05 07:06:24Z INFO Terminal] Read value: ''
[2016-11-05 07:06:24Z INFO PromptManager] Falling back to the default: 'PAT'
[2016-11-05 07:06:24Z INFO ConfigurationManager] Creating credential for auth: PAT
[2016-11-05 07:06:24Z INFO CredentialManager] GetCredentialProvider
[2016-11-05 07:06:24Z INFO CredentialManager] Creating type PAT
[2016-11-05 07:06:24Z INFO CredentialManager] Creating credential type: PAT
[2016-11-05 07:06:24Z INFO PersonalAccessToken] EnsureCredential
[2016-11-05 07:06:24Z INFO CommandSettings] Arg 'token': ''
[2016-11-05 07:06:24Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-05 07:06:24Z INFO PromptManager] ReadValue
[2016-11-05 07:06:24Z INFO Terminal] WRITE: Enter personal access token > 
[2016-11-05 07:06:24Z INFO Terminal] READ SECRET
[2016-11-05 07:06:30Z INFO Terminal] Read value: '********'
[2016-11-05 07:06:30Z INFO PersonalAccessToken] GetVssCredentials
[2016-11-05 07:06:30Z INFO PersonalAccessToken] token retrieved: 52 chars
[2016-11-05 07:06:30Z INFO ConfigurationManager] cred retrieved
[2016-11-05 07:06:30Z INFO Terminal] WRITE LINE: Connecting to server ...
[2016-11-05 07:06:30Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-05 07:06:30Z ERR  Terminal] WRITE ERROR (exception):
[2016-11-05 07:06:30Z ERR  Terminal] System.TypeInitializationException: The type initializer for 'System.Net.Http.CurlHandler' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Http' threw an exception. ---> System.TypeInitializationException: The type initializer for 'HttpInitializer' threw an exception. ---> System.TypeInitializationException: The type initializer for 'CryptoInitializer' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'System.Security.Cryptography.Native': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.CryptoInitializer.EnsureOpenSslInitialized()
   at Interop.CryptoInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.CryptoInitializer.Initialize()
   at Interop.HttpInitializer..cctor()
   --- End of inner exception stack trace ---
   at Interop.HttpInitializer.Initialize()
   at Interop.Http..cctor()
   --- End of inner exception stack trace ---
   at Interop.Http.GetSupportedFeatures()
   at System.Net.Http.CurlHandler..cctor()
   --- End of inner exception stack trace ---
   at System.Net.Http.CurlHandler..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler..ctor(VssCredentials credentials, VssHttpRequestSettings settings)
   at Microsoft.VisualStudio.Services.Agent.Util.ApiUtil.CreateConnection(Uri serverUri, VssCredentials credentials, IEnumerable`1 additionalDelegatingHandler)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<TestConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
[2016-11-05 07:06:30Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2016-11-05 07:06:30Z INFO CommandSettings] Arg 'url': ''
[2016-11-05 07:06:30Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-05 07:06:30Z INFO PromptManager] ReadValue
[2016-11-05 07:06:30Z INFO Terminal] WRITE: Enter server URL > 
[2016-11-05 07:06:30Z INFO Terminal] READ LINE
[2016-11-05 07:06:36Z INFO Terminal] WRITE LINE: Exiting...
 ```

**Comment by bryanmacfarlane** [comment]
It's possible to have 1.0.2 but it not get linked properly.  I assure you, if you're getting that error, openssl is not configured on your OSX machine properly.  It's also not an issue with the agent, it's a net core issue

See this issue as well: https://github.com/Microsoft/vsts-agent/issues/470 

Here's net core as well: https://github.com/dotnet/core/
