### ISSUE TITLE
Getting HttpException while configure Agent

### ISSUE THREAD

**Issue by ErtugrulKra** [Microsoft/vsts-agent#683]
I'm downloaded agent from VSTS and copy files to server. 

Starting config.cmd, it ask my account url and PAT. I've entered valid token and url. Starting connect to server step and it's fall down error.

diag log is included below.

## **Agent version and platform**
Version of your agent: x64-2.109.1
<br>
OS of the machine running the agent? Windows
<br>
## **VSTS type and version**
VisualStudio.com  
<br>
https://fitsaklama.visualstudio.com
<br>
## **What's not working?** 
agent\config.cmd 
<br>
 
[2016-11-16 07:02:33Z INFO AgentProcess] Agent is built for Windows - win7-x64.
[2016-11-16 07:02:33Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 6.3.9600 .
[2016-11-16 07:02:33Z INFO AgentProcess] Version: 2.108.0
[2016-11-16 07:02:33Z INFO AgentProcess] Commit: c339954225fd3466d82c4038859ca71bc83cf819
[2016-11-16 07:02:33Z INFO AgentProcess] Culture: tr-TR
[2016-11-16 07:02:33Z INFO AgentProcess] UI Culture: en-US
[2016-11-16 07:02:33Z INFO HostContext] Well known directory 'Bin': 'F:\vsoagent-saklama\bin'
[2016-11-16 07:02:33Z INFO HostContext] Well known directory 'Root': 'F:\vsoagent-saklama'
[2016-11-16 07:02:33Z INFO AgentProcess] Validating directory permissions for: 'F:\vsoagent-saklama'
[2016-11-16 07:02:33Z INFO PowerShellExeUtil] Generation: '1'
[2016-11-16 07:02:33Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1', value name 'Install': '1'
[2016-11-16 07:02:33Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2016-11-16 07:02:33Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2016-11-16 07:02:33Z INFO PowerShellExeUtil] Generation: '3'
[2016-11-16 07:02:33Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3', value name 'Install': '1'
[2016-11-16 07:02:33Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '4.0'
[2016-11-16 07:02:33Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  'CDF'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  'v2.0.50727'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  'v3.0'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  'v3.5'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  'v4'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  'v4.0'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Version': '2.0.50727.4927'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Install': '1'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v2.0.50727'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Found version: 2.0.50727
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Version': '3.0.30729.4926'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Install': '1'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.0'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Found version: 3.0
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Version': '3.5.30729.4926'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Install': '1'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.5'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Found version: 3.5
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  'Client'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  'Full'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.6.01055'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '394271'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Type is System.Int32
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Interpreted version: 4.6.1
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.6.01055'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '394271'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Type is System.Int32
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Interpreted version: 4.6.1
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Found 5 versions:
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  2.0.50727
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  3.0
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  3.5
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  4.6.1
[2016-11-16 07:02:33Z INFO NetFrameworkUtil]  4.6.1
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.5'
[2016-11-16 07:02:33Z INFO CommandLineParser] Parse
[2016-11-16 07:02:33Z INFO CommandLineParser] Parsing 1 args
[2016-11-16 07:02:33Z INFO CommandLineParser] parsing argument
[2016-11-16 07:02:33Z INFO CommandLineParser] HasArgs: False
[2016-11-16 07:02:33Z INFO CommandLineParser] Adding Command: configure
[2016-11-16 07:02:33Z INFO AgentProcess] Arguments parsed
[2016-11-16 07:02:33Z INFO ProxyConfiguration] No proxy setting found.
[2016-11-16 07:02:33Z INFO Agent] ExecuteCommand
[2016-11-16 07:02:33Z INFO ConfigurationStore] currentAssemblyLocation: F:\vsoagent-saklama\bin\Agent.Listener.dll
[2016-11-16 07:02:33Z INFO ConfigurationStore] binPath: F:\vsoagent-saklama\bin
[2016-11-16 07:02:33Z INFO ConfigurationStore] RootFolder: F:\vsoagent-saklama
[2016-11-16 07:02:33Z INFO ConfigurationStore] ConfigFilePath: F:\vsoagent-saklama\.agent
[2016-11-16 07:02:33Z INFO ConfigurationStore] CredFilePath: F:\vsoagent-saklama\.credentials
[2016-11-16 07:02:33Z INFO ConfigurationStore] ServiceConfigFilePath: F:\vsoagent-saklama\.service
[2016-11-16 07:02:33Z INFO CommandSettings] Flag 'help': 'False'
[2016-11-16 07:02:33Z INFO CommandSettings] Flag 'version': 'False'
[2016-11-16 07:02:33Z INFO CommandSettings] Flag 'commit': 'False'
[2016-11-16 07:02:33Z INFO CommandSettings] Command 'configure': 'True'
[2016-11-16 07:02:33Z INFO ConfigurationManager] ConfigureAsync
[2016-11-16 07:02:33Z INFO ConfigurationStore] IsConfigured()
[2016-11-16 07:02:33Z INFO ConfigurationStore] IsConfigured: False
[2016-11-16 07:02:33Z INFO ConfigurationManager] Is configured: False
[2016-11-16 07:02:33Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.6'
[2016-11-16 07:02:33Z INFO CommandSettings] Flag 'machinegroup': 'False'
[2016-11-16 07:02:33Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2016-11-16 07:02:34Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2016-11-16 07:02:34Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.MachineGroupAgentConfigProvider, Agent.Listener
[2016-11-16 07:02:34Z INFO Terminal] WRITE LINE: 
[2016-11-16 07:02:34Z INFO Terminal] WRITE LINE: >> Connect:
[2016-11-16 07:02:34Z INFO Terminal] WRITE LINE: 
[2016-11-16 07:02:34Z INFO CommandSettings] Arg 'url': ''
[2016-11-16 07:02:34Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-16 07:02:34Z INFO PromptManager] ReadValue
[2016-11-16 07:02:34Z INFO Terminal] WRITE: Enter server URL > 
[2016-11-16 07:02:34Z INFO Terminal] READ LINE
[2016-11-16 07:02:54Z INFO Terminal] Read value: 'https://fitsaklama.visualstudio.com/'
[2016-11-16 07:02:54Z INFO ConfigurationManager] GetCredentialProvider
[2016-11-16 07:02:54Z INFO CommandSettings] Arg 'auth': ''
[2016-11-16 07:02:54Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-16 07:02:54Z INFO PromptManager] ReadValue
[2016-11-16 07:02:54Z INFO Terminal] WRITE: Enter authentication type (press enter for PAT) > 
[2016-11-16 07:02:54Z INFO Terminal] READ LINE
[2016-11-16 07:02:57Z INFO Terminal] Read value: ''
[2016-11-16 07:02:57Z INFO PromptManager] Falling back to the default: 'PAT'
[2016-11-16 07:02:57Z INFO ConfigurationManager] Creating credential for auth: PAT
[2016-11-16 07:02:57Z INFO CredentialManager] GetCredentialProvider
[2016-11-16 07:02:57Z INFO CredentialManager] Creating type PAT
[2016-11-16 07:02:57Z INFO CredentialManager] Creating credential type: PAT
[2016-11-16 07:02:57Z INFO PersonalAccessToken] EnsureCredential
[2016-11-16 07:02:57Z INFO CommandSettings] Arg 'token': ''
[2016-11-16 07:02:57Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-16 07:02:57Z INFO PromptManager] ReadValue
[2016-11-16 07:02:57Z INFO Terminal] WRITE: Enter personal access token > 
[2016-11-16 07:02:57Z INFO Terminal] READ SECRET
[2016-11-16 07:03:08Z INFO Terminal] Read value: '********'
[2016-11-16 07:03:08Z INFO PersonalAccessToken] GetVssCredentials
[2016-11-16 07:03:08Z INFO PersonalAccessToken] token retrieved: 52 chars
[2016-11-16 07:03:08Z INFO ConfigurationManager] cred retrieved
[2016-11-16 07:03:08Z INFO Terminal] WRITE LINE: Connecting to server ...
[2016-11-16 07:03:10Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-16 07:03:10Z ERR  Terminal] WRITE ERROR (exception):
[2016-11-16 07:03:10Z ERR  Terminal] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The parameter is incorrect
   at System.Net.Http.WinHttpAuthHelper.SetWinHttpCredential(SafeWinHttpHandle requestHandle, ICredentials credentials, Uri uri, UInt32 authScheme, UInt32 authTarget)
   at System.Net.Http.WinHttpAuthHelper.CheckResponseForAuthentication(WinHttpRequestState state, UInt32& proxyAuthScheme, UInt32& serverAuthScheme)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<TestConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
[2016-11-16 07:03:10Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2016-11-16 07:03:10Z INFO CommandSettings] Arg 'url': ''
[2016-11-16 07:03:10Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-16 07:03:10Z INFO PromptManager] ReadValue
[2016-11-16 07:03:10Z INFO Terminal] WRITE: Enter server URL > 
[2016-11-16 07:03:10Z INFO Terminal] READ LINE
[2016-11-16 07:03:14Z INFO Terminal] Read value: ''
[2016-11-16 07:03:14Z INFO Terminal] WRITE: Enter server URL > 
[2016-11-16 07:03:14Z INFO Terminal] READ LINE
[2016-11-16 07:03:14Z INFO Terminal] WRITE LINE: Exiting...

**Comment by TingluoHuang** [comment]
@ErtugrulKra Is your PAT expired?

**Comment by ErtugrulKra** [comment]
No, i've create new one, it's expire date 16-11-2017

**Comment by TingluoHuang** [comment]
@ErtugrulKra are you still hitting this, have you try use the PAT token clone a git repository in your account? The error you got indicate the PAT you use isn't valid.

**Comment by ErtugrulKra** [comment]
@TingluoHuang , yes i'm still getting this error. And my PAT is valid so i'm using same PAT with another agent and it works.

**Comment by TingluoHuang** [comment]
@ErtugrulKra are you able to to capture Fiddler trace while the error happen? you can send the trace to tihuang@microsoft.com in case the https trace might contains sensitive information.

**Comment by ErtugrulKra** [comment]
@TingluoHuang i've posted trace and attached some files about authentication url. You can check the trace.

Thank you.

**Comment by D3xt3rSM** [comment]
Hello, 

did you find the issue ?
I have the same problem now since 2.117.1 
Did an update of the agent. Agent failed to start/report back to VSTS.
Tried removing and readding the agent and getting stuck at the same step after entering the PAT.

Tried an older kit and that connects and generated the agent OK.

**Comment by TingluoHuang** [comment]
@D3xt3rSM can you share your agent diag log, VSTS account name, http trace with me?
[Instruction to get http trace](https://www.visualstudio.com/en-us/docs/build/troubleshooting#http-trace-logs)
Also, which agent version works for your?

**Comment by D3xt3rSM** [comment]
Hello, I had handy a v2.107. That works ok under same circumstances.

**Comment by TingluoHuang** [comment]
@D3xt3rSM can you share your agent diag log, VSTS account name, http trace with me?

**Comment by stephenmichaelf** [comment]
@ErtugrulKra @D3xt3rSM Please reopen if you are still having this issue.

**Comment by ErtugrulKra** [comment]
It was solved for me after agent update. thanks
