### ISSUE TITLE
How to bypass local addresses when using proxy?

### ISSUE THREAD

**Issue by jdshkolnik** [Microsoft/vsts-agent#698]
## **Agent version and platform**
2.109.2
<br>
OS of the machine running the agent? Windows Server 2008 R2
<br>
## **VSTS type and version**
Both VSO and On-Prem TFS
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2? 2017
<br>
## **What's not working?** 
I upgraded to TFS 2017 and brought my agents up to the latest version (they went from VSO to VSTS agent). Each agent failed to connect during configuration. I set them up on a box within the same domain as the TFS server. In short, it turns out the agent is always hitting the proxy. I will have the opposite problem with the hosted agent for my VSTS account because it'll have connectivity but won't be able to complete tasks using local HTTP within the domain.

**Comment by TingluoHuang** [comment]
@jdshkolnik are you using http proxy? did you configure your agent to talk through the proxy? can you share you agent diag log under `_diag` folder? log for both configurations, on-prem and vsts.

**Comment by jdshkolnik** [comment]
@TingluoHuang I did configure all that and it was working fine before upgrading. Post-upgrade it continued to use the proxy except this time it was exclusive i.e. no bypassing for local addresses. Here's one of the TFS attempts; I won't have time to mess with VSTS until tomorrow or Thursday.

```
[2016-11-29 22:34:36Z INFO AgentProcess] Agent is built for Windows - win7-x64.
[2016-11-29 22:34:36Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 6.1.7601 S.
[2016-11-29 22:34:36Z INFO AgentProcess] Version: 2.109.2
[2016-11-29 22:34:36Z INFO AgentProcess] Commit: 93b086c2c987581922fbc1bed6692eefa35df81c
[2016-11-29 22:34:36Z INFO AgentProcess] Culture: en-US
[2016-11-29 22:34:36Z INFO AgentProcess] UI Culture: en-US
[2016-11-29 22:34:36Z INFO HostContext] Well known directory 'Bin': 'I:\Agent\PROD-Jason_Bourne\bin'
[2016-11-29 22:34:36Z INFO HostContext] Well known directory 'Root': 'I:\Agent\PROD-Jason_Bourne'
[2016-11-29 22:34:36Z INFO AgentProcess] Validating directory permissions for: 'I:\Agent\PROD-Jason_Bourne'
[2016-11-29 22:34:37Z INFO PowerShellExeUtil] Generation: '1'
[2016-11-29 22:34:37Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1', value name 'Install': '1'
[2016-11-29 22:34:37Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2016-11-29 22:34:37Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2016-11-29 22:34:37Z INFO PowerShellExeUtil] Generation: '3'
[2016-11-29 22:34:37Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3', value name 'Install': '1'
[2016-11-29 22:34:37Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.0.10586.117'
[2016-11-29 22:34:37Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  'CDF'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  'v2.0.50727'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  'v3.0'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  'v3.5'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  'v4'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  'v4.0'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Version': '2.0.50727.5420'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v2.0.50727', value name 'Install': '1'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v2.0.50727'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Found version: 2.0.50727
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Version': '3.0.30729.5420'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.0', value name 'Install': '1'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.0'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Found version: 3.0
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Version': '3.5.30729.5420'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v3.5', value name 'Install': '1'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Testing directory: 'C:\Windows\Microsoft.NET\Framework64\v3.5'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Found version: 3.5
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  'Client'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  'Full'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.6.01055'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '394271'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Type is System.Int32
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Interpreted version: 4.6.1
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.6.01055'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '394271'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Type is System.Int32
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Interpreted version: 4.6.1
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Found 5 versions:
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  2.0.50727
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  3.0
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  3.5
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  4.6.1
[2016-11-29 22:34:37Z INFO NetFrameworkUtil]  4.6.1
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.5'
[2016-11-29 22:34:37Z INFO CommandLineParser] Parse
[2016-11-29 22:34:37Z INFO CommandLineParser] Parsing 1 args
[2016-11-29 22:34:37Z INFO CommandLineParser] parsing argument
[2016-11-29 22:34:37Z INFO CommandLineParser] HasArgs: False
[2016-11-29 22:34:37Z INFO CommandLineParser] Adding Command: configure
[2016-11-29 22:34:37Z INFO AgentProcess] Arguments parsed
[2016-11-29 22:34:37Z INFO ProxyConfiguration] Config proxy at: http://xx.xx.xx.xx:1234.
[2016-11-29 22:34:37Z INFO ProxyConfiguration] Config authentication proxy as: DOMAIN\admin.
[2016-11-29 22:34:37Z INFO Agent] ExecuteCommand
[2016-11-29 22:34:37Z INFO ConfigurationStore] currentAssemblyLocation: I:\Agent\PROD-Jason_Bourne\bin\Agent.Listener.dll
[2016-11-29 22:34:37Z INFO ConfigurationStore] binPath: I:\Agent\PROD-Jason_Bourne\bin
[2016-11-29 22:34:37Z INFO ConfigurationStore] RootFolder: I:\Agent\PROD-Jason_Bourne
[2016-11-29 22:34:37Z INFO ConfigurationStore] ConfigFilePath: I:\Agent\PROD-Jason_Bourne\.agent
[2016-11-29 22:34:37Z INFO ConfigurationStore] CredFilePath: I:\Agent\PROD-Jason_Bourne\.credentials
[2016-11-29 22:34:37Z INFO ConfigurationStore] ServiceConfigFilePath: I:\Agent\PROD-Jason_Bourne\.service
[2016-11-29 22:34:37Z INFO CommandSettings] Flag 'help': 'False'
[2016-11-29 22:34:37Z INFO CommandSettings] Flag 'version': 'False'
[2016-11-29 22:34:37Z INFO CommandSettings] Flag 'commit': 'False'
[2016-11-29 22:34:37Z INFO CommandSettings] Command 'configure': 'True'
[2016-11-29 22:34:37Z INFO ConfigurationManager] ConfigureAsync
[2016-11-29 22:34:37Z INFO ConfigurationStore] IsConfigured()
[2016-11-29 22:34:37Z INFO ConfigurationStore] IsConfigured: False
[2016-11-29 22:34:37Z INFO ConfigurationManager] Is configured: False
[2016-11-29 22:34:37Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.6'
[2016-11-29 22:34:37Z INFO CommandSettings] Flag 'machinegroup': 'False'
[2016-11-29 22:34:37Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2016-11-29 22:34:37Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2016-11-29 22:34:37Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.MachineGroupAgentConfigProvider, Agent.Listener
[2016-11-29 22:34:37Z INFO Terminal] WRITE LINE: 
[2016-11-29 22:34:37Z INFO Terminal] WRITE LINE: >> Connect:
[2016-11-29 22:34:37Z INFO Terminal] WRITE LINE: 
[2016-11-29 22:34:37Z INFO CommandSettings] Arg 'url': ''
[2016-11-29 22:34:37Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-29 22:34:37Z INFO PromptManager] ReadValue
[2016-11-29 22:34:37Z INFO Terminal] WRITE: Enter server URL > 
[2016-11-29 22:34:37Z INFO Terminal] READ LINE
[2016-11-29 22:34:47Z INFO Terminal] Read value: 'http://servername:8080/tfs'
[2016-11-29 22:34:47Z INFO ConfigurationManager] GetCredentialProvider
[2016-11-29 22:34:47Z INFO CommandSettings] Arg 'auth': ''
[2016-11-29 22:34:47Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-29 22:34:47Z INFO PromptManager] ReadValue
[2016-11-29 22:34:47Z INFO Terminal] WRITE: Enter authentication type (press enter for Integrated) > 
[2016-11-29 22:34:47Z INFO Terminal] READ LINE
[2016-11-29 22:34:48Z INFO Terminal] Read value: ''
[2016-11-29 22:34:48Z INFO PromptManager] Falling back to the default: 'Integrated'
[2016-11-29 22:34:48Z INFO ConfigurationManager] Creating credential for auth: Integrated
[2016-11-29 22:34:48Z INFO CredentialManager] GetCredentialProvider
[2016-11-29 22:34:48Z INFO CredentialManager] Creating type Integrated
[2016-11-29 22:34:48Z INFO CredentialManager] Creating credential type: Integrated
[2016-11-29 22:34:48Z INFO IntegratedCredential] GetVssCredentials
[2016-11-29 22:34:48Z INFO ConfigurationManager] cred retrieved
[2016-11-29 22:34:48Z INFO Terminal] WRITE LINE: Connecting to server ...
[2016-11-29 22:34:48Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-29 22:34:48Z ERR  Terminal] WRITE ERROR (exception):
[2016-11-29 22:34:48Z ERR  Terminal] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Forbidden
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<TestConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
[2016-11-29 22:34:48Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2016-11-29 22:34:48Z INFO CommandSettings] Arg 'url': ''
[2016-11-29 22:34:48Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-29 22:34:48Z INFO PromptManager] ReadValue
[2016-11-29 22:34:48Z INFO Terminal] WRITE: Enter server URL > 
[2016-11-29 22:34:48Z INFO Terminal] READ LINE
[2016-11-29 22:35:05Z INFO Terminal] Read value: 'http://servername:8080/tfs'
[2016-11-29 22:35:05Z INFO ConfigurationManager] GetCredentialProvider
[2016-11-29 22:35:05Z INFO CommandSettings] Arg 'auth': ''
[2016-11-29 22:35:05Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-29 22:35:05Z INFO PromptManager] ReadValue
[2016-11-29 22:35:05Z INFO Terminal] WRITE: Enter authentication type (press enter for Integrated) > 
[2016-11-29 22:35:05Z INFO Terminal] READ LINE
[2016-11-29 22:35:06Z INFO Terminal] Read value: ''
[2016-11-29 22:35:06Z INFO PromptManager] Falling back to the default: 'Integrated'
[2016-11-29 22:35:06Z INFO ConfigurationManager] Creating credential for auth: Integrated
[2016-11-29 22:35:06Z INFO CredentialManager] GetCredentialProvider
[2016-11-29 22:35:06Z INFO CredentialManager] Creating type Integrated
[2016-11-29 22:35:06Z INFO CredentialManager] Creating credential type: Integrated
[2016-11-29 22:35:06Z INFO IntegratedCredential] GetVssCredentials
[2016-11-29 22:35:06Z INFO ConfigurationManager] cred retrieved
[2016-11-29 22:35:06Z INFO Terminal] WRITE LINE: Connecting to server ...
[2016-11-29 22:35:06Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-29 22:35:06Z ERR  Terminal] WRITE ERROR (exception):
[2016-11-29 22:35:06Z ERR  Terminal] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Forbidden
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<TestConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
[2016-11-29 22:35:06Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2016-11-29 22:35:06Z INFO CommandSettings] Arg 'url': ''
[2016-11-29 22:35:06Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-29 22:35:06Z INFO PromptManager] ReadValue
[2016-11-29 22:35:06Z INFO Terminal] WRITE: Enter server URL > 
[2016-11-29 22:35:06Z INFO Terminal] READ LINE
[2016-11-29 22:35:15Z INFO Terminal] Read value: 'http://servername:8080/tfs'
[2016-11-29 22:35:15Z INFO ConfigurationManager] GetCredentialProvider
[2016-11-29 22:35:15Z INFO CommandSettings] Arg 'auth': ''
[2016-11-29 22:35:15Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-29 22:35:15Z INFO PromptManager] ReadValue
[2016-11-29 22:35:15Z INFO Terminal] WRITE: Enter authentication type (press enter for Integrated) > 
[2016-11-29 22:35:15Z INFO Terminal] READ LINE
[2016-11-29 22:35:16Z INFO Terminal] Read value: ''
[2016-11-29 22:35:16Z INFO PromptManager] Falling back to the default: 'Integrated'
[2016-11-29 22:35:16Z INFO ConfigurationManager] Creating credential for auth: Integrated
[2016-11-29 22:35:16Z INFO CredentialManager] GetCredentialProvider
[2016-11-29 22:35:16Z INFO CredentialManager] Creating type Integrated
[2016-11-29 22:35:16Z INFO CredentialManager] Creating credential type: Integrated
[2016-11-29 22:35:16Z INFO IntegratedCredential] GetVssCredentials
[2016-11-29 22:35:16Z INFO ConfigurationManager] cred retrieved
[2016-11-29 22:35:16Z INFO Terminal] WRITE LINE: Connecting to server ...
[2016-11-29 22:35:16Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-29 22:35:16Z ERR  Terminal] WRITE ERROR (exception):
[2016-11-29 22:35:16Z ERR  Terminal] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Forbidden
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<TestConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
[2016-11-29 22:35:16Z ERR  Terminal] WRITE ERROR: Failed to connect.  Try again or ctrl-c to quit
[2016-11-29 22:35:16Z INFO CommandSettings] Arg 'url': ''
[2016-11-29 22:35:16Z INFO CommandSettings] Flag 'unattended': 'False'
[2016-11-29 22:35:16Z INFO PromptManager] ReadValue
[2016-11-29 22:35:16Z INFO Terminal] WRITE: Enter server URL > 
[2016-11-29 22:35:16Z INFO Terminal] READ LINE
```

**Comment by TingluoHuang** [comment]
@jdshkolnik you are getting error: [2016-11-29 22:34:48Z ERR  Terminal] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Forbidden
which is 403, can you check whether you have permission to access your TFS server. have you try access your tfs server from browser on the same machine?
Also, what do you mean by bypass local proxy? are you configure the agent on the TFS server machine?

**Comment by jdshkolnik** [comment]
@TingluoHuang 

1. I do have access to it, can browse to it, ping it, whisper sweet nothings in its ear, etc. I was able to connect the agent by removing all proxy information from environment variables and the .proxy file in the agent folder but now I can't add it back or the agent goes red.
2. No, I'm configuring the agent on another server in the same domain as the TFS server.
3. Not all traffic has to go through a proxy. Go to internet options in your control panel and open up LAN settings in the Connections tab. In the bottom section reserved for proxy, you will see the option to "Bypass proxy server for local addresses".

![image](https://cloud.githubusercontent.com/assets/2047520/20738423/0101676c-b681-11e6-8162-67cf9af207bf.png)

**Comment by bryanmacfarlane** [comment]
@jdshkolnik - your solution is to *not* have proxy settings (env or file).  Your IE settings mean nothing.  In net core agent proxy settings are explicit via config.  In your case of agent talking to a server in intranet (domain or cross domain, not relevant), you shouldn't be going through a proxy.  Thus your request to bypass it. 

In other words, the way bypass the proxy is to not have proxy config settings.  Simply don't configure it.

**Comment by jdshkolnik** [comment]
@bryanmacfarlane What if you have a hosted VSTS agent that uses http for internal calls as well?

**Comment by bryanmacfarlane** [comment]
The agent doesn't make any internal calls.  Are you referring to a task or an ad-hoc script?

**Comment by jdshkolnik** [comment]
Yes. I also haven't yet tried using test agents but I don't know how related that is to this repo.

**Comment by bryanmacfarlane** [comment]
In that case, the agent just works by not configuring proxy (topic of issue).  If you have ad-hoc scripts - let's say ps1 scripts which use .net desktop which respects IE settings, then Bypass local in IE settings.  ?? But that's specific to the scripts and tools being called.  Does that work for you?

There's another level of problem of writing custom tasks.  Currently we "flow" proxy settings into th agent and source control (git, tfsvc).  There's a desire to flow them into the xplat node typescript tasks.  For powershell, as noted, it's desktop .net so IE settings prevail.  

Let us know if that works.

**Comment by jdshkolnik** [comment]
That sounds reasonable considering the limitations, thank you. Do you know if it's possible to control IE's bypass setting from an environment variable or .proxy file?

**Comment by bryanmacfarlane** [comment]
@TingluoHuang can follow up.  We will dig further because proxy has been a theme to get right.

**Comment by jdshkolnik** [comment]
Great. Hit me up if you need a guinea pig.

**Comment by bryanmacfarlane** [comment]
What we need is a complete scenario and config that's **hitting an issue**.  We're happy to answer the how do I questions and where are we going with it questions.   We've done alot of work and we need a specific repo to hone in on.

**Comment by TingluoHuang** [comment]
@jdshkolnik the agent is build on coreclr, which is a xplat clr. IE is using full desktop version clr, which only works on windows. Also, coreclr and desktop clr are working side by side, your IE proxy setting won't affect any application that build on coreclr. So change your IE proxy setting from the agent doesn't make any sense.

**Comment by jdshkolnik** [comment]
@TingluoHuang How does an on-prem agent get automatically updated to the latest version?

**Comment by TingluoHuang** [comment]
@jdshkolnik I guess you are asking connect to On-prem TFS server? your agent will auto update when you install next on-prem tfs updates, like 2017 Update 1.

**Comment by jdshkolnik** [comment]
@TingluoHuang Ok, I guess this would then be off-topic but I was wondering if there's a manual way to update the "embedded" agent version for on-prem. I know I can update each one manually but it'd be nice to just update the server version and let it update the rest.

**Comment by ericsciple** [comment]
@jdshkolnik no not currently

**Comment by TingluoHuang** [comment]
Close as the original problem has be solved.
