### ISSUE TITLE
Work folder prompt for VSTS

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/vsts-agent#717]
Hi All, 

**Agent version and platform**
I downloaded the Agent today, so I have the latest version. (Not sure which version that is).
OSX El Capitan

**VSTS type and version**
I am using the Free account from VSTS.

I have TACO installed and also the OpenSSL.

What's not working?
When I try to build a cordova app using the agent.  I am getting the error that the ios platform was already added.  Here is the full details.    Any idea what I have done wrong?  I am following these instructions https://www.visualstudio.com/en-us/docs/build/apps/mobile/cordova-build.
I have also installed the agent per the instructions on your site.    Thanks!

```
*****************************************************************************
Finishing: npm install
******************************************************************************
******************************************************************************
Starting: Cordova Build ios
******************************************************************************
==============================================================================
Task         : Cordova Build
Description  : Build a hybrid app project based on the Cordova CLI, Ionic CLI, TACO CLI, or other Cordova-compliant CLI
Version      : 1.3.9
Author       : Microsoft Corporation
Help         : [More Information](http://go.microsoft.com/fwlink/?LinkID=691186)
==============================================================================
DEVELOPER_DIR was undefined
DEVELOPER_DIR for build set to /Applications/Xcode8.0.app/Contents/Developer
Input to determineIdentity: {"cwd":"/Users/jordanmc/Documents/repos/myApp/1/s","unlockDefaultKeychain":false,"defaultKeychainPassword":"","p12":"/Users/jordanmc/Documents/repos/myApp/1/s/myApp/Certificates.p12","p12pwd":"tenbag17!"}
1 identity imported.
  1) D59EFA3A582BCCFCAFA887CAE04E16B5A7ABE956 "iPhone Developer: Jordan McDonald (YGKU7EWJD4)"
     1 valid identities found
    "/Users/jordanmc/Documents/repos/myApp/1/s/_tasktmp.keychain"
    "/Users/jordanmc/Library/Keychains/login.keychain"
determineIdentity result {"identity":"iPhone Developer: Jordan McDonald (YGKU7EWJD4)","foundIdentity":"iPhone Developer: Jordan McDonald (YGKU7EWJD4)","keychain":"/Users/jordanmc/Documents/repos/myApp/1/s/_tasktmp.keychain"}
Input to determineProfile: {"cwd":"/Users/jordanmc/Documents/repos/myApp/1/s","provProfileUuid":"","provProfilePath":"/Users/jordanmc/Documents/repos/myApp/1/s/myApp/Safetypin (5).mobileprovision","removeProfile":false}
Provisioning profile file found.
/Users/jordanmc/Documents/repos/myApp/1/s/myApp/Safetypin (5).mobileprovision has UUID of e43170aa-690e-4c33-8b06-5636466561d8
determineProfile result {"uuid":"e43170aa-690e-4c33-8b06-5636466561d8","foundUuid":"e43170aa-690e-4c33-8b06-5636466561d8"}
Module cache at /Users/jordanmc/.taco_home/node_modules
cordova already installed.
Adding Xcconfig update hook
Module cache at /Users/jordanmc/.taco_home/node_modules
cordova already installed.
Adding support plugin.
cp: no such file or directory: /Users/jordanmc/Documents/repos/myApp/resources/ios/icon/icon-40@3x.png
cp: no such file or directory: /Users/jordanmc/Documents/repos/myApp/resources/ios/icon/icon-83.5@2x.png
Removing Xcconfig update hook
{ CordovaError: Platform ios already added.
    at /Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/cordova-lib/src/cordova/platform.js:130:31
    at _fulfilled (/Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/q/q.js:749:13)
    at /Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/q/q.js:557:44
    at flush (/Users/jordanmc/.taco_home/node_modules/cordova/6.4.0/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
Task failed
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'CordovaError',
  message: 'Platform ios already added.',
  code: 0,
  context: undefined }
******************************************************************************
Finishing: Cordova Build ios
******************************************************************************
******************************************************************************
Starting: Post Job Cleanup
******************************************************************************
Cleaning any cached credential from repository: Safetypin (Git)
git remote set-url origin https://jordanmc.visualstudio.com/_git/Safetypin
git remote set-url --push origin https://jordanmc.visualstudio.com/_git/Safetypin
******************************************************************************
Finishing: Post Job Cleanup
******************************************************************************
******************************************************************************
Finishing: Build
******************************************************************************

```

**Comment by ericsciple** [comment]
@jrmcdona this seems to be an issue with the Cordova Build task and does not seem to be related to the agent infrastructure. i dont know where is the correct location for that task. you could try leaving a comment on the marketplace extension.
