### ISSUE TITLE
Works with Network Service but not with local account

### ISSUE THREAD

**Issue by stibay** [Microsoft/vsts-agent#734]
Agent: Version: 2.110.0
Windows Server 2008 R2
Team Foundation Server 2017 RTW

Trying to get the agent to use a local build account instead of the NT AUTHORITY/NETWORK SERVICE
Just getting Waiting for an available agent. Current queue position is 1.

Whenever I try to use a local account on the build server instead of the Network Service account I get the following error in the logs.

If I use the Network service account it works but then I am getting problems with permissions in my build and release process.

This worked with the agent version that came with TFS 2015 but I did not find any place where I could download this agent. Is there a link for that so I could test that? Since the problems started when I updated the agent.

[2016-12-23 10:46:24Z ERR  JobDispatcher] Catch exception during renew agent jobrequest 863.
[2016-12-23 10:46:24Z ERR  JobDispatcher] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.JobDispatcher.<RenewJobRequestAsync>d__12.MoveNext()
[2016-12-23 10:46:24Z INFO JobDispatcher] Retrying lock renewal for jobrequest 863. Job is still locked for: 10 seconds.

**Comment by ericsciple** [comment]
@stibay when you changed account, did you add the user to the local group created for the agent? e.g. VSTS_AgentService_G_____?

what kind of permissions issues are you running into? the service that the agent is running as is not used to communicate back to TFS. it is only used to decrypt the creds to listen to the queue. when a build job is run, time-bombed credentials for that job are sent down in the job message, for the TFS-built-in Project Collection Build Service or Project Build Service identity (depending on the authorization settings for the build - on the general tab i think). so depending on where you are running into auth issues, you may need to grant additional permissions to one of those identities within TFS.

or are your permissions issues related to dropping files on UNC shares? or an endpoint on your network and passing default credentials? if so, then the service account running the agent does come into play.

what do you mean by local build account? do you mean a domain account? or an account that exists only on the machine?

**Comment by stibay** [comment]
On the virtual machine where TFS is running we have always had an local account on the machine, this is in the TFS_APPTIER_SERVICE_WPG group which is running on the machine's local domain.

Maybe this is not needed anymore because there is only a couple of issues by using the network account.

Should the TFS Service Account in the admin console also be set to NT AUTHORITY\NETWORK SERVICE?

In the build prosess I am getting an error from npm since its not running node-gyp rebuild as admin. 

MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [C:\agent\_work\1\s\..\..\node_modules\gulp-angular-protractor\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil\build\binding.sln]

But this is only a problem on the first build and I can solve this by running npm install again in the solution. (npm install --global windows-build-tools does not help)

The other issue is during release where I am running the deploy I have to set the website name in IIS otherwise it's creating it in a subfolder - /Y "-setParam:name='IIS Web Application Name',value='Default Web Site'"

```
2016-12-30T17:04:06.2918718Z Trace Error:
2016-12-30T17:04:06.2918718Z 
2016-12-30T17:04:06.2918718Z msdeploy.exe Error: 0 : 
2016-12-30T17:04:06.2918718Z Trace Error:
2016-12-30T17:04:06.2918718Z 
2016-12-30T17:04:06.2918718Z Skipping backup because it failed due to the following error 'System.UnauthorizedAccessException: Filename: redirection.config
2016-12-30T17:04:06.2918718Z Error: Cannot read configuration file due to insufficient permissions
2016-12-30T17:04:06.2918718Z 
2016-12-30T17:04:06.2918718Z 
2016-12-30T17:04:06.2918718Z    at Microsoft.Web.Administration.Interop.AppHostWritableAdminManager.GetAdminSection(String bstrSectionName, String bstrSectionPath)
2016-12-30T17:04:06.2918718Z    at Microsoft.Web.Administration.Configuration.GetSectionInternal(ConfigurationSection section, String sectionPath, String locationPath)
2016-12-30T17:04:06.2918718Z    at Microsoft.Web.Deployment.BackupConfigHelper.InitializeServerBackupSettings()
2016-12-30T17:04:06.2918718Z    at Microsoft.Web.Deployment.BackupConfigHelper.ResetCaching()
2016-12-30T17:04:06.2918718Z    at Microsoft.Web.Deployment.BackupConfigHelper.get_TurnedOn()
2016-12-30T17:04:06.2918718Z    at Microsoft.Web.Deployment.BackupManager.ProceedWithBackup(DeploymentObject depObj, Boolean ignoreEnabled, BackupSettings& settings, Boolean suppressLogging)'.
2016-12-30T17:04:06.2918718Z 
2016-12-30T17:04:06.2918718Z 
2016-12-30T17:04:06.4322727Z Info: Adding sitemanifest (sitemanifest).
2016-12-30T17:04:06.4634729Z Info: Creating application (Default Web Site)
2016-12-30T17:04:06.4790730Z Error: An error occurred when reading the IIS Configuration File 'MACHINE/REDIRECTION'. The identity performing the operation was 'NT AUTHORITY\NETWORK SERVICE'.
2016-12-30T17:04:06.4790730Z Error: Filename: \\?\C:\Windows\system32\inetsrv\config\redirection.config
2016-12-30T17:04:06.4790730Z Error: Cannot read configuration file due to insufficient permissions
2016-12-30T17:04:06.4790730Z 
2016-12-30T17:04:06.4790730Z 
2016-12-30T17:04:06.4790730Z Error count: 1.

```

**Comment by ericsciple** [comment]
This repo is for the agent infrastructure only. The agent should not encounter an error renewing the lock and you should be able to successfully run the agent as a Windows service using a Windows built-in service account (e.g. network service), a local machine account, or domain account. During configure, you can choose whatever account, but afterward changing it in services.msc is not sufficient. Adding the account to VSTS_AgentService_G will probably suffice. If not then unconfiguring the agent and reconfiguring would be good to try.

Also make sure you have the [prereqs](https://github.com/Microsoft/vsts-agent/blob/master/docs/start/envwin.md) (e.g. updated c runtime)

The other issues sound like they are specific to individual build tasks or custom scripts during your build. The repo for the in-the-box tasks are [here](https://github.com/Microsoft/vsts-agent). Otherwise the agent dumps the metadata about each task to the build log, so you might be able to track down the task author from that info.

**Comment by stibay** [comment]
Ok, yes I will do that. Thanks alot for your help.
