### ISSUE TITLE
 VS30063: You are not authorized to access http://mytfs.com:8080 

### ISSUE THREAD

**Issue by akolodkin** [Microsoft/vsts-agent#765]
## **Agent version and platform**
Version of your agent? vsts-agent-ubuntu.16.04-x64-2.109.2
<br>
OS of the machine running the agent? Ubuntu 16
<br>
## **VSTS type and version**
 On-Prem TFS 2015?
<br>
If On-Prem TFS, which release, 2015 RTM?
## **What's not working?** 

TFS agent receives job but failed during build process due to authorization issue. 
Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access
<br>
## **Agent and Worker's diag log**
cat Worker_20170119-230416-utc.log
[2017-01-19 23:04:16Z INFO Program] Version: 2.109.2
[2017-01-19 23:04:16Z INFO Program] Commit: 93b086c2c987581922fbc1bed6692eefa35df81c
[2017-01-19 23:04:16Z INFO Program] Culture: en-US
[2017-01-19 23:04:16Z INFO Program] UI Culture: en-US
[2017-01-19 23:04:16Z INFO ProxyConfiguration] No proxy setting found.
[2017-01-19 23:04:16Z INFO Worker] Waiting to receive the job message from the channel.
[2017-01-19 23:04:16Z INFO Worker] Message received.
[2017-01-19 23:04:17Z INFO Worker] Job message:
 {
  "tasks": [],
  "requestId": 1858,
  "lockToken": "00000000-0000-0000-0000-000000000000",
  "lockedUntil": "0001-01-01T00:00:00",
  "messageType": "JobRequest",
  "plan": {
    "scopeIdentifier": "b8b04151-43da-4647-b658-ceafe5d849c0",
    "planType": "Build",
    "version": 5,
    "planId": "74ff4840-4e7b-49ba-9c38-bd60a475f1ec",
    "artifactUri": "vstfs:///Build/Build/29046",
    "artifactLocation": null
  },
  "timeline": {
    "id": "4dd2d17f-fe3f-47db-9eba-d2de771159fc",
    "changeId": 1,
    "location": null
  },
  "jobId": "47b0a658-0942-4816-8924-27f48d566e97",
  "jobName": "Build",
  "environment": {
    "endpoints": [
      {
        "data": {
          "repositoryId": "193ddc5c-9854-46e1-ab9d-d86db45d5e4b",
          "rootFolder": null,
          "clean": "true",
          "checkoutSubmodules": "False"
        },
        "name": "MyProject",
        "type": "TfsGit",
        "url": "http://tfsd.myftp.com:8080/tfs/DefaultCollection/GitTeamProject/_git/MyProject",
        "authorization": {
          "parameters": {
            "AccessToken": "********"
          },
          "scheme": "OAuth"
        },
        "isReady": false
      }
    ],
    "mask": [
      {
        "type": "regex",
        "value": ********
      }
    ],
    "variables": {
      "system.definitionId": "343",
      "build.definitionName": "myproject_test",
      "build.definitionVersion": "3",
      "build.queuedBy": "SVC_TFS_DEV",
      "build.queuedById": "20741736-b0d4-4417-b655-3b978b29e99e",
      "build.requestedFor": "SVC_TFS_DEV",
      "build.requestedForId": "20741736-b0d4-4417-b655-3b978b29e99e",
      "build.sourceVersion": "57a95e03c98b8b9ff591afbc495bd3f89f93c7d8",
      "build.sourceBranch": "refs/heads/myproject_build",
      "build.sourceBranchName": "myproject_build",
      "system.debug": "false",
      "build.buildId": "29046",
      "build.buildUri": "vstfs:///Build/Build/29046",
      "build.buildNumber": "29046",
      "build.containerId": "50275",
      "system": "build",
      "system.hosttype": "build",
      "system.collectionId": "8686a9d8-193a-4b85-a26c-efcec24b91c0",
      "system.teamProjectId": "b8b04151-43da-4647-b658-ceafe5d849c0",
      "system.teamProject": "GitTeamProject",
      "system.culture": "en-US",
      "system.teamFoundationCollectionUri": "http://tfsd.myftp.com:8080/tfs/DefaultCollection/",
      "system.taskDefinitionsUri": "http://tfsd.myftp.com:8080/tfs/DefaultCollection/",
      "build.sourceVersionAuthor": " ",
      "build.sourceVersionMessage": "Merge branch 'development' into myproject_build"
    },
    "systemConnection": {
      "data": {
        "ServerId": "8686a9d8-193a-4b85-a26c-efcec24b91c0",
        "ServerName": "DefaultCollection"
      },
      "name": "SystemVssConnection",
      "url": "http://tfsd.myftp.com:8080/tfs/DefaultCollection/",
      "authorization": {
        "parameters": {
          "AccessToken": "********"
        },
        "scheme": "OAuth"
      },
      "isReady": false
    }
  }
}
[2017-01-19 23:04:17Z INFO JobRunner] Job ID 47b0a658-0942-4816-8924-27f48d566e97
[2017-01-19 23:04:17Z INFO ConfigurationStore] currentAssemblyLocation: /tfs/bin/Agent.Worker.dll
[2017-01-19 23:04:17Z INFO ConfigurationStore] binPath: /tfs/bin
[2017-01-19 23:04:17Z INFO ConfigurationStore] RootFolder: /tfs
[2017-01-19 23:04:17Z INFO ConfigurationStore] ConfigFilePath: /tfs/.agent
[2017-01-19 23:04:17Z INFO ConfigurationStore] CredFilePath: /tfs/.credentials
[2017-01-19 23:04:17Z INFO ConfigurationStore] ServiceConfigFilePath: /tfs/.service
[2017-01-19 23:04:17Z INFO JobRunner] Ensure endpoint url match config url base. http://tfsd.myftp.com:8080/tfs/DefaultCollection/GitTeamProject/_git/myproject
[2017-01-19 23:04:17Z INFO JobRunner] Ensure System.TaskDefinitionsUrl match config url base. http://tfsd.myftp.com:8080/tfs/DefaultCollection/
[2017-01-19 23:04:17Z INFO JobRunner] Ensure System.TFCollectionUrl match config url base. http://tfsd.myftp.com:8080/tfs/DefaultCollection/
[2017-01-19 23:04:17Z INFO JobRunner] Ensure SystemConnection url match config url base. http://tfsd.myftp.com:8080/tfs/DefautCollection/
[2017-01-19 23:04:17Z INFO JobRunner] Ensure System.TFServerUrl match config url base. http://tfsd.myftp.com:8080/tfs/DefaultCollection/
[2017-01-19 23:04:17Z INFO JobRunner] Creating job server with URL: http://tfsd.myftp.com:8080/tfs/DefaultCollection/
[2017-01-19 23:04:18Z INFO Worker] Listening for cancel message from the channel.
[2017-01-19 23:04:18Z INFO Worker] Waiting for the job to complete or for a cancel message from the channel.
[2017-01-19 23:04:18Z INFO Worker] Job completed.
[2017-01-19 23:04:18Z ERR  Program] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not a                                  uthorized to access http://tfsd.myftp.com:8080.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.ThrottlingReportHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.JobServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Worker.<RunAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Program.<MainAsync>d__1.MoveNext()

**Comment by TingluoHuang** [comment]
@akolodkin 
1. Have you try configure a windows agent to the same TFS service? I want to understand whether this is an issue for Non-windows platform only
2. If you have access to your TFS AT, can you check the event log? there should be an error correspond to the client side error.

**Comment by TingluoHuang** [comment]
Please reopen if you still hit this problem.
