### ISSUE TITLE
Agent doesn't start after docker stop/start

### ISSUE THREAD

**Issue by Rurouni** [Microsoft/vsts-agent#781]
## **Agent version and platform**
2.111.1
ubuntu.16.04(as docker container)
## **VSTS type and version**
VisualStudio.com
http://mediatonic-catapult.visualstudio.com
## **What's not working?** 
I am running agent as docker container using official image [vsts-agent-docker](https://github.com/microsoft/vsts-agent-docker/blob/21a1290f988e996b3737803ec58b13c79209bdce/ubuntu/16.04/docker/1.12.1/standard/Dockerfile)
`docker run -d --restart=always -e VSTS_ACCOUNT=mediatonic-catapult -e VSTS_TOKEN=**** -e VSTS_AGENT='$(hostname)-agent' -e VSTS_POOL=Default -e VSTS_WORK='/var/vsts/cat-agent' -v /var/run/docker.sock:/var/run/docker.sock -v /var/vsts:/var/vsts -v /.nuget:/.nuget -v /.local:/.local  microsoft/vsts-agent:ubuntu-16.04-docker-1.12.1-standard`
First time it works fine but after restarting host vm or just doing docker stop/start agent quits immediately with `An error occurred: Not configured`

## **Agent and Worker's diag log**
```
[2017-02-06 12:13:11Z INFO AgentProcess] Agent is built for Linux - ubuntu.16.04-x64.
[2017-02-06 12:13:11Z INFO AgentProcess] RuntimeInformation: Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017.
[2017-02-06 12:13:11Z INFO AgentProcess] Version: 2.111.1
[2017-02-06 12:13:11Z INFO AgentProcess] Commit: f2b339f02e4065d8500c918d883f50c347b7ba57
[2017-02-06 12:13:11Z INFO AgentProcess] Culture:
[2017-02-06 12:13:11Z INFO AgentProcess] UI Culture:
[2017-02-06 12:13:11Z INFO HostContext] Well known directory 'Bin': '/vsts/agent/bin'
[2017-02-06 12:13:11Z INFO HostContext] Well known directory 'Root': '/vsts/agent'
[2017-02-06 12:13:11Z INFO AgentProcess] Validating directory permissions for: '/vsts/agent'
[2017-02-06 12:13:11Z INFO CommandLineParser] Parse
[2017-02-06 12:13:11Z INFO CommandLineParser] Parsing 1 args
[2017-02-06 12:13:11Z INFO CommandLineParser] parsing argument
[2017-02-06 12:13:11Z INFO CommandLineParser] HasArgs: False
[2017-02-06 12:13:11Z INFO CommandLineParser] Adding Command: run
[2017-02-06 12:13:11Z INFO AgentProcess] Arguments parsed
[2017-02-06 12:13:11Z INFO ProxyConfiguration] No proxy setting found.
[2017-02-06 12:13:11Z INFO Agent] ExecuteCommand
[2017-02-06 12:13:11Z INFO ConfigurationStore] currentAssemblyLocation: /vsts/agent/bin/Agent.Listener.dll
[2017-02-06 12:13:11Z INFO ConfigurationStore] binPath: /vsts/agent/bin
[2017-02-06 12:13:11Z INFO ConfigurationStore] RootFolder: /vsts/agent
[2017-02-06 12:13:11Z INFO ConfigurationStore] ConfigFilePath: /vsts/agent/.agent
[2017-02-06 12:13:11Z INFO ConfigurationStore] CredFilePath: /vsts/agent/.credentials
[2017-02-06 12:13:11Z INFO ConfigurationStore] ServiceConfigFilePath: /vsts/agent/.service
[2017-02-06 12:13:11Z INFO CommandSettings] Flag 'help': 'False'
[2017-02-06 12:13:11Z INFO CommandSettings] Flag 'version': 'False'
[2017-02-06 12:13:11Z INFO CommandSettings] Flag 'commit': 'False'
[2017-02-06 12:13:11Z INFO CommandSettings] Command 'configure': 'False'
[2017-02-06 12:13:11Z INFO CommandSettings] Command 'remove': 'False'
[2017-02-06 12:13:11Z INFO ConfigurationManager] LoadSettings
[2017-02-06 12:13:11Z INFO ConfigurationStore] IsConfigured()
[2017-02-06 12:13:11Z INFO ConfigurationStore] IsConfigured: False
[2017-02-06 12:13:11Z INFO ConfigurationManager] Is configured: False
[2017-02-06 12:13:12Z ERR  Terminal] WRITE ERROR: An error occurred: Not configured
[2017-02-06 12:13:12Z ERR  AgentProcess] System.InvalidOperationException: Not configured
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.LoadSettings()
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Program.<MainAsync>d__1.MoveNext()
```

**Comment by TingluoHuang** [comment]
@Rurouni 
seems like the image will unconfig agent on SIGINT/SIGTERM
https://github.com/Microsoft/vsts-agent-docker/blob/c124d309a6ba1eece47bca1aa70f58f58bec8205/ubuntu/14.04/2.106.0/start.sh#L26

**Comment by AmitBhatnagar24** [comment]
I seem to have had the same problem with the same configuration as the OP, however, when I did a docker ps, the status was "Restarting 2 hours". 

Is this issue closed because it is fixed? Where is the documentation on a proper docker run command that ensures restart capabilities?

**Comment by Rurouni** [comment]
I don't think they fixed it, looks more like hey it's not our problem... in the end I have abandoned idea with docker restart and went for init script that restarts image with docker run -rm ...
