### ISSUE TITLE
Can't configure the agent via parameters when pool name contains space

### ISSUE THREAD

**Issue by gabrielweyer** [Microsoft/vsts-agent#802]
## Agent version and platform
Version of your agent? **v2.111.1**
OS of the machine running the agent? **Ubuntu 16.04-LTS (default Azure VM)**
## VSTS type and version
VisualStudio.com or On-Prem TFS? **VSTS**
If VisualStudio.com, what is your account name? **https://gabrielweyer.visualstudio.com/**
## What's not working?
When running the command:
```
./config.sh\
    --url $https://gabrielweyer.visualstudio.com/\
    --agent "docker-linux"\
    --pool "Docker Linux"\
    --acceptteeeula\
    --auth PAT\
    --token <removed>\
    --replace\
    --unattended 1>/dev/null
```
I get the following error:
```
Agent pool not found: 'Docker'
```
If I configure it in interactive mode via the prompt it works. It seems to me as the parser is stopping as the first space it's encountering.
## Agent and Worker's diag log
I found only one log filed under `_diag`, it was called `Agent_20170218-015444-utc.log`:
```
[2017-02-18 01:54:44Z INFO AgentProcess] Agent is built for Linux - ubuntu.16.04-x64.
[2017-02-18 01:54:44Z INFO AgentProcess] RuntimeInformation: Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017.
[2017-02-18 01:54:44Z INFO AgentProcess] Version: 2.111.1
[2017-02-18 01:54:44Z INFO AgentProcess] Commit: f2b339f02e4065d8500c918d883f50c347b7ba57
[2017-02-18 01:54:44Z INFO AgentProcess] Culture: en-US
[2017-02-18 01:54:44Z INFO AgentProcess] UI Culture: en-US
[2017-02-18 01:54:44Z INFO HostContext] Well known directory 'Bin': '/home/LTDbXAgDKD/myagent/bin'
[2017-02-18 01:54:44Z INFO HostContext] Well known directory 'Root': '/home/LTDbXAgDKD/myagent'
[2017-02-18 01:54:44Z INFO AgentProcess] Validating directory permissions for: '/home/LTDbXAgDKD/myagent'
[2017-02-18 01:54:45Z INFO CommandLineParser] Parse
[2017-02-18 01:54:45Z INFO CommandLineParser] Parsing 15 args
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: False
[2017-02-18 01:54:45Z INFO CommandLineParser] Adding Command: configure
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] arg: url
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] Adding option 'url': 'https://gabrielweyer.visualstudio.com/'
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] arg: agent
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] Adding option 'agent': 'docker-linux'
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] arg: pool
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] Adding option 'pool': 'Docker'
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] arg: acceptteeeula
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] arg: auth
[2017-02-18 01:54:45Z INFO CommandLineParser] Adding flag: acceptteeeula
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] Adding option 'auth': 'PAT'
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] arg: token
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] Adding option 'token': '********'
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] arg: replace
[2017-02-18 01:54:45Z INFO CommandLineParser] parsing argument
[2017-02-18 01:54:45Z INFO CommandLineParser] HasArgs: True
[2017-02-18 01:54:45Z INFO CommandLineParser] arg: unattended
[2017-02-18 01:54:45Z INFO CommandLineParser] Adding flag: replace
[2017-02-18 01:54:45Z INFO AgentProcess] Arguments parsed
[2017-02-18 01:54:45Z INFO ProxyConfiguration] No proxy setting found.
[2017-02-18 01:54:45Z INFO Agent] ExecuteCommand
[2017-02-18 01:54:45Z INFO ConfigurationStore] currentAssemblyLocation: /home/LTDbXAgDKD/myagent/bin/Agent.Listener.dll
[2017-02-18 01:54:45Z INFO ConfigurationStore] binPath: /home/LTDbXAgDKD/myagent/bin
[2017-02-18 01:54:45Z INFO ConfigurationStore] RootFolder: /home/LTDbXAgDKD/myagent
[2017-02-18 01:54:45Z INFO ConfigurationStore] ConfigFilePath: /home/LTDbXAgDKD/myagent/.agent
[2017-02-18 01:54:45Z INFO ConfigurationStore] CredFilePath: /home/LTDbXAgDKD/myagent/.credentials
[2017-02-18 01:54:45Z INFO ConfigurationStore] ServiceConfigFilePath: /home/LTDbXAgDKD/myagent/.service
[2017-02-18 01:54:45Z INFO CommandSettings] Flag 'help': 'False'
[2017-02-18 01:54:45Z INFO CommandSettings] Flag 'version': 'False'
[2017-02-18 01:54:45Z INFO CommandSettings] Flag 'commit': 'False'
[2017-02-18 01:54:45Z INFO CommandSettings] Command 'configure': 'True'
[2017-02-18 01:54:45Z INFO ConfigurationManager] ConfigureAsync
[2017-02-18 01:54:45Z INFO ConfigurationStore] IsConfigured()
[2017-02-18 01:54:45Z INFO ConfigurationStore] IsConfigured: False
[2017-02-18 01:54:45Z INFO ConfigurationManager] Is configured: False
[2017-02-18 01:54:46Z INFO Terminal] WRITE LINE:
[2017-02-18 01:54:46Z INFO Terminal] WRITE LINE: >> End User License Agreements:
[2017-02-18 01:54:46Z INFO Terminal] WRITE LINE:
[2017-02-18 01:54:46Z INFO Terminal] WRITE LINE: Building sources from a TFVC repository requires accepting the Team Explorer Everywhere End User License Agreement. This step is not required for building sources from Git repositories.

A copy of the Team Explorer Everywhere license agreement can be found at:
  /home/LTDbXAgDKD/myagent/externals/tee/license.html
[2017-02-18 01:54:46Z INFO Terminal] WRITE LINE:
[2017-02-18 01:54:46Z INFO CommandSettings] Flag 'acceptteeeula': 'True'
[2017-02-18 01:54:46Z INFO CommandSettings] Flag 'machinegroup': 'False'
[2017-02-18 01:54:46Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2017-02-18 01:54:46Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2017-02-18 01:54:46Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.MachineGroupAgentConfigProvider, Agent.Listener
[2017-02-18 01:54:46Z INFO Terminal] WRITE LINE:
[2017-02-18 01:54:46Z INFO Terminal] WRITE LINE: >> Connect:
[2017-02-18 01:54:46Z INFO Terminal] WRITE LINE:
[2017-02-18 01:54:46Z INFO CommandSettings] Arg 'url': 'https://gabrielweyer.visualstudio.com/'
[2017-02-18 01:54:46Z INFO CommandSettings] Remove url from Arg dictionary.
[2017-02-18 01:54:47Z INFO ConfigurationManager] GetCredentialProvider
[2017-02-18 01:54:47Z INFO CommandSettings] Arg 'auth': 'PAT'
[2017-02-18 01:54:47Z INFO CommandSettings] Remove auth from Arg dictionary.
[2017-02-18 01:54:47Z INFO ConfigurationManager] Creating credential for auth: PAT
[2017-02-18 01:54:47Z INFO CredentialManager] GetCredentialProvider
[2017-02-18 01:54:47Z INFO CredentialManager] Creating type PAT
[2017-02-18 01:54:47Z INFO CredentialManager] Creating credential type: PAT
[2017-02-18 01:54:47Z INFO PersonalAccessToken] EnsureCredential
[2017-02-18 01:54:47Z INFO CommandSettings] Arg 'token': '********'
[2017-02-18 01:54:47Z INFO CommandSettings] Remove token from Arg dictionary.
[2017-02-18 01:54:47Z INFO PersonalAccessToken] GetVssCredentials
[2017-02-18 01:54:47Z INFO PersonalAccessToken] token retrieved: 52 chars
[2017-02-18 01:54:47Z INFO ConfigurationManager] cred retrieved
[2017-02-18 01:54:47Z INFO Terminal] WRITE LINE: Connecting to server ...
[2017-02-18 01:54:51Z INFO ConfigurationManager] Test Connection complete.
[2017-02-18 01:54:51Z INFO RSAFileKeyManager] Creating new RSA key using 2048-bit key length
[2017-02-18 01:54:52Z INFO RSAFileKeyManager] Successfully saved RSA key parameters to file /home/LTDbXAgDKD/myagent/.credentials_rsaparams
[2017-02-18 01:54:52Z INFO WhichUtil] Which: 'chmod'
[2017-02-18 01:54:52Z INFO WhichUtil] Location: '/bin/chmod'
[2017-02-18 01:54:52Z INFO ProcessInvoker] Starting process:
[2017-02-18 01:54:52Z INFO ProcessInvoker]   File name: '/bin/chmod'
[2017-02-18 01:54:52Z INFO ProcessInvoker]   Arguments: '600 /home/LTDbXAgDKD/myagent/.credentials_rsaparams'
[2017-02-18 01:54:52Z INFO ProcessInvoker]   Working directory: '/home/LTDbXAgDKD/myagent'
[2017-02-18 01:54:52Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-18 01:54:52Z INFO ProcessInvoker]   Encoding web name:  ; code page: ''
[2017-02-18 01:54:52Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-02-18 01:54:52Z INFO ProcessInvoker] Process started with process id 2424, waiting for process exit.
[2017-02-18 01:54:52Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.2235898.
[2017-02-18 01:54:52Z INFO RSAFileKeyManager] Successfully set permissions for RSA key parameters file /home/LTDbXAgDKD/myagent/.credentials_rsaparams
[2017-02-18 01:54:52Z INFO Terminal] WRITE LINE:
[2017-02-18 01:54:52Z INFO Terminal] WRITE LINE: >> Register Agent:
[2017-02-18 01:54:52Z INFO Terminal] WRITE LINE:
[2017-02-18 01:54:52Z INFO CommandSettings] Arg 'pool': 'Docker'
[2017-02-18 01:54:52Z INFO CommandSettings] Remove pool from Arg dictionary.
[2017-02-18 01:54:52Z INFO CommandSettings] Flag 'unattended': 'True'
[2017-02-18 01:54:52Z ERR  Agent] Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentPoolNotFoundException: Agent pool not found: 'Docker'
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<GetPoolIdAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<GetPoolId>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext()
[2017-02-18 01:54:52Z ERR  Terminal] WRITE ERROR: Agent pool not found: 'Docker'
```

**Comment by ericsciple** [comment]
the fix is in master but hasnt been released yet

**Comment by ericsciple** [comment]
commit https://github.com/Microsoft/vsts-agent/commit/377d695c400474b9e44233f4fe0714ec8b836500
