### ISSUE TITLE
Windows 2012 R2 - Agent can't authenticate to On-Prem TFS 2017 Update 1 RC2 - Git fetch failed with exit code: 128

### ISSUE THREAD

**Issue by jmackay** [Microsoft/vsts-agent#813]
## **Have you try trouble shooting doc?**
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting

Yes, also posted here: 

http://stackoverflow.com/questions/42263725/tfs-build-agent-failing-to-connect-to-https-git-in-tfs-2017-when-running-as-serv

## **Agent version and platform**
Version of your agent? 2.112.0
<br>
OS of the machine running the agent? Windows Server 2012 R2
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS? On-Prem TFS
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
2017 Update 1 RC2
<br>
## **What's not working?** 

<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

AGENT:
2017-02-22 05:24:27Z INFO Terminal] WRITE LINE: Connecting to the server.
[2017-02-22 05:24:27Z INFO MessageListener] Attempt to create session.
[2017-02-22 05:24:27Z INFO MessageListener] Connecting to the Agent Server...
[2017-02-22 05:24:28Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\agent\.credentials_rsaparams
[2017-02-22 05:24:28Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\agent\.credentials_rsaparams
[2017-02-22 05:24:29Z INFO MessageListener] Session created.
[2017-02-22 05:24:29Z INFO Terminal] WRITE LINE: 2017-02-22 05:24:29Z: Listening for Jobs
[2017-02-22 05:24:43Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\agent\.credentials_rsaparams
[2017-02-22 05:24:43Z INFO MessageListener] Message '12' received from session 'c6bcb1be-999e-49bd-a0a3-c071a612e213'.
[2017-02-22 05:24:43Z INFO JobDispatcher] Job request f70c378c-48cb-4097-b883-a1d93265ed1f received.
[2017-02-22 05:24:43Z INFO Terminal] WRITE LINE: 2017-02-22 05:24:43Z: Running job: Build
[2017-02-22 05:24:43Z INFO JobDispatcher] Start renew job request 300 for job f70c378c-48cb-4097-b883-a1d93265ed1f.
[2017-02-22 05:24:44Z INFO JobDispatcher] Successfully renew job request 300, job is valid till 2/22/2017 5:29:43 AM
[2017-02-22 05:24:44Z INFO ProcessInvoker] Starting process:
[2017-02-22 05:24:44Z INFO ProcessInvoker]   File name: 'C:\agent\bin\Agent.Worker.exe'
[2017-02-22 05:24:44Z INFO ProcessInvoker]   Arguments: 'spawnclient 2560 2572'
[2017-02-22 05:24:44Z INFO ProcessInvoker]   Working directory: 'C:\agent\bin'
[2017-02-22 05:24:44Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-22 05:24:44Z INFO ProcessInvoker]   Encoding web name:  ; code page: ''
[2017-02-22 05:24:44Z INFO ProcessInvoker]   Force kill process on cancellation: 'True'
[2017-02-22 05:24:44Z INFO ProcessInvoker] Process started with process id 3804, waiting for process exit.
[2017-02-22 05:24:44Z INFO JobDispatcher] Send job request message to worker for job f70c378c-48cb-4097-b883-a1d93265ed1f.
[2017-02-22 05:24:44Z INFO JobNotification] Entering JobStarted Notification
[2017-02-22 05:24:54Z INFO ProcessInvoker] Finished process with exit code 102, and elapsed time 00:00:10.6934986.
[2017-02-22 05:24:54Z INFO JobDispatcher] Worker finished for job f70c378c-48cb-4097-b883-a1d93265ed1f. Code: 102
[2017-02-22 05:24:54Z INFO JobDispatcher] finish job request for job f70c378c-48cb-4097-b883-a1d93265ed1f with result: Failed
[2017-02-22 05:24:54Z INFO Terminal] WRITE LINE: 2017-02-22 05:24:54Z: Job Build completed with result: Failed

WORKER:
[2017-02-22 05:24:46Z INFO JobRunner] Job ID f70c378c-48cb-4097-b883-a1d93265ed1f
[2017-02-22 05:24:46Z INFO ConfigurationStore] currentAssemblyLocation: C:\agent\bin\Agent.Worker.dll
[2017-02-22 05:24:46Z INFO ConfigurationStore] binPath: C:\agent\bin
[2017-02-22 05:24:46Z INFO ConfigurationStore] RootFolder: C:\agent
[2017-02-22 05:24:46Z INFO ConfigurationStore] ConfigFilePath: C:\agent\.agent
[2017-02-22 05:24:46Z INFO ConfigurationStore] CredFilePath: C:\agent\.credentials
[2017-02-22 05:24:46Z INFO ConfigurationStore] ServiceConfigFilePath: C:\agent\.service
[2017-02-22 05:24:46Z INFO JobRunner] Ensure endpoint url match config url base. https://OUR_TFS_FQDN:8443/tfs/OUR PROJECT/Dev/_git/Elig
[2017-02-22 05:24:46Z INFO JobRunner] Ensure System.TaskDefinitionsUrl match config url base. https://OUR_TFS_FQDN:8443/tfs/OUR%20PROJECT/
[2017-02-22 05:24:46Z INFO JobRunner] Ensure System.TFCollectionUrl match config url base. https://OUR_TFS_FQDN:8443/tfs/OUR%20PROJECT/
[2017-02-22 05:24:46Z INFO JobRunner] Ensure SystemConnection url match config url base. https://OUR_TFS_FQDN:8443/tfs/OUR PROJECT/
[2017-02-22 05:24:46Z INFO JobRunner] Ensure System.TFServerUrl match config url base. https://OUR_TFS_FQDN:8443/tfs/OUR%20PROJECT/
[2017-02-22 05:24:46Z INFO JobRunner] Creating job server with URL: https://OUR_TFS_FQDN:8443/tfs/OUR PROJECT/
[2017-02-22 05:24:46Z INFO Worker] Listening for cancel message from the channel.
[2017-02-22 05:24:46Z INFO Worker] Waiting for the job to complete or for a cancel message from the channel.
[2017-02-22 05:24:48Z INFO JobServerQueue] Start process web console line queue.
[2017-02-22 05:24:48Z INFO JobServerQueue] Start process file upload queue.
[2017-02-22 05:24:48Z INFO JobServerQueue] Start process timeline update queue.
[2017-02-22 05:24:48Z INFO JobRunner] Starting the job execution context.
[2017-02-22 05:24:48Z INFO HostContext] Well known directory 'Bin': 'C:\agent\bin'
[2017-02-22 05:24:48Z INFO HostContext] Well known directory 'Root': 'C:\agent'
[2017-02-22 05:24:48Z INFO HostContext] Well known directory 'Work': 'C:\agent\_work'
[2017-02-22 05:24:48Z INFO JobRunner] Validating directory permissions for: 'C:\agent\_work'
[2017-02-22 05:24:48Z INFO JobRunner] Creating task server with https://OUR_TFS_FQDN:8443/tfs/OUR PROJECT/
[2017-02-22 05:24:48Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-02-22 05:24:49Z INFO JobRunner] Getting job extensions.
[2017-02-22 05:24:49Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.IJobExtension'
[2017-02-22 05:24:49Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension, Agent.Worker
[2017-02-22 05:24:49Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension, Agent.Worker
[2017-02-22 05:24:49Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Release.DeploymentJobExtension, Agent.Worker
[2017-02-22 05:24:49Z INFO JobRunner] Adding job prepare extensions.
[2017-02-22 05:24:49Z INFO JobRunner] Adding tasks.
[2017-02-22 05:24:49Z INFO JobRunner] Adding job finally extensions.
[2017-02-22 05:24:49Z INFO JobRunner] Downloading task definitions.
[2017-02-22 05:24:49Z INFO TaskManager] Ensuring task exists: ID '333b11bd-d341-40d9-afcf-b32d5ce6f23b', version '0.2.29', name 'NuGetInstaller', directory 'C:\agent\_work\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.29'.
[2017-02-22 05:24:49Z INFO TaskManager] Task already downloaded.
[2017-02-22 05:24:49Z INFO TaskManager] Ensuring task exists: ID '71a9a2d3-a98a-4caa-96ab-affca411ecda', version '1.0.49', name 'VSBuild', directory 'C:\agent\_work\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.0.49'.
[2017-02-22 05:24:49Z INFO TaskManager] Task already downloaded.
[2017-02-22 05:24:49Z INFO TaskManager] Ensuring task exists: ID 'ef087383-ee5e-42c7-9a53-ab56c98420f9', version '1.0.84', name 'VSTest', directory 'C:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\1.0.84'.
[2017-02-22 05:24:49Z INFO TaskManager] Task already downloaded.
[2017-02-22 05:24:49Z INFO TaskManager] Ensuring task exists: ID 'd9bafed4-0b18-4f58-968d-86655b4d2ce9', version '1.1.2', name 'CmdLine', directory 'C:\agent\_work\_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\1.1.2'.
[2017-02-22 05:24:49Z INFO TaskManager] Task already downloaded.
[2017-02-22 05:24:49Z INFO TaskManager] Ensuring task exists: ID '179fac12-2402-486e-80cf-5a6a8571f7c0', version '2.0.6', name 'OctopusPack', directory 'C:\agent\_work\_tasks\OctopusPack_179fac12-2402-486e-80cf-5a6a8571f7c0\2.0.6'.
[2017-02-22 05:24:49Z INFO TaskManager] Task already downloaded.
[2017-02-22 05:24:49Z INFO TaskManager] Ensuring task exists: ID '2ff763a7-ce83-4e1f-bc89-0ae63477cebe', version '1.0.40', name 'PublishBuildArtifacts', directory 'C:\agent\_work\_tasks\PublishBuildArtifacts_2ff763a7-ce83-4e1f-bc89-0ae63477cebe\1.0.40'.
[2017-02-22 05:24:49Z INFO TaskManager] Task already downloaded.
[2017-02-22 05:24:49Z INFO TaskManager] Ensuring task exists: ID 'd05ad9a2-5d9e-4a1c-a887-14034334d6f2', version '2.0.6', name 'OctopusPush', directory 'C:\agent\_work\_tasks\OctopusPush_d05ad9a2-5d9e-4a1c-a887-14034334d6f2\2.0.6'.
[2017-02-22 05:24:49Z INFO TaskManager] Task already downloaded.
[2017-02-22 05:24:49Z INFO StepsRunner] Processing step: DisplayName='Get Sources', AlwaysRun=False, ContinueOnError=False, Critical=True, Enabled=True, Finally=False
[2017-02-22 05:24:49Z INFO StepsRunner] Starting the step.
[2017-02-22 05:24:49Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.Build.ISourceProvider'
[2017-02-22 05:24:49Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.ExternalGitSourceProvider, Agent.Worker
[2017-02-22 05:24:49Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.GitHubSourceProvider, Agent.Worker
[2017-02-22 05:24:49Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.SvnSourceProvider, Agent.Worker
[2017-02-22 05:24:49Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsGitSourceProvider, Agent.Worker
[2017-02-22 05:24:49Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCSourceProvider, Agent.Worker
[2017-02-22 05:24:49Z INFO BuildDirectoryManager] Checking if artifacts directory exists: 'C:\agent\_work\1\a'
[2017-02-22 05:24:49Z INFO BuildDirectoryManager] Creating artifacts directory.
[2017-02-22 05:24:49Z INFO BuildDirectoryManager] Checking if test results directory exists: 'C:\agent\_work\1\TestResults'
[2017-02-22 05:24:49Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-02-22 05:24:49Z INFO BuildDirectoryManager] Creating test results directory.
[2017-02-22 05:24:49Z INFO BuildDirectoryManager] Checking if source directory exists: 'C:\agent\_work\1\s'
[2017-02-22 05:24:50Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-02-22 05:24:51Z INFO BuildDirectoryManager] Creating source directory.
[2017-02-22 05:24:51Z INFO SourceProvider] Get 'SourcesDirectory': 'C:\agent\_work\1\s'
[2017-02-22 05:24:51Z INFO SourceProvider] Get 'SourceBranch': 'refs/heads/master'
[2017-02-22 05:24:51Z INFO SourceProvider] Get 'SourceVersion': '06678b04a73aa9065f1c77d54aceee6d0cd92422'
[2017-02-22 05:24:51Z INFO TfsGitSourceProvider] Repository url=https://OUR_TFS_FQDN:8443/tfs/OUR PROJECT/Dev/_git/Elig
[2017-02-22 05:24:51Z INFO TfsGitSourceProvider] targetPath=C:\agent\_work\1\s
[2017-02-22 05:24:51Z INFO TfsGitSourceProvider] sourceBranch=refs/heads/master
[2017-02-22 05:24:51Z INFO TfsGitSourceProvider] sourceVersion=06678b04a73aa9065f1c77d54aceee6d0cd92422
[2017-02-22 05:24:51Z INFO TfsGitSourceProvider] clean=True
[2017-02-22 05:24:51Z INFO TfsGitSourceProvider] checkoutSubmodules=False
[2017-02-22 05:24:51Z INFO TfsGitSourceProvider] exposeCred=False
[2017-02-22 05:24:51Z INFO TfsGitSourceProvider] fetchDepth=0
[2017-02-22 05:24:51Z INFO TfsGitSourceProvider] gitLfsSupport=False
[2017-02-22 05:24:51Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Starting process:
[2017-02-22 05:24:51Z INFO ProcessInvoker]   File name: 'C:\agent\externals\git\cmd\git.exe'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Arguments: 'version'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Working directory: 'C:\agent\_work'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker] Process started with process id 4956, waiting for process exit.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.1027866.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Starting process:
[2017-02-22 05:24:51Z INFO ProcessInvoker]   File name: 'C:\agent\externals\git\cmd\git.exe'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Arguments: 'init "C:\agent\_work\1\s"'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Working directory: 'C:\agent\_work\1\s'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker] Process started with process id 1848, waiting for process exit.
[2017-02-22 05:24:51Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0919262.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Starting process:
[2017-02-22 05:24:51Z INFO ProcessInvoker]   File name: 'C:\agent\externals\git\cmd\git.exe'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Arguments: 'remote add origin https://OUR_TFS_FQDN:8443/tfs/OUR%20PROJECT/Dev/_git/Elig'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Working directory: 'C:\agent\_work\1\s'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker] Process started with process id 4580, waiting for process exit.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0523445.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Starting process:
[2017-02-22 05:24:51Z INFO ProcessInvoker]   File name: 'C:\agent\externals\git\cmd\git.exe'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Arguments: 'config gc.auto 0'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Working directory: 'C:\agent\_work\1\s'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker] Process started with process id 3684, waiting for process exit.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0503582.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Starting process:
[2017-02-22 05:24:51Z INFO ProcessInvoker]   File name: 'C:\agent\externals\git\cmd\git.exe'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Arguments: 'config --get-all http.https://OUR_TFS_FQDN:8443/tfs/OUR%20PROJECT/Dev/_git/Elig.extraheader'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Working directory: 'C:\agent\_work\1\s'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker] Process started with process id 5340, waiting for process exit.
[2017-02-22 05:24:51Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Finished process with exit code 1, and elapsed time 00:00:00.0496848.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Starting process:
[2017-02-22 05:24:51Z INFO ProcessInvoker]   File name: 'C:\agent\externals\git\cmd\git.exe'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Arguments: 'config --get-all http.proxy'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Working directory: 'C:\agent\_work\1\s'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2017-02-22 05:24:51Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-02-22 05:24:51Z INFO ProcessInvoker] Process started with process id 5128, waiting for process exit.
[2017-02-22 05:24:51Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0495442.
[2017-02-22 05:24:52Z INFO ProcessInvoker] Starting process:
[2017-02-22 05:24:52Z INFO ProcessInvoker]   File name: 'C:\agent\externals\git\cmd\git.exe'
[2017-02-22 05:24:52Z INFO ProcessInvoker]   Arguments: 'config --unset-all http.proxy'
[2017-02-22 05:24:52Z INFO ProcessInvoker]   Working directory: 'C:\agent\_work\1\s'
[2017-02-22 05:24:52Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-22 05:24:52Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2017-02-22 05:24:52Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-02-22 05:24:52Z INFO ProcessInvoker] Process started with process id 1520, waiting for process exit.
[2017-02-22 05:24:52Z INFO ProcessInvoker] Finished process with exit code 5, and elapsed time 00:00:00.0493439.
[2017-02-22 05:24:52Z INFO ProcessInvoker] Starting process:
[2017-02-22 05:24:52Z INFO ProcessInvoker]   File name: 'C:\agent\externals\git\cmd\git.exe'
[2017-02-22 05:24:52Z INFO ProcessInvoker]   Arguments: '-c http.extraheader="AUTHORIZATION: bearer ********" fetch --tags --prune --progress origin'
[2017-02-22 05:24:52Z INFO ProcessInvoker]   Working directory: 'C:\agent\_work\1\s'
[2017-02-22 05:24:52Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-22 05:24:52Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2017-02-22 05:24:52Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-02-22 05:24:52Z INFO ProcessInvoker] Process started with process id 4716, waiting for process exit.
[2017-02-22 05:24:52Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-02-22 05:24:53Z INFO ProcessInvoker] Finished process with exit code 128, and elapsed time 00:00:01.0222231.
[2017-02-22 05:24:53Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-02-22 05:24:53Z ERR  StepsRunner] Caught exception from step: System.InvalidOperationException: Git fetch failed with exit code: 128
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.GitSourceProvider.<GetSourceAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.<PrepareAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtensionRunner.<RunAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunAsync>d__0.MoveNext()
[2017-02-22 05:24:53Z INFO StepsRunner] Step result: Failed
[2017-02-22 05:24:53Z INFO StepsRunner] Current state: job state = 'Failed', step failed = True, critical step failed = True
[2017-02-22 05:24:53Z INFO StepsRunner] Processing step: DisplayName='NuGet restore **\*.sln', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2017-02-22 05:24:53Z INFO StepsRunner] Skipping step.
[2017-02-22 05:24:53Z INFO StepsRunner] Processing step: DisplayName='Build solution **\*.sln', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2017-02-22 05:24:53Z INFO StepsRunner] Skipping step.
[2017-02-22 05:24:53Z INFO StepsRunner] Processing step: DisplayName='Test Assemblies **\*test*.dll;-:**\obj\**', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2017-02-22 05:24:53Z INFO StepsRunner] Skipping step.
[2017-02-22 05:24:53Z INFO StepsRunner] Processing step: DisplayName='Run dotnet', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2017-02-22 05:24:53Z INFO StepsRunner] Skipping step.
[2017-02-22 05:24:53Z INFO StepsRunner] Processing step: DisplayName='Package Elig.Web', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2017-02-22 05:24:53Z INFO StepsRunner] Skipping step.
[2017-02-22 05:24:53Z INFO StepsRunner] Processing step: DisplayName='Package Elig.Auto.Service', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2017-02-22 05:24:53Z INFO StepsRunner] Skipping step.
[2017-02-22 05:24:53Z INFO StepsRunner] Processing step: DisplayName='Package Elig.PostProcessing.Service', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2017-02-22 05:24:53Z INFO StepsRunner] Skipping step.
[2017-02-22 05:24:53Z INFO StepsRunner] Processing step: DisplayName='Publish Artifact: drop', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2017-02-22 05:24:53Z INFO StepsRunner] Skipping step.
[2017-02-22 05:24:53Z INFO StepsRunner] Processing step: DisplayName='Push Packages to Octopus', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=False
[2017-02-22 05:24:53Z INFO StepsRunner] Skipping step.
[2017-02-22 05:24:53Z INFO StepsRunner] Processing step: DisplayName='Post Job Cleanup', AlwaysRun=False, ContinueOnError=False, Critical=False, Enabled=True, Finally=True
[2017-02-22 05:24:53Z INFO StepsRunner] Starting the step.
[2017-02-22 05:24:53Z INFO SourceProvider] Get 'SourcesDirectory': 'C:\agent\_work\1\s'
[2017-02-22 05:24:53Z INFO ProcessInvoker] Starting process:
[2017-02-22 05:24:53Z INFO ProcessInvoker]   File name: 'C:\agent\externals\git\cmd\git.exe'
[2017-02-22 05:24:53Z INFO ProcessInvoker]   Arguments: 'remote set-url origin https://OUR_TFS_FQDN:8443/tfs/OUR%20PROJECT/Dev/_git/Elig'
[2017-02-22 05:24:53Z INFO ProcessInvoker]   Working directory: 'C:\agent\_work\1\s'
[2017-02-22 05:24:53Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-22 05:24:53Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2017-02-22 05:24:53Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-02-22 05:24:53Z INFO ProcessInvoker] Process started with process id 3728, waiting for process exit.
[2017-02-22 05:24:53Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0543347.
[2017-02-22 05:24:53Z INFO ProcessInvoker] Starting process:
[2017-02-22 05:24:53Z INFO ProcessInvoker]   File name: 'C:\agent\externals\git\cmd\git.exe'
[2017-02-22 05:24:53Z INFO ProcessInvoker]   Arguments: 'remote set-url --push origin https://OUR_TFS_FQDN:8443/tfs/OUR%20PROJECT/Dev/_git/Elig'
[2017-02-22 05:24:53Z INFO ProcessInvoker]   Working directory: 'C:\agent\_work\1\s'
[2017-02-22 05:24:53Z INFO ProcessInvoker]   Require exit code zero: 'False'
[2017-02-22 05:24:53Z INFO ProcessInvoker]   Encoding web name: utf-8 ; code page: '65001'
[2017-02-22 05:24:53Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-02-22 05:24:53Z INFO ProcessInvoker] Process started with process id 4100, waiting for process exit.
[2017-02-22 05:24:53Z INFO ProcessInvoker] Finished process with exit code 0, and elapsed time 00:00:00.0517648.
[2017-02-22 05:24:53Z INFO StepsRunner] Step result: 
[2017-02-22 05:24:53Z INFO StepsRunner] Current state: job state = 'Failed', step failed = True, critical step failed = True
[2017-02-22 05:24:53Z INFO JobRunner] Job result: Failed
[2017-02-22 05:24:53Z INFO JobRunner] Completing the job execution context.
[2017-02-22 05:24:53Z INFO JobRunner] Shutting down the job server queue.
[2017-02-22 05:24:53Z INFO JobServerQueue] Fire signal to shutdown all queues.
[2017-02-22 05:24:53Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-02-22 05:24:53Z INFO JobServerQueue] Try to upload 3 log files or attachments, success rate: 3/3.
[2017-02-22 05:24:54Z INFO JobServerQueue] All queue process task stopped.
[2017-02-22 05:24:54Z INFO JobServerQueue] Try to append 1 batches web console lines, success rate: 1/1.
[2017-02-22 05:24:54Z INFO JobServerQueue] Web console line queue drained.
[2017-02-22 05:24:54Z INFO JobServerQueue] File upload queue drained.
[2017-02-22 05:24:54Z INFO JobServerQueue] Timeline update queue drained.
[2017-02-22 05:24:54Z INFO JobServerQueue] All queue process tasks have been stopped, and all queues are drained.
[2017-02-22 05:24:54Z INFO JobRunner] Raising job completed event.
[2017-02-22 05:24:54Z INFO Worker] Job completed.

**Comment by TingluoHuang** [comment]
@jmackay 
1. try set git.verifyssl=false to system level, or global level by agent run as account.
2. try use the git.exe under `agent/external/git/cmd` folder repro the problem, since the agent ship a copy of git.exe, we always use this git.exe instead of the one you installed on the machine.

**Comment by mackayj** [comment]
C:\agent\externals\git\cmd\git.exe config --global http.sslVerify false

Worked. I had previously set it to global for the regular C:\program files git.

What threw me was even when running the git from the agent and doing a config --list, it would say it was disabled, but was pulling from the global git and not the one it was actually using??? Frustrating!!

I spent 3 days off and on messing with this so glad to have it finally working.

**Comment by TingluoHuang** [comment]
@jmackay  glad you unblock. it is strange. :(
we will add ignore ssl cert error into the agent when dotnet core have it.
https://github.com/Microsoft/vsts-agent/issues/669
