### ISSUE TITLE
Failed to create session. No agent pool found with identifier X -- Windows Agent with TFS 2017 Update 1

### ISSUE THREAD

**Issue by fishbits** [Microsoft/vsts-agent#876]
## **Agent version and platform**
2.112.0, Windows 2012 R2

## **VSTS type and version**
On-Prem TFS 2017 Update 1<br>
This is encountered after creating the agent successfully and then executing ".\run.cmd" (or even trying to start from Services console).
```
[2017-03-22 23:16:50Z INFO Terminal] WRITE LINE: Connecting to the server.
[2017-03-22 23:16:50Z INFO MessageListener] Attempt to create session.
[2017-03-22 23:16:50Z INFO MessageListener] Connecting to the Agent Server...
[2017-03-22 23:16:50Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file E:\Agent3\.credentials_rsaparams
[2017-03-22 23:16:50Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file E:\Agent3\.credentials_rsaparams
[2017-03-22 23:16:50Z ERR  MessageListener] Catch exception during create session.
[2017-03-22 23:16:51Z ERR  MessageListener] Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentPoolNotFoundException: No agent pool found with identifier 3.
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<CreateSessionAsync>d__11.MoveNext()
[2017-03-22 23:16:51Z INFO MessageListener] Non-retriable exception: No agent pool found with identifier 3.
[2017-03-22 23:16:51Z ERR  Terminal] WRITE ERROR: Failed to create session. No agent pool found with identifier 3.
```

The agents not giving any trouble? The older VsoAgent.exe-based installs (v15.105.25910.0)

Also tried creating new Pools to add agent to; didn't make any difference.

**Comment by TingluoHuang** [comment]
@fishbits  what's your default access level setting? basic or stakeholder

**Comment by fishbits** [comment]
**Advanced** is my default access level.

**Comment by TingluoHuang** [comment]
@fishbits any information or error record in your TFS AT's event log?

**Comment by TingluoHuang** [comment]
@fishbits is pool 3 exist?
can you check in browser? 
`http(s)://yourtfs:8080/tfs/_admin/_AgentPool?poolId=3&_a=agents`

**Comment by fishbits** [comment]
Trying to put pieces back together after two months since I encountered this issue.  I believe I simply had my TFS URL entered incorrectly -- was basing it on how the older, so-named 'VSO' agents had you enter the URL.

In any case, this is no longer giving me issues, and, in fact I can just as easily create/connect agents that support VSTS, as well, with a copy of the same agent setup files/binaries.
