### ISSUE TITLE
Unable to create agent VssServiceResponseException: Redirect

### ISSUE THREAD

**Issue by andhie** [Microsoft/vsts-agent#878]
## **Agent version and platform**
Version of your agent? vsts-agent-osx.10.11-x64-2.112.0
OS of the machine running the agent? macOS 10.12.3
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS?
On-Prem TFS 2017 Update 1 RTM (9 March, 2017)
<br>
## **What's not working?** 
I am unable to complete the `./config.sh`. I can see the agent in TFS Agent Queues.

```
Connecting to server ...

>> Register Agent:
Enter agent pool (press enter for default) > 
Enter agent name (press enter for MacBook-Pro) > 
Scanning for tool capabilities.
Connecting to the server.
Enter replace? (Y/N) (press enter for N) > Y
Successfully replaced the agent
Testing agent connection.
Redirect
```

In the _diag folder. the last few lines leading to the error

```
[2017-03-23 09:52:34Z INFO Terminal] WRITE LINE: Successfully replaced the agent
[2017-03-23 09:52:34Z INFO ConfigurationManager] Agent server url resolve by server: 'http://company.com/tfs/'.
[2017-03-23 09:52:34Z INFO ConfigurationStore] Saving OAuth credential @ /Users/admin/Downloads/vsts-agent-osx.10.11-x64-2.112.0/.credentials
[2017-03-23 09:52:34Z INFO ConfigurationStore] Credentials Saved.
[2017-03-23 09:52:34Z INFO Terminal] WRITE LINE: Testing agent connection.
[2017-03-23 09:52:34Z INFO ConfigurationStore] HasCredentials()
[2017-03-23 09:52:34Z INFO ConfigurationStore] stored True
[2017-03-23 09:52:34Z INFO CredentialManager] GetCredentialProvider
[2017-03-23 09:52:34Z INFO CredentialManager] Creating type OAuth
[2017-03-23 09:52:34Z INFO CredentialManager] Creating credential type: OAuth
[2017-03-23 09:52:34Z INFO RSAFileKeyManager] Loading RSA key parameters from file /Users/admin/Downloads/vsts-agent-osx.10.11-x64-2.112.0/.credentials_rsaparams
[2017-03-23 09:52:34Z ERR  Agent] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Redirect
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext()
[2017-03-23 09:52:34Z ERR  Terminal] WRITE ERROR: Redirect
```

**Comment by TingluoHuang** [comment]
@andhie what's your network configuration looks like? do you have any thing between your agent and your TFS AT instance, like a load balancer? I want to understand where is the redirect coming from.

**Comment by andhie** [comment]
its a VM hosted in Azure, i dont think a load balancer is setup
and my computers have full direct internet access (no proxy or blocker)

**Comment by TingluoHuang** [comment]
@andhie do you mean your TFS is installed on a Azure VM?

**Comment by andhie** [comment]
that is correct, TFS is running on a VM hosted by Azure

**Comment by TingluoHuang** [comment]
@andhie try use 2.114.0 agent agent collect Http trace base on the trouble shoot doc.
https://www.visualstudio.com/en-us/docs/build/troubleshooting#http-trace-logs

**Comment by TingluoHuang** [comment]
@andhie also, is there any error or information in your TFS AT's event log?

**Comment by andhie** [comment]
Sorry for the late reply.
Below is the diag when `export VSTS_AGENT_HTTPTRACE=true` with VSTS 2.115.0
Why is the RequestUri is in http? i used `--url https://tfs.company.com/tfs`

```
[2017-04-10 07:10:53Z INFO CredentialManager] Creating type OAuth
[2017-04-10 07:10:53Z INFO CredentialManager] Creating credential type: OAuth
[2017-04-10 07:10:53Z INFO RSAFileKeyManager] Loading RSA key parameters from file /Users/admin/Downloads/vsts-agent-osx.10.11-x64-2.115.0/.credentials_rsaparams
[2017-04-10 07:10:53Z INFO HttpTrace] Trace System.Net.Http.Request event:
{ Request = Method: GET, RequestUri: 'http://tfs.company.com/tfs/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1', Version: 1.1, Content: <null>, Headers:
{
  User-Agent: VSServices/15.255.65000.0
  User-Agent: (NetStandard; Darwin 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64)
  User-Agent: VstsAgentCore-osx.10.11-x64/2.115.0
  User-Agent: (Darwin 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64)
  X-TFS-FedAuthRedirect: Suppress
  X-TFS-Session: 0ee2bbaf-558c-4228-ba00-52ce72e7851b
  X-VSS-E2EID: 0ee2bbaf-558c-4228-ba00-52ce72e7851b
  Expect: 100-continue
}, LoggingRequestId = 2b8b8c67-f5d0-437c-bce1-8a5aa6414c6e, Timestamp = 88621986225408 }
[2017-04-10 07:10:53Z INFO HttpTrace] Trace System.Net.Http.Response event:
{ Response = StatusCode: 302, ReasonPhrase: 'Redirect', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Location: https://tfs.company.com/tfs/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1
  Server: Microsoft-IIS/8.5
  X-Powered-By: ASP.NET
  P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
  Lfs-Authenticate: NTLM
  X-Content-Type-Options: nosniff
  Date: Mon, 10 Apr 2017 07:10:52 GMT
  Content-Type: text/html; charset=UTF-8
  Content-Length: 233
}, LoggingRequestId = 2b8b8c67-f5d0-437c-bce1-8a5aa6414c6e, TimeStamp = 88622036399945 }
[2017-04-10 07:10:53Z ERR  Agent] Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Redirect
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext()
[2017-04-10 07:10:53Z ERR  Terminal] WRITE ERROR: Redirect
[2017-04-10 07:10:53Z INFO HttpTrace] DiagListeners finished transmitting data.
```

**Comment by TingluoHuang** [comment]
@andhie 
What's your server's public url configured at AT?
during config, you typed https, but after we add the agent to the pool, server tells us its url in on http://...
```
[2017-03-23 09:52:34Z INFO ConfigurationManager] Agent server url resolve by server: 'http://company.com/tfs/'.
```

**Comment by andhie** [comment]
I'm not well versed in Azure or server configuration.
What is "AT"? 
Do you have a guide or hint on where to look?

**Comment by TingluoHuang** [comment]
@andhie on the machine you install TFS.
![image](https://cloud.githubusercontent.com/assets/1750815/25008667/629ddc06-2032-11e7-93af-20b3b1ef8051.png)

**Comment by andhie** [comment]
I'm guessing the Public URL part is suppose to be the `https://tfs.company.com/tfs` in my case? as in the same value i pass in via `--url` when configuring agent

**Comment by TingluoHuang** [comment]
i guess so, or you should have a bindings to https:// instead of http://

**Comment by TingluoHuang** [comment]
let us know if you need more help, close the issue for now.
