### ISSUE TITLE
"The server returned an invalid or unrecognized response" when connecting to an on-prem TFS application tier behind a load balancer (HAProxy)

### ISSUE THREAD

**Issue by ppejovic** [Microsoft/vsts-agent#944]
## **Agent version and platform**
2.112.0 + 
<br>
Windows
<br>
## **VSTS type and version**
On-Prem TFS
<br>
2017 Update 1
<br>
## **What's not working?** 
We have 2 TFS Application Tier servers sitting behind HAProxy in a round-robin configuration. Testing of all  other functionality/integrations through the proxy has not thrown up any issues so far. When pointing a VSTS Agent to the application tier through the proxy, the agent will generate the following error after starting:

```
C:\Agent\Test2>run.cmd
Scanning for tool capabilities.
Connecting to the server.
2017-05-01 19:19:17Z: Listening for Jobs
2017-05-01 19:20:03Z: Agent connect error: An error occurred while sending the request.. Retrying every 15 seconds until reconnected.
```

<br>

## **Agent and Worker's diag log**

You can see below the NTML challenge/response succeeds (HAProxy has in-built support for this to route the relevant requests to the same server), but after the "session is created" and the agent starts "Listening for Jobs" the following error occurs:

`System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response`

It looks like the agent is maintaining a session (based on the the sessionId in the query string of the request that fails)? This request could potentially be routed through a different application tier node from where the session was created, which seems is not possible? Is there any workaround to this (other than putting some HAProxy configuration place to ensure a sticky session for the agent with the same server)?

```

[2017-05-01 19:19:17Z INFO Terminal] WRITE LINE: Connecting to the server.
[2017-05-01 19:19:17Z INFO MessageListener] Attempt to create session.
[2017-05-01 19:19:17Z INFO MessageListener] Connecting to the Agent Server...
[2017-05-01 19:19:17Z INFO HttpTrace] Trace System.Net.Http.Request event:
{ Request = Method: GET, RequestUri: 'http://XXXX:8080/tfs/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1', Version: 1.1, Content: <null>, Headers: XXXX }
[2017-05-01 19:19:17Z INFO HttpTrace] Trace System.Net.Http.Response event:
{ Response = StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers: XXXX }
[2017-05-01 19:19:17Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\Agent\Test2\.credentials_rsaparams
[2017-05-01 19:19:17Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\Agent\Test2\.credentials_rsaparams
[2017-05-01 19:19:17Z INFO HttpTrace] Trace System.Net.Http.Request event:
{ Request = Method: POST, RequestUri: 'http://XXXX/tfs/_apis/oauth2/token', Version: 1.1, Content: System.Net.Http.FormUrlEncodedContent, Headers: XXXX }
[2017-05-01 19:19:17Z INFO HttpTrace] Trace System.Net.Http.Response event:
{ Response = StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers: XXXX }
[2017-05-01 19:19:17Z INFO HttpTrace] Trace System.Net.Http.Request event:
{ Request = Method: GET, RequestUri: 'http://XXXX:8080/tfs/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1', Version: 1.1, Content: <null>, Headers: XXXX }
[2017-05-01 19:19:17Z INFO HttpTrace] Trace System.Net.Http.Response event:
{ Response = StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers: XXXX }
[2017-05-01 19:19:17Z INFO HttpTrace] Trace System.Net.Http.Request event:
{ Request = Method: POST, RequestUri: 'http://XXXX:8080/tfs/_apis/distributedtask/pools/2/sessions', Version: 1.1, Content: System.Net.Http.ObjectContent`1[Microsoft.TeamFoundation.DistributedTask.WebApi.TaskAgentSession], Headers: XXXX }
[2017-05-01 19:19:17Z INFO HttpTrace] Trace System.Net.Http.Response event:
{ Response = StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers: XXXX }

///---->  Logging of interest ..

[2017-05-01 19:19:17Z INFO MessageListener] Session created.
[2017-05-01 19:19:17Z INFO Terminal] WRITE LINE: 2017-05-01 19:19:17Z: Listening for Jobs
[2017-05-01 19:19:17Z INFO HttpTrace] Trace System.Net.Http.Request event:
{ Request = Method: GET, RequestUri: 'http://XXXX:8080/tfs/_apis/distributedtask/pools/2/messages?sessionId=0465211c-3f0b-4e94-8746-c403238fcf82', Version: 1.1, Content: <null>, Headers: XXXX }
[2017-05-01 19:20:02Z ERR  MessageListener] Catch exception during get next message.
[2017-05-01 19:20:03Z ERR  MessageListener] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The server returned an invalid or unrecognized response
   
<-----///

at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__43`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.MessageListener.<GetNextMessageAsync>d__13.MoveNext()
[2017-05-01 19:20:03Z INFO MessageListener] Retriable exception: An error occurred while sending the request.
[2017-05-01 19:20:03Z ERR  Terminal] WRITE ERROR: 2017-05-01 19:20:03Z: Agent connect error: An error occurred while sending the request.. Retrying every 15 seconds until reconnected.
[2017-05-01 19:20:03Z INFO MessageListener] Sleeping for 15 seconds before retrying.
```

**Comment by TingluoHuang** [comment]
@ppejovic the session id is stored in DB, so different ATs shouldn't affect it.
Do you config the build agent talk thought the proxy using `.proxy` file? can you get a Fiddler trace see what returned from your server cause agent think the response is invalid?

**Comment by ppejovic** [comment]
Thanks for the follow-up @TingluoHuang. Here's the fiddler trace, it doesn't give away much. The response consistently comes back 45s after the following request is made:

`GET /tfs/_apis/distributedtask/pools/2/messages?sessionId=9306bb0f-1401-4570-98af-740b3d61dc58 HTTP/1.1`

I am beginning to wonder if this is a timeout at the HAProxy level. I am investigating this line also.

```
HTTP/1.1 504 Fiddler - Receive Failure
Date: Tue, 02 May 2017 17:06:59 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
Cache-Control: no-cache, must-revalidate
Timestamp: 10:06:59.666

[Fiddler] ReadResponse() failed: The server did not return a complete response for this request. Server returned 0 bytes.               
```

**Comment by TingluoHuang** [comment]
@ppejovic  `GET /tfs/_apis/distributedtask/pools/2/messages?sessionId=9306bb0f-1401-4570-98af-740b3d61dc58 HTTP/1.1` is a long pull request, it should finish every 50s.
i think your direction should be right since it got terminated every 45s.

**Comment by ppejovic** [comment]
Yes, this is tied to our HAProxy config:

```        
        timeout client 45s
        timeout server 45s
```

I am thinking of configuring a 1 minute for the relevant timeout(s). Are you aware of any other long-polling requests hitting the TFS Application Tier that could expect a response longer than this?

**Comment by TingluoHuang** [comment]
i don't there is any other long poll from build agent side, but more sure other what other software does. :)
glad you figure it out.
