### ISSUE TITLE
Unable to match any source repository endpoints with any of the supported source providers.

### ISSUE THREAD

**Issue by pkavajin** [Microsoft/vsts-agent#955]
## **Have you try trouble shooting doc?**
Yup.

## **Agent version and platform**
Version of your agent? **2.116.1**
OS of the machine running the agent? **OSX**

## **VSTS type and version**
On-Prem TFS15 Version 14.0.23128.0

## **What's not working?** 
Seems like the agent fails finding the right source provider (should be TfsGitSourceProvider), saying "Unable to match any source repository endpoints with any of the supported source providers." right after start of build.

Digged into the code and compared it to the diag logs, seems like TFS isnt sending the repositoryId Parameter of the environments endpoint which makes the agent skip that endpoint in the TrySetPrimaryEndpointAndProviderInfo method of the BuildJobExtension class. 

That predicate came from commit 04600554 @TingluoHuang and seems to be related to #763 and with it #737

Didn't found any documentation on that id, or how to make TFS populate that property or even if its safe to remove that check. Maybe you guys can help with some information on that.

If I got the other tickets right the correct behavior would be "prefer those with id over those without", see 
[0001-Stop-ignoring-environments-without-id-just-dont-prio.patch.txt](https://github.com/Microsoft/vsts-agent/files/979989/0001-Stop-ignoring-environments-without-id-just-dont-prio.patch.txt) for a simple patch fixing the problem or symptom (for me).

After that change at least that problem seems solved, even tho the next occured for me, seems like the agent doesnt want to download the CmdLine Task giving a simple "Page not found". Am I using the wrong agent version for that TFS version?
<br>
## **Agent and Worker's diag log**
[workerlog.txt](https://github.com/Microsoft/vsts-agent/files/979863/workerlog.txt)

**Comment by ericsciple** [comment]
i think you registered the agent against the collection URL during config. you need to register against the server URL.

**Comment by pkavajin** [comment]
Hm, redid the configuration, same effect:

```
Enter server URL > https://backlog.netzkern.de/tfs
Enter authentication type (press enter for Negotiate) >
Enter user name > KERNGRUPPE\nk.tfsbuild
Enter password > ***************
Connecting to server ...

>> Register Agent:

Enter agent pool (press enter for default) >
Enter agent name (press enter for WUP-BUI01-MAC) >
Scanning for tool capabilities.
Connecting to the server.
Successfully added the agent
Testing agent connection.
Enter work folder (press enter for _work) >
```

Dunno if /tfs is default configuration, didnt setup that server, but the agent just took the /tfs url, just the blank server url failed to connect.

**Comment by ericsciple** [comment]
have you tried downloading the released agent? it sounds like you built yourself, which you should be able to do but i also havent heard of anyone else running into this issue.

**Comment by pkavajin** [comment]
Happens with recent release aswell, just checked out the source and built it for seeing whats wrong :(

```
WUP-BUI01-MAC:vsts-agent$ cat _diag/Worker_20170505-191410-utc.log | fgrep "Unable to match"
[2017-05-05 19:14:11Z ERR  BuildJobExtension] Caught exception from JobExtension Initialization: System.Exception: Unable to match any source repository endpoints with any of the supported source providers.
[2017-05-05 19:14:11Z ERR  JobRunner] Caught exception from InitializeJob: System.Exception: Unable to match any source repository endpoints with any of the supported source providers.
WUP-BUI01-MAC:vsts-agent$ shasum bin/Agent.Worker
f58a58875db432321df3c691a2f1d515c27735c6  bin/Agent.Worker
WUP-BUI01-MAC:vsts-agent$

```

**Comment by ericsciple** [comment]
which TFS version are you on? 2015? or 2017?

**Comment by ericsciple** [comment]
and which update

**Comment by ericsciple** [comment]
in team foundation server administraton console, the root node in the tree on the left should display something like this:
![image](https://cloud.githubusercontent.com/assets/12102068/25760970/1e502780-31a7-11e7-9092-e9ee5d212833.png)

**Comment by pkavajin** [comment]
2015, About screen says 14.0.23128.0, according to msdn that should be RTM

**Comment by ericsciple** [comment]
with your code change and with registering against the TFS URL (not the collection URL), does that fix both problems (endpoint chosen correctly and tasks download)?

**Comment by pkavajin** [comment]
Not both, just choses correct endpoint, checking whats wrong with task download now.

**Comment by ericsciple** [comment]
it sounds like an older release might work better until we get the TFS 2015 compat issues worked out again - it used to work :)

i would try the agent release that lines up with [TFS 2017 RTM](https://github.com/Microsoft/vsts-agent/releases/tag/v2.105.7)

**Comment by pkavajin** [comment]
Ahh nice, that works

Thank you! :-)

**Comment by ericsciple** [comment]
thanks for confirmation

**Comment by TingluoHuang** [comment]
@bryanmacfarlane i think i should fix this for back compat.

**Comment by DJRobertson** [comment]
I have this same issue.
**Error: Unable to match any source repository endpoints with any of the supported source providers.**

## Agent Version and Platform
Version of your agent? vsts-agent-osx-x64-2.1440.tar OSX (macOS Mojave, version 10.14.1)

## VSTS Type and Version
VisualStudio.com or On-Prem TFS?On-Prem TFS

On-Prem TFS, which release? 2015

## Agent and Worker's Diagnostic Logs

[2018-12-10 14:37:50Z ERR  BuildJobExtension] Caught exception from JobExtension Initialization: System.Exception: Unable to match any source repository endpoints with any of the supported source providers.
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.InitializeJobExtension(IExecutionContext executionContext, IList`1 steps, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
[2018-12-10 14:37:50Z ERR  JobRunner] Job initialize failed.

**Comment by TingluoHuang** [comment]
@DJRobertson can you share the full worker log with us from the agent?

**Comment by DJRobertson** [comment]
@TingluoHuang

[2018-12-11 13:21:44Z INFO Program] Version: 2.144.0
[2018-12-11 13:21:44Z INFO Program] Commit: c13cbf94b5e5b760e187fa1e32dcc329d1caf731
[2018-12-11 13:21:44Z INFO Program] Culture: en-GB
[2018-12-11 13:21:44Z INFO Program] UI Culture: en-GB
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:44Z INFO HostContext] Well known config file 'Proxy': '/Users/dean/iOSBuildAgent/.proxy'
[2018-12-11 13:21:44Z INFO VstsAgentWebProxy] No proxy setting found.
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:44Z INFO HostContext] Well known config file 'Certificates': '/Users/dean/iOSBuildAgent/.certificates'
[2018-12-11 13:21:44Z INFO AgentCertificateManager] No certificate setting found.
[2018-12-11 13:21:44Z INFO Worker] Waiting to receive the job message from the channel.
[2018-12-11 13:21:44Z INFO Worker] Message received.
[2018-12-11 13:21:44Z INFO Worker] Job message:
 {
  "steps": [
    {
      "inputs": {
        "solution": "$/Convey/Mobile/ConveyDriver/Main/ConveyDotNet.iOs.sln",
        "noCache": "false",
        "nuGetRestoreArgs": "",
        "nuGetPath": ""
      },
      "type": "task",
      "reference": {
        "id": "333b11bd-d341-40d9-afcf-b32d5ce6f23b",
        "name": "NuGetInstaller",
        "version": "0.1.12"
      },
      "condition": "succeeded()",
      "id": "6eb888e2-2812-43bf-8c17-879aad91b02f",
      "displayName": "NuGet restore $/Convey/Mobile/ConveyDriver/Main/ConveyDotNet.iOs.sln"
    },
    {
      "inputs": {
        "solution": "$/Convey/Mobile/ConveyDriver/Main/iOS/ConveyDotNet.iOS.csproj",
        "configuration": "$(Configuration)",
        "mdtoolLocation": "",
        "forSimulator": "false"
      },
      "type": "task",
      "reference": {
        "id": "0f077e3a-af59-496d-81bc-ad971b7464e0",
        "name": "XamariniOS",
        "version": "1.0.3"
      },
      "condition": "succeeded()",
      "id": "d6a745ac-49fc-467d-9a85-64c14f5d3c43",
      "displayName": "Build Xamarin.iOS solution $/Convey/Mobile/ConveyDriver/Main/iOS/ConveyDotNet.iOS.csproj"
    },
    {
      "inputs": {
        "CopyRoot": "",
        "Contents": "**\\bin\\**\n**/*.ipa",
        "ArtifactName": "drop",
        "ArtifactType": "FilePath",
        "TargetPath": "\\\\CONVEYDC001\\builds\\$(Build.DefinitionName)\\$(Build.BuildNumber)"
      },
      "type": "task",
      "reference": {
        "id": "1d341bb0-2106-458c-8422-d00bcea6512a",
        "name": "PublishBuildArtifacts",
        "version": "1.0.4"
      },
      "condition": "succeeded()",
      "id": "eaa53a30-39bd-4682-afb2-5b5f3d163037",
      "displayName": "Publish Artifact: drop"
    }
  ],
  "variables": {
    "system": {
      "value": "build"
    },
    "system.collectionId": {
      "value": "c45e2c00-a0a2-42d4-871a-eb329aefd96d"
    },
    "system.teamProject": {
      "value": "Convey"
    },
    "system.teamProjectId": {
      "value": "7ab8a40a-dc62-4cb5-af88-228db39d7483"
    },
    "system.definitionId": {
      "value": "68"
    },
    "build.definitionName": {
      "value": "Convey.Driver.iOS"
    },
    "build.definitionVersion": {
      "value": "37"
    },
    "build.queuedBy": {
      "value": "Dean Robertson"
    },
    "build.queuedById": {
      "value": "e02abe1b-93d1-4f86-aaf0-d4b9f2945954"
    },
    "build.requestedFor": {
      "value": "Dean Robertson"
    },
    "build.requestedForId": {
      "value": "e02abe1b-93d1-4f86-aaf0-d4b9f2945954"
    },
    "build.sourceVersion": {
      "value": "C5383"
    },
    "build.sourceBranch": {
      "value": "$/Convey/Mobile/ConveyDriver/Main"
    },
    "build.sourceBranchName": {
      "value": "Main"
    },
    "Configuration": {
      "value": "Release"
    },
    "Agent.OS": {
      "value": "Darwin"
    },
    "system.debug": {
      "value": "true"
    },
    "Build.Repository.Uri": {
      "value": "http://mytfs:8080/tfs/DefaultCollection/Convey"
    },
    "Build.Repository.Provider": {
      "value": "TfsVersionControl"
    },
    "Build.Repository.Name": {
      "value": "Tfvc"
    },
    "Build.Repository.Tfvc.Workspace": {
      "value": "~/Users/dean/iOSBuildAgent/_work/"
    },
    "build.repository.id": {
      "value": "1"
    },
    "build.buildId": {
      "value": "2043"
    },
    "build.buildUri": {
      "value": "vstfs:///Build/Build/2043"
    },
    "build.buildNumber": {
      "value": "20181211.26"
    },
    "build.containerId": {
      "value": "12043"
    },
    "system.hosttype": {
      "value": "build"
    }
  },
  "messageType": "PipelineAgentJobRequest",
  "plan": {
    "scopeIdentifier": "7ab8a40a-dc62-4cb5-af88-228db39d7483",
    "planType": "Build",
    "version": 4,
    "planId": "3b7e6609-8fa4-4d72-9f20-f93ebaec2e8a",
    "planGroup": null,
    "artifactUri": "vstfs:///Build/Build/2043",
    "artifactLocation": null,
    "definition": null,
    "owner": null
  },
  "timeline": {
    "id": "9813572b-623b-4458-983e-ebb5b017e4ea",
    "changeId": 1,
    "location": null
  },
  "jobId": "161296b4-a98f-4474-b67a-9d7ea7d47f48",
  "jobDisplayName": "Build",
  "jobName": null,
  "jobContainer": null,
  "requestId": 2038,
  "lockedUntil": "0001-01-01T00:00:00",
  "resources": {
    "endpoints": [
      {
        "data": {
          "rootFolder": "$/Convey",
          "clean": "true",
          "checkoutSubmodules": "False",
          "tfvcWorkspaceMapping": "{\"mappings\":[{\"serverPath\":\"$/Convey/Mobile/ConveyDriver/Main\",\"mappingType\":\"map\"}]}"
        },
        "name": "Convey",
        "type": "TfsVersionControl",
        "url": "http://mytfs:8080/tfs/DefaultCollection/",
        "authorization": {
          "parameters": {
            "AccessToken": "***"
          },
          "scheme": "OAuth"
        },
        "isShared": false,
        "isReady": false
      },
      {
        "data": {
          "ServerId": "c45e2c00-a0a2-42d4-871a-eb329aefd96d",
          "ServerName": "DefaultCollection"
        },
        "name": "SystemVssConnection",
        "url": "http://mytfs:8080/tfs/DefaultCollection/",
        "authorization": {
          "parameters": {
            "AccessToken": "***"
          },
          "scheme": "OAuth"
        },
        "isShared": false,
        "isReady": false
      }
    ]
  },
  "workspace": {}
}
[2018-12-11 13:21:44Z INFO JobRunner] Job ID 161296b4-a98f-4474-b67a-9d7ea7d47f48
[2018-12-11 13:21:44Z INFO ConfigurationStore] currentAssemblyLocation: /Users/dean/iOSBuildAgent/bin/Agent.Worker.dll
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:44Z INFO ConfigurationStore] binPath: /Users/dean/iOSBuildAgent/bin
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:44Z INFO ConfigurationStore] RootFolder: /Users/dean/iOSBuildAgent
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:44Z INFO HostContext] Well known config file 'Agent': '/Users/dean/iOSBuildAgent/.agent'
[2018-12-11 13:21:44Z INFO ConfigurationStore] ConfigFilePath: /Users/dean/iOSBuildAgent/.agent
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:44Z INFO HostContext] Well known config file 'Credentials': '/Users/dean/iOSBuildAgent/.credentials'
[2018-12-11 13:21:44Z INFO ConfigurationStore] CredFilePath: /Users/dean/iOSBuildAgent/.credentials
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:44Z INFO HostContext] Well known config file 'Service': '/Users/dean/iOSBuildAgent/.service'
[2018-12-11 13:21:44Z INFO ConfigurationStore] ServiceConfigFilePath: /Users/dean/iOSBuildAgent/.service
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:44Z INFO HostContext] Well known config file 'Autologon': '/Users/dean/iOSBuildAgent/.autologon'
[2018-12-11 13:21:44Z INFO ConfigurationStore] AutoLogonSettingsFilePath: /Users/dean/iOSBuildAgent/.autologon
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:44Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:44Z INFO HostContext] Well known config file 'Options': '/Users/dean/iOSBuildAgent/.options'
[2018-12-11 13:21:44Z INFO ConfigurationStore] RuntimeOptionsFilePath: /Users/dean/iOSBuildAgent/.options
[2018-12-11 13:21:44Z INFO ConfigurationStore] Read setting file: 160 chars
[2018-12-11 13:21:44Z INFO JobRunner] Ensure endpoint url match config url base. http://mytfs:8080/tfs/DefaultCollection/
[2018-12-11 13:21:44Z INFO JobRunner] Ensure endpoint url match config url base. http://mytfs:8080/tfs/DefaultCollection/
[2018-12-11 13:21:44Z INFO JobRunner] Ensure System.TFServerUrl match config url base. http://mytfs:8080/tfs/DefaultCollection/
[2018-12-11 13:21:44Z INFO JobRunner] Creating job server with URL: http://mytfs:8080/tfs/DefaultCollection/
[2018-12-11 13:21:44Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2018-12-11 13:21:45Z INFO Worker] Listening for cancel message from the channel.
[2018-12-11 13:21:45Z INFO Worker] Waiting for the job to complete or for a cancel message from the channel.
[2018-12-11 13:21:45Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2018-12-11 13:21:45Z INFO JobServerQueue] Start process web console line queue.
[2018-12-11 13:21:45Z INFO JobServerQueue] Start process file upload queue.
[2018-12-11 13:21:45Z INFO JobServerQueue] Start process timeline update queue.
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Diag': '/Users/dean/iOSBuildAgent/_diag'
[2018-12-11 13:21:45Z INFO JobRunner] Starting the job execution context.
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Work': '/Users/dean/iOSBuildAgent/_work'
[2018-12-11 13:21:45Z INFO JobRunner] Validating directory permissions for: '/Users/dean/iOSBuildAgent/_work'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Work': '/Users/dean/iOSBuildAgent/_work'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Work': '/Users/dean/iOSBuildAgent/_work'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Work': '/Users/dean/iOSBuildAgent/_work'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Work': '/Users/dean/iOSBuildAgent/_work'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Tools': '/Users/dean/iOSBuildAgent/_work/_tool'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Work': '/Users/dean/iOSBuildAgent/_work'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Temp': '/Users/dean/iOSBuildAgent/_work/_temp'
[2018-12-11 13:21:45Z INFO JobRunner] Can't determine task download url from JobMessage or the endpoint doesn't exist.
[2018-12-11 13:21:45Z INFO JobRunner] Recreate task server with configuration server url: http://mytfs:8080/tfs/
[2018-12-11 13:21:45Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2018-12-11 13:21:45Z INFO VisualStudioServices] Finished operation Location.GetConnectionData
[2018-12-11 13:21:45Z INFO JobRunner] Getting job extension.
[2018-12-11 13:21:45Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.IJobExtension'
[2018-12-11 13:21:45Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension, Agent.Worker
[2018-12-11 13:21:45Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension, Agent.Worker
[2018-12-11 13:21:45Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Release.DeploymentJobExtension, Agent.Worker
[2018-12-11 13:21:45Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Maintenance.MaintenanceJobExtension, Agent.Worker
[2018-12-11 13:21:45Z INFO JobRunner] Initialize job. Getting all job steps.
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Bin': '/Users/dean/iOSBuildAgent/bin'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Root': '/Users/dean/iOSBuildAgent'
[2018-12-11 13:21:45Z INFO HostContext] Well known directory 'Diag': '/Users/dean/iOSBuildAgent/_diag'
[2018-12-11 13:21:45Z INFO BuildJobExtension] Run initial step from extension BuildJobExtension.
[2018-12-11 13:21:45Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Worker.Build.ISourceProvider'
[2018-12-11 13:21:45Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.ExternalGitSourceProvider, Agent.Worker
[2018-12-11 13:21:45Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.GitHubSourceProvider, Agent.Worker
[2018-12-11 13:21:45Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.GitHubEnterpriseSourceProvider, Agent.Worker
[2018-12-11 13:21:45Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.BitbucketSourceProvider, Agent.Worker
[2018-12-11 13:21:45Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.SvnSourceProvider, Agent.Worker
[2018-12-11 13:21:45Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsGitSourceProvider, Agent.Worker
[2018-12-11 13:21:45Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Worker.Build.TfsVCSourceProvider, Agent.Worker
[2018-12-11 13:21:45Z ERR  BuildJobExtension] Caught exception from JobExtension Initialization: System.Exception: Unable to match any source repository endpoints with any of the supported source providers.
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.InitializeJobExtension(IExecutionContext executionContext, IList`1 steps, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
[2018-12-11 13:21:45Z ERR  JobRunner] Job initialize failed.
[2018-12-11 13:21:45Z ERR  JobRunner] Caught exception from InitializeJob: System.Exception: Unable to match any source repository endpoints with any of the supported source providers.
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.BuildJobExtension.InitializeJobExtension(IExecutionContext executionContext, IList`1 steps, WorkspaceOptions workspace)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message)
   at Microsoft.VisualStudio.Services.Agent.Worker.JobRunner.RunAsync(AgentJobRequestMessage message, CancellationToken jobRequestCancellationToken)
[2018-12-11 13:21:45Z INFO JobRunner] Shutting down the job server queue.
[2018-12-11 13:21:45Z INFO JobServerQueue] Fire signal to shutdown all queues.
[2018-12-11 13:21:46Z INFO JobServerQueue] All queue process task stopped.
[2018-12-11 13:21:46Z INFO JobServerQueue] Try to append 1 batches web console lines for record '161296b4-a98f-4474-b67a-9d7ea7d47f48', success rate: 1/1.
[2018-12-11 13:21:46Z INFO JobServerQueue] Try to append 1 batches web console lines for record '552ba710-5f75-4006-a062-60ca5be921b6', success rate: 1/1.
[2018-12-11 13:21:46Z INFO JobServerQueue] Web console line queue drained.
[2018-12-11 13:21:46Z INFO JobServerQueue] Uploading 2 files in one shot.
[2018-12-11 13:21:46Z INFO JobServerQueue] Try to upload 2 log files or attachments, success rate: 2/2.
[2018-12-11 13:21:46Z INFO JobServerQueue] File upload queue drained.
[2018-12-11 13:21:46Z INFO JobServerQueue] Timeline update queue drained.
[2018-12-11 13:21:46Z INFO JobServerQueue] All queue process tasks have been stopped, and all queues are drained.
[2018-12-11 13:21:46Z INFO TempDirectoryManager] Cleaning agent temp folder: /Users/dean/iOSBuildAgent/_work/_temp
[2018-12-11 13:21:46Z INFO JobRunner] Skip raise job completed event call from worker because Plan version is 4
[2018-12-11 13:21:46Z INFO Worker] Job completed.

**Comment by TingluoHuang** [comment]
@DJRobertson, thanks for reporting this, i have found the problem. will prepare a fix soon.

**Comment by DJRobertson** [comment]
@TingluoHuang has this issue been fixed in v2.144.1?

**Comment by TingluoHuang** [comment]
@DJRobertson it is not in 2.144.1. Due to the coming holiday session, the release that contains the fix won't happen until 1/1/2019. :(

**Comment by DJRobertson** [comment]
@TingluoHuang Thanks

**Comment by DJRobertson** [comment]
Hi @TingluoHuang any update on this fix?

**Comment by TingluoHuang** [comment]
the fix is in, we still waiting on consume/release it.
