### ISSUE TITLE
Building vsts from Master causes Windows Service functionality to fail

### ISSUE THREAD

**Issue by warbands** [Microsoft/vsts-agent#983]
## **Have you try trouble shooting doc?**
Yes
Link to trouble shooting doc: https://www.visualstudio.com/en-us/docs/build/troubleshooting

## **Agent version and platform**
Version of your agent? 2.102.0/2.100.1...
Latest from Master Branch ( 5/21/2017 )
<br>
OS of the machine running the agent? OSX/Windows/Linux...
Windows 10 ( Latest update )
<br>
## **VSTS type and version**
VSTS online
VisualStudio.com or On-Prem TFS?
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://account.visualstudio.com
http://institute-games.visualstudio.com
<br>
## **What's not working?** 
Please include error messages and screenshots

running 'dev layout Release' creates an Agent build that is able to run correctly via run.cmd but can't be config.cmd as a service

```
Connecting to server ...

>> Register Agent:

Enter agent pool (press enter for default) >
Enter agent name (press enter for METALGEAR) >
Scanning for tool capabilities.
Connecting to the server.
Enter replace? (Y/N) (press enter for N) > Y
Successfully replaced the agent
Testing agent connection.
Enter work folder (press enter for _work) >
2017-05-21 17:26:50Z: Settings Saved.
Enter run agent as service? (Y/N) (press enter for N) > Y
Enter User account to use for the service (press enter for NT AUTHORITY\NETWORK SERVICE) >

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'AgentService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
   --- End of inner exception stack trace ---
Exit code 255 returned from process: file name 'c:\Users\Nakago\Documents\vsts-agent\_layout\bin\AgentService.exe', arguments 'init'.
```

<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here. 

```
[2017-05-21 17:51:22Z INFO Terminal] WRITE: Enter User account to use for the service (press enter for NT AUTHORITY\NETWORK SERVICE) > 
[2017-05-21 17:51:22Z INFO Terminal] READ LINE
[2017-05-21 17:51:24Z INFO Terminal] Read value: ''
[2017-05-21 17:51:24Z INFO PromptManager] Falling back to the default: 'NT AUTHORITY\NETWORK SERVICE'
[2017-05-21 17:51:24Z INFO WindowsServiceControlManager] LogonAccount after transforming: NT AUTHORITY\NETWORK SERVICE, user: NETWORK SERVICE, domain: NT AUTHORITY
[2017-05-21 17:51:24Z INFO WindowsServiceControlManager] Service name 'vstsagent.institute-games.METALGEAR' display name 'VSTS Agent (institute-games.METALGEAR)' will be used for service configuration.
[2017-05-21 17:51:24Z INFO WindowsServiceControlManager] Verifying if the account has LogonAsService permission
[2017-05-21 17:51:24Z INFO WindowsServiceControlManager] Account: NT AUTHORITY\NETWORK SERVICE already has Logon As Service Privilege.
[2017-05-21 17:51:24Z INFO WindowsServiceControlManager] Create local group and grant folder permission to service logon account.
[2017-05-21 17:51:24Z INFO WindowsServiceControlManager] Calculated unique group name VSTS_AgentService_G410e7
[2017-05-21 17:51:24Z INFO WindowsServiceControlManager] Trying to create group VSTS_AgentService_G410e7
[2017-05-21 17:51:24Z INFO NativeWindowsServiceHelper] Local Group 'VSTS_AgentService_G410e7' created
[2017-05-21 17:51:24Z INFO WindowsServiceControlManager] Trying to add userName NT AUTHORITY\NETWORK SERVICE to the group VSTS_AgentService_G410e7
[2017-05-21 17:51:24Z INFO NativeWindowsServiceHelper] Account 'NT AUTHORITY\NETWORK SERVICE' is added to local group 'VSTS_AgentService_G410e7'.
[2017-05-21 17:51:24Z INFO WindowsServiceControlManager] Set full access control to group for the folder c:\Users\Nakago\Documents\vsts-agent\_layout
[2017-05-21 17:51:24Z INFO WindowsServiceControlManager] Set full access control to group for the folder c:\Users\Nakago\Documents\vsts-agent\_layout\_work
[2017-05-21 17:51:24Z INFO NativeWindowsServiceHelper] Local group 'VSTS_AgentService_G410e7' already has full control to path 'c:\Users\Nakago\Documents\vsts-agent\_layout\_work'.
[2017-05-21 17:51:24Z INFO ProcessInvoker] Starting process:
[2017-05-21 17:51:24Z INFO ProcessInvoker]   File name: 'c:\Users\Nakago\Documents\vsts-agent\_layout\bin\AgentService.exe'
[2017-05-21 17:51:24Z INFO ProcessInvoker]   Arguments: 'init'
[2017-05-21 17:51:24Z INFO ProcessInvoker]   Working directory: ''
[2017-05-21 17:51:24Z INFO ProcessInvoker]   Require exit code zero: 'True'
[2017-05-21 17:51:24Z INFO ProcessInvoker]   Encoding web name:  ; code page: ''
[2017-05-21 17:51:24Z INFO ProcessInvoker]   Force kill process on cancellation: 'False'
[2017-05-21 17:51:24Z INFO ProcessInvoker] Process started with process id 5548, waiting for process exit.
[2017-05-21 17:51:24Z INFO Terminal] WRITE LINE: 
[2017-05-21 17:51:24Z INFO Terminal] WRITE LINE: Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'AgentService, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
[2017-05-21 17:51:24Z INFO Terminal] WRITE LINE:    --- End of inner exception stack trace ---
[2017-05-21 17:51:28Z INFO ProcessInvoker] Finished process with exit code 255, and elapsed time 00:00:03.2427572.
[2017-05-21 17:51:28Z ERR  Agent] Microsoft.VisualStudio.Services.Agent.ProcessExitCodeException: Exit code 255 returned from process: file name 'c:\Users\Nakago\Documents\vsts-agent\_layout\bin\AgentService.exe', arguments 'init'.
   at Microsoft.VisualStudio.Services.Agent.ProcessInvoker.<ExecuteAsync>d__19.MoveNext() in C:\Users\Nakago\Documents\vsts-agent\src\Microsoft.VisualStudio.Services.Agent\ProcessInvoker.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.NativeWindowsServiceHelper.InstallService(String serviceName, String serviceDisplayName, String logonAccount, String logonPassword) in C:\Users\Nakago\Documents\vsts-agent\src\Agent.Listener\Configuration\NativeWindowsServiceHelper.cs:line 452
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.WindowsServiceControlManager.ConfigureService(AgentSettings settings, CommandSettings command) in C:\Users\Nakago\Documents\vsts-agent\src\Agent.Listener\Configuration\WindowsServiceControlManager.cs:line 105
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext() in C:\Users\Nakago\Documents\vsts-agent\src\Agent.Listener\Configuration\ConfigurationManager.cs:line 332
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext() in C:\Users\Nakago\Documents\vsts-agent\src\Agent.Listener\Agent.cs:line 79
[2017-05-21 17:51:28Z ERR  Terminal] WRITE ERROR: Exit code 255 returned from process: file name 'c:\Users\Nakago\Documents\vsts-agent\_layout\bin\AgentService.exe', arguments 'init'.
```

**Comment by TingluoHuang** [comment]
@warbands you need disable strong name validation. we strongname sign the agentservice.exe when we release it.
[doc for disable strong name validation](https://msdn.microsoft.com/en-us/library/cc713694(v=vs.110).aspx)

**Comment by warbands** [comment]
Ok I will take a look at it when I am back in the box, thanks!

-Rock

**Comment by warbands** [comment]
I tried as you suggested, disabling strong name validation, but I couldn't get it to work.

I tried the registry edit as well as trying to modify the App.config under src/Agent.Service/Windows/App.config, both set to true and false, and nothing modified the behavior.

I am including what my App.config looks like:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup>
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
    <runtime>
        <bypassTrustedAppStrongNames enabled="true" />  
    </runtime>
</configuration>
```

The reason I am even looking at using the src from Master is that the current downloadable agent: vsts-agent-win7-x64-2.116.1.zip fails to handle grabbing my git repo that makes use of LFS with the following error:

```
Fetch LFS objects for git repository at: c:\agent\_work\1\s remote: origin.
git -c http.extraheader="AUTHORIZATION: bearer ********" lfs fetch origin 6efe4575660e2eb944ab687b4cad8c87111af197
Fetching 6efe4575660e2eb944ab687b4cad8c87111af197
batch response: Client error: https://OAuth:********@institute-games.visualstudio.com/_git/Matchy_Dungeon.git/info/lfs/objects/batch
batch response: Client error: https://OAuth:********@institute-games.visualstudio.com/_git/Matchy_Dungeon.git/info/lfs/objects/batch
batch response: Client error: https://OAuth:********@institute-games.visualstudio.com/_git/Matchy_Dungeon.git/info/lfs/objects/batch
batch response: Client error: https://OAuth:********@institute-games.visualstudio.com/_git/Matchy_Dungeon.git/info/lfs/objects/batch
batch response: Client error: https://OAuth:********@institute-games.visualstudio.com/_git/Matchy_Dungeon.git/info/lfs/objects/batch
batch response: Client error: https://OAuth:********@institute-games.visualstudio.com/_git/Matchy_Dungeon.git/info/lfs/objects/batch
Warning: errors occurred
Git LFS: (0 of 541 files) 0 B / 847.20 MB                                      
Git fetch failed with exit code: 2
System.InvalidOperationException: Git fetch failed with exit code: 2
```

Taking the source code for vsts-agent, and running: dev layout Release allowed me to run vsts-agent in run mode ( non service ) and successfully Get Sources against my vsts git repo that has lfs data in it.

I am assuming that the downloadable agent was built against the current master, so I am at a bit of a loss why performing a local build of it would result in a working version ( as long as I don't want it as a service )

I wanted to give some background to the issue, as well as find out if the current downloadable agent is current against the master branch. Thanks!!

**Comment by TingluoHuang** [comment]
@warbands try the latest released agent. 2.117.0 that version should has the proper fix.
we release agent every 3 weeks, so the released agent might not have latest changes in Master.

**Comment by warbands** [comment]
That worked great! Thanks Ting!
I wanted to let you know that the link from within VSTS still points to:
https://github.com/Microsoft/vsts-agent/releases/download/v2.116.1/vsts-agent-win7-x64-2.116.1.zip

This should get updated as soon as possible. Thanks again!!

**Comment by TingluoHuang** [comment]
yeah, we will start release the newer version agent to VSTS soon.
