### ISSUE TITLE
Connection with PAT only, still requires Windows authentication?

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/vsts-agent#996]
## **Agent version and platform**
Version: 2.112.0
Windows 2016<br>
## **On-Prem TFS Express 2017**
On-Prem TFS Express 2017
<br>
## **What's not working?**
I'm trying to automate agent installation using DSC. I assumed if I pass PAT during registration it will be able to registry without requirement to have secondary authentication available, but I'm gGetting access denied when registering agent using PAT method. 
I might have misunderstood architecture but does PAT in fact requires also Windows Authentication authentication to register agent as well? I can see in Fiddler logs that agent is trying to authenticate to `GET /tfs/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 HTTP/1.1` but getting access denied since account I run installation from do not have access to TFS server.  If I run configuration under account which has access to TFS server then issue does not happen.
```
c:\agent>cmd.exe /c ""C:\agent\config.cmd" --unattended --url https://vsts/tfs --auth PAT --token 4sigxzmp6olocapvoorfsk3xxkvmpf226asnjbvycxkoolar27aq --pool default --agent vststestagent "

>> Connect:

Connecting to server ...
VS30063: You are not authorized to access https://vsts.
```
Agent log
```
[2017-05-28 23:01:16Z INFO AgentProcess] Agent is built for Windows - win7-x64.
[2017-05-28 23:01:16Z INFO AgentProcess] RuntimeInformation: Microsoft Windows 10.0.14393 .
[2017-05-28 23:01:16Z INFO AgentProcess] Version: 2.112.0
[2017-05-28 23:01:16Z INFO AgentProcess] Commit: 7f51dc44f64f29b26d5f0f00c26f99352201418e
[2017-05-28 23:01:16Z INFO AgentProcess] Culture: en-US
[2017-05-28 23:01:16Z INFO AgentProcess] UI Culture: en-US
[2017-05-28 23:01:16Z INFO HostContext] Well known directory 'Bin': 'C:\agent\bin'
[2017-05-28 23:01:16Z INFO HostContext] Well known directory 'Root': 'C:\agent'
[2017-05-28 23:01:16Z INFO AgentProcess] Validating directory permissions for: 'C:\agent'
[2017-05-28 23:01:16Z INFO PowerShellExeUtil] Generation: '1'
[2017-05-28 23:01:16Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1', value name 'Install': '1'
[2017-05-28 23:01:16Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\PowerShellEngine', value name 'PowerShellVersion': '2.0'
[2017-05-28 23:01:16Z INFO PowerShellExeUtil] Unsupported version. Skipping.
[2017-05-28 23:01:16Z INFO PowerShellExeUtil] Generation: '3'
[2017-05-28 23:01:16Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3', value name 'Install': '1'
[2017-05-28 23:01:16Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'PowerShellVersion': '5.1.14393.0'
[2017-05-28 23:01:16Z INFO PowerShellExeUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', value name 'ApplicationBase': 'C:\Windows\System32\WindowsPowerShell\v1.0'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework', value name 'InstallRoot': 'C:\Windows\Microsoft.NET\Framework64\'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP' contains sub keys:
[2017-05-28 23:01:16Z INFO NetFrameworkUtil]  'CDF'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil]  'v4'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil]  'v4.0'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name 'Version' is null.
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4', value name '' is null.
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'SOFTWARE\Microsoft\NET Framework Setup\NDP\v4' contains sub keys:
[2017-05-28 23:01:16Z INFO NetFrameworkUtil]  'Client'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil]  'Full'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Version': '4.6.01586'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Install': '1'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Client', value name 'Release': '394802'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Type is System.Int32
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Interpreted version: 4.6.2
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Version': '4.6.01586'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Install': '1'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'InstallPath': 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full', value name 'Release': '394802'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Type is System.Int32
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Interpreted version: 4.6.2
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name 'Version' is null.
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Key name 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0', value name '': 'deprecated'
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Found 2 versions:
[2017-05-28 23:01:16Z INFO NetFrameworkUtil]  4.6.2
[2017-05-28 23:01:16Z INFO NetFrameworkUtil]  4.6.2
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.5'
[2017-05-28 23:01:16Z INFO CommandLineParser] Parse
[2017-05-28 23:01:16Z INFO CommandLineParser] Parsing 12 args
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: False
[2017-05-28 23:01:16Z INFO CommandLineParser] Adding Command: configure
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: True
[2017-05-28 23:01:16Z INFO CommandLineParser] arg: unattended
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: True
[2017-05-28 23:01:16Z INFO CommandLineParser] arg: url
[2017-05-28 23:01:16Z INFO CommandLineParser] Adding flag: unattended
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: True
[2017-05-28 23:01:16Z INFO CommandLineParser] Adding option 'url': 'https://vsts/tfs'
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: True
[2017-05-28 23:01:16Z INFO CommandLineParser] arg: auth
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: True
[2017-05-28 23:01:16Z INFO CommandLineParser] Adding option 'auth': 'PAT'
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: True
[2017-05-28 23:01:16Z INFO CommandLineParser] arg: token
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: True
[2017-05-28 23:01:16Z INFO CommandLineParser] Adding option 'token': '********'
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: True
[2017-05-28 23:01:16Z INFO CommandLineParser] arg: pool
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: True
[2017-05-28 23:01:16Z INFO CommandLineParser] Adding option 'pool': 'default'
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: True
[2017-05-28 23:01:16Z INFO CommandLineParser] arg: agent
[2017-05-28 23:01:16Z INFO CommandLineParser] parsing argument
[2017-05-28 23:01:16Z INFO CommandLineParser] HasArgs: True
[2017-05-28 23:01:16Z INFO CommandLineParser] Adding option 'agent': 'vststestagent'
[2017-05-28 23:01:16Z INFO AgentProcess] Arguments parsed
[2017-05-28 23:01:16Z INFO ProxyConfiguration] No proxy setting found.
[2017-05-28 23:01:16Z INFO Agent] ExecuteCommand
[2017-05-28 23:01:16Z INFO ConfigurationStore] currentAssemblyLocation: C:\agent\bin\Agent.Listener.dll
[2017-05-28 23:01:16Z INFO ConfigurationStore] binPath: C:\agent\bin
[2017-05-28 23:01:16Z INFO ConfigurationStore] RootFolder: C:\agent
[2017-05-28 23:01:16Z INFO ConfigurationStore] ConfigFilePath: C:\agent\.agent
[2017-05-28 23:01:16Z INFO ConfigurationStore] CredFilePath: C:\agent\.credentials
[2017-05-28 23:01:16Z INFO ConfigurationStore] ServiceConfigFilePath: C:\agent\.service
[2017-05-28 23:01:16Z INFO CommandSettings] Flag 'help': 'False'
[2017-05-28 23:01:16Z INFO CommandSettings] Flag 'version': 'False'
[2017-05-28 23:01:16Z INFO CommandSettings] Flag 'commit': 'False'
[2017-05-28 23:01:16Z INFO CommandSettings] Command 'configure': 'True'
[2017-05-28 23:01:16Z INFO ConfigurationManager] ConfigureAsync
[2017-05-28 23:01:16Z INFO ConfigurationStore] IsConfigured()
[2017-05-28 23:01:16Z INFO ConfigurationStore] IsConfigured: False
[2017-05-28 23:01:16Z INFO ConfigurationManager] Is configured: False
[2017-05-28 23:01:16Z INFO NetFrameworkUtil] Testing for min NET Framework version: '4.6'
[2017-05-28 23:01:16Z INFO CommandSettings] Flag 'machinegroup': 'False'
[2017-05-28 23:01:16Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2017-05-28 23:01:16Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2017-05-28 23:01:16Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.MachineGroupAgentConfigProvider, Agent.Listener
[2017-05-28 23:01:16Z INFO Terminal] WRITE LINE: 
[2017-05-28 23:01:16Z INFO Terminal] WRITE LINE: >> Connect:
[2017-05-28 23:01:16Z INFO Terminal] WRITE LINE: 
[2017-05-28 23:01:16Z INFO CommandSettings] Arg 'url': 'https://vsts/tfs'
[2017-05-28 23:01:16Z INFO CommandSettings] Remove url from Arg dictionary.
[2017-05-28 23:01:16Z INFO ConfigurationManager] GetCredentialProvider
[2017-05-28 23:01:16Z INFO CommandSettings] Arg 'auth': 'PAT'
[2017-05-28 23:01:16Z INFO CommandSettings] Remove auth from Arg dictionary.
[2017-05-28 23:01:16Z INFO ConfigurationManager] Creating credential for auth: PAT
[2017-05-28 23:01:16Z INFO CredentialManager] GetCredentialProvider
[2017-05-28 23:01:16Z INFO CredentialManager] Creating type PAT
[2017-05-28 23:01:16Z INFO CredentialManager] Creating credential type: PAT
[2017-05-28 23:01:16Z INFO PersonalAccessToken] EnsureCredential
[2017-05-28 23:01:16Z INFO CommandSettings] Arg 'token': '********'
[2017-05-28 23:01:16Z INFO CommandSettings] Remove token from Arg dictionary.
[2017-05-28 23:01:16Z INFO PersonalAccessToken] GetVssCredentials
[2017-05-28 23:01:16Z INFO PersonalAccessToken] token retrieved: 52 chars
[2017-05-28 23:01:16Z INFO ConfigurationManager] cred retrieved
[2017-05-28 23:01:16Z INFO Terminal] WRITE LINE: Connecting to server ...
[2017-05-28 23:01:17Z INFO CommandSettings] Flag 'unattended': 'True'
[2017-05-28 23:01:17Z ERR  Agent] Microsoft.VisualStudio.Services.Common.VssUnauthorizedException: VS30063: You are not authorized to access https://vsts.
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.<SendAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.<SendAsync>d__42`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.<GetConnectionDataAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.<ConnectAsync>d__41.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.AgentServer.<ConnectAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider.<TestConnectionAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.<ConfigureAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Listener.Agent.<ExecuteCommand>d__9.MoveNext()
[2017-05-28 23:01:17Z ERR  Terminal] WRITE ERROR: VS30063: You are not authorized to access https://vsts.
```
Fiddler log
```
GET https://vsts/tfs/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 HTTP/1.1
Connection: Keep-Alive
Accept-Encoding: gzip
Accept-Language: en-US
Authorization: Basic VnN0c0FnZW50OjRzaWd4em1wNm9sb2NhcHZvb3Jmc2szeHhrdm1wZjIyNmFzbmpidnljeGtvb2xhcjI3YXE=
Expect: 100-continue
User-Agent: VSServices/15.255.65000.0 (NetStandard) VstsAgentCore-win7-x64/2.112.0 (Microsoft Windows 10.0.14393)
X-TFS-FedAuthRedirect: Suppress
X-TFS-Session: 87ac1a4f-f035-4d3c-bd37-19d66be89e35
Host: vsts
```
Response
```
HTTP/1.1 401 Unauthorized
Server: Microsoft-IIS/10.0
X-TFS-ProcessId: f00ce975-9679-48e8-a5e5-45c7d0a41c5c
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-FRAME-OPTIONS: SAMEORIGIN
WWW-Authenticate: Basic realm="https://vsts/tfs"
WWW-Authenticate: NTLM
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff
Date: Sun, 28 May 2017 21:50:11 GMT
Content-Length: 0

```

**Comment by artisticcheese** [comment]
PAT was wrong
